force-app/main/default/objects/Term_Quote__c/Term_Quote__c.object-meta.xml
<CustomObject>
    <description>Junction object of SBQQ__Quote__c and SBQQ__QuoteTerm__c usied to generate terms for specific quote</description>
    <label>Term Quote</label>
    <nameField>
        <displayFormat>TQ-{000000}</displayFormat>
        <label>Term Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Term Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Term_Quote__c/fields/Modified__c.field-meta.xml
<CustomField>
    <fullName>Modified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Modified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Term_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Term Quotes</relationshipLabel>
    <relationshipName>Term_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Term_Quote__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Term</label>
    <referenceTo>SBQQ__QuoteTerm__c</referenceTo>
    <relationshipLabel>Term Quotes</relationshipLabel>
    <relationshipName>Term_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GetTermQuote.cls
/**
* @description       : BIZ-50132-This class is used in Approval Email Template.
* @author            : Pankaj Kumar
* @last modified on  : 01-08-2024
* @last modified by  : Pankaj Kumar
* Modifications Log
* Ver   Date         Author         Modification
* 1.0   01-02-2024   Pankaj Kumar   Initial Version
**/
public class GetTermQuote {

    public List<Term_Quote__c> termQuotes;
    public Id relatedId {get;set;}
 
    public List<Term_Quote__c> getTermQuotes() {
        try{
            termQuotes = [SELECT id,Body__c,Quote__c,Term__c,Name,Modified__c FROM Term_Quote__c
                          Where Modified__c=true AND Quote__c =: relatedId ];
            if(termQuotes!=null){
                for(Term_Quote__c t:termQuotes){
                    t.Body__c = t.Body__c.stripHtmlTags();
                }
            }
         }catch(Exception ex){
            System.debug('Exception Caught  :'+ex.getMessage() + ' **Line Number : '+ex.getLineNumber());
         }
          return termQuotes;
    }
}