force-app/main/default/objects/Campaign/fields/Value_of_Closed_Won_opportunities__c.field-meta.xml
<CustomField>
    <fullName>Value_of_Closed_Won_opportunities__c</fullName>
    <defaultValue>0</defaultValue>
    <description>sums the ‘Recurring Amount (Change)’ of the opportunities where ‘Simple Status’ = ‘Closed Won’</description>
    <inlineHelpText>sums the ‘Recurring Amount (Change)’ of the opportunities where ‘Simple Status’ = ‘Closed Won’</inlineHelpText>
    <label>Value of Closed Won opportunities</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Value_of_Open_opportunities__c.field-meta.xml
<CustomField>
    <fullName>Value_of_Open_opportunities__c</fullName>
    <defaultValue>0</defaultValue>
    <description>sums the ‘Recurring Amount (Change)’ of the opportunities where ‘Simple Status’ = ‘Open’ and ‘Stage’ not equal to ‘Target Account’</description>
    <inlineHelpText>sums the ‘Recurring Amount (Change)’ of the opportunities where ‘Simple Status’ = ‘Open’ and ‘Stage’ not equal to ‘Target Account’</inlineHelpText>
    <label>Value of Open opportunities</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Value_of_Target_Account_opportunities__c.field-meta.xml
<CustomField>
    <fullName>Value_of_Target_Account_opportunities__c</fullName>
    <defaultValue>0</defaultValue>
    <description>sum of the ‘Recurring Amount (Change)’ of the opportunities where ‘Stage’ = ‘Target Account’</description>
    <inlineHelpText>sum of the ‘Recurring Amount (Change)’ of the opportunities where ‘Stage’ = ‘Target Account’</inlineHelpText>
    <label>Value of Target Account opportunities</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maintenance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Amount__c</fullName>
    <description>This field shows CHANGES to the annual recurring amount commitment for the referenced product. The value can be positive, if the closed-won opportunity increases the annual recurring commitment, or negative, if the closed-won opportunity decreases the annual recurring commitment.</description>
    <inlineHelpText>This field shows CHANGES to the annual recurring commitment for the referenced product. The value is positive, if the closed-won opportunity increases the annual commitment, or negative, if the closed-won opportunity decreases the annual commitment.</inlineHelpText>
    <label>Recurring Amount Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Opportunity_Deletion_Notification__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Deletion_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Object Deletion Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
/********************************************************************************     
 *  Name             :  OpportunityTriggerHandler
 *  Author           :  Hiforte Technologies
 *  Description      :  1. Notifies users when an opportunity is deleted
 *                      2. Populates the fields-Value of Open opportunities,Value of Closed Won opportunities &
 *                         Value of Target Account opportunities in the Campaign object by calculating the summation of the 
  *                        recurring amount values of the associated opportunities.                             
 *  Change history   :
 *  Date                Author                          Description
 *  05/30/14        Vasu Pulipati                       Created
 * 03/29/2018       Anisha Dhekne                       Added populateValueofOpportunities method
 *  10/9/15         FUNCTIONALITY MOVED TO OPPORTUNITES CLASS. NO LONGER USED!
 ********************************************************************************/
public class OpportunityTriggerHandler {

    //public static void sendOpportunityDeletedNotification(List<Opportunity> opps) {
    //List<String> toAddresses = new List<String> ();
    //for (User u :[select email from User where Opportunity_Deletion_Notification__c = true and isActive = true]) {
    //toAddresses.add(u.email);
    //}
    //if (opps.size() > 0 && toAddresses.size() > 0) {
    //Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    //mail.setToAddresses(toAddresses);
    //mail.setSubject('Opportunity deleted');
    //mail.setSaveAsActivity(false);
    //String textBody = UserInfo.getName() + ' (' + UserInfo.getUserEmail() + ') deleted the following opportunities: \n';
    //for (Opportunity opp : opps) {
    //textBody += '\n  ' + opp.Name;
    //}
    //mail.setPlainTextBody(textBody);
    //System.debug('#### OpportunityTriggerHandler- sending notifications to: ' + toAddresses);
    ////    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    //}
    //}

    // Method to calculate vaLue of opportunities
    public static void populateValueofOpportunities(List<Opportunity> newOpportunity)
    {
	/*
        List<Campaign> CampaignsToUpdate = new List<Campaign> ();
        List<Id> CampaignIds = new List<Id> ();
        if (Trigger.isInsert || Trigger.isUpdate)
        {
            for (Opportunity opp : newOpportunity) {
                CampaignIds.add(opp.CampaignId);
            }
            for (Campaign camp :[Select Id, Value_of_Target_Account_opportunities__c, Value_of_Open_opportunities__c, Value_of_Closed_Won_opportunities__c, (SELECT Maintenance_Amount__c, StageName, Simple_Stage__c FROM Opportunities) From Campaign where Id in :CampaignIds]) {
                camp.Value_of_Target_Account_opportunities__c = 0;
                camp.Value_of_Open_opportunities__c = 0;
                camp.Value_of_Closed_Won_opportunities__c = 0;


                for (Opportunity oppo : camp.Opportunities)
                { 
                    //Populate the field value of Target Account opportunities
                    if (oppo.Maintenance_Amount__c != null && oppo.StageName.equals('Target Account')) {

                        camp.Value_of_Target_Account_opportunities__c += oppo.Maintenance_Amount__c;
                   
                    }
                    else if(Trigger.isDelete) {camp.Value_of_Target_Account_opportunities__c -= oppo.Maintenance_Amount__c;}
                    //Populate the field value of Open opportunities
                    if (oppo.Maintenance_Amount__c != null && oppo.Simple_Stage__c.equals('Open') && oppo.StageName != 'Target Account') {
                        camp.Value_of_Open_opportunities__c += oppo.Maintenance_Amount__c;
                    }
                    //Populate the field value of Closed Won opportunities
                    if (oppo.Maintenance_Amount__c != null && oppo.StageName.equals('Closed Won')) {
                        camp.Value_of_Closed_Won_opportunities__c += oppo.Maintenance_Amount__c;
                    }
                }

                CampaignsToUpdate.add(camp);
            }
            
            if (CampaignsToUpdate.size() > 0) {
                update CampaignsToUpdate;
            }

        }
	*/
    }
}