force-app/main/default/objects/News_Alert__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/News_Alert__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>News/Alerts</relationshipLabel>
    <relationshipName>News_Alerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Knowledge &amp; Content</fullName>
            </value>
            <value>
                <fullName>Tech</fullName>
            </value>
            <value>
                <fullName>Leaders &amp; Professionals</fullName>
            </value>
            <value>
                <fullName>Marketing &amp; BD</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Operations &amp; Finance</fullName>
            </value>
            <value>
                <fullName>DealCloud</fullName>
            </value>
            <value>
                <fullName>Risk &amp; Compliance</fullName>
            </value>
            <value>
                <fullName>OnePlace</fullName>
            </value>
            <value>
                <fullName>Collaboration &amp; Content</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductNewsController.cls
public with sharing class ProductNewsController {
	
	public String recordLimit{get;set;}
	public String recordTypeName{get;set;}

	public List<News_Alert__c> getNewsAlerts () {
		String qry = 'Select n.Product_Line__r.Practice__c, n.Product_Line__r.Name, n.Product_Line__c, n.Name, n.Content__c, CreatedDate'; 
		qry += ' From News_Alert__c n';
		qry += ' Where recordType.developerName = :recordTypeName';
		qry += ' Order by CreatedDate desc '; 
		qry += 'limit ' + recordLimit;
		return (List<News_Alert__c>) Database.query(qry);
	}

	private static testMethod void testProductController() {
	  	ProductNewsController ctrl = new ProductNewsController();
	  	ctrl.recordTypeName = 'News';
	  	ctrl.recordLimit = '10';
	  	ctrl.getNewsAlerts();
	  	
	  }

/*
//Returns list of Alert Strings
public List<String> getlstNewsAlerts () {
	mapNewsAndAlerts = new Map<String, List<News_Alert__c>> ();
String qry = 'Select n.Product_Line__r.Practice__c, n.Product_Line__r.Name, n.Product_Line__c, n.Name, n.Content__c, CreatedDate'; 
qry += ' From News_Alert__c n';
qry += ' Where recordType.Name = ' + recordTypeName;
qry += ' Order by CreatedDate desc '; 
qry += 'limit ' + recordLimit;

List<String> createdDates = new List<String> ();
for (News_Alert__c news : (List<News_Alert__c>) Database.query(qry)) {
	String createdDate = news.createdDate.format('MM/dd/yyyy');
	if (!mapNewsAndAlerts.containsKey(createdDate)) {
		mapNewsAndAlerts.put(createdDate, new List<News_Alert__c> ());
		createdDates.add(createdDate);
	}
	mapNewsAndAlerts.get(createdDate).add(news);
	
}

	return createdDates;
}*/

}