force-app/main/default/objects/Subscription__c/fields/Most_Recent_Term_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Term_Start_Date__c</fullName>
    <label>Most Recent Term Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Term__c/fields/Product_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Customer_Number__c</fullName>
    <label>Product Customer Number</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipName>Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Term__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Term Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TermsTest.cls
@isTest(SeeAllData = true)
private class TermsTest {

	@isTest static void testUpdateProductCustomerTermStartDate() {
		Term__c term = (Term__c) SmartFactory.createSObject('Term__c');
		Date startDate = date.today();
		term.Start_Date__c = startDate;
		term.Product_Customer_Number__c = 'a1A50000000a3iGEAQ';
		insert term;

		Subscription__c sub = [SELECT Most_Recent_Term_Start_Date__c FROM Subscription__c WHERE Id = 'a1A50000000a3iGEAQ' LIMIT 1];

		system.assertEquals(sub.Most_Recent_Term_Start_Date__c, startDate, 'Dates match');
	}
}