force-app/main/default/objects/blng__Invoice__c/blng__Invoice__c.object-meta.xml
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/blng__Invoice__c/fields/blng__InvoiceStatus__c.field-meta.xml
<CustomField>
    <fullName>blng__InvoiceStatus__c</fullName>
    <description>Warning: Invoice Status is an internal field. Changing it could cause basic functionality to fail or become unstable.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>blng__InvoiceStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceTriggerHandler.cls
public class InvoiceTriggerHandler {   
    public Static void invoiceAfterUpdate(list<blng__Invoice__c> invoiceNewList, Map<Id,blng__Invoice__c> invoiceOldMap) {
        List<blng__Invoice__c> invoiceEligibleList = new List<blng__Invoice__c>();
        if(!invoiceNewList.isEmpty())
        {
            for(blng__Invoice__c invoiceObj : invoiceNewList)
            {
                if(invoiceObj.blng__InvoiceStatus__c!=invoiceOldMap.get(invoiceObj.id).blng__InvoiceStatus__c && invoiceObj.blng__InvoiceStatus__c == 'Posted')
                {
                    invoiceEligibleList.add(invoiceObj);
                }
                if(invoiceObj.Sync_NetSuite__c == true && invoiceObj.Sync_NetSuite__c!=invoiceOldMap.get(invoiceObj.id).Sync_NetSuite__c){
                    invoiceEligibleList.add(invoiceObj);  
                }
            }    
        } 
        IntegrationUtility.publishsObjectRecords(invoiceEligibleList,'blng__Invoice__c');
    }
}