force-app/main/default/objects/blng__Invoice__c/blng__Invoice__c.object-meta.xml
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/blng__Invoice__c/fields/blng__Account__c.field-meta.xml
<CustomField>
    <fullName>blng__Account__c</fullName>
    <inlineHelpText>Lookup to the Account this invoice is billed to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>AccountInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/blng__Invoice__c/fields/NS_Inv_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Inv_Internal_ID__c</fullName>
    <label>NS Inv Internal ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QtC_Mig_Invoice_Lines_Temp_Table__c/fields/T_Invoice__c.field-meta.xml
<CustomField>
    <fullName>T_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T_Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>QtC Mig Invoice Lines Temp Table</relationshipLabel>
    <relationshipName>QtC_Mig_Invoice_Lines_Temp_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/T_Invoice__c/T_Invoice__c.object-meta.xml
<CustomObject>
    <label>T_Invoice</label>
    <nameField>
        <label>T_Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T_Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/T_InvoiceLinesLookupBatchTest.cls
/**** @name        : T_InvoiceLinesLookupBatchTest
***** @author      : KPMG
***** @date        : Nov 11th, 2023
***** @description : Test Class for T_InvoiceLinesLookupBatch
******/
@isTest
public class T_InvoiceLinesLookupBatchTest {
@testSetup
    // Test Data Setup
    static void setupData(){
        //Create QtC_Mig_Invoice_Lines_Temp_Table__c
        QtC_Mig_Invoice_Lines_Temp_Table__c qtcmigInvLines = new QtC_Mig_Invoice_Lines_Temp_Table__c();
        qtcmigInvLines.Internal_ID__c = '123456';
		qtcmigInvLines.T_Invoice__c = Null;
        insert qtcmigInvLines;
        //Create Account
        Account acc = new Account();
        acc.name='Test';
        insert acc;
        //Create Billing Invoice
        blng__Invoice__c blngInvoice = new blng__Invoice__c();
        blngInvoice.NS_Inv_Internal_ID__c = qtcmigInvLines.Internal_ID__c;
        blngInvoice.T_IsMigrated__c = true;
        blngInvoice.blng__Account__c = acc.Id;
        insert blngInvoice;
    }
@isTest
    //Method to execute the testData
    static void invoiceLinesLookupBatchTest(){
        //Start test
        Test.startTest();
        //Executing the batch for test data
        T_InvoiceLinesLookupBatch bc = new T_InvoiceLinesLookupBatch();
        Database.executeBatch(bc);
        //Stop test
        Test.stopTest();
        
        //Validating the results
        List<QtC_Mig_Invoice_Lines_Temp_Table__c> tempList = [SELECT Id,T_Invoice__c FROM QtC_Mig_Invoice_Lines_Temp_Table__c Limit 1];
        List<blng__Invoice__c> billingInv = [SELECT Id from blng__Invoice__c Limit 1];
        if(tempList.size() > 0 && billingInv.size() >0  && tempList[0].T_Invoice__c != null){
            System.assertEquals(tempList[0].T_Invoice__c,billingInv[0].Id,'Invoice Id populated successfully');
        }
    }
}