force-app/main/default/objects/blng__Invoice__c/blng__Invoice__c.object-meta.xml
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/blng__Invoice__c/fields/blng__Account__c.field-meta.xml
<CustomField>
    <fullName>blng__Account__c</fullName>
    <inlineHelpText>Lookup to the Account this invoice is billed to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>AccountInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/blng__Invoice__c/fields/blng__InvoiceStatus__c.field-meta.xml
<CustomField>
    <fullName>blng__InvoiceStatus__c</fullName>
    <description>Warning: Invoice Status is an internal field. Changing it could cause basic functionality to fail or become unstable.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>blng__InvoiceStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceTriggerHandlerTest.cls
@isTest
public class InvoiceTriggerHandlerTest {
    @isTest
    public static void testMethod1(){
        
        Account acc = IntappTestObjectFactory.createAccount(true);
        
        blng__Invoice__c invoice = new blng__Invoice__c();
        invoice.blng__Account__c = acc.id;
        invoice.blng__InvoiceStatus__c = 'Draft';
        insert invoice;
        
        invoice.blng__InvoiceStatus__c = 'Initiated';
        update invoice;
        
        blng__Invoice__c invoice1 = new blng__Invoice__c();
        invoice1.blng__Account__c = acc.id;
        invoice1.blng__InvoiceStatus__c = 'Error';
        insert invoice1;
        
        invoice1.blng__InvoiceStatus__c = 'Posted';
        update invoice1;
        
        list<blng__Invoice__c> listOfInvoice = new list<blng__Invoice__c>();
        listOfInvoice.add(invoice);
        listOfInvoice.add(invoice1);
        system.assertNotEquals(listOfInvoice.size(), null);
    }
}