force-app/main/default/objects/Intapp_Pricing__c/fields/Premium_price__c.field-meta.xml
<CustomField>
    <fullName>Premium_price__c</fullName>
    <label>Premium price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/IntappPricingHandlerTest.cls
@isTest public class IntappPricingHandlerTest {
    @isTest static void testMethod1(){
      Intapp_Pricing__c intapppriceObj = (Intapp_Pricing__c) SmartFactory.createSObject('Intapp_Pricing__c');
      intapppriceObj.Name = 'Testintappprice';
      intapppriceObj.CurrencyIsoCode = 'USD';
      insert intapppriceObj;
      List<Intapp_Pricing__c> pList = new List<Intapp_Pricing__c>();
      List<Intapp_Pricing__c> pList2 = new List<Intapp_Pricing__c>();
      pList.add(intapppriceObj);
      Test.startTest();
      IntappPricingHandler.intappPriceAfterInsert(pList);
      pList2.add(intapppriceObj);
      pList2[0].Intapp_ID__c = 'test';
      pList2[0].Premium_price__c = 123;
      update pList2;
      system.assertNotEquals(null,pList2,'Product');
      Test.stopTest();
    }
    }