force-app/main/default/objects/SBQQ__LookupData__c/SBQQ__LookupData__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__LookupQueryHelp</customHelpPage>
    <label>Lookup Data</label>
    <nameField>
        <displayFormat>DATA-{0000}</displayFormat>
        <label>Lookup Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lookup Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__LookupData__c/fields/Child_Product__c.field-meta.xml
<CustomField>
    <fullName>Child_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture the Child Product info for Static Bundle, created as per BIZ-47580</description>
    <label>Child Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lookup Data (Child Product)</relationshipLabel>
    <relationshipName>Lookup_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__LookupData__c/fields/Product_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Product_Allocation__c</fullName>
    <description>Pricing allocation of child products based on the % defined, created as per BIZ-47580</description>
    <label>Product Allocation %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__LookupData__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For use with Product Selection Rules, represents the Product to which the Product Action applies.</description>
    <inlineHelpText>For use with Product Selection Rules, represents the Product to which the Product Action applies.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lookup Data</relationshipLabel>
    <relationshipName>LookupData</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Dimension__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Dimension__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</description>
    <inlineHelpText>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</inlineHelpText>
    <label>Price Dimension</label>
    <referenceTo>SBQQ__Dimension__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddStaticBundleHandlerTest.cls
/**
 * @description       : This test class will cover AddStaticBundleHandler class.
 * @author            : Dhiraj Kumar
 * @last modified on  : 11-28-2023
 * @last modified by  : Dhiraj Kumar
 * Modifications Log
 * Ver   Date         Author         Modification
 * 1.0   11-28-2023   Dhiraj Kumar   Initial Version
**/
@isTest
public class AddStaticBundleHandlerTest {
    /**
    * ***********************************************************
    * This method is test SetUp method 
    * ***********************************************************
    */
    @testSetup
    public static void setup(){
        List<Product2> parentProd = TestDataFactory.createProdList('Intapp Risk & Compliance PIN-01670',1,true);
        List<Product2> childProd = TestDataFactory.createProdList('Intapp Billstream Cloud PIN-01879',1,true);
        PricebookEntry parntProdPriceBookEntry = TestDataFactory.createPricebookEntry(parentProd[0].Id,true);
        SBQQ__Dimension__c parntProdPriceBookDimension = TestDataFactory.createPricebookDimension(parentProd[0].Id,true);
        PricebookEntry priceBookEntry = TestDataFactory.createPricebookEntry(childProd[0].Id,true);
        SBQQ__Dimension__c priceBookDimension = TestDataFactory.createPricebookDimension(childProd[0].Id,true);     
        SBQQ__LookupData__c lookupData = new SBQQ__LookupData__c(SBQQ__Product__c=parentProd[0].Id,Child_Product__c=childProd[0].Id,PriceBookEntry_Id__c=priceBookEntry.Id,Dimension_Id__c=priceBookDimension.Id,Product_Allocation__c=10,CurrencyIsoCode='USD',SBQQ__Value__c='2187638');
        insert lookupData;
        
        List<Account> accList = TestDataFactory.createAccount(1,True);              
        List<Opportunity> opportunityList = TestDataFactory.createOppty(2, accList[0].Id, true);
        List<SBQQ__Quote__c> quoteList1 = TestDataFactory.createQuote(1, opportunityList[0].Id, true);
        List<SBQQ__Quote__c> quoteList2 = TestDataFactory.createQuote(1, opportunityList[1].Id, true);
        
        //List<User> createSalesUser = TestDataFactory.createSalesUser(1,true);
    }
    
    /**
    * ***********************************************************
    * This method is test method for addStaticBundle
    * ***********************************************************
    */
    @isTest
    public static void testAddStaticBundle(){        
        Test.startTest();
        try
        {
           List<SBQQ__Quote__c> quoteList = [SELECT Id, Name FROM SBQQ__Quote__c];
            List<Product2> parentProd = [SELECT Id, Name FROM Product2 WHERE NAME LIKE 'Intapp Risk & Compliance%' LIMIT 1];
            List<SBQQ__QuoteLine__c> quoteLineList = TestDataFactory.createQuoteLine(1,quoteList[0].Id,parentProd[0].Id,true);
            //List<SBQQ__QuoteLine__c> quoteLineList1 = TestDataFactory.createQuoteLine(1,quoteList[1].Id,parentProd[0].Id,true);
            System.assertEquals(1,quoteLineList.size());
            delete quoteLineList[0]; 
        }
        catch(Exception ex)
        {
            System.debug('Exception Caught at :'+ ex.getMessage() );
        }
            
        Test.stopTest();
    }
    
    /**
    * ***********************************************************
    * This method is test method for afterDelete
    * ***********************************************************
    */
    @isTest
    public static void testDeleteStaticBundle(){    

            Map<Id,SBQQ__QuoteLine__c> oldMap = new Map<Id,SBQQ__QuoteLine__c>();
            List<SBQQ__Quote__c> quoteList = [SELECT Id, Name FROM SBQQ__Quote__c];
            List<Product2> parentProd = [SELECT Id, Name FROM Product2 WHERE NAME LIKE 'Intapp Risk & Compliance%' LIMIT 1];
            List<SBQQ__QuoteLine__c> quoteLineList = TestDataFactory.createQuoteLine(1,quoteList[0].Id,parentProd[0].Id,true);
            oldMap.put(quoteLineList[0].Id,quoteLineList[0]);
            Test.startTest();
            AddStaticBundleHandler.afterDelete(oldMap);
            System.assertEquals(1,quoteList.size());
            Test.stopTest();    
    }
    
    /*@isTest
    public static void testAddStaticBundle1(){     
        
        List<SBQQ__Quote__c> quoteList = [SELECT Id, Name FROM SBQQ__Quote__c];
        List<Product2> parentProd = [SELECT Id, Name FROM Product2 WHERE NAME LIKE 'Intapp Risk & Compliance%' LIMIT 1];
        List<SBQQ__QuoteLine__c> quoteLineList = TestDataFactory.createQuoteLine(1,quoteList[0].Id,parentProd[0].Id,true);
        Test.startTest();
        List<SBQQ__QuoteLine__c> quoteLineList2 = TestDataFactory.createQuoteLine(1,quoteList[0].Id,parentProd[0].Id,true);
        Test.stopTest();
        
    }*/
    
}