force-app/main/default/objects/SBQQ__LookupData__c/SBQQ__LookupData__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__LookupQueryHelp</customHelpPage>
    <label>Lookup Data</label>
    <nameField>
        <displayFormat>DATA-{0000}</displayFormat>
        <label>Lookup Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lookup Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__LookupData__c/fields/Child_Product__c.field-meta.xml
<CustomField>
    <fullName>Child_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture the Child Product info for Static Bundle, created as per BIZ-47580</description>
    <label>Child Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lookup Data (Child Product)</relationshipLabel>
    <relationshipName>Lookup_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__LookupData__c/fields/Product_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Product_Allocation__c</fullName>
    <description>Pricing allocation of child products based on the % defined, created as per BIZ-47580</description>
    <label>Product Allocation %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__LookupData__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For use with Product Selection Rules, represents the Product to which the Product Action applies.</description>
    <inlineHelpText>For use with Product Selection Rules, represents the Product to which the Product Action applies.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lookup Data</relationshipLabel>
    <relationshipName>LookupData</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Bypass_PriceRule__c.field-meta.xml
<CustomField>
    <fullName>Bypass_PriceRule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to Bypass Static Bundle Price rule</description>
    <label>Bypass PriceRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Lookup_Data_Id__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Data_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used in price rule to calculate Markup Rate if the Support Type = Premium for Software Products</description>
    <label>Lookup Data Id</label>
    <referenceTo>SBQQ__LookupData__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Parent_of_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Parent_of_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicator field for Parent Static and Select Bundle, created as per BIZ-48496</description>
    <label>Parent of Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Allocation_for_Static_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Product_Allocation_for_Static_Bundle__c</fullName>
    <description>This field will be used in Static Bundle price rule which ensures product allocation % is distributed properly in child line items</description>
    <label>Product Allocation for Static Bundle</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Dimension__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Dimension__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</description>
    <inlineHelpText>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</inlineHelpText>
    <label>Price Dimension</label>
    <referenceTo>SBQQ__Dimension__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__PricebookEntryId__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PricebookEntryId__c</fullName>
    <label>Pricebook Entry Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SegmentKey__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SegmentKey__c</fullName>
    <description>For multi-segmented Products, this is a shared key used to group multi-dimensional Quote Lines together.</description>
    <inlineHelpText>For multi-segmented Products, this is a shared key used to group multi-dimensional Quote Lines together.</inlineHelpText>
    <label>Segment Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Skip_OP4I_Sync__c.field-meta.xml
<CustomField>
    <fullName>Skip_OP4I_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To bypass integration for static bundle child products;BIZ-49254</description>
    <label>Skip OP4I Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CloneQuoteLines.cls
/**
* @description       : This class is a utility class for AddStaticBundleHandler.
* @author            : Dhiraj Kumar
* @last modified on  : 09-22-2023
* @last modified by  : Dhiraj Kumar
* Modifications Log
* Ver   Date         Author         Modification
* 1.0   09-22-2023   Dhiraj Kumar   Initial Version
**/
public class CloneQuoteLines {
    
    /**
* @description : Return list of Child Products to be Inserted into the database
* @author Dhiraj Kumar | 09-22-2023 
* @param List<Id> ListOfParentQLI
* Map<Id,List<SBQQ__LookupData__c>> mapOfLookUpDataByQuoteLineId
**/
    public static List<SBQQ__QuoteLine__c> createQuoteLines(List<Id> listOfParentQLIs, Map<Id,List<SBQQ__LookupData__c>> mapOfLookUpDataByQuoteLineId)
    {
        System.debug('CloneQuoteLines Method STARTS --->');
        List<SBQQ__QuoteLine__c> clonedQuoteLines = new List<SBQQ__QuoteLine__c>();
        List<SBQQ__QuoteLine__c> originalQuoteLines = Database.query(allFields('SBQQ__QuoteLine__c')+' Where ID IN : ListOfParentQLIs');
        
        for(SBQQ__QuoteLine__c parentQLI : originalQuoteLines)
        {
            //System.debug('parentQLI : '+ parentQLI.Id);
            If(parentQLI.SBQQ__Quantity__c > 0){
                List<SBQQ__LookupData__c> lookupDataList = new List<SBQQ__LookupData__c>();
                
                if(mapOfLookUpDataByQuoteLineId.containskey(parentQLI.SBQQ__Product__c))
                {
                    lookupDataList=  mapOfLookUpDataByQuoteLineId.get(parentQLI.SBQQ__Product__c);
                }
                
                for(Integer i = 0; i<lookupDataList.size();i++)
                {  
                    SBQQ__QuoteLine__c clonedLineRec = parentQLI.Clone(false, true, false, false);
                    if(clonedLineRec.CurrencyIsoCode == lookupDataList[i].CurrencyIsoCode)
                    {
                        clonedLineRec.SBQQ__Product__c = lookupDataList[i].Child_Product__c;
                        clonedLineRec.SBQQ__RequiredBy__c = parentQLI.Id;
                        clonedLineRec.SBQQ__Dimension__c = lookupDataList[i].Dimension_Id__c;
                        clonedLineRec.SBQQ__PricebookEntryId__c = lookupDataList[i].PriceBookEntry_Id__c;
                        clonedLineRec.SBQQ__CustomerPrice__c =  parentQLI.SBQQ__CustomerPrice__c * (lookupDataList[i].Product_Allocation__c/100);
                        clonedLineRec.SBQQ__SegmentKey__c = lookupDataList[i].SBQQ__Value__c;
                        clonedLineRec.SBQQ__ListPrice__c = parentQLI.SBQQ__ListPrice__c * (lookupDataList[i].Product_Allocation__c/100);
                        clonedLineRec.SBQQ__NetPrice__c = (parentQLI.SBQQ__NetTotal__c * (lookupDataList[i].Product_Allocation__c/100))/parentQLI.SBQQ__Quantity__c;
                        clonedLineRec.Bypass_PriceRule__c = true;
                        clonedLineRec.Lookup_Data_Id__c = lookupDataList[i].Id;
                        clonedLineRec.Product_Allocation_for_Static_Bundle__c = lookupDataList[i].Product_Allocation__c;
                        clonedLineRec.SBQQ__Bundle__c = false;
                        clonedLineRec.Skip_OP4I_Sync__c = true;
                        clonedLineRec.Parent_of_Bundle__c = false;
                        
                        clonedQuoteLines.add(clonedLineRec); 
                    }
                    
                }
            }
        }
        System.debug('CloneQuoteLines Method ENDS --->'+clonedQuoteLines.size());
        return clonedQuoteLines;
    }
    
    public static String allFields(String objectName) {
        List<String> fields = new List<String>(Schema.getGlobalDescribe().get(ObjectName).getDescribe().fields.getMap().keySet());
        String query  = 'SELECT '+String.join(fields, ',')+' FROM '+ObjectName;
        return query;
    }
    
}