force-app/main/default/objects/Contract/fields/Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_1_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Exception_Approval__c.field-meta.xml
<CustomField>
    <fullName>Exception_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, uses Exception Approval process</description>
    <label>Exception Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Exception_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Exception_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exception Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exception_Approver_1_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestContractApprovalHelper.cls
@isTest
private class TestContractApprovalHelper {
	
	@isTest static void testmethodone() {
        
		Account testAccount = IntappTestObjectFactory.createAccount(true); 
		
		Contract testContract = IntappTestObjectFactory.createContract(testAccount.Id);
		testContract.Approver_1__c = UserInfo.getUserId();
		testContract.OwnerId = UserInfo.getUserId();
		insert testContract;
		ContractApprovalHelper.submitForApproval(testContract.Id);
        System.assertNotEquals(testAccount.Id, null);
	}
	
	@isTest static void testmethodtwo() {
		Account testAccount = IntappTestObjectFactory.createAccount(true);
		
		Contract testContract = IntappTestObjectFactory.createContract(testAccount.Id);
		testContract.Exception_Approver_1__c = UserInfo.getUserId();
		testContract.OwnerId = UserInfo.getUserId();
		testContract.Exception_Approval__c = true;
		insert testContract;
		ContractApprovalHelper.submitForApproval(testContract.Id);
        System.assertNotEquals(testAccount.Id, null);
	}
	
}