force-app/main/default/objects/Contract/fields/Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_1_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Approver_2__c.field-meta.xml
<CustomField>
    <fullName>Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_2_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Approver_3__c.field-meta.xml
<CustomField>
    <fullName>Approver_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_3_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Approver_4__c.field-meta.xml
<CustomField>
    <fullName>Approver_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_4_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Approver_5__c.field-meta.xml
<CustomField>
    <fullName>Approver_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 5</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_5_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Approver_6__c.field-meta.xml
<CustomField>
    <fullName>Approver_6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 6</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver_6_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Exception_Approval__c.field-meta.xml
<CustomField>
    <fullName>Exception_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, uses Exception Approval process</description>
    <label>Exception Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Exception_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Exception_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exception Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exception_Approver_1_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Exception_Approver_2__c.field-meta.xml
<CustomField>
    <fullName>Exception_Approver_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exception Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exception_Approver_2_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Exception_Approver_3__c.field-meta.xml
<CustomField>
    <fullName>Exception_Approver_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exception Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exception_Approver_3_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Exception_Approver_4__c.field-meta.xml
<CustomField>
    <fullName>Exception_Approver_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exception Approver 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exception_Approver_4_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Exception_Approver_5__c.field-meta.xml
<CustomField>
    <fullName>Exception_Approver_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exception Approver 5</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exception_Approver_5_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Exception_Approver_6__c.field-meta.xml
<CustomField>
    <fullName>Exception_Approver_6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exception Approver 6</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Services Only</fullName>
            </value>
            <value>
                <fullName>Software Only</fullName>
            </value>
            <value>
                <fullName>Software Co-Term</fullName>
            </value>
            <value>
                <fullName>Services Change Order</fullName>
            </value>
            <value>
                <fullName>Services Change Order (Internal)</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Repstor G-Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractApprovalHelper.cls
/*
 * Helper class for submitting contract for approval
 * Author : Vasu Pulipati (vasu@hiforte.com)
 * Date   : 1/30/2015
 */
 global class ContractApprovalHelper {

    WebService static String submitForApprovalWS(String contractId){
        try{
            submitForApproval(contractId);
            return '';
        }catch(Exception ex){
            if(ex.getMessage().contains('MANAGER_NOT_DEFINED')){
                return 'Please select approver(s) for the contract and try again';
            }
            return ex.getMessage();
        }
    }
    
    //----------------------------------------------------------------------------------------------------------
    // Prepare and submit contract for approval
    //----------------------------------------------------------------------------------------------------------
    public static void submitForApproval(String contractId){
        if(contractId == null || contractId.trim() == ''){
            return;
        }
        List<Contract> lstContracts = [Select Id, Name, Type__c, Exception_Approval__c, 
                                        Approver_1__c, Approver_2__c, Approver_3__c, Approver_4__c, Approver_5__c,
                                        Approver_6__c, 
                                        Exception_Approver_1__c, Exception_Approver_2__c, Exception_Approver_3__c, 
                                        Exception_Approver_4__c, Exception_Approver_5__c, Exception_Approver_6__c
                                       from Contract
                                       where id = :contractId];
        if(lstContracts==null || lstContracts.size()==0){
            System.debug('#### ContractApprovalHelper.submitForApproval(), no contract found for id: '+ contractId);
            return;
        }
        Contract contr = lstContracts[0];
        System.debug('#### ContractApprovalHelper.submitForApproval(), contract: '+ contr);
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setObjectId(contr.Id);
        // Submit on behalf of current user
        req.setSubmitterId(UserInfo.getUserId());
        // Approval process fails if all the approvers are not set. So, check and add dummy approvers if required
        Boolean dummyAdded = false;   
        if(contr.Approver_1__c != null){
            if(contr.Approver_2__c == null){
                contr.Approver_2__c = contr.Approver_1__c;
                dummyAdded = true;
            } 
            if(contr.Approver_3__c == null){
                contr.Approver_3__c = contr.Approver_1__c;
                dummyAdded = true;
            } 
            if(contr.Approver_4__c == null){
                contr.Approver_4__c = contr.Approver_1__c;
                dummyAdded = true;
            } 
            if(contr.Approver_5__c == null){
                contr.Approver_5__c = contr.Approver_1__c;
                dummyAdded = true;
            } 
            if(contr.Approver_6__c == null){
                contr.Approver_6__c = contr.Approver_1__c;
                dummyAdded = true;
            } 
        } 
        if(contr.Exception_Approver_1__c != null){
            if(contr.Exception_Approver_2__c == null){
                contr.Exception_Approver_2__c = contr.Exception_Approver_1__c;
                dummyAdded = true;
            } 
            if(contr.Exception_Approver_3__c == null){
                contr.Exception_Approver_3__c = contr.Exception_Approver_1__c;
                dummyAdded = true;
            } 
            if(contr.Exception_Approver_4__c == null){
                contr.Exception_Approver_4__c = contr.Exception_Approver_1__c;
                dummyAdded = true;
            } 
            if(contr.Exception_Approver_5__c == null){
                contr.Exception_Approver_5__c = contr.Exception_Approver_1__c;
                dummyAdded = true;
            }
            if(contr.Exception_Approver_6__c == null){
                contr.Exception_Approver_6__c = contr.Exception_Approver_1__c;
                dummyAdded = true;
            }
        }
        if(dummyAdded){
            System.debug('#### ContractApprovalHelper.submitForApproval(), dummy approvers added, updating contract.. ');
            update contr;
        }
        
        // Submit the approval request
        //req.setSkipEntryCriteria(true);
        Exception ex = null;
        try{
            System.debug('#### ContractApprovalHelper.submitForApproval(), submitting.. ');
            Approval.ProcessResult result = Approval.process(req);
        }catch(Exception e){
            ex = e;
        }
        // If dummy approvers were added above then remove them
        if(dummyAdded){
            if(contr.Approver_1__c != null){
                if(contr.Approver_2__c == contr.Approver_1__c){
                    contr.Approver_2__c = null;
                } 
                if(contr.Approver_3__c == contr.Approver_1__c){
                    contr.Approver_3__c = null;
                } 
                if(contr.Approver_4__c == contr.Approver_1__c){
                    contr.Approver_4__c = null;
                } 
                if(contr.Approver_5__c == contr.Approver_1__c){
                    contr.Approver_5__c = null;
                }
                if(contr.Approver_6__c == contr.Approver_1__c){
                    contr.Approver_6__c = null;
                }
            } 
            if(contr.Exception_Approver_1__c != null){
                if(contr.Exception_Approver_2__c == contr.Exception_Approver_1__c){
                    contr.Exception_Approver_2__c = null;
                } 
                if(contr.Exception_Approver_3__c == contr.Exception_Approver_1__c){
                    contr.Exception_Approver_3__c = null;
                } 
                if(contr.Exception_Approver_4__c == contr.Exception_Approver_1__c){
                    contr.Exception_Approver_4__c = null;
                } 
                if(contr.Exception_Approver_5__c == contr.Exception_Approver_1__c){
                    contr.Exception_Approver_5__c = null;
                }
                if(contr.Exception_Approver_6__c == contr.Exception_Approver_1__c){
                    contr.Exception_Approver_6__c = null;
                }
            }
            System.debug('#### ContractApprovalHelper.submitForApproval(), dummy approvers removed, updating contract.. ');
            update contr;
        }
        // rethrow exception
        if(ex != null){
            throw ex;
        }
    }
}