force-app/main/default/objects/Contract/fields/Consolidated_Quote__c.field-meta.xml
<CustomField>
    <fullName>Consolidated_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as Part for BIZ-47457. To store the consolidated quote in case of renewal contract consolidation.</description>
    <label>Consolidated Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts (Consolidated Quote)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom field made to populate the Deal type on contract record from op4i.
Built according to US # BIZ-46098
Edited and added values on the basis of BIZ-47145, API values edited according to BIZ-46894</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acquired_Contract</fullName>
                <label>Acquired Contract</label>
            </value>
            <value>
                <fullName>AddOn</fullName>
                <label>Add-On</label>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Contract_Replacement</fullName>
                <label>Contract Replacement</label>
            </value>
            <value>
                <fullName>Expansion</fullName>
            </value>
            <value>
                <fullName>New_Software</fullName>
                <label>New Software</label>
            </value>
            <value>
                <fullName>Next Year_Multi-Year</fullName>
                <label>Next Year, Multi-Year</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Platform Conversion_INTERNAL</fullName>
                <label>Platform Conversion - Internal</label>
            </value>
            <value>
                <fullName>Platform_Fee</fullName>
                <label>Platform Fee</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Services_Only</fullName>
                <label>Services Only</label>
            </value>
            <value>
                <fullName>Services_Replacement</fullName>
                <label>Services Replacement</label>
            </value>
            <value>
                <fullName>Uplift</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__RenewedContract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
    <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
    <label>Renewed Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>RenewalOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-47145</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/OP4I_Deal_Name__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_Name__c</fullName>
    <label>Deal Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/OP4IDealID__c.field-meta.xml
<CustomField>
    <fullName>OP4IDealID__c</fullName>
    <externalId>true</externalId>
    <label>OP4I Deal ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-45119.</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Deal_Name__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_Name__c</fullName>
    <label>OP4I Deal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4IDealID__c.field-meta.xml
<CustomField>
    <fullName>OP4IDealID__c</fullName>
    <description>This is a reference ID of Deal ID</description>
    <externalId>true</externalId>
    <label>OP4I Deal ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Stage__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stage__c</fullName>
    <description>Sales user should be able to move a Quote to the Pricing Proposal stage when ready to create a Pricing Proposal Document, built as per BIZ-45102
Updated for story BIZ-49730..</description>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Configure Products</fullName>
                <default>true</default>
                <label>Configure Products</label>
            </value>
            <value>
                <fullName>Pricing Proposal</fullName>
            </value>
            <value>
                <fullName>Finalize OSA</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Contract Executed</fullName>
            </value>
            <value>
                <fullName>Closed-Lost</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Forecast</fullName>
                <isActive>false</isActive>
                <label>Forecast</label>
            </value>
            <value>
                <fullName>OSA</fullName>
                <isActive>false</isActive>
                <label>OSA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Renewal_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Quote_Type__c</fullName>
    <description>Created as part of BIZ-47716, to specify the renewal Quote type.
Auto Renewal - Created Automatically by the system when renewal quoted is selected on the contract.
Renewal-Changes - Created by cloning Auto-Renewal Quotes.
COntract consolidation - created while consolidating contracts</description>
    <label>Renewal Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto-Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal-Changes</fullName>
            </value>
            <value>
                <fullName>Consolidated-Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/StaticBundleIds__c.field-meta.xml
<CustomField>
    <fullName>StaticBundleIds__c</fullName>
    <description>Capture Parent Id of Static Bundles, will not be placed in page layout. used in AddStaticBundleHandler class. Created as per BIZ-47580</description>
    <label>StaticBundleIds</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Draft_Quote.recordType-meta.xml
<RecordType>
    <fullName>Draft_Quote</fullName>
    <active>true</active>
    <label>Draft Quote</label>
</RecordType>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Renewed_Subscription_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewed_Subscription_End_Date__c</fullName>
    <formula>SBQQ__RenewedSubscription__r.SBQQ__EndDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewed Subscription End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Dimension__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Dimension__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</description>
    <inlineHelpText>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</inlineHelpText>
    <label>Price Dimension</label>
    <referenceTo>SBQQ__Dimension__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
    <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SegmentIndex__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SegmentIndex__c</fullName>
    <description>For multi-segmented Products, Index representing this Quote Line&apos;s position in the segment table.</description>
    <inlineHelpText>For multi-segmented Products, Index representing this Quote Line&apos;s position in the segment table.</inlineHelpText>
    <label>Segment Index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SegmentKey__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SegmentKey__c</fullName>
    <description>For multi-segmented Products, this is a shared key used to group multi-dimensional Quote Lines together.</description>
    <inlineHelpText>For multi-segmented Products, this is a shared key used to group multi-dimensional Quote Lines together.</inlineHelpText>
    <label>Segment Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired_Contract</fullName>
        <label>Acquired Contract</label>
    </customValue>
    <customValue>
        <fullName>Add-On</fullName>
        <label>Add-On Amendment</label>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Contract_Replacement</fullName>
        <label>Contract Replacement</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New_Software</fullName>
        <label>New Software</label>
    </customValue>
    <customValue>
        <fullName>NextYear_MultiYear</fullName>
        <label>Next Year, Multi-Year</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PlatformConversion_INTERNAL</fullName>
        <label>Platform Conversion - Internal</label>
    </customValue>
    <customValue>
        <fullName>Platform_Fee</fullName>
        <label>Platform Fee</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Services_Only</fullName>
        <label>Services Only</label>
    </customValue>
    <customValue>
        <fullName>Services_Replacement</fullName>
        <label>Services Replacement</label>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
    </customValue>
    <description>Modified as part of BIZ-46501</description>
    <masterLabel>Deal Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CloneQuote.cls
/**
 * @description       :  class for Renewal based Contract Consolidation
 * @author            : Keerthan N
 * Jira story : BIZ-47457
**/
global without sharing class  CloneQuote {
    
    // FINAL Static String PERFORMA_INVOICE_STATUS_WORKING_WITH_CUSTOMER = 'Working with Customer for changes';
     
     public class InputVariables{
         @InvocableVariable
         public List<Id> contractIdList;
         @InvocableVariable
         public Date startDate;
     }
     
     public class ReturnVariables{
         @InvocableVariable
         public SBQQ__Quote__c consolidatedQuote;
     }
     
     @InvocableMethod(label='Duplicate Renewal Quote' description='Method to clone Quote And Quote Lines for Renewal')
     public static List<ReturnVariables> duplicateQuote(List<InputVariables> inputVariables){
         try{
             System.debug('InputVariables.get(0).contractIdList '+ inputVariables.get(0).contractIdList);
             Date startDate = inputVariables.get(0).startDate;
             Map<Id,Contract> contrMap = new Map<Id,Contract>([Select Id,AccountId,Consolidated_Quote__c From Contract where Id In : inputVariables.get(0).contractIdList Order by CreatedDate]);
             List<SBQQ__Quote__c> quotList = [Select Id,SBQQ__Account__c,Name,currencyIsoCode,Deal_Type__c,SBQQ__Opportunity2__r.SBQQ__RenewedContract__c,SBQQ__Opportunity2__c,SBQQ__StartDate__c From SBQQ__Quote__c Where SBQQ__Opportunity2__r.SBQQ__RenewedContract__c In : contrMap.keyset() And Renewal_Quote_Type__c =: ConstantUtilityClass.AUTORENEWAL Order By SBQQ__StartDate__c Asc];
             Id quot1Id = quotList[0].Id;
             //System.debug('quotList'+quotList);  
             SBQQ__Quote__c originalquot = Database.query(allFields('SBQQ__Quote__c')+' Where Id =: quot1Id Limit 1');
             SBQQ__Quote__c quot = originalquot.Clone(false, true, false, false);
             Id devRecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('Draft_Quote').getRecordTypeId();
             quot.SBQQ__Opportunity2__c = quotList[0].SBQQ__Opportunity2__c;//opp.Id;
             quot.OwnerId = UserInfo.getUserId();
             quot.SBQQ__Primary__c = False;
             //quot.OP4IDealID__c = dealId;
             //quot.OP4I_Deal_Name__c = dealId;
             quot.SBQQ__Account__c = quotList[0].SBQQ__Account__c;
             quot.recordTypeId = devRecordTypeId;
             quot.Deal_Type__c = quotList[0].Deal_Type__c;
             quot.CurrencyIsoCode = quotList[0].currencyIsoCode;
             quot.Renewal_Quote_Type__c = System.Label.Consolidated_Quote;
             quot.SBQQ__ContractingMethod__c = ConstantUtilityClass.SINGLECONTRACT;
             quot.SBQQ__StartDate__c = startDate;
             quot.SBQQ__EndDate__c = null;
             quot.Quote_Stage__c = System.Label.Configure_Products;
             //quot.StaticBundleIds__c = '';
             Insert quot;
             List<SBQQ__QuoteLine__c> originalQuoteLines = Database.query(allFields('SBQQ__QuoteLine__c')+' Where SBQQ__Quote__c =: quotList');
             If(originalQuoteLines.size() > 0){
                 List<SBQQ__QuoteLine__c> clonedQuoteLines = new List<SBQQ__QuoteLine__c>();
                 //create renewal lines
                 for(SBQQ__QuoteLine__c ql : originalQuoteLines){
                     SBQQ__QuoteLine__c clonedLineRec = ql.Clone(false, true, false, false);
                     clonedLineRec.SBQQ__Quote__c = quot.Id;
                     clonedLineRec.SBQQ__StartDate__c = startDate;
                     //Include Select Bundle Products and Stand alone products and Static bundle parent products.
                     If(String.isBlank(ql.SBQQ__RequiredBy__c) || ql.Required_By_Product_Code__c==ConstantUtilityClass.SELECTBUNDLECODE){
                         clonedQuoteLines.add(clonedLineRec);
                     }
                     //Populate Select Bundle Field
                     If(ql.SBQQ__ProductCode__c == ConstantUtilityClass.SELECTBUNDLECODE){
                         clonedLineRec.Cloned_Select_Bundle_Id__c = ql.Id;
                     }
                 }
                 //create negative lines
                 for(SBQQ__QuoteLine__c ql : originalQuoteLines){
                     If((ql.SBQQ__Quote__c != quotList[0].Id)||(quotList[0].SBQQ__StartDate__c != startDate)){
                         SBQQ__QuoteLine__c clonedLineRec = ql.Clone(false, true, false, false);
                         clonedLineRec.SBQQ__Quote__c = quot.Id;
                         clonedLineRec.SBQQ__StartDate__c = startDate;
                         clonedLineRec.SBQQ__EndDate__c = ql.Renewed_Subscription_End_Date__c;
                         clonedLineRec.SBQQ__Quantity__c = clonedLineRec.SBQQ__Quantity__c * -1;
                         clonedLineRec.SBQQ__SegmentIndex__c = null;
                         clonedLineRec.SBQQ__SegmentLabel__c = null;
                         clonedLineRec.SBQQ__SegmentKey__c = null;
                         clonedLineRec.SBQQ__Dimension__c = null;
                         //Populate Select Bundle Field
                         If(ql.SBQQ__ProductCode__c == ConstantUtilityClass.SELECTBUNDLECODE){
                             clonedLineRec.Cloned_Select_Bundle_Id__c = ql.Id;
                         }
                         //clonedQuoteLines.add(clonedLineRec);
                         If((String.isBlank(ql.SBQQ__RequiredBy__c) || ql.Required_By_Product_Code__c==ConstantUtilityClass.SELECTBUNDLECODE) &&(startDate <= ql.Renewed_Subscription_End_Date__c)){
                             clonedQuoteLines.add(clonedLineRec);
                         }
                         
                     }
                 }
                 If(clonedQuoteLines.size() > 0){
                     Insert clonedQuoteLines;
                 }
                 Map<String,Id> selectBundleId = new Map<String,Id>();
                 List<SBQQ__QuoteLine__c> updateLines = new List<SBQQ__QuoteLine__c>();
                 for(SBQQ__QuoteLine__c ql : clonedQuoteLines){
                     if(ql.Cloned_Select_Bundle_Id__c != Null && ql.SBQQ__Quantity__c < 0){
                         selectBundleId.put(ql.Cloned_Select_Bundle_Id__c+'-',ql.Id);
                     }
                     else if(ql.Cloned_Select_Bundle_Id__c != Null && ql.SBQQ__Quantity__c >= 0){
                         selectBundleId.put(ql.Cloned_Select_Bundle_Id__c+'+',ql.Id);
                     }
                 }
                 System.debug('selectBundleId'+selectBundleId);
                 for(SBQQ__QuoteLine__c ql : clonedQuoteLines){
                     //System.debug('ql.SBQQ__RequiredBy__c'+ql.SBQQ__RequiredBy__c);
                     //System.debug('ql.Required_By_Product_Code__c'+ql.Required_By_Product_Code__c);
                     //System.debug('ql.SBQQ__RequiredBy__c+String.valueOf(ql.SBQQ__Quantity__c).substring(0,1)'+ql.SBQQ__RequiredBy__c+String.valueOf(ql.SBQQ__Quantity__c).substring(0,1));
                     if(ql.SBQQ__RequiredBy__c != Null && ql.Required_By_Product_Code__c==ConstantUtilityClass.SELECTBUNDLECODE && ql.SBQQ__Quantity__c >= 0 && selectBundleId.containsKey(ql.SBQQ__RequiredBy__c+'+')){
                             ql.SBQQ__RequiredBy__c = selectBundleId.get(ql.SBQQ__RequiredBy__c+'+');
                             updateLines.add(ql);
                         }
                     else if(ql.SBQQ__RequiredBy__c != Null && ql.Required_By_Product_Code__c==ConstantUtilityClass.SELECTBUNDLECODE && ql.SBQQ__Quantity__c < 0 && selectBundleId.containsKey(ql.SBQQ__RequiredBy__c+'-')){
                             ql.SBQQ__RequiredBy__c = selectBundleId.get(ql.SBQQ__RequiredBy__c+'-');
                             updateLines.add(ql);
                         }
                     }
                 System.debug('updateLines'+updateLines);
                 If(updateLines.size() > 0){
                     Update updateLines;
                 }
             }
             List<ReturnVariables> outputVariables = new List<ReturnVariables>();
             ReturnVariables outputVariable = new ReturnVariables();
             outputVariable.consolidatedQuote = quot;
             outputVariables.add(outputVariable);
             return outputVariables;
         }
         catch(Exception e){
             System.debug('Exception : '+e);
             return null;
         }
        
     }
     
     
     public static String allFields(String objectName) {
         List<String> fields = new List<String>(Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap().keySet());
         String query  = 'SELECT '+String.join(fields, ',')+' FROM '+objectName;
         return query;
     }
 }