force-app/main/default/objects/Contract/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom field made to populate the Deal type on contract record from op4i.
Built according to US # BIZ-46098
Edited and added values on the basis of BIZ-47145, API values edited according to BIZ-46894</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acquired_Contract</fullName>
                <label>Acquired Contract</label>
            </value>
            <value>
                <fullName>AddOn</fullName>
                <label>Add-On</label>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Contract_Replacement</fullName>
                <label>Contract Replacement</label>
            </value>
            <value>
                <fullName>Expansion</fullName>
            </value>
            <value>
                <fullName>New_Software</fullName>
                <label>New Software</label>
            </value>
            <value>
                <fullName>Next Year_Multi-Year</fullName>
                <label>Next Year, Multi-Year</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Platform Conversion_INTERNAL</fullName>
                <label>Platform Conversion - Internal</label>
            </value>
            <value>
                <fullName>Platform_Fee</fullName>
                <label>Platform Fee</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Services_Only</fullName>
                <label>Services Only</label>
            </value>
            <value>
                <fullName>Services_Replacement</fullName>
                <label>Services Replacement</label>
            </value>
            <value>
                <fullName>Uplift</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/OP4I_Deal_ID__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_ID__c</fullName>
    <description>Custom field made to populate the Deal Id on contract record from op4i.
Built according to US # BIZ-46098</description>
    <label>OP4I Deal ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContractAmendController.cls
/**
* @description       : Controller class for LWC Component
* @author            : Vivek Singh
* Jira story : BIZ-46098
**/
public with sharing class ContractAmendController {

    //class to populate amendment details and land on contract record page.
    @AuraEnabled
    public static String updateContract(String contractId, String dealId, String dealType){
            try{
                
                List<Contract> contractLstToUpdate = new List<Contract>();
                Contract contractRecord = [Select Id From Contract Where Id =: contractId Limit 1];

                if(contractRecord != null){
                     contractRecord.Deal_Type__c =dealType;
                    contractRecord.OP4I_Deal_ID__c = dealId;
                    contractLstToUpdate.add(contractRecord);

                    if(contractLstToUpdate != null && !contractLstToUpdate.isEmpty()){
                        Database.update(contractLstToUpdate);
                    }

                }
                else{

                        return 'Error;'+'Contract not found. Please enter a valid Contract Id';
                    }
                return 'Success;'+contractRecord.Id; 
                
            }
            catch(Exception e){
                System.debug('Exception :'+e);
                return 'Error;'+e.getMessage();
            }
    }
}