force-app/main/default/objects/Contract/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom field made to populate the Deal type on contract record from op4i.
Built according to US # BIZ-46098
Edited and added values on the basis of BIZ-47145, API values edited according to BIZ-46894</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acquired_Contract</fullName>
                <label>Acquired Contract</label>
            </value>
            <value>
                <fullName>AddOn</fullName>
                <label>Add-On</label>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Contract_Replacement</fullName>
                <label>Contract Replacement</label>
            </value>
            <value>
                <fullName>Expansion</fullName>
            </value>
            <value>
                <fullName>New_Software</fullName>
                <label>New Software</label>
            </value>
            <value>
                <fullName>Next Year_Multi-Year</fullName>
                <label>Next Year, Multi-Year</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Platform Conversion_INTERNAL</fullName>
                <label>Platform Conversion - Internal</label>
            </value>
            <value>
                <fullName>Platform_Fee</fullName>
                <label>Platform Fee</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Services_Only</fullName>
                <label>Services Only</label>
            </value>
            <value>
                <fullName>Services_Replacement</fullName>
                <label>Services Replacement</label>
            </value>
            <value>
                <fullName>Uplift</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>In Processing</fullName>
            </value>
            <value>
                <fullName>Migrated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
            <value>
                <fullName>ACV Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Associated_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated OSA</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semiannual</fullName>
            </value>
            <value>
                <fullName>Quarterly Y1 Only</fullName>
            </value>
            <value>
                <fullName>Semi-annual Y1 Only</fullName>
            </value>
            <value>
                <fullName>Invoice Plan</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>No Software</fullName>
            </value>
            <value>
                <fullName>XXXXX</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due on receipt</fullName>
            </value>
            <value>
                <fullName>Net 7</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Net 120</fullName>
            </value>
            <value>
                <fullName>XXXXX</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>No Software</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
            <value>
                <fullName>ACV Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>This is the date that the billing pause ends and the billing restarts.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Migration_Contract__c.field-meta.xml
<CustomField>
    <fullName>Migration_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Migration Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Migration Contract)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>This is the date the the billing pause begins.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-47145</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-45119.</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <inlineHelpText>&apos;First invoice period (number of months)</inlineHelpText>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Migration_Contract__c.field-meta.xml
<CustomField>
    <fullName>Migration_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Migration Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quotes (Migration Contract)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Re-Quote</fullName>
            </value>
            <value>
                <fullName>Migration Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired_Contract</fullName>
        <label>Acquired Contract</label>
    </customValue>
    <customValue>
        <fullName>Add-On</fullName>
        <label>Add-On Amendment</label>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Contract_Replacement</fullName>
        <label>Contract Replacement</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New_Software</fullName>
        <label>New Software</label>
    </customValue>
    <customValue>
        <fullName>NextYear_MultiYear</fullName>
        <label>Next Year, Multi-Year</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PlatformConversion_INTERNAL</fullName>
        <label>Platform Conversion - Internal</label>
    </customValue>
    <customValue>
        <fullName>Platform_Fee</fullName>
        <label>Platform Fee</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Services_Only</fullName>
        <label>Services Only</label>
    </customValue>
    <customValue>
        <fullName>Services_Replacement</fullName>
        <label>Services Replacement</label>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
    </customValue>
    <description>Modified as part of BIZ-46501</description>
    <masterLabel>Deal Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/OpportunityQuoteMigrationBatch.cls
//Batch Opportunity creation for Migration Data
global class OpportunityQuoteMigrationBatch implements Database.Batchable<sObject> {
    List<string> lstOfContractAssignment;
    global OpportunityQuoteMigrationBatch(List<string> lstOfContractNumbers){
      lstOfContractAssignment = lstOfContractNumbers ;
    }
    global OpportunityQuoteMigrationBatch() {}

    global Database.QueryLocator start(Database.BatchableContext bc){
        string endCondition;
        if (lstOfContractAssignment != null && !lstOfContractAssignment.isempty()) {
            for (string endDigit : lstOfContractAssignment) {
                endCondition = endCondition != null? (endCondition +  ' OR ContractNumber like \'%' + endDigit + '\'') :' ContractNumber like \'%' + endDigit + '\'';
            }
        } 
        String query = 'SELECT Id,Migration_Status__c,ContractNumber '
                     + 'FROM Contract WHERE Migration_Status__c = \'Ready\'';            
        query = endCondition != null? query + ' AND (' + endCondition + ')' : query;
        system.debug('Start Query' +query);     
        return Database.getQueryLocator(query);        
    }
    
    global void execute(Database.BatchableContext bc, List<Contract> lstOfContracts){
        List<OP4I_Entitlement_View__c> lstOfEntitlementToProcessOpportunity = new List<OP4I_Entitlement_View__c>();
        List<OP4I_Entitlement_View__c> lstOfEntitlementToProcessQuote = new List<OP4I_Entitlement_View__c>();
        List<OP4I_Entitlement_View__c> lstOfEntitlementsExistingOpp = new List<OP4I_Entitlement_View__c>();
        List<OP4I_Entitlement_View__c> lstOfEntitlementsExistingQuote = new List<OP4I_Entitlement_View__c>();
        List<OP4I_Entitlement_View__c> lstOfEntitlementRecords = new List<OP4I_Entitlement_View__c>();
        List<Contract> lstOfContractsToUpdate = new List<Contract>();
        set<id> setOfContractIds = new set<id>();
        Map<String,Opportunity> mapOfContractToOpportunity = new Map<String,Opportunity>();
        Map<String,SBQQ__Quote__c> mapOfContractToQuote = new Map<String,SBQQ__Quote__c>();
        Map<String,Opportunity> mapOfContractToOpportunityCreate = new Map<String,Opportunity>();
        Map<String,SBQQ__Quote__c> mapOfContractToQuoteCreate = new Map<String,SBQQ__Quote__c>();
        if(!lstOfContracts.IsEmpty())
        {
            
          system.debug('listOfOCntracts' +lstOfContracts[0].ContractNumber);    
          lstOfEntitlementRecords = [SELECT Id,DLIP_Id__c,Account__c,CurrencyIsoCode,Associated_OSA__c,Account__r.Name,Associated_OSA__r.ContractNumber,Opportunity__c,
                                    Processing_Status__c,Start_Date__c,Deal_Type__c,Total_Contract_Months__c,First_Segment_Months__c,Billing_Frequency__c,
                                    Payment_Terms__c,Associated_OSA__r.Migration_Status__c,Associated_OSA__r.Processing_Status__c,End_Date__c
                                    FROM OP4I_Entitlement_View__c WHERE Associated_OSA__c IN: lstOfContracts ORDER BY Start_Date__c ASC NULLS LAST];  
            if(!lstOfEntitlementRecords.IsEmpty()){                                 
              for(OP4I_Entitlement_View__c entitlement : lstOfEntitlementRecords)
              {
                setOfContractIds.add(entitlement.Associated_OSA__c); 
                entitlement.Migration_Status__c = 'In Processing'; 
                entitlement.Associated_OSA__r.Migration_Status__c = 'In Processing';
                entitlement.Error_Log__c = '';
                if(!lstOfContractsToUpdate.contains(entitlement.Associated_OSA__r))
                {
                  lstOfContractsToUpdate.add(entitlement.Associated_OSA__r); 
                }             
              }
              update lstOfEntitlementRecords;
              update lstOfContractsToUpdate;
            } 
            
            List<Opportunity> existingOpp = [Select Id,Migration_Contract__c FROM Opportunity WHERE Migration_Contract__c IN: setOfContractIds];
            if(!existingOpp.IsEmpty())
            {
            for(Opportunity oppObj : existingOpp)
            {
            mapOfContractToOpportunity.put(oppObj.Migration_Contract__c , oppObj);
            }
            }
            
            for(OP4I_Entitlement_View__c entitlement : lstOfEntitlementRecords)
            {             
            if(mapOfContractToOpportunity.containskey(entitlement.Associated_OSA__c))
            {
            entitlement.Opportunity__c = mapOfContractToOpportunity.get(entitlement.Associated_OSA__c).id;
            entitlement.Processing_Status__c = 'Opportunity Created';
            entitlement.Associated_OSA__r.Processing_Status__c = 'Opportunity Created';
            lstOfEntitlementsExistingOpp.add(entitlement);
            if(!lstOfContractsToUpdate.contains(entitlement.Associated_OSA__r))
            {
              lstOfContractsToUpdate.add(entitlement.Associated_OSA__r);
            }
            }
            else
            {
                if(!mapOfContractToOpportunityCreate.containskey(entitlement.Associated_OSA__c))
                { 
                Opportunity migrateOpportunity = createOpportunity(entitlement);
                mapOfContractToOpportunityCreate.put(entitlement.Associated_OSA__c,migrateOpportunity);
                }   
                lstOfEntitlementToProcessOpportunity.add(entitlement);               
            }           
            }
            
            if(!lstOfEntitlementsExistingOpp.IsEmpty())
            {
              update lstOfEntitlementsExistingOpp;
            }
            
            if(!lstOfContractsToUpdate.IsEmpty())
            {
              update lstOfContractsToUpdate;    
            }
                
            if(!mapOfContractToOpportunityCreate.IsEmpty())
            {                    
            updateOpportunityAndEntitlement(mapOfContractToOpportunityCreate,lstOfEntitlementToProcessOpportunity);
            }
                    
            List<SBQQ__Quote__c> existingQuote = [Select Id,Migration_Contract__c FROM SBQQ__Quote__c WHERE Migration_Contract__c IN: setOfContractIds];
            if(!existingQuote.IsEmpty())
            {
            for(SBQQ__Quote__c quoteObj : existingQuote)
            {
            mapOfContractToQuote.put(quoteObj.Migration_Contract__c , quoteObj);
            }
            }
            
            for(OP4I_Entitlement_View__c entitlement : lstOfEntitlementRecords)
            {             
            if(mapOfContractToQuote.containskey(entitlement.Associated_OSA__c))
            {
                entitlement.Quote__c = mapOfContractToQuote.get(entitlement.Associated_OSA__c).id;
                entitlement.Processing_Status__c = 'Quote Created';
                entitlement.Associated_OSA__r.Processing_Status__c = 'Quote Created';
                lstOfEntitlementsExistingQuote.add(entitlement);
                if(!lstOfContractsToUpdate.contains(entitlement.Associated_OSA__r))
                {
                  lstOfContractsToUpdate.add(entitlement.Associated_OSA__r);
                }
            }
            else
            {
            if(!mapOfContractToQuoteCreate.containskey(entitlement.Associated_OSA__c))
            { 
            SBQQ__Quote__c migrateQuote = createQuote(entitlement , entitlement.Opportunity__c);
            mapOfContractToQuoteCreate.put(entitlement.Associated_OSA__c,migrateQuote);
            } 
            lstOfEntitlementToProcessQuote.add(entitlement);             
            }            
            }
            
            if(!lstOfEntitlementsExistingQuote.IsEmpty())
            {
            update lstOfEntitlementsExistingQuote;
            }
            
            if(!lstOfContractsToUpdate.IsEmpty())
            {
              update lstOfContractsToUpdate;    
            }
                
            if(!mapOfContractToQuoteCreate.IsEmpty())
            {                    
            updateQuoteAndEntitlement(mapOfContractToQuoteCreate,lstOfEntitlementToProcessQuote);
            }
        }         
    }
    
    global void finish(Database.BatchableContext bc){
       
    }
       
    global static opportunity createOpportunity(OP4I_Entitlement_View__c entitlement)
    {
        Opportunity oppMigration = new Opportunity();
        String oppName = entitlement.Account__r.Name + '' + '|' + '' + entitlement.Associated_OSA__r.ContractNumber + '' + '|' + '' + 'Migration Opportunity';        
        String opportunityName = OppName.length()>80 ? OppName.substring(0,80) : OppName;
        oppMigration.Name = opportunityName;    
        oppMigration.AccountId = entitlement.Account__c;
        oppMigration.CloseDate = system.today();
        oppMigration.StageName = 'Closed - Migration';
        oppMigration.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
                                .get('Migration_Opportunity').getRecordTypeId();
        oppMigration.Migration_Contract__c = entitlement.Associated_OSA__c;
        oppMigration.CurrencyIsoCode = entitlement.CurrencyIsoCode;
        return oppMigration;    
    }  

   global static SBQQ__Quote__c createQuote(OP4I_Entitlement_View__c entitlement , Id oppMigrationId)
   {
        SBQQ__Quote__c quoteMigration = new SBQQ__Quote__c();
        quoteMigration.SBQQ__Account__c = entitlement.Account__c;
        quoteMigration.SBQQ__StartDate__c = entitlement.Start_Date__c;
        quoteMigration.SBQQ__Opportunity2__c = oppMigrationId;
        quoteMigration.SBQQ__Type__c = 'Migration Quote';
        quoteMigration.CurrencyIsoCode = entitlement.CurrencyIsoCode;
        quoteMigration.SBQQ__FirstSegmentTermEndDate__c = entitlement.End_Date__c;
        if(entitlement.Deal_Type__c == 'Renewal')
        {
            quoteMigration.SBQQ__SubscriptionTerm__c = 12;
            quoteMigration.First_Segment_Months__c = 12;
        }
        else
        {
            quoteMigration.SBQQ__SubscriptionTerm__c = entitlement.Total_Contract_Months__c;
            quoteMigration.First_Segment_Months__c = entitlement.First_Segment_Months__c;
        }
        quoteMigration.SBQQ__Primary__c = true;
        if(entitlement.Billing_Frequency__c == 'Annually')
        {
        quoteMigration.SBQQ__BillingFrequency__c = 'Annual';
        }
        else
        {
        quoteMigration.SBQQ__BillingFrequency__c =entitlement.Billing_Frequency__c;
        }
        quoteMigration.Software_Payment_Terms__c = entitlement.Payment_Terms__c; 
        quoteMigration.SBQQ__PaymentTerms__c = entitlement.Payment_Terms__c; 
        quoteMigration.Migration_Contract__c = entitlement.Associated_OSA__c;     
        return quoteMigration;  
    } 


    global static void updateOpportunityAndEntitlement(Map<String,Opportunity> mapOfContractToOpportunityCreate,List<OP4I_Entitlement_View__c> lstOfEntitlementToProcessOpportunity)
    {
        List<Contract> lstOfContractsToUpdate = new List<Contract>();
        List<Opportunity> opportunityList = mapOfContractToOpportunityCreate.values();
        Database.SaveResult[] opportunitySaveResultList = Database.insert(opportunityList,false); 
        map<string,string> resultMap = HandleCustomException.logMigrationDatabaseError(
            opportunitySaveResultList,
            mapOfContractToOpportunityCreate,
            'Migration_Contract__c',
            opportunityList
        );
        
        string keyFields = 'Associated_OSA__c';
        for(OP4I_Entitlement_View__c entitlement : lstOfEntitlementToProcessOpportunity) {             
            if(mapOfContractToOpportunityCreate.containskey(entitlement.Associated_OSA__c)) {
                string key = HandleCustomException.getKey(keyFields, entitlement);
                if (resultMap.containsKey(key)) {
                    entitlement.Processing_Status__c = 'Opportunity Creation Failed';
                    entitlement.Error_Log__c = resultMap.get(key);
                    entitlement.Associated_OSA__r.Processing_Status__c = 'Opportunity Creation Failed';
                } else {
                    entitlement.Opportunity__c = mapOfContractToOpportunityCreate.get(entitlement.Associated_OSA__c).id;
                    entitlement.Processing_Status__c = 'Opportunity Created';
                    entitlement.Associated_OSA__r.Processing_Status__c = 'Opportunity Created';
                }

                if(!lstOfContractsToUpdate.contains(entitlement.Associated_OSA__r)) {
                    lstOfContractsToUpdate.add(entitlement.Associated_OSA__r);
                }
            }
        }

        Database.SaveResult[] entitlementListOpp = Database.update(lstOfEntitlementToProcessOpportunity, false);
        HandleCustomException.logDatabaseErrors(entitlementListOpp); 
        
        Database.SaveResult[] contrList = Database.update(lstOfContractsToUpdate, false);
        HandleCustomException.logDatabaseErrors(contrList);         
    }   

    global static void updateQuoteAndEntitlement(Map<String,SBQQ__Quote__c> mapOfContractToQuoteCreate,List<OP4I_Entitlement_View__c> lstOfEntitlementToProcessQuote)
    {
        List<Contract> lstOfContractsToUpdate = new List<Contract>();
        List<SBQQ__Quote__c> quoteList = mapOfContractToQuoteCreate.values();
        Database.SaveResult[] quoteSaveResultList = Database.insert(quoteList, false); 
        //HandleCustomException.logDatabaseErrorsForEntitlements(quoteList,mapOfContractToQuoteCreate);
        map<string,string> resultMap = HandleCustomException.logMigrationDatabaseError(
            quoteSaveResultList,
            mapOfContractToQuoteCreate,
            'Migration_Contract__c',
            quoteList
        );
        
        string keyFields = 'Associated_OSA__c';
        for(OP4I_Entitlement_View__c entitlement : lstOfEntitlementToProcessQuote) {             
            if(mapOfContractToQuoteCreate.containskey(entitlement.Associated_OSA__c)){
                string key = HandleCustomException.getKey(keyFields, entitlement);
                if (resultMap.containsKey(key)) {
                    entitlement.Processing_Status__c = 'Quote Creation Failed';
                    entitlement.Error_Log__c = resultMap.get(key);
                    entitlement.Associated_OSA__r.Processing_Status__c = 'Quote Creation Failed';
                } else {
                    entitlement.Quote__c = mapOfContractToQuoteCreate.get(entitlement.Associated_OSA__c).id;
                    entitlement.Processing_Status__c = 'Quote Created';
                    entitlement.Associated_OSA__r.Processing_Status__c = 'Quote Created';
                }

                if(!lstOfContractsToUpdate.contains(entitlement.Associated_OSA__r)) {
                    lstOfContractsToUpdate.add(entitlement.Associated_OSA__r);
                }
            }
        }
        
        Database.SaveResult[] entitlementListQuote = Database.update(lstOfEntitlementToProcessQuote, false);
        HandleCustomException.logDatabaseErrors(entitlementListQuote);

        Database.SaveResult[] contrList = Database.update(lstOfContractsToUpdate, false);
        HandleCustomException.logDatabaseErrors(contrList);     
    }       
}