force-app/main/default/objects/Contract/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>In Processing</fullName>
            </value>
            <value>
                <fullName>Migrated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
            <value>
                <fullName>ACV Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Associated_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated OSA</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
            <value>
                <fullName>ACV Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BIZ-45643</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteEntitlementView.cls
global class DeleteEntitlementView implements Database.Batchable<sObject> {
    global set<string> entitlementIds = new set<string>();
    global deleteEntitlementView(set<string> entitlementsToProcess){
       entitlementIds = entitlementsToProcess; 
    }
    global deleteEntitlementView(){
            
    }
    global Database.QueryLocator start(Database.BatchableContext bc){
        String query;
        if(entitlementIds.size()>0)
        {
         query = 'SELECT Id,Opportunity__c,Quote__c,Order__c,Associated_OSA__c,Associated_OSA__r.Processing_Status__c'
                 +',Associated_OSA__r.Migration_Status__c FROM OP4I_Entitlement_View__c '
                 +'Where ID IN: entitlementIds'; 
        }
        else
        {
         query = 'SELECT Id,Opportunity__c,Quote__c,Order__c,Associated_OSA__c,Associated_OSA__r.Processing_Status__c'
                 +',Associated_OSA__r.Migration_Status__c FROM OP4I_Entitlement_View__c';
        }
        return Database.getQueryLocator(query);        
    }
    
    global void execute(Database.BatchableContext bc, List<OP4I_Entitlement_View__c> lstOfEntitlementRecords){
      List<Opportunity> lstOfOpportunity = new List<Opportunity>();
      List<SBQQ__Quote__c> lstOfQuotes = new List<SBQQ__Quote__c>();
      set<id> setOfOpportunityIds = new set<id>();
      set<id> setOfQuoteIds = new set<id>();
      set<id> setOfOrderIds = new set<id>();
      List<SBQQ__QuoteLine__c> lstOfQuoteLines = new List<SBQQ__QuoteLine__c>();
      List<Contract> lstOfContractsToUpdate = new List<Contract>();
      if(!lstOfEntitlementRecords.IsEmpty())
      {
        for(OP4I_Entitlement_View__c entitlement : lstOfEntitlementRecords)
        {
         if(entitlement.Associated_OSA__c!=null)
         {
         entitlement.Associated_OSA__r.Processing_Status__c = '';
         entitlement.Associated_OSA__r.Migration_Status__c = '';
         if(!lstOfContractsToUpdate.contains(entitlement.Associated_OSA__r))
         lstOfContractsToUpdate.add(entitlement.Associated_OSA__r);
         }
         if(entitlement.Quote__c!=null)
         setOfQuoteIds.add(entitlement.Quote__c);
         if(entitlement.Opportunity__c!=null) 
         setOfOpportunityIds.add(entitlement.Opportunity__c);
         if(entitlement.Order__c!=null)  
         setOfOrderIds.add(entitlement.Order__c); 
         entitlement.Processing_Status__c = '';
         entitlement.Migration_Status__c = '';           
        }
        Database.SaveResult[] entitlementListQuote = Database.update(lstOfEntitlementRecords, false);
        Database.SaveResult[] contractsToUpdate = Database.update(lstOfContractsToUpdate, false);
        if(setOfQuoteIds.size()>0)
        {
          lstOfQuoteLines = [Select Id FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c IN: setOfQuoteIds];
          lstOfQuotes = [Select Id FROM SBQQ__Quote__c WHERE Id IN: setOfQuoteIds];
        }
        
        if(setOfOpportunityIds.size()>0)
        lstOfOpportunity = [Select Id FROM Opportunity WHERE Id IN: setOfOpportunityIds];
    
        if(setOfOrderIds.size()>0)
        {      
          deleteRecords(setOfOrderIds);  
        }
        
          if(!lstOfQuoteLines.IsEmpty())
          Database.DeleteResult[] quoteLinesDeleteList = Database.delete(lstOfQuoteLines, false);
          
          if(!lstOfQuotes.IsEmpty())
          Database.DeleteResult[] quoteDeleteList = Database.delete(lstOfQuotes, false);
      
          if(!lstOfOpportunity.IsEmpty())
          Database.DeleteResult[] opportunityDeleteList = Database.delete(lstOfOpportunity, false);         
      }
    }

   global void finish(Database.BatchableContext bc){
       
   } 

   global static void deleteRecords( set<id> setOfOrderIds)
   {
      List<Order> lstOfOrderToUpdate = new List<Order>();
      for(Order orderObj : [Select Id FROM ORDER WHERE ID IN: setOfOrderIds])
      {
        orderObj.SBQQ__Quote__c = null;
        orderObj.Status = 'Draft';
        lstOfOrderToUpdate.add(orderObj);
      }
      if(!lstOfOrderToUpdate.IsEmpty())
      {
        Database.SaveResult[] orderUpdateList = Database.update(lstOfOrderToUpdate, false);
      }
      
      List<OrderItem> lstOfOrderLineItems = [Select Id FROM OrderItem WHERE OrderId IN: setOfOrderIds];
      List<Order> lstOfOrdersToUpd = [Select Id FROM Order WHERE Id IN: setOfOrderIds];
      List<Contract> lstOfContracts = [Select Id FROM Contract WHERE SBQQ__Order__c IN: setOfOrderIds];
      
      if(!lstOfContracts.IsEmpty())
      {
      List<SBQQ__Subscription__c> lstOfSubscriptions = [Select Id FROM SBQQ__Subscription__c WHERE SBQQ__Contract__c IN: lstOfContracts];
      if(!lstOfSubscriptions.IsEmpty())
      Database.DeleteResult[] subscriptionDeleteList = Database.delete(lstOfSubscriptions, false); 
  
      Database.DeleteResult[] contractDeleteList = Database.delete(lstOfContracts, false);
      }
      
      if(!lstOfOrderLineItems.IsEmpty())
      Database.DeleteResult[] orderLineItemDeleteList = Database.delete(lstOfOrderLineItems, false);
  
      if(!lstOfOrdersToUpd.IsEmpty())
      Database.DeleteResult[] orderDeleteList = Database.delete(lstOfOrdersToUpd, false);
   }       
}