force-app/main/default/objects/Contract/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>In Processing</fullName>
            </value>
            <value>
                <fullName>Migrated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
            <value>
                <fullName>ACV Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Associated_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated OSA</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
            <value>
                <fullName>ACV Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Migration_Contract__c.field-meta.xml
<CustomField>
    <fullName>Migration_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Migration Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quotes (Migration Contract)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BIZ-45643</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Initial license term (in months). By default, this will be populated to 12 months. It can be overwritten by Contract Ops.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrderAndOliMigrationBatch.cls
global class OrderAndOliMigrationBatch implements Database.Batchable<sObject> {
    List<string> lstOfContractAssignment;
    global OrderAndOliMigrationBatch(List<string> lstOfContractNumbers){
      lstOfContractAssignment = lstOfContractNumbers ;
    }
    global OrderAndOliMigrationBatch() {}

    global Database.QueryLocator start(Database.BatchableContext bc){
        string endCondition;
        if (lstOfContractAssignment != null && !lstOfContractAssignment.isempty()) {
            for (string endDigit : lstOfContractAssignment) {
                endCondition = endCondition != null? (endCondition +  ' OR ContractNumber like \'%' + endDigit + '\'') :' ContractNumber like \'%' + endDigit + '\'';
            }
        } 
        String query = 'SELECT Id,Processing_Status__c FROM Contract WHERE ( Processing_Status__c = \'Child Quote Line Created\''  
                        +' OR Processing_Status__c = \'Parent Quote Line Created\')';            
        query = endCondition != null? query + ' AND (' + endCondition + ')' : query;
        system.debug('Start Query' +query);     
        return Database.getQueryLocator(query);        
    }

    global void execute(Database.BatchableContext bc, List<Contract> lstOfContracts){
        set<id> setOfQuoteIds = new set<id>();
        List<SBQQ__Quote__c> lstOfQuotesToUpdate = new List<SBQQ__Quote__c>();
        List<OP4I_Entitlement_View__c> lstOfEntitlementRecords = new List<OP4I_Entitlement_View__c>();
        List<Contract> lstOfContractsToUpdate = new List<Contract>();
        set<id> setOfQuoteIdsUpd = new set<id>();
        List<OP4I_Entitlement_View__c> lstOfEntitlementRecordsUpd = new List<OP4I_Entitlement_View__c>();
        List<OP4I_Entitlement_View__c> lstOfEntitlementRecordsOrderUpd = new List<OP4I_Entitlement_View__c>();
        Map<String,SBQQ__Quote__c> mapOfContractToQuote = new Map<String,SBQQ__Quote__c>();
        Map<String,String> mapOfQuoteToOrder = new Map<String,String>();  
        if(!lstOfContracts.IsEmpty()) {
            lstOfEntitlementRecords = [SELECT Id,DLIP_Id__c,Account__c,Quote__c,Quote__r.SBQQ__Ordered__c,Quantity__c,
                                        Start_Date__c,End_Date__c,Associated_OSA__c,Account__r.Name,Associated_OSA__r.ContractNumber,
                                        Opportunity__c,Processing_Status__c,Associated_OSA__r.Migration_Status__c,
                                        Associated_OSA__r.Processing_Status__c FROM OP4I_Entitlement_View__c 
                                        WHERE Associated_OSA__c IN: lstOfContracts];
            if(!lstOfEntitlementRecords.IsEmpty()){                                  
                for(OP4I_Entitlement_View__c entitlement : lstOfEntitlementRecords){ 
                    setOfQuoteIds.add(entitlement.Quote__c); 
                }
            }
            List<SBQQ__Quote__c> existingQuotes = [Select Id,Migration_Contract__c,SBQQ__Ordered__c FROM SBQQ__Quote__c WHERE Id IN: setOfQuoteIds];
            
            if(!existingQuotes.IsEmpty())
            {
                for(SBQQ__Quote__c quoteObj : existingQuotes)
                {
                    mapOfContractToQuote.put(quoteObj.Migration_Contract__c , quoteObj);
                }
            }
            
            for(OP4I_Entitlement_View__c entitlement : lstOfEntitlementRecords)
            {             
                if(mapOfContractToQuote.containskey(entitlement.Associated_OSA__c))
                {
                    if(mapOfContractToQuote.get(entitlement.Associated_OSA__c).SBQQ__Ordered__c == false)
                    {
                        mapOfContractToQuote.get(entitlement.Associated_OSA__c).SBQQ__Ordered__c = true; 
                        lstOfQuotesToUpdate.add(mapOfContractToQuote.get(entitlement.Associated_OSA__c));
                        setOfQuoteIdsUpd.add(mapOfContractToQuote.get(entitlement.Associated_OSA__c).id);
                        entitlement.Processing_Status__c = 'Order and OLI created';
                        entitlement.Associated_OSA__r.Processing_Status__c = 'Order and OLI created';
                        lstOfEntitlementRecordsUpd.add(entitlement);
                        if(!lstOfContractsToUpdate.contains(entitlement.Associated_OSA__r))
                        {
                            lstOfContractsToUpdate.add(entitlement.Associated_OSA__r);
                        }
                    }
                    
                    else
                    {
                        entitlement.Processing_Status__c = 'Order and OLI created';
                        entitlement.Associated_OSA__r.Processing_Status__c = 'Order and OLI created';
                        setOfQuoteIdsUpd.add(mapOfContractToQuote.get(entitlement.Associated_OSA__c).id);
                        lstOfEntitlementRecordsUpd.add(entitlement);
                        if(!lstOfContractsToUpdate.contains(entitlement.Associated_OSA__r))
                        {               
                            lstOfContractsToUpdate.add(entitlement.Associated_OSA__r); 
                        }           
                    }  
                }          
            }
            
            if(!lstOfQuotesToUpdate.IsEmpty())
            {
                createOrder(mapOfContractToQuote,lstOfEntitlementRecordsUpd);
            }
        
            List<Order> lstOfOrders = [Select Id,SBQQ__Quote__c FROM ORDER WHERE SBQQ__Quote__c IN: setOfQuoteIdsUpd];
            set<id> setOfOrderIds = new set<id>();
            List<orderItem> lstOfOrderItems = new List<orderItem>();
            if(!lstOfOrders.IsEmpty()) {
                for(order orderObj : lstOfOrders){
                    mapOfQuoteToOrder.put(orderObj.SBQQ__Quote__c , orderObj.Id); 
                }
                
                for(OP4I_Entitlement_View__c entitlmnt : lstOfEntitlementRecordsUpd){
                    if(mapOfQuoteToOrder.containskey(entitlmnt.Quote__c)){
                        entitlmnt.Order__c = mapOfQuoteToOrder.get(entitlmnt.Quote__c);
                        lstOfEntitlementRecordsOrderUpd.add(entitlmnt);
                        setOfOrderIds.add(entitlmnt.Order__c);
                    }               
                }
                lstOfOrderItems = [Select Id,SBQQ__DefaultSubscriptionTerm__c,Product2.SBQQ__SubscriptionTerm__c
                                                FROM OrderItem WHERE OrderId IN: setOfOrderIds];
            }  
            
            if(!lstOfEntitlementRecordsUpd.IsEmpty()){           
                updateEntitlementView(lstOfEntitlementRecordsUpd,lstOfContractsToUpdate,lstOfOrderItems);
            }
                  
        }
    }
  
    global void finish(Database.BatchableContext bc){
        
    }
  
    global static void createOrder( Map<String,SBQQ__Quote__c> mapOfContractToQuote,List<OP4I_Entitlement_View__c> lstOfEntitlementRecordsUpd){
        List<SBQQ__Quote__c> quoteUpdateList = mapOfContractToQuote.values();
        Database.SaveResult[] quoteUpdateResultList = Database.update(quoteUpdateList, false); 
        //HandleCustomException.logDatabaseErrorsForEntitlements(quoteList,mapOfContractToQuote);
        map<string,string> resultMap = HandleCustomException.logMigrationDatabaseError(
            quoteUpdateResultList,
            mapOfContractToQuote,
            'Migration_Contract__c',
            quoteUpdateList
        );

        string keyFields = 'Associated_OSA__c';
        for(OP4I_Entitlement_View__c entitlement : lstOfEntitlementRecordsUpd) {          
                string key = HandleCustomException.getKey(keyFields, entitlement);
                system.debug('key--->'+key);
                if (resultMap.containsKey(key)) {
                    entitlement.Processing_Status__c = 'Order Creation Failed';
                    entitlement.Error_Log__c = resultMap.get(key);
                    entitlement.Associated_OSA__r.Processing_Status__c = 'Order Creation Failed';
                }
        }
    }
  
    global static void updateEntitlementView(List<OP4I_Entitlement_View__c> lstOfEntitlementRecordsOrderUpd,List<Contract> lstOfContractsToUpdate,List<orderItem> lstOfOrderItems){
        Database.SaveResult[] entitlementListQuoteOrder = Database.update(lstOfEntitlementRecordsOrderUpd, false);
        HandleCustomException.logDatabaseErrors(entitlementListQuoteOrder); 
        if(lstOfOrderItems.size()>0) {
            for(orderitem ordritem : lstOfOrderItems){
                if(ordritem.Product2.SBQQ__SubscriptionTerm__c!=null)
                ordritem.SBQQ__DefaultSubscriptionTerm__c = ordritem.Product2.SBQQ__SubscriptionTerm__c;
            }           
            Database.SaveResult[] orderItemUpdateLst = Database.update(lstOfOrderItems, false);
            HandleCustomException.logDatabaseErrors(orderItemUpdateLst);  
        }   
        Database.SaveResult[] contrUpdateLst = Database.update(lstOfContractsToUpdate, false);
        HandleCustomException.logDatabaseErrors(contrUpdateLst);    
    }
}