force-app/main/default/objects/Contract/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>In Processing</fullName>
            </value>
            <value>
                <fullName>Migrated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
            <value>
                <fullName>ACV Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Associated_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated OSA</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/DLI_Product__c.field-meta.xml
<CustomField>
    <fullName>DLI_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DLI Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OP4I Entitlement Views (DLI Product)</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Migration_Status__c</fullName>
    <label>Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
            <value>
                <fullName>ACV Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price__c</fullName>
    <label>Sale Price</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Meter_Type__c.field-meta.xml
<CustomField>
    <fullName>Meter_Type__c</fullName>
    <label>Meter Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lawyers</fullName>
            </value>
            <value>
                <fullName>Fee Earners</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Named Users</fullName>
            </value>
            <value>
                <fullName>Records</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Firmwide</fullName>
            </value>
            <value>
                <fullName>no meter type</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Dimension__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Dimension__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</description>
    <inlineHelpText>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</inlineHelpText>
    <label>Price Dimension</label>
    <referenceTo>SBQQ__Dimension__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
    <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__PricebookEntryId__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PricebookEntryId__c</fullName>
    <label>Pricebook Entry Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SegmentIndex__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SegmentIndex__c</fullName>
    <description>For multi-segmented Products, Index representing this Quote Line&apos;s position in the segment table.</description>
    <inlineHelpText>For multi-segmented Products, Index representing this Quote Line&apos;s position in the segment table.</inlineHelpText>
    <label>Segment Index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SegmentKey__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SegmentKey__c</fullName>
    <description>For multi-segmented Products, this is a shared key used to group multi-dimensional Quote Lines together.</description>
    <inlineHelpText>For multi-segmented Products, this is a shared key used to group multi-dimensional Quote Lines together.</inlineHelpText>
    <label>Segment Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuoteLinesMigrationBatch.cls
global class QuoteLinesMigrationBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id,Processing_Status__c FROM Contract WHERE Processing_Status__c = \'Quote Created\'';
        return Database.getQueryLocator(query);        
    }

    global void execute(Database.BatchableContext bc, List<Contract> lstOfContracts){
        List<OP4I_Entitlement_View__c> lstOfEntitlementRecords = new List<OP4I_Entitlement_View__c>();
        List<SBQQ__QuoteLine__c> lstOfQuoteLinesToInsert = new List<SBQQ__QuoteLine__c>();
        List<OP4I_Entitlement_View__c> lstOfEntitlementRecordsUpd = new List<OP4I_Entitlement_View__c>(); 
        Map<String,SBQQ__QuoteLine__c> mapOfContractToQuoteLineCreate = new Map<String,SBQQ__QuoteLine__c>();
        List<Contract> lstOfContractsToUpdate = new List<Contract>();
        Map<string,Id> productPricbookEntryMap = new Map<String,Id>();
        Set<id> productIds = new set<id>();
        set<id> priceBookIds = new set<id>(); 
        set<string> currencySet = new set<string>();
        if(!lstOfContracts.IsEmpty()){
            lstOfEntitlementRecords = [SELECT Id,DLIP_Id__c,Account__c,Quote__c,Quote__r.SBQQ__PriceBook__c,
                                    Quantity__c,Quote__r.CurrencyIsoCode,Start_Date__c,End_Date__c,Associated_OSA__c,
                                    Account__r.Name,Associated_OSA__r.ContractNumber,Opportunity__c,Processing_Status__c,
                                    DLI_Product__c,Sale_Price__c,Meter_Type__c,Segment_Index__c,Associated_OSA__r.Migration_Status__c,
                                    Associated_OSA__r.Processing_Status__c,DLI_Product__r.SBQQ__ChargeType__c,DLI_Product__r.SBQQ__BillingType__c 
                                    FROM OP4I_Entitlement_View__c WHERE Associated_OSA__c IN: lstOfContracts];
          if(!lstOfEntitlementRecords.IsEmpty()){                                   
            for(OP4I_Entitlement_View__c entitlement : lstOfEntitlementRecords){ 
                priceBookIds.add(entitlement.Quote__r.SBQQ__PriceBook__c);     
                currencySet.add(entitlement.Quote__r.CurrencyIsoCode);
                productIds.add(entitlement.DLI_Product__c); 
            }
          }         
        }

        for(PriceBookEntry priceEntry : [Select Id,Pricebook2Id,Product2Id,Pricebook2.Name,CurrencyIsoCode 
            FROM PriceBookEntry 
           WHERE Product2Id IN: productIds AND Pricebook2Id IN: priceBookIds
        ]){
            productPricbookEntryMap.put(priceEntry.Product2Id + '-' +priceEntry.Pricebook2Id + '-' +priceEntry.CurrencyIsoCode, priceEntry.Id);
        }

        system.debug('currencySet--->'+currencySet);
        system.debug('priceBookIds--->'+priceBookIds);
        system.debug('productIds--->'+productIds);
        Map<string,Id> dimentionMap = new Map<string,Id>();
        for (SBQQ__Dimension__c  dimention : [
            Select id,CurrencyIsoCode, SBQQ__PriceBook__c, SBQQ__Product__c from SBQQ__Dimension__c 
            WHERE CurrencyIsoCode IN :currencySet AND SBQQ__Product__c IN :productIds
        ]) {
            string key = dimention.CurrencyIsoCode + dimention.SBQQ__Product__c;
            system.debug('key--->'+key);
            dimentionMap.put(key, dimention.Id);
        }

        for(OP4I_Entitlement_View__c entitlement : lstOfEntitlementRecords){ 
            SBQQ__QuoteLine__c migrateQuoteLine = createQuoteLine(entitlement,
                productPricbookEntryMap,dimentionMap
            );
            mapOfContractToQuoteLineCreate.put(entitlement.Associated_OSA__c,migrateQuoteLine);         
            lstOfQuoteLinesToInsert.add(migrateQuoteLine);
            entitlement.Processing_Status__c = 'Quote Line Created';
            entitlement.Associated_OSA__r.Processing_Status__c = 'Quote Line Created';
            lstOfEntitlementRecordsUpd.add(entitlement);
            if(!lstOfContractsToUpdate.contains(entitlement.Associated_OSA__r))
            {
            lstOfContractsToUpdate.add(entitlement.Associated_OSA__r);
            }
        }

        if(!lstOfQuoteLinesToInsert.IsEmpty())
        { 
           insertQuoteLinesAndEntitlement(lstOfQuoteLinesToInsert,lstOfEntitlementRecordsUpd,mapOfContractToQuoteLineCreate);
        }
        
        if(!lstOfContractsToUpdate.IsEmpty())
        {
          update lstOfContractsToUpdate;
        }           
    }

    global void finish(Database.BatchableContext bc){
       
    }
    
    global static SBQQ__QuoteLine__c createQuoteLine(OP4I_Entitlement_View__c entitlement ,
                                                     map<string,Id> productPricbookEntryMap,Map<string,Id> dimentionMap)
    {
        SBQQ__QuoteLine__c quoteLineMigration = new SBQQ__QuoteLine__c();
        quoteLineMigration.SBQQ__Quote__c = entitlement.Quote__c;
        quoteLineMigration.SBQQ__Quantity__c = entitlement.Quantity__c;
        quoteLineMigration.SolutionQuantity__c = entitlement.Quantity__c;
        quoteLineMigration.SBQQ__ListPrice__c = entitlement.Sale_Price__c;
        quoteLineMigration.Meter_Type__c = entitlement.Meter_Type__c;
        quoteLineMigration.SBQQ__StartDate__c = entitlement.Start_Date__c;
        quoteLineMigration.SBQQ__EndDate__c = entitlement.End_Date__c;
        quoteLineMigration.SBQQ__Product__c = entitlement.DLI_Product__c;
        if(quoteLineMigration.SBQQ__ChargeType__c == null)
        {
          quoteLineMigration.SBQQ__ChargeType__c = entitlement.DLI_Product__r.SBQQ__ChargeType__c;  
        }
         if(quoteLineMigration.SBQQ__BillingType__c == null)
        {
          quoteLineMigration.SBQQ__BillingType__c = entitlement.DLI_Product__r.SBQQ__BillingType__c;    
        }
        quoteLineMigration.Price_Book__c = entitlement.Quote__r.SBQQ__PriceBook__c;
        quoteLineMigration.SBQQ__SegmentIndex__c = entitlement.Segment_Index__c;
        quoteLineMigration.SBQQ__SegmentLabel__c = 'Year ' + entitlement.Segment_Index__c;
        
        quoteLineMigration.CurrencyIsoCode = entitlement.Quote__r.CurrencyIsoCode;
        //quoteLineMigration.SBQQ__SubscriptionPricing__c = 'Fixed Price';
        quoteLineMigration.SBQQ__PricebookEntryId__c = productPricbookEntryMap.get(quoteLineMigration.SBQQ__Product__c + '-' + quoteLineMigration.Price_Book__c + '-' + quoteLineMigration.CurrencyIsoCode);
        system.debug('quoteLineMigration.SBQQ__SegmentIndex__c--->'+quoteLineMigration.SBQQ__SegmentIndex__c);
        if (quoteLineMigration.SBQQ__SegmentIndex__c != null) {
            string key = quoteLineMigration.CurrencyIsoCode+quoteLineMigration.SBQQ__Product__c;
            system.debug('key 2--->'+key);
            system.debug('dimentionMap.get(key)--->'+dimentionMap.get(key));
            quoteLineMigration.SBQQ__Dimension__c = dimentionMap.get(key);
            quoteLineMigration.SBQQ__SegmentKey__c = quoteLineMigration.SBQQ__Dimension__c;
        }
        
        return quoteLineMigration;  
    }
    
    
    global static void insertQuoteLinesAndEntitlement(List<SBQQ__QuoteLine__c> lstOfQuoteLinesToInsert,List<OP4I_Entitlement_View__c> lstOfEntitlementRecordsUpd,Map<String,SBQQ__QuoteLine__c> mapOfContractToQuoteLineCreate)
    {
        Database.SaveResult[] quoteLinesToInsert = Database.insert(lstOfQuoteLinesToInsert, false); 
        HandleCustomException.logDatabaseErrorsForEntitlements(quoteLinesToInsert,mapOfContractToQuoteLineCreate);
        
        Database.SaveResult[] entitlementListOpp = Database.update(lstOfEntitlementRecordsUpd, false);
        HandleCustomException.logDatabaseErrors(entitlementListOpp);
    }
}