force-app/main/default/objects/ACV_Allocation__c/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>ACV Allocations</relationshipLabel>
    <relationshipName>ACV_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ACV_Allocation__c/fields/Percent_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Percent_Allocation__c</fullName>
    <label>Percent Allocation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ACV_Allocation__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRING 4/28</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Time</fullName>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Records Management</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
            </value>
            <value>
                <fullName>Intapp Open Sandbox</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Relationships</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Flow</fullName>
            </value>
            <value>
                <fullName>Intapp Flow - Cloud</fullName>
            </value>
            <value>
                <fullName>Integration Service - Cloud</fullName>
            </value>
            <value>
                <fullName>DealCloud - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_Master_Product__c/Item_Master_Product__c.object-meta.xml
<CustomObject>
    <label>Item Master Product</label>
    <nameField>
        <displayFormat>PIN-{00000}</displayFormat>
        <label>Product Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Master Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Master_Product__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRING 4/28</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Compliguard</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Lateral Hire</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Sandbox</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms of Business</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms of Business - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Workflow</fullName>
            </value>
            <value>
                <fullName>Intapp Time</fullName>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Third Party Connectors</fullName>
            </value>
            <value>
                <fullName>Relationships</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Conflicts - On Prem</fullName>
                <color>#E27001</color>
                <label>Conflicts - On Prem</label>
            </value>
            <value>
                <fullName>Intake - On Prem</fullName>
                <color>#E27001</color>
                <label>Intake - On Prem</label>
            </value>
            <value>
                <fullName>Records Management</fullName>
                <color>#E27001</color>
                <label>Records Management</label>
            </value>
            <value>
                <fullName>TFG - Legacy</fullName>
                <color>#E27001</color>
                <label>TFG - Legacy</label>
            </value>
            <value>
                <fullName>Terms - On Prem</fullName>
                <color>#E27001</color>
                <label>Terms - On Prem</label>
            </value>
            <value>
                <fullName>Terms - Cloud</fullName>
                <color>#E27001</color>
                <label>Terms - Cloud</label>
            </value>
            <value>
                <fullName>LegalKey - Legacy</fullName>
            </value>
            <value>
                <fullName>Experience - On Prem</fullName>
            </value>
            <value>
                <fullName>Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Multiple Products - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>L&amp;P - Cloud</fullName>
            </value>
            <value>
                <fullName>Relationships - On Prem</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - On Prem</fullName>
            </value>
            <value>
                <fullName>Multiple Products - Cloud</fullName>
            </value>
            <value>
                <fullName>Time - On Prem</fullName>
            </value>
            <value>
                <fullName>Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Walls - On Prem</fullName>
            </value>
            <value>
                <fullName>Integrate - On Prem</fullName>
            </value>
            <value>
                <fullName>DealCloud - Cloud</fullName>
            </value>
            <value>
                <fullName>OPIS - Cloud</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Integration Service - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRING 4/28</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Integrate</fullName>
            </value>
            <value>
                <fullName>Walls</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms</fullName>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestUtil.cls
/*******************************************************************************
Name      : TestUtil
Purpose   : Contains Utility Methods for Test Classes
Date      : 28-Mar-2012
********************************************************************************/

@isTest(seeAllData=true)
public without sharing class TestUtil {
	
   public static Account createAccount() {
  	  Account account = IntappTestObjectFactory.createAccount(true);
  	  return account;
  }

  public static User createUser(Boolean isInsert) {
  Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
  
  User u = new User(Alias = 'standt', Email='standarduser@intapp.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@intapp.com');
  if(isInsert) {
    insert u;
  }
  return u;

  }
    
  public static Contact createContact(Id accId, Boolean isInsert) {
     Contact contact   = new Contact();
     contact.LastName  = 'test name';
     contact.FirstName = 'Test First';
     contact.Accountid = accId; 
     contact.RecordTypeId = 'Conatct';
     contact.CurrencyIsoCode = 'USD';
     if(isInsert) {
        insert contact;
     }
     return contact;
  }
  
  public static Item_Master_Product__c createItemMaster(Boolean isInsert) {
     Item_Master_Product__c item   = new Item_Master_Product__c();
     item.Item_Name__c  = 'test name';
     item.CurrencyIsoCode = 'USD';
     
     if(isInsert) {
        insert item;
     }
     return item;
  }
  
  public static ACV_Allocation__c createAcvAllocation(Id itemMaster , Double percent , Boolean isInsert) {
     ACV_Allocation__c acvLocation   = new ACV_Allocation__c();
     acvLocation.Product_Line__c = 'Wall Builder';
     acvLocation.Percent_Allocation__c = percent;
     acvLocation.Item_Master_Product__c = itemMaster;
     acvLocation.CurrencyIsoCode = 'USD';
     
     if(isInsert) {
        insert acvLocation;
     }
     return acvLocation;
  }
  
  public static Product2 createProduct(Boolean isInsert) {
     Product2 prod = new Product2();
     prod.Name = 'Test Prd1';
     prod.Family = 'Major';
     if(isInsert) {
       insert prod;
     }
     return prod;
  }
  
  public static Id priceBook2Id;
  
  static {
      priceBook2Id = [Select id from Pricebook2 where IsStandard = true Limit 1][0].Id;
  }
  
  //-----------------------------------------------------------------------------------------------------------
  //Returns PriceBookEntry Record
  //-----------------------------------------------------------------------------------------------------------
  public static PricebookEntry createPriceBookEntry(Id prodId, Double unitPrice, Boolean isInsert) {
      PricebookEntry pbEntry = new PricebookEntry ();
     pbEntry.product2id = prodId;
     pbEntry.UnitPrice = unitPrice;
     pbEntry.IsActive = true;
     pbEntry.pricebook2id = priceBook2Id;
     pbEntry.UseStandardPrice = false;
    
    if(isInsert) {
       insert pbEntry;
    }
    return pbEntry;
  }
  
  public static Campaign createCampaign(Boolean isInsert) {
     Campaign cmp = new Campaign();
     cmp.Name = 'Test campaign';
     
     if(isInsert) {        
       insert cmp;   
     }
     return cmp; 
  }
  
  public static Opportunity createOpportunity(Id accId, Boolean isInsert) {
     Opportunity opp = new Opportunity();
     opp.name = 'Test Opportunity ';
     opp.AccountId = accId; 
     opp.stageName = 'Target Account';
     opp.CloseDate = Date.newInstance(2006,10,10);
     opp.ForecastCategoryName = 'Pipeline';
     opp.License_Type__c = 'Annual';
     opp.CurrencyIsoCode = 'USD';
     opp.Type = 'Cancellation - CPI';
     //opp.Campaign = Campaign.Id;
     opp.CloseDate = Date.today();
     if(isInsert) {        
       insert opp;   
     }
     return opp;        
  }
  
  public static OpportunityLineItem createOpportunityLineItem(Id oppId, Id pbEntryId, double unitPrice, Boolean isInsert) {
     OpportunityLineItem oli = new OpportunityLineItem();
    oli.opportunityid = oppId; 
    oli.pricebookentryid = pbEntryId; 
    oli.unitprice = unitPrice;
    oli.quantity  = 2;
    if(isInsert) {
       insert oli;
    }
    return oli;
  }
}