force-app/main/default/objects/ACV_Allocation__c/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>ACV Allocations</relationshipLabel>
    <relationshipName>ACV_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_Master_Product__c/Item_Master_Product__c.object-meta.xml
<CustomObject>
    <label>Item Master Product</label>
    <nameField>
        <displayFormat>PIN-{00000}</displayFormat>
        <label>Product Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Master Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Product_Component__c/Opportunity_Product_Component__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Component</label>
    <nameField>
        <displayFormat>OPC-{0000000}</displayFormat>
        <label>Opportunity Product Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestOpportunityProductTrigger.cls
@isTest(seeAllData=true)
private class TestOpportunityProductTrigger {

	static testMethod void testCreateOppCompRecord(){
		Account accId = TestUtil.createAccount(true);
		Opportunity opp = TestUtil.createOpportunity( accId.Id , true);
		
		Item_Master_Product__c master = TestUtil.createItemMaster(true);
		
		Pricebook2 p = new Pricebook2();
		p.Name = 'Test';
		p.CurrencyIsoCode = 'USD';
		insert p;
		
		ACV_Allocation__c acvLocation1 = TestUtil.createAcvAllocation(master.Id, 30 , true);
		ACV_Allocation__c acvLocation2 = TestUtil.createAcvAllocation(master.Id, 70 , true);
		
		Product2 pd = TestUtil.createProduct(false);
		pd.Item_Master_Product__c = master.Id;
		insert pd;
		
		PricebookEntry pbook = TestUtil.createPriceBookEntry(pd.Id, 10, true);
		OpportunityLineItem oppProduct = TestUtil.createOpportunityLineItem(opp.Id, pbook.Id , 10000, true);
		
	 // Integer total = new Integer([Select count(id) from Opportunity_Product_Component__c where Opportunity_Product_ID__c = :oppProduct.Id]);
		//system.assertEquals(2, total);
		
		oppProduct.UnitPrice = 15000;
		update oppProduct;
		
		delete oppProduct;
		//Test.startTest();
		//undelete oppProduct;
		//test.stopTest();
	}
}