force-app/main/default/objects/Account/fields/At_Risk_Count__c.field-meta.xml
<CustomField>
    <fullName>At_Risk_Count__c</fullName>
    <description>Count of all at risk Subscriptions - Integration.</description>
    <inlineHelpText>Count of all at risk Subscriptions - Integration.</inlineHelpText>
    <label>At Risk Count</label>
    <summaryFilterItems>
        <field>Subscription__c.CSM_Health_Rating__c</field>
        <operation>equals</operation>
        <value>D - At Risk / Anticipated Cancellation</value>
    </summaryFilterItems>
    <summaryForeignKey>Subscription__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/CSM_Health_Rating__c.field-meta.xml
<CustomField>
    <fullName>CSM_Health_Rating__c</fullName>
    <label>Account Health Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <color>#78C953</color>
                <label>Green</label>
            </value>
            <value>
                <fullName>Amber</fullName>
                <color>#F3D904</color>
                <label>Amber</label>
            </value>
            <value>
                <fullName>Red</fullName>
                <color>#FF0000</color>
                <label>Red</label>
            </value>
            <value>
                <fullName>Black</fullName>
                <color>#000000</color>
                <label>Black</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <color>#DDDDDD</color>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Governance</fullName>
                <default>true</default>
                <label>Pending Governance</label>
            </value>
            <value>
                <fullName>Verification Approved</fullName>
            </value>
            <value>
                <fullName>Verification Declined</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Survey.recordType-meta.xml
<RecordType>
    <fullName>Survey</fullName>
    <active>true</active>
    <businessProcess>Survey</businessProcess>
    <description>For use with surveys</description>
    <label>Survey</label>
</RecordType>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/At_Risk_Count__c.field-meta.xml
<CustomField>
    <fullName>At_Risk_Count__c</fullName>
    <label>At Risk Count</label>
    <summaryFilterItems>
        <field>CR_Engagement__c.CR_Engagement_Status__c</field>
        <operation>equals</operation>
        <value>Not Started, In Process</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>CR_Engagement__c.CR_Engagement_Type__c</field>
        <operation>equals</operation>
        <value>D - At Risk</value>
    </summaryFilterItems>
    <summaryForeignKey>CR_Engagement__c.Subscription__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/At_Risk_Flag__c.field-meta.xml
<CustomField>
    <fullName>At_Risk_Flag__c</fullName>
    <formula>IF(ISPICKVAL(CSM_Health_Rating__c,&quot;D - At Risk / Anticipated Cancellation&quot;),TRUE,FALSE)</formula>
    <label>At Risk Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/CSM_Health_Rating__c.field-meta.xml
<CustomField>
    <fullName>CSM_Health_Rating__c</fullName>
    <label>CSM Health Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
                <color>#FF0000</color>
                <label>Red</label>
            </value>
            <value>
                <fullName>Amber</fullName>
                <color>#F3D904</color>
                <label>Amber</label>
            </value>
            <value>
                <fullName>Green</fullName>
                <color>#33CC00</color>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Black</fullName>
                <color>#000000</color>
                <label>Black</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Customer_Lifecycle_Stage__c.field-meta.xml
<CustomField>
    <fullName>Customer_Lifecycle_Stage__c</fullName>
    <label>Product Implementation Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project not started yet</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Within 90 days of Production</fullName>
            </value>
            <value>
                <fullName>In Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
                <color>#E27001</color>
                <label>Intapp Open - Conflicts</label>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
                <color>#E27001</color>
                <label>Intapp Open - Intake</label>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Time</fullName>
                <color>#78C953</color>
                <label>Intapp Time</label>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
                <color>#E27001</color>
                <label>TFG - Other</label>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
                <label>PSP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VSDashBoard_Account.cls
public without sharing class VSDashBoard_Account { 
    private final Account account;
        
    public VSDashBoard_Account() 
    {
        account = [SELECT Id, Name, Site, Territory__c, Hot_List_Case_Count__c, Hot_List_Status__c, At_Risk_Status__c, At_Risk_Count__c, IntApp_Account_Number__c 
        FROM Account WHERE Id =:ApexPages.currentPage().getParameters().get('id')];
    }
    
    public Account getAccount() {
        return account;
    }
    
   public List<Case> getCases(){  
     return [SELECT Id,CaseNumber,Status,Subject, Priority FROM Case WHERE Account.Id = :account.Id AND isClosed = false  AND Record_Type_Name__c <> 'Survey'];  
   }  
    public List<Subscription__c> getSubscriptions() {
        return [SELECT Id, Name, CSM_Health_Rating__c, Product_Line__c, Customer_Lifecycle_Stage__c, At_Risk_Count__c, At_Risk_Flag__c 
        FROM Subscription__c WHERE Account__c = :account.Id];// AND (Customer_Lifecycle_Stage__c LIKE 'In Production%') AND Status__c = 'Active'];
    }
 }