force-app/main/default/objects/Account/fields/Contract_Term_Version__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term_Version__c</fullName>
    <inlineHelpText>What Intapp contract terms is this account currently active on?</inlineHelpText>
    <label>Master Terms: Term Version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>10.1.1</fullName>
            </value>
            <value>
                <fullName>10.2</fullName>
            </value>
            <value>
                <fullName>10.2.1</fullName>
            </value>
            <value>
                <fullName>10.2.2</fullName>
            </value>
            <value>
                <fullName>10.3</fullName>
            </value>
            <value>
                <fullName>10.4</fullName>
            </value>
            <value>
                <fullName>10.5</fullName>
            </value>
            <value>
                <fullName>10.6</fullName>
            </value>
            <value>
                <fullName>10.6 excluding Cloud Terms</fullName>
            </value>
            <value>
                <fullName>10.7</fullName>
            </value>
            <value>
                <fullName>10.7 excluding Cloud Terms</fullName>
            </value>
            <value>
                <fullName>10.8</fullName>
            </value>
            <value>
                <fullName>10.8 Excluding Cloud Terms</fullName>
            </value>
            <value>
                <fullName>10.9</fullName>
            </value>
            <value>
                <fullName>10.9 Excluding Cloud Terms</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>11 Excluding Cloud Terms</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>8.5</fullName>
            </value>
            <value>
                <fullName>8.8</fullName>
            </value>
            <value>
                <fullName>8.9</fullName>
            </value>
            <value>
                <fullName>9.0</fullName>
            </value>
            <value>
                <fullName>9.1</fullName>
            </value>
            <value>
                <fullName>9.2</fullName>
            </value>
            <value>
                <fullName>9.3</fullName>
            </value>
            <value>
                <fullName>9.4</fullName>
            </value>
            <value>
                <fullName>9.4.1</fullName>
            </value>
            <value>
                <fullName>9.4v3</fullName>
            </value>
            <value>
                <fullName>Acquired Rekoop Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Contract_Master_Terms__c.field-meta.xml
<CustomField>
    <fullName>Contract_Master_Terms__c</fullName>
    <label>Contract Master Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>URL Terms</fullName>
            </value>
            <value>
                <fullName>Existing Terms Cloud</fullName>
                <label>Existing Intapp MSSA Plus Cloud</label>
            </value>
            <value>
                <fullName>Existing Terms</fullName>
                <label>Existing Intapp MSSA Terms</label>
            </value>
            <value>
                <fullName>Existing Terms with Annex</fullName>
                <label>Existing Intapp MSSA plus Annex</label>
            </value>
            <value>
                <fullName>MSSA Attached</fullName>
                <label>New Intapp MSSA Attached</label>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>OnePlace Legacy</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Custom Master Term from Account</fullName>
            </value>
            <value>
                <fullName>Repstor Legacy Agreement Attached</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
                <label>Intapp Reseller</label>
            </value>
            <value>
                <fullName>Repstor G-Cloud</fullName>
            </value>
            <value>
                <fullName>Existing Intapp MSSA signed by Customer Affiliate</fullName>
            </value>
            <value>
                <fullName>Legacy DealCloud Agreement</fullName>
            </value>
            <value>
                <fullName>New MSSA Signed Separate</fullName>
            </value>
            <value>
                <fullName>Existing Intapp MSSA plus Cloud and Annex</fullName>
            </value>
            <value>
                <fullName>Existing Terms Plus Prime</fullName>
                <isActive>false</isActive>
                <label>Existing Terms Plus Prime</label>
            </value>
            <value>
                <fullName>Prime</fullName>
                <isActive>false</isActive>
                <label>Partner and Prime</label>
            </value>
            <value>
                <fullName>Repstor Legacy</fullName>
                <isActive>false</isActive>
                <label>Repstor Legacy</label>
            </value>
            <value>
                <fullName>Repstor Legacy Term</fullName>
                <isActive>false</isActive>
                <label>Repstor Legacy Term</label>
            </value>
            <value>
                <fullName>Repstor Retro-Booking</fullName>
                <isActive>false</isActive>
                <label>Repstor Retro-Booking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteTerm__c/SBQQ__QuoteTerm__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteTermHelp</customHelpPage>
    <description>Legal term printed on quote document.</description>
    <label>Quote Term</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Term #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__TermCondition__c/fields/SBQQ__Operator__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Operator__c</fullName>
    <description>The operator for this field.</description>
    <inlineHelpText>Choose the operator for the field.</inlineHelpText>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
            </value>
            <value>
                <fullName>not equals</fullName>
            </value>
            <value>
                <fullName>less than</fullName>
            </value>
            <value>
                <fullName>less or equals</fullName>
            </value>
            <value>
                <fullName>greater than</fullName>
            </value>
            <value>
                <fullName>greater or equals</fullName>
            </value>
            <value>
                <fullName>starts with</fullName>
            </value>
            <value>
                <fullName>ends with</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
            <value>
                <fullName>does not contain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__TermCondition__c/fields/SBQQ__TestedField__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__TestedField__c</fullName>
    <description>Field on quote object used for testing this condition.</description>
    <inlineHelpText>Field on quote object used for testing this condition.</inlineHelpText>
    <label>Tested Field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account_country__c</fullName>
            </value>
            <value>
                <fullName>Account_Type__c</fullName>
            </value>
            <value>
                <fullName>Advanced_Flow_Products__c</fullName>
            </value>
            <value>
                <fullName>Advanced_Intake_Products__c</fullName>
            </value>
            <value>
                <fullName>after_hours_work_price_for_quote_terms__c</fullName>
            </value>
            <value>
                <fullName>Agree_to_Press_Release__c</fullName>
            </value>
            <value>
                <fullName>Cancellation_terms__c</fullName>
            </value>
            <value>
                <fullName>Conflicts_Products__c</fullName>
            </value>
            <value>
                <fullName>Contains_CR_01539__c</fullName>
            </value>
            <value>
                <fullName>Contract_Master_Terms__c</fullName>
            </value>
            <value>
                <fullName>Contract_Term_Version__c</fullName>
            </value>
            <value>
                <fullName>Contract_Type__c</fullName>
            </value>
            <value>
                <fullName>CurrencyIsoCode</fullName>
            </value>
            <value>
                <fullName>Customer_owns_Integrate__c</fullName>
            </value>
            <value>
                <fullName>Customer Amount</fullName>
            </value>
            <value>
                <fullName>D_B__c</fullName>
            </value>
            <value>
                <fullName>Engagement_Letter_Products__c</fullName>
            </value>
            <value>
                <fullName>Exclude_Product_Specific_Language__c</fullName>
            </value>
            <value>
                <fullName>Experience_Products__c</fullName>
            </value>
            <value>
                <fullName>Extended_Initial_Term__c</fullName>
            </value>
            <value>
                <fullName>First_Segment_Months__c</fullName>
            </value>
            <value>
                <fullName>Flow_Enterprise_Products__c</fullName>
            </value>
            <value>
                <fullName>Include_Master_Term_Tax_Language__c</fullName>
            </value>
            <value>
                <fullName>Initial_Term_Discount__c</fullName>
            </value>
            <value>
                <fullName>Intake_Products__c</fullName>
            </value>
            <value>
                <fullName>Legacy_Relationships_Products__c</fullName>
            </value>
            <value>
                <fullName>License_Basis__c</fullName>
            </value>
            <value>
                <fullName>Line_of_Business__c</fullName>
            </value>
            <value>
                <fullName>List Amount</fullName>
            </value>
            <value>
                <fullName>master_product_pins_from_all_quote_lines__c</fullName>
            </value>
            <value>
                <fullName>SBQQ__ProductCode__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Term_Quote__c/Term_Quote__c.object-meta.xml
<CustomObject>
    <description>Junction object of SBQQ__Quote__c and SBQQ__QuoteTerm__c usied to generate terms for specific quote</description>
    <label>Term Quote</label>
    <nameField>
        <displayFormat>TQ-{000000}</displayFormat>
        <label>Term Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Term Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Term_Quote__c/fields/Print_Order__c.field-meta.xml
<CustomField>
    <fullName>Print_Order__c</fullName>
    <label>Print Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Term_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Term Quotes</relationshipLabel>
    <relationshipName>Term_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Term_Quote__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Term</label>
    <referenceTo>SBQQ__QuoteTerm__c</referenceTo>
    <relationshipLabel>Term Quotes</relationshipLabel>
    <relationshipName>Term_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Subsidiary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01:200 Integration Appliance (US)</fullName>
        <default>true</default>
        <label>01:200 Integration Appliance (US)</label>
    </customValue>
    <customValue>
        <fullName>05:400 TFG - US</fullName>
    </customValue>
    <customValue>
        <fullName>06:700 Rekoop Limited (UK)</fullName>
    </customValue>
    <customValue>
        <fullName>09:750 Rekoop Pty Limited (AUS)</fullName>
    </customValue>
    <customValue>
        <fullName>23:Gwabbit</fullName>
    </customValue>
    <customValue>
        <fullName>35:Repstor Limited</fullName>
    </customValue>
    <customValue>
        <fullName>37:Repstor, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>18:DealCloud, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>28:OnePlace Pte Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>42:Paragon Data Labs, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>22:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>22:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>Polar Placeholder</fullName>
        <isActive>false</isActive>
        <label>Polar Placeholder</label>
    </customValue>
    <description>Will be used in Account,Contract, Quote &amp; Order created as part of BIZ-47396 story</description>
    <masterLabel>Subsidiary</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteTermValidatorTest.cls
/**
 * @description       : This test class will cover QuoteTermValidator class.
 * @author            : Shikha Verma
 * @last modified on  : 11-29-2023
 * @last modified by  : Shikha Verma
 * Modifications Log
 * Ver   Date         Author         Modification
 * 1.0   11-29-2023   Shikha Verma   Initial Version
**/
@isTest
public class QuoteTermValidatorTest {
    /**
    * ***********************************************************
    * This method is test SetUp method 
    * ***********************************************************
    */
    @testSetup
    public static void setup(){     
        List<Account> accList = TestDataFactory.createAccount(1,True);              
        List<Opportunity> opportunityList = TestDataFactory.createOppty(1, accList[0].Id, true);
        List<SBQQ__Quote__c> quoteList = TestDataFactory.createQuote(1, opportunityList[0].Id, true);
        SBQQ__QuoteTerm__c quoteTerm = new SBQQ__QuoteTerm__c(SBQQ__Body__c='Subsidiary__c',SBQQ__PrintOrder__c=26,SBQQ__Active__c=true);
        insert quoteTerm;        
        Term_Quote__c termQuote = new Term_Quote__c(Quote__c=quoteList[0].Id,Term__c=quoteTerm.Id,Body__c='Test',Print_Order__c=300);
        insert termQuote;
    }
    
    /**
    * ***********************************************************
    * This method is test method for generateQuoteTerms
    * ***********************************************************
    */
    @isTest
    public static void testgenerateQuoteTerms(){        
        Test.startTest();
            List<SBQQ__Quote__c> quoteList = [SELECT Id, Name FROM SBQQ__Quote__c LIMIT 1];
            SBQQ__QuoteTerm__c quoteTerm = [SELECT Id, Name FROM SBQQ__QuoteTerm__c LIMIT 1];
            SBQQ__TermCondition__c termCondition1 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='SBQQ__ProductCode__c',SBQQ__Operator__c='contains',SBQQ__Value__c='DealCloud',SBQQ__Index__c=1);
            SBQQ__TermCondition__c termCondition2 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='SBQQ__ProductCode__c',SBQQ__Operator__c='does not contain',SBQQ__Value__c='Test',SBQQ__Index__c=2);
            SBQQ__TermCondition__c termCondition3 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='Contract_Master_Terms__c',SBQQ__Operator__c='not equals',SBQQ__Value__c='Existing Intapp MSSA Terms',SBQQ__Index__c=3);
            SBQQ__TermCondition__c termCondition4 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='Contract_Master_Terms__c',SBQQ__Operator__c='equals',SBQQ__Value__c='Existing Intapp MSSA Plus Cloud',SBQQ__Index__c=4);
            List<SBQQ__TermCondition__c> termCondList = new List<SBQQ__TermCondition__c>();
            termCondList.add(termCondition1);
            termCondList.add(termCondition2);
            termCondList.add(termCondition3);
            termCondList.add(termCondition4);
            insert termCondList;
            quoteTerm.SBQQ__ConditionsMet__c='Any';
            update quoteTerm;
            QuoteTermValidator.generateQuoteTerms(quoteList[0].Id);
            System.assertEquals(1,quoteList.size());
        Test.stopTest();
    }
    /**
    * ***********************************************************
    * This method is test method for generateQuoteTerms
    * ***********************************************************
    */
    @isTest
    public static void testgenerateQuoteTerms1(){  
        List<SBQQ__Quote__c> quoteList = [SELECT Id, Name FROM SBQQ__Quote__c LIMIT 1];
        SBQQ__QuoteTerm__c quoteTerm = [SELECT Id, Name FROM SBQQ__QuoteTerm__c LIMIT 1];
        SBQQ__TermCondition__c termCondition1 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='Subsidiary__c',SBQQ__Operator__c='contains',SBQQ__Value__c='DealCloud',SBQQ__Index__c=1);
        SBQQ__TermCondition__c termCondition2 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='Subsidiary__c',SBQQ__Operator__c='does not contain',SBQQ__Value__c='Test',SBQQ__Index__c=2);
        SBQQ__TermCondition__c termCondition3 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='Contract_Master_Terms__c',SBQQ__Operator__c='not equals',SBQQ__Value__c='Existing Intapp MSSA Terms',SBQQ__Index__c=3);
        SBQQ__TermCondition__c termCondition4 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='Contract_Master_Terms__c',SBQQ__Operator__c='equals',SBQQ__Value__c='Existing Intapp MSSA Plus Cloud',SBQQ__Index__c=4);
        List<SBQQ__TermCondition__c> termCondList = new List<SBQQ__TermCondition__c>();
        termCondList.add(termCondition1);
        termCondList.add(termCondition2);
        termCondList.add(termCondition3);
        termCondList.add(termCondition4);
        insert termCondList;
        quoteTerm.SBQQ__ConditionsMet__c='Custom';
        quoteTerm.SBQQ__AdvancedCondition__c='1 AND 2 AND ( 3 OR 4 )';
        update quoteTerm;
        Test.startTest();           
            QuoteTermValidator.generateQuoteTerms(quoteList[0].Id);
            System.assertEquals(1,quoteList.size());
        Test.stopTest();
    }
    
    /**
    * ***********************************************************
    * This method is test method for generateQuoteTerms
    * ***********************************************************
    */
    @isTest
    public static void testgenerateQuoteTerms2(){  
        List<SBQQ__Quote__c> quoteList = [SELECT Id, Name FROM SBQQ__Quote__c LIMIT 1];
        SBQQ__QuoteTerm__c quoteTerm = [SELECT Id, Name FROM SBQQ__QuoteTerm__c LIMIT 1];
        SBQQ__TermCondition__c termCondition1 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='Contract_Term_Version__c',SBQQ__Operator__c='greater or equals',SBQQ__Value__c='10.7',SBQQ__Index__c=1);
        SBQQ__TermCondition__c termCondition2 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='Contract_Term_Version__c',SBQQ__Operator__c='less than',SBQQ__Value__c='10.9',SBQQ__Index__c=2);
        SBQQ__TermCondition__c termCondition3 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='Contract_Term_Version__c',SBQQ__Operator__c='greater than',SBQQ__Value__c='10.6',SBQQ__Index__c=3);
        SBQQ__TermCondition__c termCondition4 = new SBQQ__TermCondition__c(SBQQ__QuoteTerm__c=quoteTerm.Id,SBQQ__TestedField__c='Contract_Term_Version__c',SBQQ__Operator__c='less or equals',SBQQ__Value__c='10.8',SBQQ__Index__c=4);
        List<SBQQ__TermCondition__c> termCondList = new List<SBQQ__TermCondition__c>();
        termCondList.add(termCondition1);
        termCondList.add(termCondition2);
        termCondList.add(termCondition3);
        termCondList.add(termCondition4);
        insert termCondList;
        quoteTerm.SBQQ__ConditionsMet__c='All';
        update quoteTerm;
        Test.startTest();           
            QuoteTermValidator.generateQuoteTerms(quoteList[0].Id);
            System.assertEquals(1,quoteList.size());
        Test.stopTest();
    }
    
}