force-app/main/default/objects/Account/fields/CRD__c.field-meta.xml
<CustomField>
    <fullName>CRD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Please pick the appropriate CRD for this account</description>
    <label>Account Mgr</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Amount_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Amount_Invoiced__c</fullName>
    <label>Amount Invoiced</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Date_Paid__c.field-meta.xml
<CustomField>
    <fullName>Date_Paid__c</fullName>
    <label>Date Paid (Expiring on Aug 2)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Is_Deleted_in_NS__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted_in_NS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>TRUE, if deleted from NetSuite</description>
    <inlineHelpText>TRUE, if deleted from NetSuite</inlineHelpText>
    <label>Is Deleted in NS?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Outstanding_Balance__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance__c</fullName>
    <label>Outstanding Balance(Expiring on Aug 2)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Sales_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Type__c</fullName>
    <label>Sales Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>New license sale</fullName>
            </value>
            <value>
                <fullName>Services Agreement</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>DTE Usage</fullName>
            </value>
            <value>
                <fullName>RollCall Usage</fullName>
            </value>
            <value>
                <fullName>Services Agreement–T&amp;M</fullName>
            </value>
            <value>
                <fullName>Services Agreement-Upgrade</fullName>
            </value>
            <value>
                <fullName>Comprehensive Mobile</fullName>
            </value>
            <value>
                <fullName>Evaulation Program</fullName>
            </value>
            <value>
                <fullName>DTE Axiom Upgrade</fullName>
            </value>
            <value>
                <fullName>Usage</fullName>
            </value>
            <value>
                <fullName>Additional DTE Licenses</fullName>
            </value>
            <value>
                <fullName>Renewal-Exception</fullName>
            </value>
            <value>
                <fullName>New Hardware</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NS_Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>NS Payments</relationshipLabel>
    <relationshipName>NS_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NS_Payment__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <description>Tran Date of Payment from NS</description>
    <inlineHelpText>Tran Date of Payment from NS</inlineHelpText>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NS_Payment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoicePastDueNotificationHandlerTest.cls
@isTest(seeAllData=true)
private class InvoicePastDueNotificationHandlerTest {
    
    @isTest static void TestInvoicePastDueHandler() {
        User u = TestUtil.createUser(true);
        Account a = TestUtil.CreateAccount(false);
        a.CRD__c = u.Id;
        insert a;

        List<Invoice__c> invoices = new List<Invoice__c>();
        
        invoices.add(new Invoice__c(Amount_Invoiced__c = 1200, Account__c = a.Id, Name = 'Invoice1', Outstanding_Balance__c = 1100.00, Due_Date__c = date.today().addDays(-30)));
        invoices.add(new Invoice__c(Amount_Invoiced__c = 1200, Account__c = a.Id, Name = 'Invoice2', Outstanding_Balance__c = 1100.00, Due_Date__c = date.today().addDays(-60)));
        invoices.add(new Invoice__c(Amount_Invoiced__c = 1200, Account__c = a.Id, Name = 'Invoice3', Outstanding_Balance__c = 1100.00, Due_Date__c = date.today().addDays(-90)));
        invoices.add(new Invoice__c(Amount_Invoiced__c= 1200, Account__c = a.Id, Name = 'Invoice5', Outstanding_Balance__c = 1100.00, Due_Date__c = date.today().addDays(-113)));
        invoices.add(new Invoice__c(Amount_Invoiced__c = 1200, Account__c = a.Id, Name = 'Invoice4', Outstanding_Balance__c = 1100.00, Date_Paid__c = date.today().addDays(-1), 
                    Due_Date__c = date.today().addDays(-95)));
        invoices.add(new Invoice__c(Amount_Invoiced__c = 1200, Account__c = a.Id, Name = 'Invoice5', Outstanding_Balance__c = 1100.00, Due_Date__c = date.today().addDays(-30),Sales_Order_Type__c = 'Services Agreement'));
        invoices.add(new Invoice__c(Amount_Invoiced__c = 1200, Account__c = a.Id, Name = 'Invoice6', Outstanding_Balance__c = 1100.00, Due_Date__c = date.today().addDays(-60),Sales_Order_Type__c = 'Services Agreement'));
        
        //updates
        invoices.add(new Invoice__c(Amount_Invoiced__c = 10, Account__c = a.Id, Name = 'Invoice1A',Outstanding_Balance__c = 1100.00, Due_Date__c = date.today().addDays(-60), 
                                   Date_Paid__c = Date.today().addDays(-1), Is_Deleted_in_NS__c = False));
        
        insert invoices;
        
        List<NS_Payment__c> payments = new List<NS_Payment__c>();
        
        for(Invoice__c invoice: invoices ){
            payments.add(new NS_Payment__c(Amount__c = 10, Invoice__c = invoice.id, Transaction_Date__c = Date.today().addDays(-1), Type__c = 'Payment'));
        }
        
        
        insert payments;
        
        invoices = new List<invoice__c>();
        invoices.add(new Invoice__c(Amount_Invoiced__c = 1200, Account__c = a.Id, Name = 'Invoice2A', Outstanding_Balance__c = 1100.00, Due_Date__c = date.today().addDays(-30),Sales_Order_Type__c = 'Services Agreement'));
        invoices.add(new Invoice__c(Amount_Invoiced__c = 1200, Account__c = a.Id, Name = 'Invoice2B', Outstanding_Balance__c = 1100.00, Due_Date__c = date.today().addDays(-60),Sales_Order_Type__c = 'Services Agreement'));
        invoices.add(new Invoice__c(CurrencyISOCode = 'USD', Amount_Invoiced__c = 5000, Account__c = a.Id, Name = 'Invoice2C', Due_Date__c = date.today().addDays(-90),
                                    Sales_Order_Type__c = 'Renewal'));
        invoices.add(new Invoice__c(CurrencyISOCode = 'USD', Amount_Invoiced__c = 5000, Account__c = a.Id, Name = 'Invoice2C', Due_Date__c = date.today().addDays(-113),
                                    Sales_Order_Type__c = 'Renewal'));
        
        insert invoices;
        
        InvoicePastDueNotificationHandler handler = new InvoicePastDueNotificationHandler();
        handler.SendNotifications();
    }

   /*
    @isTest static void TestInvoicePastDueWebService() {
        InvoicePastDueNotificationWebService.Send30DayNotifications(1000);
        InvoicePastDueNotificationWebService.Send60DayNotifications(1000);
        InvoicePastDueNotificationWebService.Send90DayNotifications(1000);
    }
    */
}