force-app/main/default/objects/Account/fields/CRD__c.field-meta.xml
<CustomField>
    <fullName>CRD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Please pick the appropriate CRD for this account</description>
    <label>Account Mgr</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Governance</fullName>
                <default>true</default>
                <label>Pending Governance</label>
            </value>
            <value>
                <fullName>Verification Approved</fullName>
            </value>
            <value>
                <fullName>Verification Declined</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Related_OSA__c.field-meta.xml
<CustomField>
    <fullName>Related_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related OSA</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Sales_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Type__c</fullName>
    <label>Sales Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>New license sale</fullName>
            </value>
            <value>
                <fullName>Services Agreement</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>DTE Usage</fullName>
            </value>
            <value>
                <fullName>RollCall Usage</fullName>
            </value>
            <value>
                <fullName>Services Agreement–T&amp;M</fullName>
            </value>
            <value>
                <fullName>Services Agreement-Upgrade</fullName>
            </value>
            <value>
                <fullName>Comprehensive Mobile</fullName>
            </value>
            <value>
                <fullName>Evaulation Program</fullName>
            </value>
            <value>
                <fullName>DTE Axiom Upgrade</fullName>
            </value>
            <value>
                <fullName>Usage</fullName>
            </value>
            <value>
                <fullName>Additional DTE Licenses</fullName>
            </value>
            <value>
                <fullName>Renewal-Exception</fullName>
            </value>
            <value>
                <fullName>New Hardware</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status (Expiring on Aug 2)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credited in Full</fullName>
            </value>
            <value>
                <fullName>Partially Credited</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Paid In Full</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoicePastDueNotificationScheduler.cls
/********************************************************************************     
 *  Name             :  InvoicePastDueNotificationScheduler
 *  Author           :  Intapp
 *  Description      :  Schedulable class to send out invoice past due notifications
 *
 *  Change history   :
 *  Date            Author                      Description
 *  04/07/15        Alan Westley                Separated out InvoicePastNotificationHandler class for better unit testing 
 ********************************************************************************/
global class InvoicePastDueNotificationScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        InvoicePastDueNotificationHandler handler = new InvoicePastDueNotificationHandler();
        handler.SendNotifications();
    }

    //public void SendTestNotification()
    //{
    //    EmailTemplate et = [SELECT id FROM EmailTemplate WHERE Name = 'Invoice Past Due 30 Days'];
    //    List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
    //    Invoice__c invoice = [SELECT Id, Name, Account_Name__c, Related_OSA__r.ContractNumber, OSA_Name__c, Status__c, Due_Date__c 
    //        FROM Invoice__c WHERE Id = 'a1750000001oEIRAA2'];

    //    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); // new mail object
         
    //    mail.setSenderDisplayName('Jason Wood');    //Sender would be owner of Profile
    //    mail.setTargetObjectIds('0035000000ej4Cf');         //target to receipient
    //    mail.setWhatId(invoice.Id);
    //    mail.setTemplateId(et.id);                  // pull the email template through id
    //    messages.add(mail);
        
    //    Messaging.sendEmail(messages);  //send emails
    //}

    //public void Send30DayNotificationsTEST() {
    //    EmailTemplate et = [SELECT id FROM EmailTemplate WHERE Name = 'Invoice 30 Days Past Due'];
    //    List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
    //    List<Invoice__c> invoices = [SELECT Id, Name, Account__r.Name, Account__r.OwnerId, Account__r.CRD__c, Sales_Order_Type__c, 
    //        Related_OSA__r.ContractNumber, OSA_Name__c, Status__c, Due_Date__c 
    //        FROM Invoice__c WHERE Status__c = 'Open' and Due_Date__c = N_DAYS_AGO:30];
    //    for(Invoice__c invoice: invoices)
    //    {
    //        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); // new mail object
    //        List<Id> recipients = new List<Id> ();
    //        if (invoice.Sales_Order_Type__c == 'Renewal') {
    //            recipients.add(invoice.Account__r.CRD__c);
    //        }
    //        else {
    //            recipients.add(invoice.Account__r.OwnerId);
    //        }
    //        mail.setTargetObjectIds(recipients); 
    //        mail.setWhatIds(invoice.Id);
    //        mail.setTemplateId(et.Id);
    //        mail.setSaveAsActivity(false);
    //        mail.setSenderDisplayName('Jason Wood');//Sender would be owner of Profile

    //        messages.add(mail);
    //    }
        
    //    Messaging.sendEmail(messages);  //send emails
    //}

}