force-app/main/default/objects/Account/fields/CRD__c.field-meta.xml
<CustomField>
    <fullName>CRD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Please pick the appropriate CRD for this account</description>
    <label>Account Mgr</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Create_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Create_Prospect__c</fullName>
    <description>Action picklist : Setting a value to this field and saving this record would create a new Customer in NetSuite and subsequently OpenAir</description>
    <inlineHelpText>Action picklist : Setting a value to this field and saving this record would create a new Customer in NetSuite and subsequently OpenAir</inlineHelpText>
    <label>Create Prospect for NS Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>37</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
            <value>
                <fullName>05</fullName>
                <isActive>false</isActive>
                <label>05</label>
            </value>
            <value>
                <fullName>06</fullName>
                <isActive>false</isActive>
                <label>06</label>
            </value>
            <value>
                <fullName>09</fullName>
                <isActive>false</isActive>
                <label>09</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/CRD__c.field-meta.xml
<CustomField>
    <fullName>CRD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSM Account Mgr</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Subscriptions_CRD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
                <color>#E27001</color>
                <label>Intapp Open - Conflicts</label>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
                <color>#E27001</color>
                <label>Intapp Open - Intake</label>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Time</fullName>
                <color>#78C953</color>
                <label>Intapp Time</label>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
                <color>#E27001</color>
                <label>TFG - Other</label>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
                <label>PSP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountsTest.cls
/**
 * @modified by Venkataraman Sriram
 * 
 * @description Test class for Accounts Trigger
 *
 * @modified on 2/9/2018
 **/ 

@isTest
private class AccountsTest {
    
    @isTest static void testAccountTypeChange() {
        User usr = (User) SmartFactory.createSObject('User');
        insert usr;

        User usr2 = (User) SmartFactory.createSObject('User');
        insert usr2;
        
        User usr3 = (User) SmartFactory.createSObject('User');
        insert usr3;

        Account a = new Account ();
        a = IntappTestObjectFactory.createAccount(false);

        a.CRD__c = usr.Id;
        a.Type = 'Customer';
        a.Create_Prospect__c = '01';
        a.BillingCountry = 'United States';
        insert a;
        
        Subscription__c pc = (Subscription__c) SmartFactory.createSObject('Subscription__c');
        PC.Account__c = a.Id;
        PC.CRD__c = usr.Id;
        PC.Product_Line__c = 'Time';
        insert PC;

        a.CRD__c = usr2.Id;
        update a;

        //Change to Customer-Lapsed changes the Account Manager to null
        //This inturn triggers the coverage for other functions
        
        a.Type = 'Customer - Lapsed';
        a.OwnerId = usr.Id;
        update a;

       // a = [Select Id, CRD__c from Account where Id =: a.Id];
        System.assertNotEquals(null, a.CRD__c);
        
        
        a.CRD__c = null;
        update a;
        
		Contact c = new Contact ();
		c.OwnerId = usr3.Id;
        c.LastName = 'Last';
        insert c;
        Contact c1 = new Contact ();
        c1.AccountId = a.id;
		c1.OwnerId = usr3.Id;
        c1.LastName = 'Last1';
        insert c1;
        a.OwnerId = usr2.Id;
        update a;
        
        List<Contact> testList = new list<Contact>();
        testList.add(c);
        testList.add(c1);
        update testList;           
    }  
    
     @isTest
    	 static void testOnStatusChangeRemoveAccountManager() {
         // Create test data
         User usr = (User) SmartFactory.createSObject('User');
         insert usr;
             
         User usr2 = (User) SmartFactory.createSObject('User');
         insert usr2;
             
 			Account account = new Account(Name = 'Test Account', CRD__c = usr.id);
 			insert account;

			Subscription__c subscription = new Subscription__c(Account__c = account.Id, CRD__c = usr2.Id);
 			insert subscription;

	 		List<Account> accounts = new List<Account>{account};
		    Accounts accountsHandler = new Accounts(accounts);

 		    Map<Id, SObject> existingRecords = new Map<Id, SObject>();
			existingRecords.put(account.Id, account);

             Test.startTest();
  
             accountsHandler.onStatusChangeRemoveAccountManager(existingRecords);
  
             Test.stopTest();
             System.assertNotEquals(null, account.Id);
  }
}