force-app/main/default/objects/Account/fields/Create_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Create_Prospect__c</fullName>
    <description>Action picklist : Setting a value to this field and saving this record would create a new Customer in NetSuite and subsequently OpenAir</description>
    <inlineHelpText>Action picklist : Setting a value to this field and saving this record would create a new Customer in NetSuite and subsequently OpenAir</inlineHelpText>
    <label>Create Prospect for NS Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>37</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
            <value>
                <fullName>05</fullName>
                <isActive>false</isActive>
                <label>05</label>
            </value>
            <value>
                <fullName>06</fullName>
                <isActive>false</isActive>
                <label>06</label>
            </value>
            <value>
                <fullName>09</fullName>
                <isActive>false</isActive>
                <label>09</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Subsidiaries__c.field-meta.xml
<CustomField>
    <fullName>Subsidiaries__c</fullName>
    <description>Available subsidiaries in NetSuite (C - Customer, P - Prospect)</description>
    <inlineHelpText>Available subsidiaries in NetSuite (C - Customer, P - Prospect)</inlineHelpText>
    <label>NS Subsidiaries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>--DO NOT SELECT--</fullName>
            </value>
            <value>
                <fullName>18P</fullName>
            </value>
            <value>
                <fullName>37C</fullName>
            </value>
            <value>
                <fullName>18C</fullName>
            </value>
            <value>
                <fullName>42C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(
  ISPICKVAL(StatusCode,&quot;Activated&quot;),
  TRUE,
  FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Account with whom we have the billing relationship.</inlineHelpText>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>This field denotes the Billing Subsidiary for this contract for the Account to Customer sync in NetSuite,</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Intapp_Settings__c/fields/NS_Customer_webhook_PROD__c.field-meta.xml
<CustomField>
    <fullName>NS_Customer_webhook_PROD__c</fullName>
    <label>NS Prospect/Customer webhook (PROD)</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Intapp_Settings__c/fields/NS_customer_webhook_sbx__c.field-meta.xml
<CustomField>
    <fullName>NS_customer_webhook_sbx__c</fullName>
    <label>NS Prospect/Customer webhook (SBX)</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Order/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Populate Subsidiary value from related contract created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Subsidiary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01:200 Integration Appliance (US)</fullName>
        <default>true</default>
        <label>01:200 Integration Appliance (US)</label>
    </customValue>
    <customValue>
        <fullName>05:400 TFG - US</fullName>
    </customValue>
    <customValue>
        <fullName>06:700 Rekoop Limited (UK)</fullName>
    </customValue>
    <customValue>
        <fullName>09:750 Rekoop Pty Limited (AUS)</fullName>
    </customValue>
    <customValue>
        <fullName>23:Gwabbit</fullName>
    </customValue>
    <customValue>
        <fullName>35:Repstor Limited</fullName>
    </customValue>
    <customValue>
        <fullName>37:Repstor, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>18:DealCloud, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>28:OnePlace Pte Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>42:Paragon Data Labs, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>22:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>22:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>Polar Placeholder</fullName>
        <isActive>false</isActive>
        <label>Polar Placeholder</label>
    </customValue>
    <description>Will be used in Account,Contract, Quote &amp; Order created as part of BIZ-47396 story</description>
    <masterLabel>Subsidiary</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IntegrationHandler.cls
public class IntegrationHandler {
    public class CustomerWrapper{
        public String recordId;
        public String customerNumber;
        public String customerCountry;
        public String subsidiary;
        public String updatedAccountSubsidiaries;
        public String accountType; //Prospect or Customer
        public String eventType;
        public String subsidiaries;
        
        public customerWrapper(String recordId, String customerNumber, String customerCountry, String subsidiary, 
                               String accountType, String accSubsidiaries, String eventType){
            this.recordId = recordId;
            if(subsidiary!=null) {
                this.customerNumber = subsidiary.contains('01')? customerNumber : customerNumber + ':' + subsidiary;
                this.UpdatedAccountSubsidiaries = accSubsidiaries == '' || accSubsidiaries == null ? subsidiary  : accSubsidiaries + ';' + subsidiary;
            } else {
                this.customerNumber = customerNumber;
            }
            this.customerCountry = getCountryNSFormat(customerCountry);
            this.subsidiary = subsidiary;
            //this.UpdatedAccountSubsidiaries += accountType.substring(0,1); //C or P
            this.accountType = accountType;                                   
            this.eventType = eventType;
        }
    }
    
    public static void createSignedCustomer(List<Contract> contracts){
        List<CustomerWrapper> wrapperList = new List<CustomerWrapper>();
        List<Contract> listContractsWithAccounts = [
            SELECT Id, Name, AccountId, Account.IntApp_Account_Number__c 
                 , Account.BillingCountry, Account.Subsidiaries__c
                 , Billing_Account__c, Billing_Account__r.IntApp_Account_Number__c 
                 , Billing_Account__r.BillingCountry, Billing_Account__r.Subsidiaries__c,Subsidiary__c
              FROM Contract
             WHERE Id in : contracts
               AND Subsidiary__c != null
               AND Active__c = TRUE
               AND Status = 'In Force'
        ];
        
        for(Contract contract : listContractsWithAccounts){
            
            //for Contract's Account
            if(contract.Account.BillingCountry != null) {
                CustomerWrapper customerWrapper = generateCustomerRequest(contract.Account,contract.Subsidiary__c);
                if (customerWrapper != null) {
                    wrapperList.add(customerWrapper);
                }
                
            }

            //for Contract's Billing Account is present and is not same as Account
            if(contract.Billing_Account__c != null 
                && contract.AccountId != contract.Billing_Account__c
                && contract.Billing_Account__r.BillingCountry != null) {
                CustomerWrapper customerWrapper = generateCustomerRequest(contract.Billing_Account__r,contract.Subsidiary__c);
                if (customerWrapper != null) {
                    wrapperList.add(customerWrapper);
                }
            }
            
        }
        
        if(wrapperList.size() > 0 && !Test.isRunningTest()) {
            SendRequest(JSON.serialize(wrapperList));
            System.debug('@@request Body' +JSON.serialize(wrapperList));
        }
        
    }

    public static void createSignedCustomerFromOrder(List<Order> orders){
        List<CustomerWrapper> wrapperList = new List<CustomerWrapper>();
        List<Order> orderList = [
            SELECT Id, Name, AccountId, Account.IntApp_Account_Number__c 
                 , Account.BillingCountry, Account.Subsidiaries__c
                 , blng__BillingAccount__c, blng__BillingAccount__r.IntApp_Account_Number__c 
                 , blng__BillingAccount__r.BillingCountry, blng__BillingAccount__r.Subsidiaries__c,Subsidiary__c
              FROM Order
             WHERE Id in : orders
        ];
        
        for(Order order : orderList){
            
            //for Order's Account
            if(order.Account.BillingCountry != null) {
                CustomerWrapper customerWrapper = generateCustomerRequest(order.Account,order.Subsidiary__c);
                if (customerWrapper != null) {
                    wrapperList.add(customerWrapper);
                }
                
            }

            //for Order's Billing Account is present and is not same as Account
            if(order.blng__BillingAccount__c != null 
                && order.AccountId != order.blng__BillingAccount__c
                && order.blng__BillingAccount__r.BillingCountry != null) {
                CustomerWrapper customerWrapper = generateCustomerRequest(order.blng__BillingAccount__r,order.Subsidiary__c);
                if (customerWrapper != null) {
                    wrapperList.add(customerWrapper);
                }
            }
            
        }
        
        if(wrapperList.size() > 0 && !Test.isRunningTest()) {
            SendRequest(JSON.serialize(wrapperList));
        }
        
    }

    public static CustomerWrapper generateCustomerRequest(Account account, string subsidiary) {
        CustomerWrapper customerWrapper;
        //subsidiary for this contract - eg. 01:200
        //String subsidiary = contract.Subsidiary__c;
        String eventType = 'Create';
        //subsidiary for all the contracts - eg. 01,05,06
        String accsubsidiaries = account.Subsidiaries__c == null? '': account.Subsidiaries__c;
        
        //If no subsidiary is assigned, then do not process 
        if(!(subsidiary == null || !subsidiary.contains(':'))) {
            subsidiary = subsidiary.split(':')[0];
            
            //If contract already has a customer in NetSuite
            if(!(accsubsidiaries != '' && accsubsidiaries.contains(subsidiary + 'C'))) {
                if(!(accsubsidiaries != '' && accsubsidiaries.contains(subsidiary + 'P'))){
                    accsubsidiaries = accsubsidiaries.contains(subsidiary + 'P;') ? accsubsidiaries.remove(subsidiary + 'P;'):accsubsidiaries.remove(subsidiary + 'P');
                    eventType = 'Update';
                }
                customerWrapper = new CustomerWrapper(account.Id, account.IntApp_Account_Number__c, account.BillingCountry, subsidiary, 'Customer', accsubsidiaries, eventType);
            }
        }
        return customerWrapper;
    }
    
    public static void createProspect(List<Account> accounts,Map<Id,Account> accountOldMap){
        List<CustomerWrapper> wrapperList = new List<CustomerWrapper>();
        for(Account acc : Accounts){
            String eventType = 'Create';
            //No value chosen in the action picklist - No processing required
            Account accountOld = accountOldMap.get(acc.Id);
            boolean hasProsepect = String.isNotblank(acc.Create_Prospect__c);
            system.debug('@@has Prospect' +hasProsepect);
            String custLabelValues = Label.Account_Details;
            List<String> accountFieldsCheck = custLabelValues.split(',');
            boolean isNameChange = false;
            for(String field: accountFieldsCheck){
                if(accountOld.get(field) != acc.get(field) && acc.Subsidiaries__c != null){
                    isNameChange = true;
                    break;      
                }
            }
            if (hasProsepect == false && isNameChange == false) {
                continue;
            }

            if(acc.Subsidiaries__c == null){
                acc.Subsidiaries__c = '';
            }
            
            //If subsidiaries for this account already includes the one set on the create subsidiary field, no processing required
            if(acc.Subsidiaries__c != '' && acc.Create_Prospect__c!=null && acc.Subsidiaries__c.contains(acc.Create_Prospect__c) && isNameChange == false){
                acc.Create_Prospect__c = null;
                continue;
            }

            eventType = hasProsepect == false && isNameChange == true? 'Update' : 'Create';
            
            CustomerWrapper wrapper = new CustomerWrapper(acc.Id, acc.IntApp_Account_Number__c, acc.BillingCountry, acc.Create_Prospect__c, 'Customer', acc.Subsidiaries__c, eventType);
            if (eventType == 'Update') {
                wrapper.customerNumber = acc.IntApp_Account_Number__c;
                wrapper.Subsidiaries = acc.Subsidiaries__c;
                wrapper.subsidiary = null;
                wrapper.accountType = null;
            }
            //SerializedWrapperList.add(JSON.serialize(wrapper));
            wrapperList.add(wrapper);
        }
        
        if(wrapperList.size() > 0 && !test.isRunningTest())
        {
            SendRequest(JSON.serialize(wrapperList)); 
            System.debug('@@request Body' +JSON.serialize(wrapperList));
        }       
    }
    
    public static String getCountryNSFormat(String countryCode){
        String customerCountry = countryCode.toLowerCase();
        
        if(countryCode == 'curaçao' || countryCode == 'usa' || countryCode == 'us')
            customerCountry = 'unitedStates';
        
        if(countryCode == 'uk') 
            customerCountry = 'unitedKingdom';
        
        if(countryCode.contains(' ')){
            List<String> wordSplit = countryCode.split(' ');
            Boolean firstWord = true;
            customerCountry = '';
            for(String eachWord: WordSplit){
                if(firstWord) customerCountry += eachWord.toLowerCase();
                else customerCountry += eachWord.capitalize();
                firstWord = false;
            }
        }
        
        return '_' + customerCountry;
    } 
    
    @future (callout = true)
    public static void sendRequest(String reqBody){
        Intapp_Settings__c settings = Intapp_Settings__c.getInstance();
        
        HttpRequest req = new HttpRequest();
        if(IsSandbox()) 
            req.setEndpoint(settings.NS_customer_webhook_sbx__c);
        else 
            req.setEndpoint(settings.NS_Customer_webhook_PROD__c);
        req.setMethod('POST');
        req.setBody(reqBody);
        Http http = new Http();
        HTTPResponse res = http.send(req);
    }
    
    public static Boolean isSandbox(){
        return [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
    }
}