force-app/main/default/objects/Account/fields/CRM__c.field-meta.xml
<CustomField>
    <fullName>CRM__c</fullName>
    <label>CRM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CRM - Cloud</fullName>
            </value>
            <value>
                <fullName>OnePlace CRM (Salesforce-Legacy)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dealcloud__c.field-meta.xml
<CustomField>
    <fullName>Dealcloud__c</fullName>
    <label>Dealcloud</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DealCloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Experience - On Prem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Flow__c.field-meta.xml
<CustomField>
    <fullName>Flow__c</fullName>
    <label>Flow</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Flow - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - On Prem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IIS__c.field-meta.xml
<CustomField>
    <fullName>IIS__c</fullName>
    <label>IIS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Integration Service - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Intake_Product__c.field-meta.xml
<CustomField>
    <fullName>Intake_Product__c</fullName>
    <label>Intake</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intake - On Prem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Integrate__c.field-meta.xml
<CustomField>
    <fullName>Integrate__c</fullName>
    <label>Integrate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - On Prem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/L_P__c.field-meta.xml
<CustomField>
    <fullName>L_P__c</fullName>
    <label>L&amp;P</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L&amp;P - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LegalKey__c.field-meta.xml
<CustomField>
    <fullName>LegalKey__c</fullName>
    <label>LegalKey</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LegalKey - On Prem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nudges__c.field-meta.xml
<CustomField>
    <fullName>Nudges__c</fullName>
    <label>Nudges</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nudges - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Pricing__c.field-meta.xml
<CustomField>
    <fullName>Pricing__c</fullName>
    <label>Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>Pricing - On Prem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Owned_Conflicts__c.field-meta.xml
<CustomField>
    <fullName>Product_Owned_Conflicts__c</fullName>
    <label>Product_Owned_Conflicts</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Conflicts - On Prem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Relationships__c.field-meta.xml
<CustomField>
    <fullName>Relationships__c</fullName>
    <label>Relationships</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
            <value>
                <fullName>Relationships - On Prem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level_CRM__c.field-meta.xml
<CustomField>
    <fullName>Support_Level_CRM__c</fullName>
    <label>Support Level - CRM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level_Dealcloud__c.field-meta.xml
<CustomField>
    <fullName>Support_Level_Dealcloud__c</fullName>
    <label>Support Level - Dealcloud</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level_Experience__c.field-meta.xml
<CustomField>
    <fullName>Support_Level_Experience__c</fullName>
    <label>Support Level - Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level_Flow__c.field-meta.xml
<CustomField>
    <fullName>Support_Level_Flow__c</fullName>
    <label>Support Level - Flow</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level_IIS__c.field-meta.xml
<CustomField>
    <fullName>Support_Level_IIS__c</fullName>
    <label>Support Level - IIS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level_Intake__c.field-meta.xml
<CustomField>
    <fullName>Support_Level_Intake__c</fullName>
    <label>Support Level - Intake</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level_Integrate__c.field-meta.xml
<CustomField>
    <fullName>Support_Level_Integrate__c</fullName>
    <label>Support Level - Integrate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level_L_P__c.field-meta.xml
<CustomField>
    <fullName>Support_Level_L_P__c</fullName>
    <label>Support Level - L&amp;P</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level_Nudges__c.field-meta.xml
<CustomField>
    <fullName>Support_Level_Nudges__c</fullName>
    <label>Support Level - Nudges</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Support_Level_Pricing__c</fullName>
    <label>Support Level - Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <label>Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Terms - On Prem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TFG_Other__c.field-meta.xml
<CustomField>
    <fullName>TFG_Other__c</fullName>
    <label>TFG - Other</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LegalKey - Legacy</fullName>
            </value>
            <value>
                <fullName>TFG - Legacy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Time - On Prem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Walls__c.field-meta.xml
<CustomField>
    <fullName>Walls__c</fullName>
    <label>Walls</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Walls - On Prem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CRM__c.field-meta.xml
<CustomField>
    <fullName>CRM__c</fullName>
    <label>CRM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>ContactEase</fullName>
            </value>
            <value>
                <fullName>Dynamics</fullName>
            </value>
            <value>
                <fullName>InterAction</fullName>
            </value>
            <value>
                <fullName>OnePlace</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>false</active>
    <businessProcess>Other</businessProcess>
    <description>Catch-all for uncategorized INTERNAL cases</description>
    <label>Other</label>
</RecordType>

force-app/main/default/classes/Batch_updateOwnership_Handler.cls
public class Batch_updateOwnership_Handler {
    
    public static String updateDCAccounts (List<Account> accounts){
        List<Account> accToUpdate = new List<Account>();
        
        for(Account b:accounts){
            if(b.DealCloud__c != 'DealCloud' || b.Support_Level_Dealcloud__c != 'Standard'){
                b.DealCloud__c = 'DealCloud';
                b.Support_Level_Dealcloud__c = 'Standard';
                accToUpdate.add(b);
            }
        }
        
        if(accToUpdate.size()> 0)
    		update accToUpdate;
        
        String errors = '';
        
        if(accToUpdate.size() > 0){
            Database.SaveResult[] updateResult = Database.update(accToUpdate, false);
            for (Database.SaveResult r : updateResult){
                if (!r.isSuccess()){
                	for (Database.Error e : r.getErrors()){ 
                		errors += r.getId() + '-' + e.getMessage() + '<b/>';
                    }
                }
            }
    	}
        
        return String.isBlank(errors)? '':errors;
	}	

    public static String updateNonDCAccounts(List<Product_Ownership_detail__c> trigger_new){
        Set<Id> accountId_set = new Set<Id>();
        Map<Id, Account> account_map = new Map<Id, Account>();
        
        //Sample map data - {00130000001RB23 = {'Experience' = 'Experience-Cloud', 'Intake' = 'Intake-On Prem'}}
        Map<Id, Map<String, String>> account_ownership_map = new Map<Id, Map<String, String>>();
        //Sample map data - {00130000001RB23 = {'Experience' = 'Standard', 'Intake' = 'Standard'}}
        Map<Id, Map<String, String>> account_supportLevel_map = new Map<Id, Map<String, String>>();
        
        //Final map that will contain only accounts that need to be updated
        Map<Id, Account> map_accountsToUpdate = new Map<Id, Account>();
        
        //Maps to get API name of the field dynamically
        Map<String, String> ownerShipFieldAPIName_map = new Map<String, String>{
                'CRM' => 'CRM__c',
                'DealCloud' => 'DealCloud__c',   
                'Experience' => 'Experience__c',
                'Flow' => 'Flow__c',
            	'IIS' => 'IIS__c',
                'Intake' => 'Intake_Product__c',
                'Integrate' => 'Integrate__c',
                'L&P' => 'L_P__c',
                'LegalKey' => 'LegalKey__c',
                'Nudges' => 'Nudges__c',
                'Pricing' => 'Pricing__c',
                'Conflicts' => 'Product_Owned_Conflicts__c',
                'Relationships' => 'Relationships__c',
                'Terms' => 'Terms__c',
                'TFG - Other' => 'TFG_Other__c',    
                'Time' => 'Time__c',
                'Walls' => 'Walls__c'
        };
            
        Map<String, String> supportLevelFieldAPIName_map = new Map<String, String>{
                'CRM' => 'Support_Level_CRM__c',
                'DealCloud' => 'Support_Level_DealCloud__c',   
                'Experience' => 'Support_Level_Experience__c',
                'Flow' => 'Support_Level_Flow__c',
            	'IIS' => 'Support_Level_IIS__c',
                'Intake' => 'Support_Level_Intake__c',
                'Integrate' => 'Support_Level_Integrate__c',
                'L&P' => 'Support_Level_L_P__c',
                'Nudges' => 'Support_Level_Nudges__c',
                'Pricing' => 'Support_Level_Pricing__c',
                'Conflicts' => 'Support_Level_Conflicts__c',
                'Relationships' => 'Support_Level_Relationships__c',
                'Terms' => 'Support_Level_Terms__c', 
                'Time' => 'Support_Level_Time__c',
                'Walls' => 'Support_Level_Walls__c'
        };
        
        
        for(Product_Ownership_detail__c pod: trigger_new){
            accountId_set.add(pod.Account_Name__c);
        }
        
        //Get all accounts in a map
        for(Account acc: [Select Id, Type, CRM__c, DealCloud__c, Experience__c, Flow__c, IIS__c, Intake_Product__c, 
                         		 Integrate__c, L_P__c, LegalKey__c, Nudges__c, Pricing__c, Product_Owned_Conflicts__c, Relationships__c, 
                          		 Terms__c, TFG_Other__c, Time__c, Walls__c,
                          		 Support_Level_CRM__c,Support_Level_DealCloud__c,Support_Level_Experience__c,Support_Level_Flow__c,
                          		 Support_Level_IIS__c,Support_Level_Intake__c,Support_Level_Integrate__c,Support_Level_L_P__c,
                          		 Support_Level_Nudges__c,Support_Level_Pricing__c,Support_Level_Conflicts__c,Support_Level_Relationships__c,
                          		 Support_Level_Terms__c,Support_Level_Time__c,Support_Level_Walls__c
                         FROM Account
                         WHERE Id in: accountId_set]){
                             
                             if(!account_map.containsKey(acc.id)){
                                 account_map.put(acc.id, acc);
                             } 
        }
        
        //Construct the map initialized in line 8 and 10 - Get data for all products except CRM - CRM needs License basis data
        for(AggregateResult pod: [Select count(id), 
                                  		 Product_line_link__r.Name pl, 
                                  		 Product_line_link__r.Simple_Product_Line__c spl,
                                  		 Account_Name__c,
                                  		 Support_Level__c
                                  FROM Product_Ownership_detail__c 
                                  WHERE Account_Name__c in : account_map.keySet() 
                                  AND Status__c NOT IN ('Converted', 'Lapsed')
                                  AND Product_line_link__r.Simple_Product_Line__c <> 'CRM'
                                  GROUP BY Product_line_link__r.Name, Product_line_link__r.Simple_Product_Line__c,Account_Name__c, Support_Level__c]){
                                      
                                      if(!account_ownership_map.containsKey((ID)pod.get('Account_Name__c'))){
                                          account_ownership_map.put((ID)pod.get('Account_Name__c'), new Map<String, String>());
                                          account_supportLevel_map.put((ID)pod.get('Account_Name__c'), new Map<String, String>());
                                      }
                                      
                                      //SPL for LegalKey is TFG - Other, the ownership hence goes to TFG - the logic below is to correct that
                                      if(((String)pod.get('pl')).contains('LegalKey')){
                                          account_ownership_map.get((ID)pod.get('Account_Name__c')).put('LegalKey', 'LegalKey - On Prem');
                                      }
                                      else{
                                      	account_ownership_map.get((ID)pod.get('Account_Name__c')).put((String)pod.get('spl'), (String)pod.get('pl'));
                                      }
                                      
                                      String convertedSupportLevel = '';
                                      
                                      if((String)pod.get('Support_Level__c') == null){
                                          convertedSupportLevel = 'Standard';
                                      }
                                      else{
                                          convertedSupportLevel = ((String)pod.get('Support_Level__c')).toLowerCase().contains('premium')?'Premium':'Standard';
                                      }
                                      
                                      account_supportLevel_map.get((ID)pod.get('Account_Name__c')).put((String)pod.get('spl'), convertedSupportLevel);
                                      
                                      //Special case - If Account owns IIS, then Flow - Cloud is automatically owned
                                      if((String)pod.get('spl') == 'IIS' && !(account_ownership_map.get((ID)pod.get('Account_Name__c')).containsKey('Flow'))){
                                          account_ownership_map.get((ID)pod.get('Account_Name__c')).put('Flow', 'Flow - Cloud');
                                          account_supportLevel_map.get((ID)pod.get('Account_Name__c')).put('Flow', convertedSupportLevel);
                                      }
                                      
                                      
                                  }
        
        //Cont. Construct the map initialized in line 8 and 10 - Get data for CRM - CRM needs License basis data
        for(AggregateResult pod: [Select Product_line_link__r.Name, 
                                                     Product_line_link__r.Simple_Product_Line__c spl,
                                                     Account_Name__c,
                                                     Support_Level__c,
                                              		 License_basis_link__r.Name lb 
                                              FROM Product_Ownership_detail__c 
                                              WHERE Account_Name__c in : account_map.keySet() 
                                              AND Status__c NOT IN ('Converted', 'Lapsed')
                                              AND Product_line_link__r.Simple_Product_Line__c = 'CRM'
                                              AND License_basis_link__c != null
                                              GROUP BY Product_line_link__r.Name, Product_line_link__r.Simple_Product_Line__c,Account_Name__c, 
                                              Support_Level__c, License_basis_link__r.Name]){
                                                 
                                                  if(!account_ownership_map.containsKey((ID)pod.get('Account_Name__c'))){
                                                      account_ownership_map.put((ID)pod.get('Account_Name__c'), new Map<String, String>());
                                                      account_supportLevel_map.put((ID)pod.get('Account_Name__c'), new Map<String, String>());
                                                  }
                                                  
                                                  if((String)pod.get('lb') == null) continue;
                                                  
                                                  String convertedCRMMapping = ((String)pod.get('lb')).toLowerCase().contains('oneplace') ? 'OnePlace CRM (Salesforce-Legacy)':'CRM - Cloud';
                                                  account_ownership_map.get((ID)pod.get('Account_Name__c')).put((String)pod.get('spl'), convertedCRMMapping);
                                                  
                                                  String convertedSupportLevel = '';
                                      
                                                  if((String)pod.get('Support_Level__c') == null){
												      convertedSupportLevel = 'Standard';
                                                  }
                                                  else{
                                                      convertedSupportLevel = ((String)pod.get('Support_Level__c')).toLowerCase().contains('premium')?'Premium':'Standard';
                                                  }
                                                  
                                                  account_supportLevel_map.get((ID)pod.get('Account_Name__c')).put((String)pod.get('spl'), convertedSupportLevel);
                                                  
            
        }
            
        for(Id accountId: account_map.keySet()){
            if(!account_ownership_map.containsKey(accountId)){
                //Non - DC Customers with PODs but Lapsed or Converted
            	for(String simpleProductLine: OwnerShipFieldAPIName_map.keySet()){
                	if(account_map.get(accountId).get(OwnerShipFieldAPIName_map.get(simpleProductLine)) != null ||
                       (supportLevelFieldAPIName_map.containsKey(simpleProductLine) && account_map.get(accountId).get(supportLevelFieldAPIName_map.get(simpleProductLine)) != null)){
                    	Account accountToUpdate = new Account();
                        if(map_accountsToUpdate.containsKey(accountId)){
                            accountToUpdate = map_accountsToUpdate.get(accountId);   
                        }
                        else{
                        	accountToUpdate = account_map.get(accountId);
                        }
                        accountToUpdate.put(OwnerShipFieldAPIName_map.get(simpleProductLine),null);
                        if(supportLevelFieldAPIName_map.containsKey(simpleProductLine)) accountToUpdate.put(supportLevelFieldAPIName_map.get(simpleProductLine),null);
                           
                        map_accountsToUpdate.put(accountId, accountToUpdate);
                    }
                }
                continue;
            }
            
            for(String simpleProductLine: OwnerShipFieldAPIName_map.keySet()){
                if(account_ownership_map.get(accountId).containsKey(simpleProductLine)){
                    //System.debug('SPL ' + simpleProductLine + ' check 1');
                    if(account_map.get(accountId).get(OwnerShipFieldAPIName_map.get(simpleProductLine)) != account_ownership_map.get(accountId).get(simpleProductLine)||
                       (supportLevelFieldAPIName_map.containsKey(simpleProductLine) && account_map.get(accountId).get(supportLevelFieldAPIName_map.get(simpleProductLine)) != null)){
                        //System.debug('SPL ' + simpleProductLine + ' check 2');
                    	Account accountToUpdate = new Account();
                        if(map_accountsToUpdate.containsKey(accountId)){
                            accountToUpdate = map_accountsToUpdate.get(accountId);   
                        }
                        else{
                        	accountToUpdate = account_map.get(accountId);
                        }
                        accountToUpdate.put(OwnerShipFieldAPIName_map.get(simpleProductLine),account_ownership_map.get(accountId).get(simpleProductLine));
                        if(supportLevelFieldAPIName_map.containsKey(simpleProductLine)) accountToUpdate.put(supportLevelFieldAPIName_map.get(simpleProductLine),account_supportLevel_map.get(accountId).get(simpleProductLine));
                        map_accountsToUpdate.put(accountId, accountToUpdate);
                    }
                }
                else{
                    
                    if(account_map.get(accountId).get(OwnerShipFieldAPIName_map.get(simpleProductLine)) != null || 
                       (supportLevelFieldAPIName_map.containsKey(simpleProductLine) && account_map.get(accountId).get(supportLevelFieldAPIName_map.get(simpleProductLine)) != null)){
                    	Account accountToUpdate = new Account();
                        if(map_accountsToUpdate.containsKey(accountId)){
                        	accountToUpdate = map_accountsToUpdate.get(accountId);   
                        }
                        else{
                        	accountToUpdate = account_map.get(accountId);
                        }
                        accountToUpdate.put(OwnerShipFieldAPIName_map.get(simpleProductLine),null);
                        if(supportLevelFieldAPIName_map.containsKey(simpleProductLine))accountToUpdate.put(supportLevelFieldAPIName_map.get(simpleProductLine),null);
                        map_accountsToUpdate.put(accountId, accountToUpdate);
                    }
                }
        	} 
        }
        
        String errors = '';
        
        if(map_accountsToUpdate.size() > 0){
            Database.SaveResult[] updateResult = Database.update(map_accountsToUpdate.values(), false);
            for (Database.SaveResult r : updateResult){
                if (!r.isSuccess()){
                	for (Database.Error e : r.getErrors()){ 
                		errors += r.getId() + '-' + e.getMessage() + '<br/>';
                    }
                }
            }
    	}
        
        return String.isBlank(errors)? '':errors;
        
    }
}