force-app/main/default/objects/Account/fields/Dealcloud__c.field-meta.xml
<CustomField>
    <fullName>Dealcloud__c</fullName>
    <label>Dealcloud</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DealCloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</description>
    <inlineHelpText>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</inlineHelpText>
    <label>License Basis - DO NOT USE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Governance</fullName>
                <default>true</default>
                <label>Pending Governance</label>
            </value>
            <value>
                <fullName>Verification Approved</fullName>
            </value>
            <value>
                <fullName>Verification Declined</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/License_Basis__c/fields/Highest_Package__c.field-meta.xml
<CustomField>
    <fullName>Highest_Package__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox indicates if this license basis is the highest package available for a Product Line.</description>
    <label>Highest Package</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/License_Basis__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>License Basis</relationshipLabel>
    <relationshipName>License_Basis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is used to determine if this field should be available for use in the Product Line lookup fields.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Simple_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Simple_Product_Line__c</fullName>
    <description>Field used to simplify the product line list for reporting purposes. This is used in the data warehouse.</description>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Conflicts</fullName>
            </value>
            <value>
                <fullName>Experience</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Integrate</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>L&amp;P</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Relationships</fullName>
            </value>
            <value>
                <fullName>Terms</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Walls</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>DealCloud</fullName>
            </value>
            <value>
                <fullName>IIS</fullName>
            </value>
            <value>
                <fullName>Small Firms</fullName>
            </value>
            <value>
                <fullName>Nudges</fullName>
            </value>
            <value>
                <fullName>OPIS</fullName>
            </value>
            <value>
                <fullName>OnePlace</fullName>
            </value>
            <value>
                <fullName>OPMBD</fullName>
            </value>
            <value>
                <fullName>Data - Risk</fullName>
            </value>
            <value>
                <fullName>Data - MBD</fullName>
            </value>
            <value>
                <fullName>Collaboration &amp; Content</fullName>
                <label>C&amp;C Other</label>
            </value>
            <value>
                <fullName>Billstream</fullName>
            </value>
            <value>
                <fullName>Documents</fullName>
            </value>
            <value>
                <fullName>Workspaces</fullName>
            </value>
            <value>
                <fullName>Multiple Products – C&amp;C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Ownership Details</relationshipLabel>
    <relationshipName>Product_Ownership_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <label>License Basis (EXPIRING 3/8)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Line__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activity Tracker</fullName>
            </value>
            <value>
                <fullName>Additional Security Extensions</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
            <value>
                <fullName>Advanced - Cloud</fullName>
            </value>
            <value>
                <fullName>Advanced Security Package</fullName>
            </value>
            <value>
                <fullName>AI Module</fullName>
            </value>
            <value>
                <fullName>Assessment Module</fullName>
            </value>
            <value>
                <fullName>Attorney Acknowledgements</fullName>
            </value>
            <value>
                <fullName>Auditing Package</fullName>
            </value>
            <value>
                <fullName>CG Analyze</fullName>
            </value>
            <value>
                <fullName>CG Clear</fullName>
            </value>
            <value>
                <fullName>CG Flow</fullName>
            </value>
            <value>
                <fullName>CG Hold</fullName>
            </value>
            <value>
                <fullName>CG Lateral Hire</fullName>
            </value>
            <value>
                <fullName>CG Mobile</fullName>
            </value>
            <value>
                <fullName>CG Protect</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Confidentiality Package</fullName>
            </value>
            <value>
                <fullName>Confidentiality Plus</fullName>
                <label>Confidentiality Plus Package</label>
            </value>
            <value>
                <fullName>Connected (Including Quick Search &amp; IRC)</fullName>
            </value>
            <value>
                <fullName>Contractors</fullName>
            </value>
            <value>
                <fullName>Criteria Based Access</fullName>
            </value>
            <value>
                <fullName>D&amp;B Company Profile &amp; Family Tree</fullName>
            </value>
            <value>
                <fullName>DMS Package</fullName>
            </value>
            <value>
                <fullName>Axiom</fullName>
                <label>DTE - Axiom</label>
            </value>
            <value>
                <fullName>Axiom Mobile</fullName>
                <label>DTE - Axiom Mobile</label>
            </value>
            <value>
                <fullName>Legacy DTE</fullName>
                <label>DTE - Legacy</label>
            </value>
            <value>
                <fullName>Legacy Mobile</fullName>
                <label>DTE - Legacy Mobile</label>
            </value>
            <value>
                <fullName>Dynamic Groups</fullName>
            </value>
            <value>
                <fullName>eBillingHub Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>SC-000016</description>
    <label>Product Line (EXPIRING 3/8)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conflicts</fullName>
            </value>
            <value>
                <fullName>Experience</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
                <label>Integrate</label>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Terms</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Walls</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
                <isActive>false</isActive>
                <label>Third Party Product - Experience</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Product_line_link__c.field-meta.xml
<CustomField>
    <fullName>Product_line_link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Product Ownership Details</relationshipLabel>
    <relationshipName>Product_Ownership_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Own it</fullName>
            </value>
            <value>
                <fullName>Own Partial</fullName>
            </value>
            <value>
                <fullName>Own it - Limited License</fullName>
            </value>
            <value>
                <fullName>Own it - Trial</fullName>
            </value>
            <value>
                <fullName>Entitled</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Own it - Bridgeway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Batch_updateOwnership.cls
@isTest
private class Test_Batch_updateOwnership {

    static testmethod void test_DC() {
    
    // Create test accounts to be updated
    // by the batch job.
    
        List<Account> accList = new List<Account>();
        for (Integer i=0;i<200;i++) {
            Account m = new Account(Name = 'Account ' + i, Type = 'DealCloud Customer');
            accList.add(m);
        }
        insert accList;
        
        Test.startTest();
            Batch_updateOwnership_DC c = new Batch_updateOwnership_DC('');
            Database.executeBatch(c);
        Test.stopTest();
        
        // Verify accounts updated
        Account[] accUpdatedList = [SELECT Id,Name,Dealcloud__c FROM Account];
        System.assertEquals('DealCloud', accUpdatedList[0].DealCloud__c);
    }
    
    static testmethod void test_nonDC() {
    
    // Create test accounts to be updated
    // by the batch job.
    
        List<Account> accList = new List<Account>();
        for (Integer i=0;i<1;i++) {
            Account m = new Account(Name = 'Account ' + i, Type = 'Customer');
            accList.add(m);
        }
        insert accList;
        
        List<Product_Ownership_Detail__c> podList = new List<Product_Ownership_Detail__c>();
        
        Product_line__c experience = new Product_Line__c();
        experience.Name = 'Experience - Cloud';
        experience.Simple_Product_Line__c = 'Experience';
        experience.Active__c = true;
        insert experience;
        
        Product_line__c crm = new Product_Line__c();
        crm.Name = 'CRM - Cloud';
        crm.Simple_Product_Line__c = 'CRM';
        crm.Active__c = true;
        insert crm;
        
        Product_line__c legalKey = new Product_Line__c();
        legalKey.Name = 'LegalKey - Legacy';
        legalKey.Simple_Product_Line__c = 'TFG - Other';
        legalKey.Active__c = true;
        insert legalKey;
        
        License_Basis__c crm_cloud = new License_Basis__c();
        crm_cloud.Name = 'CRM - Cloud';
        crm_cloud.Product_Line__c = crm.id;
        crm_cloud.Highest_Package__c = true;
        insert crm_cloud;
        
        for(Account a: accList){
            Product_Ownership_Detail__c pod_experience = new Product_Ownership_Detail__c();
            pod_experience.Product_line_link__c = legalKey.Id;
            pod_experience.Account_Name__c = a.Id;
            pod_experience.Status__c = 'Own it - Trial';
            pod_experience.Support_Level__c = 'Standard (Silver)';
            podList.add(pod_experience);
            
            /*
            Product_Ownership_Detail__c pod_crm = new Product_Ownership_Detail__c();
            pod_crm.Product_line_link__c = crm.Id;
            pod_crm.Account_Name__c = a.Id;
            pod_crm.Status__c = 'Own it';
            pod_crm.Support_Level__c = 'Standard (Silver)';
            pod_crm.License_basis_link__c = crm_cloud.id;
            
            podList.add(pod_crm);
			*/
        }
        
        insert podList;
        
        Test.startTest();
            Batch_updateOwnership_nonDC c = new Batch_updateOwnership_nonDC('');
            Database.executeBatch(c);
        Test.stopTest();
        
            // Verify accounts updated
        Account[] accUpdatedList = [SELECT Id,Name,Experience__c,TFG_Other__c, LegalKey__c FROM Account];
        System.assertEquals('LegalKey - On Prem', accUpdatedList[0].LegalKey__c);
        
    }
    
    static testmethod void test_nonDC2() {
        List<Account> accList = new List<Account>();
        List<Product_Ownership_Detail__c> podList = new List<Product_Ownership_Detail__c>();
        
        for (Integer i=0;i<1;i++) {
            Account m = new Account(Name = 'Account ' + i, Type = 'Customer', TFG_Other__c = 'LegalKey - Legacy');
            accList.add(m);
        }
        insert accList;
        
        Product_line__c legalKey = new Product_Line__c();
        legalKey.Name = 'LegalKey - Legacy';
        legalKey.Simple_Product_Line__c = 'TFG - Other';
        legalKey.Active__c = true;
        insert legalKey;
        
        for(Account a: accList){
            Product_Ownership_Detail__c pod_experience = new Product_Ownership_Detail__c();
            pod_experience.Product_line_link__c = legalKey.Id;
            pod_experience.Account_Name__c = a.Id;
            pod_experience.Status__c = 'Lapsed';
            pod_experience.Support_Level__c = 'Standard (Silver)';
            podList.add(pod_experience);
        }
        
        insert podList;
        
        Test.startTest();
            Batch_updateOwnership_nonDC c = new Batch_updateOwnership_nonDC('');
            Database.executeBatch(c);
        Test.stopTest();
    }
    
    static testmethod void test_scheduler_DC(){
        List<Account> accList = new List<Account>();
        for (Integer i=0;i<200;i++) {
            Account m = new Account(Name = 'Account ' + i, Type = 'DealCloud Customer');
            accList.add(m);
        }
        insert accList;
        String CRON_EXP = '0 0 0 15 3 ? *';
        String jobId = System.schedule('ScheduleApexClassTest',  CRON_EXP, new Batch_updateOwnership_DC_scheduler());
    }
    
    static testmethod void test_scheduler_nonDC(){
        List<Account> accList = new List<Account>();
        for (Integer i=0;i<1;i++) {
            Account m = new Account(Name = 'Account ' + i, Type = 'Customer');
            accList.add(m);
        }
        insert accList;
        
        List<Product_Ownership_Detail__c> podList = new List<Product_Ownership_Detail__c>();
        
        Product_line__c experience = new Product_Line__c();
        experience.Name = 'Experience - Cloud';
        experience.Simple_Product_Line__c = 'Experience';
        experience.Active__c = true;
        insert experience;
        
        Product_line__c crm = new Product_Line__c();
        crm.Name = 'CRM - Cloud';
        crm.Simple_Product_Line__c = 'CRM';
        crm.Active__c = true;
        insert crm;
        
        Product_line__c legalKey = new Product_Line__c();
        legalKey.Name = 'LegalKey - Legacy';
        legalKey.Simple_Product_Line__c = 'TFG - Other';
        legalKey.Active__c = true;
        insert legalKey;
        
        License_Basis__c crm_cloud = new License_Basis__c();
        crm_cloud.Name = 'CRM - Cloud';
        crm_cloud.Product_Line__c = crm.id;
        crm_cloud.Highest_Package__c = true;
        insert crm_cloud;
        
        for(Account a: accList){
            Product_Ownership_Detail__c pod_experience = new Product_Ownership_Detail__c();
            pod_experience.Product_line_link__c = legalKey.Id;
            pod_experience.Account_Name__c = a.Id;
            pod_experience.Status__c = 'Own it - Trial';
            pod_experience.Support_Level__c = 'Standard (Silver)';
            podList.add(pod_experience);
            
            /*
            Product_Ownership_Detail__c pod_crm = new Product_Ownership_Detail__c();
            pod_crm.Product_line_link__c = crm.Id;
            pod_crm.Account_Name__c = a.Id;
            pod_crm.Status__c = 'Own it';
            pod_crm.Support_Level__c = 'Standard (Silver)';
            pod_crm.License_basis_link__c = crm_cloud.id;
            
            podList.add(pod_crm);
			*/
        }
        
        insert podList;

        String CRON_EXP = '0 0 0 15 3 ? *';
        String jobId = System.schedule('ScheduleApexClassTest',  CRON_EXP, new Batch_updateOwnership_nonDC_scheduler());
    }
}