force-app/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OP4I_Deal_Id__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_Id__c</fullName>
    <label>OP4I Deal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-45119.</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Existing_Client__c.field-meta.xml
<CustomField>
    <fullName>Existing_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of  BIZ-49298 to capture URL parameters</description>
    <label>Existing Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Deal_Name__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_Name__c</fullName>
    <label>OP4I Deal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4IDealID__c.field-meta.xml
<CustomField>
    <fullName>OP4IDealID__c</fullName>
    <description>This is a reference ID of Deal ID</description>
    <externalId>true</externalId>
    <label>OP4I Deal ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Stage__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stage__c</fullName>
    <description>Sales user should be able to move a Quote to the Pricing Proposal stage when ready to create a Pricing Proposal Document, built as per BIZ-45102
Updated for story BIZ-49730..</description>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Configure Products</fullName>
                <default>true</default>
                <label>Configure Products</label>
            </value>
            <value>
                <fullName>Pricing Proposal</fullName>
            </value>
            <value>
                <fullName>Finalize OSA</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Contract Executed</fullName>
            </value>
            <value>
                <fullName>Closed-Lost</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Forecast</fullName>
                <isActive>false</isActive>
                <label>Forecast</label>
            </value>
            <value>
                <fullName>OSA</fullName>
                <isActive>false</isActive>
                <label>OSA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Draft_Quote.recordType-meta.xml
<RecordType>
    <fullName>Draft_Quote</fullName>
    <active>true</active>
    <label>Draft Quote</label>
</RecordType>

force-app/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired_Contract</fullName>
        <label>Acquired Contract</label>
    </customValue>
    <customValue>
        <fullName>Add-On</fullName>
        <label>Add-On Amendment</label>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Contract_Replacement</fullName>
        <label>Contract Replacement</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New_Software</fullName>
        <label>New Software</label>
    </customValue>
    <customValue>
        <fullName>NextYear_MultiYear</fullName>
        <label>Next Year, Multi-Year</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PlatformConversion_INTERNAL</fullName>
        <label>Platform Conversion - Internal</label>
    </customValue>
    <customValue>
        <fullName>Platform_Fee</fullName>
        <label>Platform Fee</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Services_Only</fullName>
        <label>Services Only</label>
    </customValue>
    <customValue>
        <fullName>Services_Replacement</fullName>
        <label>Services Replacement</label>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
    </customValue>
    <description>Modified as part of BIZ-46501</description>
    <masterLabel>Deal Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/SingleQuoteSingleDealController.cls
/**
* @description       : Controller class for SingleQuoteSingleDeal LWC Component
* @author            : Keerthan N
* Jira story : BIZ-45100,BIZ-45932,BIZ-46504,BIZ-46899,BIZ-49349
**/
public with sharing class SingleQuoteSingleDealController {
    
    //class to create quote and opportunity on click of manage quote from OP4I.
    @AuraEnabled
    public static String checkAndCreateQuote(String dealId, String accId, String dealType, String currencyIso,String existingClient){
        Savepoint sp = Database.setSavepoint();
        try{
            List<SBQQ__Quote__c> quoteList = [Select Id,Deal_Type__c From SBQQ__Quote__c Where OP4IDealID__c =: dealId Limit 1];
            SBQQ__Quote__c quoteRec;
            List<Account> getAcc = [Select Id,Name,CurrencyIsoCode,Industry__c From Account Where Id =: accId Limit 1];
                if(quoteList.size() > 0 && getAcc.size() > 0){ // Added as part of BIZ-46504
                    quoteRec = quoteList[0]; 
                    if(quoteRec.Deal_Type__c != dealType){
                        quoteRec.Deal_Type__c = dealType;
                        Update quoteRec;
                    }
                }
                else{
                    if(getAcc.size() > 0){
                        String currencyCode='USD';
                        if(currencyIso != ''){
                            currencyCode = currencyIso;
                        }
                        else{
                            currencyCode = getAcc[0].CurrencyIsoCode;
                        }
                        Integer numberOfDays = Date.daysInMonth(System.Today().year(), System.Today().month());
                        Date lastDayOfMonth = Date.newInstance(System.Today().year(), System.Today().month(), numberOfDays);
                        Opportunity opp = new Opportunity();
                        opp.AccountId = getAcc[0].Id;
                        opp.Name = getAcc[0].Name;
                        opp.CloseDate = lastDayOfMonth;
                        opp.StageName = 'Qualify';
                        opp.OwnerId = UserInfo.getUserId();
                        opp.OP4I_Deal_Id__c = dealId;//BIZ-45932
                        opp.CurrencyIsoCode = currencyCode;
                        Insert opp;
                        SBQQ__Quote__c quot = new SBQQ__Quote__c();
                        Id devRecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('Draft_Quote').getRecordTypeId();
                        quot.SBQQ__Opportunity2__c = opp.Id;
                        quot.OwnerId = UserInfo.getUserId();
                        quot.SBQQ__Primary__c = True;
                        quot.OP4IDealID__c = dealId;
                        quot.OP4I_Deal_Name__c = dealId;
                        quot.SBQQ__Account__c = accId;
                        quot.recordTypeId = devRecordTypeId;
                        quot.Deal_Type__c = dealType;
                        quot.CurrencyIsoCode = currencyCode;
                        quot.Quote_Stage__c = System.Label.Configure_Products;
                        quot.Existing_Client__c = existingClient == 'Y' ? True : False;
                        Insert quot;
                        quoteRec = quot; 
                    }
                    else{
                        return 'Error;'+System.Label.Manage_Quote_Error;//Created as part of BIZ-46899
                    }
                }
                return 'Success;SBQQ__Quote__c;'+quoteRec.Id; 
        }
        catch(Exception e){
            Database.rollback(sp);
            return 'Error;'+e.getMessage();
            
        }
    }
}