force-app/main/default/objects/Account/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <inlineHelpText>What New Business Intake product does the customer currently use?</inlineHelpText>
    <label>Intake</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aderant NBI</fullName>
            </value>
            <value>
                <fullName>AgilePoint</fullName>
            </value>
            <value>
                <fullName>BizFlow</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>DB/Text</fullName>
            </value>
            <value>
                <fullName>Dimension Data</fullName>
            </value>
            <value>
                <fullName>Elegrity</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Elite 3E</fullName>
            </value>
            <value>
                <fullName>Elite Relay</fullName>
            </value>
            <value>
                <fullName>FloSuite</fullName>
            </value>
            <value>
                <fullName>Frayman Compliflow NBI</fullName>
            </value>
            <value>
                <fullName>iManage</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
            </value>
            <value>
                <fullName>Interwoven NBI</fullName>
            </value>
            <value>
                <fullName>K2</fullName>
            </value>
            <value>
                <fullName>LegalKey NBI</fullName>
            </value>
            <value>
                <fullName>Lexis One</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>MatterSphere</fullName>
            </value>
            <value>
                <fullName>Metastorm</fullName>
            </value>
            <value>
                <fullName>Metastorm (9+ Version)</fullName>
            </value>
            <value>
                <fullName>Metastorm (Pre 9 Version)</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Peppermint Technology</fullName>
            </value>
            <value>
                <fullName>SharePoint</fullName>
            </value>
            <value>
                <fullName>Ultimus/Elegrity</fullName>
            </value>
            <value>
                <fullName>viFormPath</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/pse__Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Consultant</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Data Architect</fullName>
            </value>
            <value>
                <fullName>Engagement Manager</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Partner Technologist</fullName>
            </value>
            <value>
                <fullName>Principal Architect</fullName>
            </value>
            <value>
                <fullName>Principal Consultant</fullName>
            </value>
            <value>
                <fullName>Programme Manager</fullName>
            </value>
            <value>
                <fullName>PS Management</fullName>
            </value>
            <value>
                <fullName>QA Engineer</fullName>
            </value>
            <value>
                <fullName>Senior Solution Engineer</fullName>
            </value>
            <value>
                <fullName>Services Product Engineer</fullName>
            </value>
            <value>
                <fullName>Solution Engineer</fullName>
            </value>
            <value>
                <fullName>Solution Engineer - After Hours</fullName>
            </value>
            <value>
                <fullName>Solutions Architect</fullName>
            </value>
            <value>
                <fullName>Team Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/IntappMetadataHelperTest.cls
@isTest(SeeAllData = true)
private class IntappMetadataHelperTest {
	@isTest static void TestGetPicklistValues() {
		List<String> results = IntappMetadataHelper.GetPicklistValues('Contact', 'pse__Resource_Role__c');
		system.assert(results.size() > 0);
	}
	@isTest static void TestGetMultiPicklistValues() {
		List<String> results = IntappMetadataHelper.GetPicklistValues('Account', 'Intake__c');
		system.assert(results.size() > 0);
	}
}