force-app/main/default/objects/Account/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</description>
    <inlineHelpText>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</inlineHelpText>
    <label>License Basis - DO NOT USE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <label>OP4I Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>01-Legal NA North</fullName>
            </value>
            <value>
                <fullName>01-Legal NA West</fullName>
            </value>
            <value>
                <fullName>01-PS NA North</fullName>
            </value>
            <value>
                <fullName>02-Legal NA East</fullName>
            </value>
            <value>
                <fullName>02-Legal NA South</fullName>
            </value>
            <value>
                <fullName>02-PS NA South/APAC</fullName>
            </value>
            <value>
                <fullName>03-Legal EMEA</fullName>
            </value>
            <value>
                <fullName>03-PS EMEA</fullName>
            </value>
            <value>
                <fullName>04-Legal APAC</fullName>
            </value>
            <value>
                <fullName>05-Legal Large Accounts</fullName>
            </value>
            <value>
                <fullName>06-Accounting/Consulting</fullName>
            </value>
            <value>
                <fullName>07-Corporate Legal</fullName>
            </value>
            <value>
                <fullName>08-FS NA East New Sales</fullName>
            </value>
            <value>
                <fullName>04 - FS NA New Sales</fullName>
                <isActive>false</isActive>
                <label>08-FS NA New Sales</label>
            </value>
            <value>
                <fullName>05 - FS EMEA New Sales</fullName>
                <isActive>false</isActive>
                <label>09-FS EMEA New Sales</label>
            </value>
            <value>
                <fullName>09-FS NA West New Sales</fullName>
            </value>
            <value>
                <fullName>06 - FS Account Management</fullName>
                <isActive>false</isActive>
                <label>10-FS Account Management</label>
            </value>
            <value>
                <fullName>10-FS APAC New Sales</fullName>
            </value>
            <value>
                <fullName>11-FS EMEA New Sales</fullName>
            </value>
            <value>
                <fullName>12-FS AM Core</fullName>
            </value>
            <value>
                <fullName>13-FS AM Enterprise</fullName>
            </value>
            <value>
                <fullName>14-FS AM EMEA</fullName>
            </value>
            <value>
                <fullName>15-FS AM Portfolio</fullName>
            </value>
            <value>
                <fullName>16-FS AM APAC</fullName>
            </value>
            <value>
                <fullName>17-Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <formula>SBQQ__Quote__r.OP4I_Sales_Segment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Sales Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>This field will be used to send data to Integration system;BIZ-51285</description>
    <formula>SBQQ__PrimaryQuote__r.OP4I_Sales_Segment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Sales Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Contract_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Requested_Contract_Expiration__c</fullName>
    <label>Requested Contract Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Submission</fullName>
                <default>true</default>
                <label>Pending Submission</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Deal_ACV__c.field-meta.xml
<CustomField>
    <fullName>Deal_ACV__c</fullName>
    <label>Deal ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <inlineHelpText>&apos;First invoice period (number of months)</inlineHelpText>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>CR #43996</description>
    <label>Meter Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fee Earners</fullName>
            </value>
            <value>
                <fullName>Lawyers</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Named Users</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
                <isActive>false</isActive>
                <label>Attorneys</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Deal_Synced__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OP4I Deal Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_OSA_Request_Received__c.field-meta.xml
<CustomField>
    <fullName>OP4I_OSA_Request_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <description>BIZ-201</description>
    <label>OP4I OSA Request Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>Holds the Sales Segment Values from OP4I Deal</description>
    <label>OP4I Sales Segment</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Initial license term (in months). By default, this will be populated to 12 months. It can be overwritten by Contract Ops.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Print_at_Quote__c.field-meta.xml
<CustomField>
    <fullName>Print_at_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Print at Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuoteLineTriggerHandlerTest.cls
@isTest
public class QuoteLineTriggerHandlerTest {

    static TestMethod void quoteLineMethod1(){
        Map<id,SBQQ__Quote__c> mapOfQuote= new Map<id,SBQQ__Quote__c>();
        Account acc = IntappTestObjectFactory.createAccount(true);
      	acc.Industry = 'Test Industry';
        acc.SBQQ__RenewalModel__c = 'Contract Based';
        acc.OP4I_Sales_Segment__c = '03-Legal EMEA';
        update acc;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Opportunity opp = IntappTestObjectFactory.createOpportunity();
        opp.Name= 'TestOppoty';
    	opp.AccountId = acc.Id;
        opp.StageName = '01. Qualify';
    	opp.Requested_Contract_Expiration__c = Date.today();
    	opp.Initial_Software_Term_Length_Months__c = 12;
    	insert opp;
        
        opp.Pricebook2Id = pricebookId;
        update opp;

        Product2 prodObj = (Product2) SmartFactory.createSObject('Product2');
        prodObj.Name = 'Testproduct';
        prodObj.IsActive = true;
        prodObj.ProductCode = '123462';
        insert prodObj;
        
        Product2 prodObj1 = (Product2) SmartFactory.createSObject('Product2');
        prodObj1.Name = 'Testproduct2';
        prodObj1.IsActive = true;
        prodObj1.ProductCode = '12346289';
        insert prodObj1;

        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=prodObj.id, UnitPrice=1, IsActive=True);
        insert pbe; 
        
        SBQQ__Quote__c newQuote = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
        newQuote.SBQQ__Opportunity2__c = opp.Id;
        newQuote.SBQQ__Account__c = acc.Id;
        newQuote.SBQQ__SubscriptionTerm__c =36;
        newQuote.First_Segment_Months__c = 12;
        newQuote.License_Basis__c = 'Lawyers';
        newQuote.Number_of_DLIs__c= 1;
        newQuote.Number_of_QLIs__c= 1;
        newQuote.ApprovalStatus__c = 'Pending';
        newQuote.OP4I_OSA_Request_Received__c = true;
        newQuote.OP4I_Deal_Synced__c = true;
        newQuote.Deal_ACV__c = null;
        newQuote.SBQQ__LastCalculatedOn__c = null;
        newQuote.SBQQ__LastSavedOn__c = null;
        newQuote.Number_of_QLIs__c = 3;
        insert newQuote;
        mapOfQuote.put(newQuote.id,newQuote);
        
        SBQQ__QuoteLine__c testqli1 = new SBQQ__QuoteLine__c();
        testqli1.SBQQ__Quote__c = newQuote.Id;
        testqli1.SBQQ__Quantity__c = 1;        
        testqli1.SBQQ__Product__c = prodObj.id;
        testqli1.Print_at_Quote__c = true;
        testqli1.SBQQ__CustomerPrice__c = 25;
        insert testqli1;
        List<SBQQ__QuoteLine__c> lstOfQLE = new List<SBQQ__QuoteLine__c>();
        lstOfQLE.add(testqli1);
        System.assertNotEquals(lstOfQLE.size(), null);
    }
    
    static TestMethod void quoteLineMethod2(){
        Map<id,SBQQ__Quote__c> mapOfQuote= new Map<id,SBQQ__Quote__c>();
        Account acc = IntappTestObjectFactory.createAccount(true);
      	acc.Industry = 'Test Industry';
        acc.SBQQ__RenewalModel__c = 'Contract Based';
        acc.OP4I_Sales_Segment__c = '03-Legal EMEA';
        update acc;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Opportunity opp = IntappTestObjectFactory.createOpportunity();
        opp.Name= 'TestOppoty';
    	opp.AccountId = acc.Id;
        opp.StageName = '01. Qualify';
    	opp.Requested_Contract_Expiration__c = Date.today();
    	opp.Initial_Software_Term_Length_Months__c = 12;
    	insert opp;
        
        opp.Pricebook2Id = pricebookId;
        update opp;

        Product2 prodObj = (Product2) SmartFactory.createSObject('Product2');
        prodObj.Name = 'Testproduct';
        prodObj.IsActive = true;
        prodObj.ProductCode = '123462';
        insert prodObj;
        
        Product2 prodObj1 = (Product2) SmartFactory.createSObject('Product2');
        prodObj1.Name = 'Testproduct2';
        prodObj1.IsActive = true;
        prodObj1.ProductCode = '12346289';
        insert prodObj1;

        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=prodObj.id, UnitPrice=1, IsActive=True);
        insert pbe; 
        
        SBQQ__Quote__c newQuote = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
        newQuote.SBQQ__Opportunity2__c = opp.Id;
        newQuote.SBQQ__Account__c = acc.Id;
        newQuote.SBQQ__SubscriptionTerm__c =36;
        newQuote.First_Segment_Months__c = 12;
        newQuote.License_Basis__c = 'Lawyers';
        newQuote.Number_of_DLIs__c= 1;
        newQuote.Number_of_QLIs__c= 1;
        newQuote.ApprovalStatus__c = 'Pending';
        newQuote.OP4I_OSA_Request_Received__c = true;
        newQuote.OP4I_Deal_Synced__c = true;
        newQuote.Deal_ACV__c = null;
        newQuote.SBQQ__LastCalculatedOn__c = null;
        newQuote.SBQQ__LastSavedOn__c = null;
        newQuote.Number_of_QLIs__c = 3;
        insert newQuote;
        mapOfQuote.put(newQuote.id,newQuote);
        
        SBQQ__QuoteLine__c testqli1 = new SBQQ__QuoteLine__c();
        testqli1.SBQQ__Quote__c = newQuote.Id;
        testqli1.SBQQ__Quantity__c = 1;        
        testqli1.SBQQ__Product__c = prodObj.id;
        testqli1.Print_at_Quote__c = true;
        testqli1.SBQQ__CustomerPrice__c = 25;
        insert testqli1;
        SBQQ__QuoteLine__c testqli2 = new SBQQ__QuoteLine__c();
        testqli2.SBQQ__Quote__c = newQuote.Id;
        testqli2.SBQQ__Quantity__c = 1;        
        testqli2.SBQQ__Product__c = prodObj.id;
        testqli2.Print_at_Quote__c = true;
        testqli2.SBQQ__CustomerPrice__c = 25;
        testqli2.SBQQ__RequiredBy__c=testqli1.id;
        insert testqli2;
        List<SBQQ__QuoteLine__c> lstOfQLE = new List<SBQQ__QuoteLine__c>();
        lstOfQLE.add(testqli1);
        lstOfQLE.add(testqli2);
        delete lstOfQLE;
        System.assertEquals(lstOfQLE.size(), null);
    }
}