force-app/main/default/objects/Account/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</description>
    <inlineHelpText>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</inlineHelpText>
    <label>License Basis - DO NOT USE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/Approvers_Matrix__c.object-meta.xml
<CustomObject>
    <label>Approver Matrix</label>
    <nameField>
        <label>Approvers Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approvers_Matrix__c/fields/Approver_Role__c.field-meta.xml
<CustomField>
    <fullName>Approver_Role__c</fullName>
    <label>Approver Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/fields/Approver_User__c.field-meta.xml
<CustomField>
    <fullName>Approver_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/fields/Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>Sales_Segment__c</fullName>
    <label>Sales Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Contract_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Requested_Contract_Expiration__c</fullName>
    <label>Requested Contract Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Submission</fullName>
                <default>true</default>
                <label>Pending Submission</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <inlineHelpText>&apos;First invoice period (number of months)</inlineHelpText>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>CR #43996</description>
    <label>Meter Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fee Earners</fullName>
            </value>
            <value>
                <fullName>Lawyers</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Named Users</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
                <isActive>false</isActive>
                <label>Attorneys</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Initial license term (in months). By default, this will be populated to 12 months. It can be overwritten by Contract Ops.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AssignDefaultApproversControllerTest.cls
@isTest
Public class AssignDefaultApproversControllerTest{
	@isTest
	private static void doProcessContractDefaultApprovers_Verify(){
		// Arrange
        String contractId;
        Database.SaveResult dsr;
        Account acc = new Account(Name = 'TestClsAcc', Industry = 'Banking' ,Type ='Prospect', Rating = 'Hot' );
        insert acc;
            
        Date dtToday = Date.today();
        Opportunity opp = new Opportunity(Name= 'TestOpp1805' , CloseDate = dtToday, StageName='Prospecting' , Amount = 8008);
        opp.AccountId = acc.Id;
        opp.Requested_Contract_Expiration__c = Date.today();
        opp.Initial_Software_Term_Length_Months__c = 12;
        insert opp;
  
        Approvers_Matrix__c AppMatrix1 = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix1.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix1.Approver_Role__c ='Segment Lead';
        AppMatrix1.Approver_User__c =userinfo.getUserId();
        insert AppMatrix1;
            
        SBQQ__Quote__c newQuote = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
        newQuote.SBQQ__Opportunity2__c = opp.Id;
        newQuote.SBQQ__Account__c = acc.Id;
        newQuote.SBQQ__SubscriptionTerm__c =36;
        newQuote.First_Segment_Months__c = 12;
		newQuote.License_Basis__c = 'Lawyers';
        newQuote.ApprovalStatus__c = 'Pending';    
        insert newQuote;
       
        Contract drContract;
        drContract=new Contract(AccountId=acc.Id);
        drContract.SBQQ__Quote__c = newQuote.ID;
        dsr=Database.insert(drContract,false);
        contractId = drContract.Id;
        
        // Act
        Test.startTest();
        PageReference pageref = new PageReference('/'+contractId);
        Test.setCurrentPage(pageref);
        pageref.getParameters().put('Id', String.valueOf(contractId));
       
        Contract contract1 = [SELECT Id
                              , Approval_Status__c
                              , SBQQ__Quote__r.ApprovalStatus__c
                              FROM Contract
                              WHERE Id = :contractId LIMIT 1];
       
        contract1.SBQQ__Quote__c = newQuote.ID;
        update contract1;
       
        AssignDefaultApproversController obj = new AssignDefaultApproversController(null);
        obj.doProcessContractDefaultApprovers();
        Test.stopTest();
            
		// Assert
        system.Assert(obj.isError == false);
    }
	@isTest
	private static void doProcessContractDefaultApprovers_NullQuote(){
        // Arrange   
        String contractId;
        Database.SaveResult dsr;
        Account acc = new Account(Name = 'TestClsAcc', Industry = 'Banking' ,Type ='Prospect', Rating = 'Hot' );
        insert acc;
            
        Date dtToday = Date.today();
        Opportunity opp = new Opportunity(Name= 'TestOpp1805' , CloseDate = dtToday, StageName='Prospecting' , Amount = 8008);
        opp.AccountId = acc.Id;
        opp.Requested_Contract_Expiration__c = Date.today();
        opp.Initial_Software_Term_Length_Months__c = 12;
        insert opp;
            
        Approvers_Matrix__c AppMatrix1 = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix1.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix1.Approver_Role__c ='Segment Lead';
        AppMatrix1.Approver_User__c =userinfo.getUserId();
        insert AppMatrix1;
            
        SBQQ__Quote__c newQuote = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
        newQuote.SBQQ__Opportunity2__c = opp.Id;
        newQuote.SBQQ__Account__c = acc.Id;
        newQuote.SBQQ__SubscriptionTerm__c =36;
        newQuote.First_Segment_Months__c = 12;
		newQuote.License_Basis__c = 'Lawyers';
        insert newQuote;
               
        Contract drContract;
        drContract=new Contract(AccountId=acc.Id);
        drContract.SBQQ__Quote__c = null;
        dsr=Database.insert(drContract,false);
        contractId = drContract.Id;
        
        // Act
        Test.startTest();
        PageReference pageref = new PageReference('/'+contractId);
        Test.setCurrentPage(pageref);
        pageref.getParameters().put('Id', String.valueOf(contractId));
       
        Contract contract1 = [SELECT Id
                              , Approval_Status__c
                              , SBQQ__Quote__r.ApprovalStatus__c
                              FROM Contract
                              WHERE Id = :contractId LIMIT 1];
       
        contract1.SBQQ__Quote__c = null;
        update contract1;
        
        AssignDefaultApproversController obj = new AssignDefaultApproversController(null);
        obj.doProcessContractDefaultApprovers();
        Test.stopTest();

        // Assert
        system.Assert(obj.isError == true);
    }
	@isTest
	private static void doProcessContractDefaultApprovers_PendingApproval(){
        // Arrange
		String contractId;
        Database.SaveResult dsr;
        Account acc = new Account(Name = 'TestClsAcc', Industry = 'Banking' ,Type ='Prospect', Rating = 'Hot' );
        insert acc;
        Date dtToday = Date.today();
        
        Opportunity opp = new Opportunity(Name= 'TestOpp1805' , CloseDate = dtToday, StageName='Prospecting' , Amount = 8008);
        opp.AccountId = acc.Id;
        opp.Requested_Contract_Expiration__c = Date.today();
        opp.Initial_Software_Term_Length_Months__c = 12;
        insert opp;
  
        Approvers_Matrix__c AppMatrix1 = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix1.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix1.Approver_Role__c ='Segment Lead';
        AppMatrix1.Approver_User__c =userinfo.getUserId();
        insert AppMatrix1;
            
        SBQQ__Quote__c newQuote = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
        newQuote.SBQQ__Opportunity2__c = opp.Id;
        newQuote.SBQQ__Account__c = acc.Id;
        newQuote.SBQQ__SubscriptionTerm__c =36;
        newQuote.First_Segment_Months__c = 12;
        newQuote.ApprovalStatus__c = 'Pending';
		newQuote.License_Basis__c = 'Lawyers';
        insert newQuote;
       
        Contract drContract;
        drContract=new Contract(AccountId=acc.Id);
        drContract.SBQQ__Quote__c = newQuote.ID;
        drContract.Approval_Status__c = 'Pending';    
        dsr=Database.insert(drContract,false);
        contractId = drContract.Id;
        
        // Act            
        Test.startTest();
        PageReference pageref = new PageReference('/'+contractId);
        Test.setCurrentPage(pageref);
        pageref.getParameters().put('Id', String.valueOf(contractId));
       
        Contract contract1 = [SELECT Id
                              , Approval_Status__c
                              , SBQQ__Quote__r.ApprovalStatus__c,SBQQ__Quote__c
                              FROM Contract
                              WHERE Id = :contractId LIMIT 1];
       
        contract1.SBQQ__Quote__c = newQuote.ID;
        update contract1;

        AssignDefaultApproversController obj = new AssignDefaultApproversController(null);
        obj.doProcessContractDefaultApprovers();
        Test.stopTest();
        // Assert
        system.Assert(obj.isError == false);       
    }
	@isTest    
    private static void doProcessContractDefaultApprovers_Exception(){
        // Arrange
        Database.SaveResult dsr;
        Account acc = new Account(Name = 'TestClsAcc', Industry = 'Banking' ,Type ='Prospect', Rating = 'Hot' );
        insert acc;
        
        Date dtToday = Date.today();
        Opportunity opp = new Opportunity(Name= 'TestOpp1805' , CloseDate = dtToday, StageName='Prospecting' , Amount = 8008);
        opp.AccountId = acc.Id;
        opp.Requested_Contract_Expiration__c = Date.today();
        opp.Initial_Software_Term_Length_Months__c = 12;
        insert opp;
        
        Approvers_Matrix__c AppMatrix1 = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix1.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix1.Approver_Role__c ='Segment Lead';
        AppMatrix1.Approver_User__c =userinfo.getUserId();
        insert AppMatrix1;
        
        SBQQ__Quote__c newQuote = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
        newQuote.SBQQ__Opportunity2__c = opp.Id;
        newQuote.SBQQ__Account__c = acc.Id;
        newQuote.SBQQ__SubscriptionTerm__c =36;
        newQuote.First_Segment_Months__c = 12;
		newQuote.License_Basis__c = 'Lawyers';
        insert newQuote;
        
        Contract drContract;
        drContract=new Contract(AccountId=acc.Id);
        drContract.SBQQ__Quote__c = newQuote.Id;
        dsr=Database.insert(drContract,false);
        
        // Act
        Test.startTest();
        AssignDefaultApproversController obj = new AssignDefaultApproversController(null);
        obj.doProcessContractDefaultApprovers();
        Test.stopTest();
        
        // Assert
        system.Assert(obj.isError == true);
    }
    @isTest
    private static void doProcessContractDefaultApprovers_GoBackTest(){
        Test.startTest();
        AssignDefaultApproversController obj = new AssignDefaultApproversController(null);
        obj.goBack();
        Test.stopTest();
    }
}