force-app/main/default/objects/Account/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</description>
    <inlineHelpText>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</inlineHelpText>
    <label>License Basis - DO NOT USE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/Approvers_Matrix__c.object-meta.xml
<CustomObject>
    <label>Approver Matrix</label>
    <nameField>
        <label>Approvers Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approvers_Matrix__c/fields/Approver_User__c.field-meta.xml
<CustomField>
    <fullName>Approver_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>The record type to be used for products such as Wall Builder</description>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Submission</fullName>
                <default>true</default>
                <label>Pending Submission</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Deal_ACV__c.field-meta.xml
<CustomField>
    <fullName>Deal_ACV__c</fullName>
    <label>Deal ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <inlineHelpText>&apos;First invoice period (number of months)</inlineHelpText>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>CR #43996</description>
    <label>Meter Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fee Earners</fullName>
            </value>
            <value>
                <fullName>Lawyers</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Named Users</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
                <isActive>false</isActive>
                <label>Attorneys</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Deal_Synced__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Deal_Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OP4I Deal Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_OSA_Request_Received__c.field-meta.xml
<CustomField>
    <fullName>OP4I_OSA_Request_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <description>BIZ-201</description>
    <label>OP4I OSA Request Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/QLI_Update_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>QLI_Update_Date_Time__c</fullName>
    <label>QLI Update Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Initial license term (in months). By default, this will be populated to 12 months. It can be overwritten by Contract Ops.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Submit_For_Approval__c.field-meta.xml
<CustomField>
    <fullName>Submit_For_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit For Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuoteApprovalTriggerBatchTest.cls
@isTest
public class QuoteApprovalTriggerBatchTest{
    @testSetup
    static void setupTestData(){
		Account acc = IntappTestObjectFactory.createAccount(true);
    
        Id pricebookId = Test.getStandardPricebookId();
        
        Opportunity opp = IntappTestObjectFactory.createOpportunity();
		insert opp;      
        opp.Pricebook2Id = pricebookId;
        update opp;

        Approvers_Matrix__c appMatrix = IntappTestObjectFactory.createApproversMatrix();
        AppMatrix.Approver_User__c = userinfo.getUserId();
        insert AppMatrix;

        Product2 product = IntappTestObjectFactory.createProduct(true);

        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=product.id, UnitPrice=1, IsActive=True);
        insert pbe;
        
        SBQQ__Cost__c cost = new SBQQ__Cost__c();
        cost.SBQQ__Product__c = product.Id;
        cost.SBQQ__UnitCost__c = 100;
        insert cost;

        SBQQ__Quote__c newQuote = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
		newQuote.SBQQ__Opportunity2__c = opp.Id;
		newQuote.SBQQ__Account__c = acc.Id;
        newQuote.SBQQ__SubscriptionTerm__c =36;
        newQuote.First_Segment_Months__c = 12;
		newQuote.License_Basis__c = 'Lawyers';
        newQuote.Number_of_DLIs__c= 1;
        newQuote.Number_of_QLIs__c= 1;
        newQuote.ApprovalStatus__c = 'Pending';
        newQuote.OP4I_OSA_Request_Received__c = true;
        newQuote.OP4I_Deal_Synced__c = true;
        newQuote.Deal_ACV__c = null;
        newQuote.SBQQ__LastCalculatedOn__c = null;
        newQuote.SBQQ__LastSavedOn__c = null;
        newQuote.Submit_For_Approval__c = true;
        newQuote.QLI_Update_Date_Time__c =  Datetime.Now().addMinutes(-3);
        insert newQuote;
        
        System.assertNotEquals(acc.id, null);
    }

	@isTest static void quoteApprovalTriggerBatchIsUncalculated(){
        // Arrange
		List<SBQQ__Quote__c> quoteList = [SELECT Id
                                          ,Number_of_QLIs__c
                                          ,Number_of_DLIs__c
                                          ,ApprovalStatus__c
                                          ,Deal_ACV__c
                                          ,OP4I_Deal_Synced__c
                                          ,OP4I_OSA_Request_Received__c
                                          ,SBQQ__Uncalculated__c
                                          FROM SBQQ__Quote__c]; 
        
        // Act
        quoteList[0].Number_of_QLIs__c = 0;
        update quoteList[0];
        Test.startTest();
        database.executeBatch(new QuoteApprovalTriggerBatch());
        Test.stopTest();

		// Assert
        system.Assert(quoteList[0].SBQQ__Uncalculated__c == true);
    }
	@isTest static void quoteApprovalTriggerBatchIsCalculated(){
        // Arrange
		List<SBQQ__Quote__c> quoteList = [SELECT Id
                                          ,Number_of_QLIs__c
                                          ,Number_of_DLIs__c
                                          ,ApprovalStatus__c
                                          ,Deal_ACV__c
                                          ,OP4I_Deal_Synced__c
                                          ,OP4I_OSA_Request_Received__c
                                          ,SBQQ__Uncalculated__c
                                          FROM SBQQ__Quote__c]; 
        
        for(SBQQ__Quote__c quote : quoteList){
            quote.SBQQ__LastCalculatedOn__c = Datetime.now();
            quote.SBQQ__LastSavedOn__c = Datetime.now().addDays(-1);
        }
        update quoteList;
        
        // Act
        Test.startTest();
        database.executeBatch(new QuoteApprovalTriggerBatch());
        Test.stopTest();
        
        // Assert
        system.Assert(quoteList[0].SBQQ__Uncalculated__c == true);
    }
	@isTest static void quoteApprovalTriggerBatchQuoteApprovalStatusError(){
        // Arrange
		List<SBQQ__Quote__c> quoteList = [SELECT Id
                                          ,Number_of_QLIs__c
                                          ,Number_of_DLIs__c
                                          ,ApprovalStatus__c
                                          ,Deal_ACV__c
                                          ,OP4I_Deal_Synced__c
                                          ,OP4I_OSA_Request_Received__c 
                                          FROM SBQQ__Quote__c]; 
        
        for(SBQQ__Quote__c quote : quoteList){
        	Generic_Key_Value_Setting__mdt approvalErrorMaxRetrySetting = Generic_Key_Value_Setting__mdt.getInstance('Approval_Error_Max_Retry');
        	Integer approvalErrorMaxRetry = Integer.valueOf(approvalErrorMaxRetrySetting.Value__c);
            quote.Counter__c = approvalErrorMaxRetry;
        }
        update quoteList; 
        System.assertNotEquals(quoteList.size(), null);
        // Act
        Test.startTest();
        database.executeBatch(new QuoteApprovalTriggerBatch());
        Test.stopTest();
    }
    @isTest static void quoteApprovalTriggerBatchConstructorCoverage(){
		// Arrange
		String jobName = 'Test Job Name';
         
		// Act 
		QuoteApprovalTriggerBatch batch = new QuoteApprovalTriggerBatch(jobName);

		//Assert
		System.assertEquals(jobName, batch.JOB_NAME);
     }
	@isTest static void quoteApprovalTriggerBatchIsCalculatedWithDealAcv(){
        //Arrange
		List<SBQQ__Quote__c> quoteList = [SELECT Id
                                          ,Number_of_QLIs__c
                                          ,Number_of_DLIs__c
                                          ,ApprovalStatus__c
                                          ,Deal_ACV__c
                                          ,OP4I_Deal_Synced__c
                                          ,OP4I_OSA_Request_Received__c 
                                          FROM SBQQ__Quote__c]; 
        
        for(SBQQ__Quote__c quote : quoteList){
            quote.SBQQ__LastCalculatedOn__c = Datetime.now();
            quote.SBQQ__LastSavedOn__c = Datetime.now().addDays(-1);
            quote.Deal_ACV__c = 10000;
        }
        update quoteList;
        
        //Act
        Test.startTest();
        List<CronJobDetail> cronJobDetails = [SELECT Id FROM CronJobDetail WHERE Name=  
            'Quote Approval Trigger Batch' LIMIT 1];
        // Reschedules this job for one minute in the future. 
        Generic_Key_Value_Setting__mdt configurableScheduleMetadata = Generic_Key_Value_Setting__mdt.getInstance('Quote_Approval_Job_Interval_Minute'); 
         
        Integer jobInterval = Integer.valueOf(configurableScheduleMetadata.Value__c); 
        Datetime sysTime = System.now().addMinutes(jobInterval); 
        String cronExpression = '' + sysTime.second() + ' ' + sysTime.minute() + ' ' +
            sysTime.hour() + ' ' + sysTime.day() + ' ' + sysTime.month() + ' ? ' +   sysTime.year(); 
        
        if (cronJobDetails.isEmpty()) {
            System.schedule('Quote Approval Trigger Batch', cronExpression, new QuoteApprovalTriggerBatch());
        }
        
        database.executeBatch(new QuoteApprovalTriggerBatch());
        Test.stopTest();
        
        //Assert
		System.assert(quoteList[0].Deal_ACV__c != null);
    }
	@isTest static void quoteApprovalTriggerBatchException(){
		// Arrange
        List<SBQQ__Quote__c> quoteList = [SELECT Id
                                          ,Number_of_QLIs__c
                                          ,Number_of_DLIs__c
                                          ,ApprovalStatus__c
                                          ,Deal_ACV__c
                                          ,OP4I_Deal_Synced__c
                                          ,OP4I_OSA_Request_Received__c 
                                          FROM SBQQ__Quote__c]; 
        // Act
		Test.startTest();
		QuoteApprovalTriggerBatch.coverException=true;
		database.executeBatch(new QuoteApprovalTriggerBatch());
        Test.stopTest();
        System.assertNotEquals(quoteList.size(), null);
    }
}