force-app/main/default/objects/Account/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</description>
    <inlineHelpText>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</inlineHelpText>
    <label>License Basis - DO NOT USE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <label>OP4I Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>01-Legal NA North</fullName>
            </value>
            <value>
                <fullName>01-Legal NA West</fullName>
            </value>
            <value>
                <fullName>01-PS NA North</fullName>
            </value>
            <value>
                <fullName>02-Legal NA East</fullName>
            </value>
            <value>
                <fullName>02-Legal NA South</fullName>
            </value>
            <value>
                <fullName>02-PS NA South/APAC</fullName>
            </value>
            <value>
                <fullName>03-Legal EMEA</fullName>
            </value>
            <value>
                <fullName>03-PS EMEA</fullName>
            </value>
            <value>
                <fullName>04-Legal APAC</fullName>
            </value>
            <value>
                <fullName>05-Legal Large Accounts</fullName>
            </value>
            <value>
                <fullName>06-Accounting/Consulting</fullName>
            </value>
            <value>
                <fullName>07-Corporate Legal</fullName>
            </value>
            <value>
                <fullName>08-FS NA East New Sales</fullName>
            </value>
            <value>
                <fullName>04 - FS NA New Sales</fullName>
                <isActive>false</isActive>
                <label>08-FS NA New Sales</label>
            </value>
            <value>
                <fullName>05 - FS EMEA New Sales</fullName>
                <isActive>false</isActive>
                <label>09-FS EMEA New Sales</label>
            </value>
            <value>
                <fullName>09-FS NA West New Sales</fullName>
            </value>
            <value>
                <fullName>06 - FS Account Management</fullName>
                <isActive>false</isActive>
                <label>10-FS Account Management</label>
            </value>
            <value>
                <fullName>10-FS APAC New Sales</fullName>
            </value>
            <value>
                <fullName>11-FS EMEA New Sales</fullName>
            </value>
            <value>
                <fullName>12-FS AM Core</fullName>
            </value>
            <value>
                <fullName>13-FS AM Enterprise</fullName>
            </value>
            <value>
                <fullName>14-FS AM EMEA</fullName>
            </value>
            <value>
                <fullName>15-FS AM Portfolio</fullName>
            </value>
            <value>
                <fullName>16-FS AM APAC</fullName>
            </value>
            <value>
                <fullName>17-Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/Approvers_Matrix__c.object-meta.xml
<CustomObject>
    <label>Approver Matrix</label>
    <nameField>
        <label>Approvers Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approvers_Matrix__c/fields/Approver_Role__c.field-meta.xml
<CustomField>
    <fullName>Approver_Role__c</fullName>
    <label>Approver Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/fields/Approver_User__c.field-meta.xml
<CustomField>
    <fullName>Approver_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/fields/Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>Sales_Segment__c</fullName>
    <label>Sales Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contract/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <formula>SBQQ__Quote__r.OP4I_Sales_Segment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Sales Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Signer__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Signer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contract Signer)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>This field will be used to send data to Integration system;BIZ-51285</description>
    <formula>SBQQ__PrimaryQuote__r.OP4I_Sales_Segment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Sales Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Contract_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Requested_Contract_Expiration__c</fullName>
    <label>Requested Contract Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <inlineHelpText>&apos;First invoice period (number of months)</inlineHelpText>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>CR #43996</description>
    <label>Meter Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fee Earners</fullName>
            </value>
            <value>
                <fullName>Lawyers</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Named Users</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
                <isActive>false</isActive>
                <label>Attorneys</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>Holds the Sales Segment Values from OP4I Deal</description>
    <label>OP4I Sales Segment</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__MasterContract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__MasterContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master contract with which subscription products in this quote are to be co-terminated.</description>
    <inlineHelpText>Associated OSA for this Opportunity.</inlineHelpText>
    <label>Master Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.SBQQ__Evergreen__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Co-Terminated Quotes</relationshipLabel>
    <relationshipName>CoTerminatedQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Initial license term (in months). By default, this will be populated to 12 months. It can be overwritten by Contract Ops.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreateContractFromQuoteControllerTest.cls
@isTest
public class CreateContractFromQuoteControllerTest { 
    @testSetup
    static void setupTestData(){
        Account acc = (Account) SmartFactory.createSObject('Account');
		acc.Industry = 'Test Industry';
		acc.BillingCountry = 'Test';
        acc.OP4I_Sales_Segment__c = '03-Legal EMEA';
        insert acc;

		Contact con = (Contact) SmartFactory.createSObject('Contact');
		con.AccountId = acc.Id;
		insert con;

		Opportunity opp = (Opportunity) SmartFactory.createSObject('Opportunity');
		opp.AccountId = acc.Id;
		opp.Contract_Signer__c = con.Id;
		opp.Requested_Contract_Expiration__c = Date.today();
		opp.Initial_Software_Term_Length_Months__c = 12;
		insert opp;
        
       /* Approvers_Matrix__c AppMatrix1 = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix1.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix1.Approver_Role__c ='Segment Lead';
        AppMatrix1.Approver_User__c =userinfo.getUserId();
        insert AppMatrix1; */
     
		SBQQ__Quote__c newQuote = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
		newQuote.SBQQ__Opportunity2__c = opp.Id;
		newQuote.SBQQ__Account__c = acc.Id;
        newQuote.SBQQ__SubscriptionTerm__c =36;
        newQuote.First_Segment_Months__c = 12;
		newQuote.License_Basis__c = 'Lawyers';
        insert newQuote;
    }
    @isTest 
    static void TestCreateContractFromQuote_NewContract() {
        // Arrange
        List<SBQQ__Quote__c> quoteList = [Select id
                                          ,Name 
                                          From SBQQ__Quote__c];
        
        PageReference pageRef = Page.CreateContractFromQuote; 
		pageRef.getParameters().put('id', quoteList[0].Id);
		Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc;
     	CreateContractFromQuoteController createContract = New CreateContractFromQuoteController(sc); 
        
        // Act
		Test.startTest();
        createContract.createContractOnQuote();
        createContract.goBack();
        Test.stopTest(); 
        
		// Assert
        system.Assert(createContract.isError == false);
     }

    @isTest 
    static void TestCreateContractFromQuote_ExstingContract() {
        // Arrange
        List<SBQQ__Quote__c> quoteList = [Select id
                                          ,Name
                                          ,SBQQ__Account__c
                                          ,SBQQ__Opportunity2__c
                                          ,SBQQ__MasterContract__c
                                          From SBQQ__Quote__c];
        
        if (quoteList[0].SBQQ__MasterContract__c == null){
            Contract contract = new Contract(SBQQ__Quote__c = quoteList[0].Id, AccountId = quoteList[0].SBQQ__Account__c, SBQQ__Opportunity__c = quoteList[0].SBQQ__Opportunity2__c);
            insert contract;
            quoteList[0].SBQQ__MasterContract__c = contract.Id;
            update quoteList[0];
        }
        
        PageReference pageRef = Page.CreateContractFromQuote; 
        pageRef.getParameters().put('id', quoteList[0].Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc;
        CreateContractFromQuoteController createContract = New CreateContractFromQuoteController(sc); 
        
        // Act
        Test.startTest();
        createContract.createContractOnQuote();
        Test.stopTest(); 
        
		// Assert
        system.Assert(createContract.isError == false);        
    }
	@isTest 
    static void TestCreateContractFromQuoteException() {
        // Arrange
        PageReference pageRef = Page.CreateContractFromQuote; 
		pageRef.getParameters().put('id', null);
		Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc;
     	CreateContractFromQuoteController createContract = New CreateContractFromQuoteController(sc);
        
        //Act
        Test.startTest();
        createContract.createContractOnQuote();
        Test.stopTest(); 

		// Assert
        system.Assert(createContract.isError == true);        
    }
}