force-app/main/default/objects/Account/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</description>
    <inlineHelpText>License Basis&quot; rollup on Account that gathers text values of License Basis when Status = Own it, License Basis = CG Analyze, CG Flow, CG Protect</inlineHelpText>
    <label>License Basis - DO NOT USE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <label>OP4I Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>01-Legal NA North</fullName>
            </value>
            <value>
                <fullName>01-Legal NA West</fullName>
            </value>
            <value>
                <fullName>01-PS NA North</fullName>
            </value>
            <value>
                <fullName>02-Legal NA East</fullName>
            </value>
            <value>
                <fullName>02-Legal NA South</fullName>
            </value>
            <value>
                <fullName>02-PS NA South/APAC</fullName>
            </value>
            <value>
                <fullName>03-Legal EMEA</fullName>
            </value>
            <value>
                <fullName>03-PS EMEA</fullName>
            </value>
            <value>
                <fullName>04-Legal APAC</fullName>
            </value>
            <value>
                <fullName>05-Legal Large Accounts</fullName>
            </value>
            <value>
                <fullName>06-Accounting/Consulting</fullName>
            </value>
            <value>
                <fullName>07-Corporate Legal</fullName>
            </value>
            <value>
                <fullName>08-FS NA East New Sales</fullName>
            </value>
            <value>
                <fullName>04 - FS NA New Sales</fullName>
                <isActive>false</isActive>
                <label>08-FS NA New Sales</label>
            </value>
            <value>
                <fullName>05 - FS EMEA New Sales</fullName>
                <isActive>false</isActive>
                <label>09-FS EMEA New Sales</label>
            </value>
            <value>
                <fullName>09-FS NA West New Sales</fullName>
            </value>
            <value>
                <fullName>06 - FS Account Management</fullName>
                <isActive>false</isActive>
                <label>10-FS Account Management</label>
            </value>
            <value>
                <fullName>10-FS APAC New Sales</fullName>
            </value>
            <value>
                <fullName>11-FS EMEA New Sales</fullName>
            </value>
            <value>
                <fullName>12-FS AM Core</fullName>
            </value>
            <value>
                <fullName>13-FS AM Enterprise</fullName>
            </value>
            <value>
                <fullName>14-FS AM EMEA</fullName>
            </value>
            <value>
                <fullName>15-FS AM Portfolio</fullName>
            </value>
            <value>
                <fullName>16-FS AM APAC</fullName>
            </value>
            <value>
                <fullName>17-Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/Approvers_Matrix__c.object-meta.xml
<CustomObject>
    <label>Approver Matrix</label>
    <nameField>
        <label>Approvers Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approvers_Matrix__c/fields/Approver_Role__c.field-meta.xml
<CustomField>
    <fullName>Approver_Role__c</fullName>
    <label>Approver Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/fields/Approver_User__c.field-meta.xml
<CustomField>
    <fullName>Approver_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/fields/Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>Sales_Segment__c</fullName>
    <label>Sales Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contract/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <formula>SBQQ__Quote__r.OP4I_Sales_Segment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Sales Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Associated_Contract_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contract_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the Contract record for this Opportunity?</description>
    <inlineHelpText>What is the Contract record for this Opportunity?</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Correct)</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Signer__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Signer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contract Signer)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>This field will be used to send data to Integration system;BIZ-51285</description>
    <formula>SBQQ__PrimaryQuote__r.OP4I_Sales_Segment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Sales Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Requested_Contract_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Requested_Contract_Expiration__c</fullName>
    <label>Requested Contract Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Submission</fullName>
                <default>true</default>
                <label>Pending Submission</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/COO__c.field-meta.xml
<CustomField>
    <fullName>COO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>COO</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <inlineHelpText>&apos;First invoice period (number of months)</inlineHelpText>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Industry_President__c.field-meta.xml
<CustomField>
    <fullName>Industry_President__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry President</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Industry_Sales_Lead__c.field-meta.xml
<CustomField>
    <fullName>Industry_Sales_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Sales Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/License_Basis__c.field-meta.xml
<CustomField>
    <fullName>License_Basis__c</fullName>
    <description>CR #43996</description>
    <label>Meter Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fee Earners</fullName>
            </value>
            <value>
                <fullName>Lawyers</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Named Users</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Attorneys</fullName>
                <isActive>false</isActive>
                <label>Attorneys</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>Holds the Sales Segment Values from OP4I Deal</description>
    <label>OP4I Sales Segment</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Initial license term (in months). By default, this will be populated to 12 months. It can be overwritten by Contract Ops.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Segment_Lead__c.field-meta.xml
<CustomField>
    <fullName>Segment_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Services_Segment_Lead__c.field-meta.xml
<CustomField>
    <fullName>Services_Segment_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Services Segment Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SVP_Sales__c.field-meta.xml
<CustomField>
    <fullName>SVP_Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP Sales</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SVP_Services__c.field-meta.xml
<CustomField>
    <fullName>SVP_Services__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP Services</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>To display OP4I Sales Segment of User. Created as part of BIZ-50210.</description>
    <label>OP4I Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Op4I_Sales_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Op4I_Sales_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01-Legal NA West</fullName>
    </customValue>
    <customValue>
        <fullName>02-Legal NA East</fullName>
    </customValue>
    <customValue>
        <fullName>03-Legal EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>04-Legal APAC</fullName>
    </customValue>
    <customValue>
        <fullName>05-Legal Connected Firms</fullName>
    </customValue>
    <customValue>
        <fullName>06-Legal Mid-Market</fullName>
    </customValue>
    <customValue>
        <fullName>07-Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>08-Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>09-Corporates New Sales</fullName>
    </customValue>
    <customValue>
        <fullName>10-Corporates AM</fullName>
    </customValue>
    <customValue>
        <fullName>11-FS New Sales NA IB/RE</fullName>
    </customValue>
    <customValue>
        <fullName>12-FS New Sales NA PCM East</fullName>
    </customValue>
    <customValue>
        <fullName>13-FS New Sales NA PCM West</fullName>
    </customValue>
    <customValue>
        <fullName>14-FS New Sales EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>15-FS New Sales APAC</fullName>
    </customValue>
    <customValue>
        <fullName>16-FS AM NA IB/RE</fullName>
    </customValue>
    <customValue>
        <fullName>17-FS AM NA PCM East</fullName>
    </customValue>
    <customValue>
        <fullName>18-FS AM NA PCM Central</fullName>
    </customValue>
    <customValue>
        <fullName>19-FS AM NA PCM West</fullName>
    </customValue>
    <customValue>
        <fullName>20-FS AM EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>21-FS AM APAC</fullName>
    </customValue>
    <customValue>
        <fullName>22-FS Strategics NA</fullName>
    </customValue>
    <customValue>
        <fullName>24-Corporates Partners AM</fullName>
    </customValue>
    <customValue>
        <fullName>23-Corporates EMEA AM</fullName>
    </customValue>
    <customValue>
        <fullName>01-PS NA North</fullName>
    </customValue>
    <customValue>
        <fullName>02-PS NA South/APAC</fullName>
    </customValue>
    <customValue>
        <fullName>03-PS EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>08-FS NA East New Sales</fullName>
    </customValue>
    <customValue>
        <fullName>09-FS NA West New Sales</fullName>
    </customValue>
    <customValue>
        <fullName>10-FS APAC New Sales</fullName>
    </customValue>
    <description>Op4I Sales Segment</description>
    <masterLabel>Op4I Sales Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteTriggerHandlerTest.cls
@isTest
public class QuoteTriggerHandlerTest {
    @testSetup
    static void setup(){
        Account account = IntappTestObjectfactory.createAccount(true);
        
        Contact con = (Contact) SmartFactory.createSObject('Contact');
        con.AccountId = account.Id; 
        insert con;
        
        Contract ctr = (Contract) SmartFactory.createSObject('Contract');
        ctr.AccountId = account.Id;
        insert ctr;
        
        Opportunity opportunity = (Opportunity) SmartFactory.createSObject('Opportunity');
        opportunity.AccountId = account.Id;
        opportunity.Associated_Contract_OSA__c = ctr.Id;
        opportunity.Contract_Signer__c = con.Id;
        opportunity.Requested_Contract_Expiration__c = Date.today();
        opportunity.Initial_Software_Term_Length_Months__c = 12;
        insert opportunity;
        
        Profile profile = [select id from profile where name='System Administrator' LIMIT 1]; 
        User user = createuser('Testing', '', 'test@testintapp.com', profile.Id, 'intapp_1', 'UTF-8', 'en_US', 'en_US', 'America/Los_Angeles', 'stdtusr@testintapp.com', '', true);
        
        Approvers_Matrix__c appMatrix1 = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix1.Sales_Segment__c = '03-Legal EMEA';
        AppMatrix1.Approver_Role__c = 'Segment Lead';
        AppMatrix1.Approver_User__c = user.Id;
        insert AppMatrix1;
        
        SBQQ__Quote__c newQuote = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
        newQuote.OP4I_Sales_Segment__c = '03-Legal EMEA';
        newQuote.SBQQ__Opportunity2__c = opportunity.Id;
        newQuote.SBQQ__Account__c = account.Id;
        newQuote.SBQQ__SubscriptionTerm__c = 36;
        newQuote.First_Segment_Months__c = 12;
        newQuote.License_Basis__c = 'Lawyers';
        newQuote.SBQQ__StartDate__c = system.today();
        insert newQuote;
    }
    
    private static List<SBQQ__Quote__c> getQuoteList(){
        return [SELECT Id
                , SBQQ__Account__c
                , Segment_Lead__c
                , Industry_Sales_Lead__c
                , Services_Segment_Lead__c
                , SVP_Sales__c
                , SVP_Services__c
                , Industry_President__c
                , COO__c
                , SBQQ__Opportunity2__c
                , SBQQ__SubscriptionTerm__c
                , First_Segment_Months__c
                , License_Basis__c
                , OP4I_Sales_Segment__c
                , ApprovalStatus__c,SBQQ__StartDate__c
                FROM SBQQ__Quote__c LIMIT 1];
    }
    
    private static User getUser(){
        return [SELECT Id
                FROM User
                WHERE Email = 'test@testintapp.com'
                LIMIT 1];
    }
    
    private static User createUser(String lastName, string firstName, string email, String profileId, 
                                   string alias, String emailEncodingKey, string languageLocaleKey,
                                   string localeSidKey, string timeZoneSidKey, string userName,
                                   string communityNickname, Boolean create){
                                       User user = new User();
                                       user.LastName = lastName;
                                       user.FirstName = firstName;
                                       user.Email = email;
                                       user.EmailEncodingKey = emailEncodingKey;
                                       user.LanguageLocaleKey = languageLocaleKey;
                                       user.LocaleSidKey = localeSidKey;
                                       user.TimeZoneSidKey = timeZoneSidKey;
                                       user.ProfileId = profileId;
                                       user.Alias = alias;
                                       user.UserName = userName;
                                       user.CommunityNickname = communityNickname + '-' + (Math.random() * 10000);
                                       if(create)
                                       {
                                           insert user;
                                       }
                                       return user;
                                   }
    
    @isTest
    static void processRecordsBeforeInsertWithValidSalesSegment(){
        // Arrange
        List<SBQQ__Quote__c> quotelist = getQuoteList();
        
        for(SBQQ__Quote__c quote : quoteList){
            quote.Segment_Lead__c = null;
        }
        
        User user = getUser();
        
        System.assertNotEquals(quoteList.size(), null);
    }
    
    @isTest
    static void processRecordsBeforeInsertWithInvalidSalesSegment(){
        // Arrange
        List<SBQQ__Quote__c> quotelist = getQuoteList();
        
        for(SBQQ__Quote__c quote : quoteList){
            quote.Segment_Lead__c = null;
            quote.OP4I_Sales_Segment__c = '03-Legal_Not Matching';    
        }
        
        User user = getUser();
        System.assertNotEquals(quoteList.size(), null);
    }
    
    @isTest static void processRecordsBeforeUpdateWithValidSalesSegment(){
        // Arrange
        List<SBQQ__Quote__c> oldQuote = getQuoteList();
        oldQuote[0].ApprovalStatus__c = 'Error';
        oldQuote[0].OP4I_Sales_Segment__c = '04-Legal APAC';
        
        Map<Id, SBQQ__Quote__c> quotelistMapOld = New Map<Id, SBQQ__Quote__c> (oldQuote);
        
        Generic_Key_Value_Setting__mdt approvalErrorMaxRetrySetting = Generic_Key_Value_Setting__mdt.getInstance('Approval_Error_Max_Retry');
        Integer approvalErrorMaxRetry = Integer.valueOf(approvalErrorMaxRetrySetting.Value__c);
        
        List<SBQQ__Quote__c> newQuote = getQuoteList();
        newQuote[0].ApprovalStatus__c = 'Pending'; 
        newQuote[0].Counter__c = approvalErrorMaxRetry;
        newQuote[0].OP4I_Sales_Segment__c = '03-Legal EMEA';
        
        Map<Id, SBQQ__Quote__c> quotelistMapNew = New Map<Id, SBQQ__Quote__c> (newQuote);
        
        User user = getUser();
        
        System.assertNotEquals(newQuote.size(), null);
    }
    
    @isTest static void processRecordsBeforeUpdateWithInvalidSalesSegment(){
        // Arrange
        List<SBQQ__Quote__c> oldQuote = getQuoteList();
        oldQuote[0].ApprovalStatus__c = 'Error';
        oldQuote[0].OP4I_Sales_Segment__c = '04-Legal APAC';
        
        Map<Id, SBQQ__Quote__c> quotelistMapOld = New Map<Id, SBQQ__Quote__c> (oldQuote);
        
        Generic_Key_Value_Setting__mdt approvalErrorMaxRetrySetting = Generic_Key_Value_Setting__mdt.getInstance('Approval_Error_Max_Retry');
        Integer approvalErrorMaxRetry = Integer.valueOf(approvalErrorMaxRetrySetting.Value__c);
        
        List<SBQQ__Quote__c> newQuote = getQuoteList();
        newQuote[0].ApprovalStatus__c = 'Pending'; 
        newQuote[0].Counter__c = approvalErrorMaxRetry;
        newQuote[0].Segment_Lead__c = null;
        newQuote[0].OP4I_Sales_Segment__c = '03-Legal_Not EMEA';
        
        Map<Id, SBQQ__Quote__c> quotelistMapNew = New Map<Id, SBQQ__Quote__c> (newQuote);
        
        User user = getUser();
        System.Assert(newQuote[0].Segment_Lead__c == null); 
    }
}