force-app/main/default/objects/Account/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <label>OP4I Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>01-Legal NA North</fullName>
            </value>
            <value>
                <fullName>01-Legal NA West</fullName>
            </value>
            <value>
                <fullName>01-PS NA North</fullName>
            </value>
            <value>
                <fullName>02-Legal NA East</fullName>
            </value>
            <value>
                <fullName>02-Legal NA South</fullName>
            </value>
            <value>
                <fullName>02-PS NA South/APAC</fullName>
            </value>
            <value>
                <fullName>03-Legal EMEA</fullName>
            </value>
            <value>
                <fullName>03-PS EMEA</fullName>
            </value>
            <value>
                <fullName>04-Legal APAC</fullName>
            </value>
            <value>
                <fullName>05-Legal Large Accounts</fullName>
            </value>
            <value>
                <fullName>06-Accounting/Consulting</fullName>
            </value>
            <value>
                <fullName>07-Corporate Legal</fullName>
            </value>
            <value>
                <fullName>08-FS NA East New Sales</fullName>
            </value>
            <value>
                <fullName>04 - FS NA New Sales</fullName>
                <isActive>false</isActive>
                <label>08-FS NA New Sales</label>
            </value>
            <value>
                <fullName>05 - FS EMEA New Sales</fullName>
                <isActive>false</isActive>
                <label>09-FS EMEA New Sales</label>
            </value>
            <value>
                <fullName>09-FS NA West New Sales</fullName>
            </value>
            <value>
                <fullName>06 - FS Account Management</fullName>
                <isActive>false</isActive>
                <label>10-FS Account Management</label>
            </value>
            <value>
                <fullName>10-FS APAC New Sales</fullName>
            </value>
            <value>
                <fullName>11-FS EMEA New Sales</fullName>
            </value>
            <value>
                <fullName>12-FS AM Core</fullName>
            </value>
            <value>
                <fullName>13-FS AM Enterprise</fullName>
            </value>
            <value>
                <fullName>14-FS AM EMEA</fullName>
            </value>
            <value>
                <fullName>15-FS AM Portfolio</fullName>
            </value>
            <value>
                <fullName>16-FS AM APAC</fullName>
            </value>
            <value>
                <fullName>17-Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentTriggerHandlerTest.cls
@isTest
public class PaymentTriggerHandlerTest {
    @testSetup
    static void setup(){
        Account acc = IntappTestObjectFactory.createAccount(true);
        
        blng__Payment__c newPayment = IntappTestObjectFactory.createPayment();
        newPayment.blng__Account__c = acc.Id;
        newPayment.blng__Amount__c = 123;
        newPayment.CurrencyIsoCode = 'USD';
        insert newPayment;
    }
    
    @isTest static void setup1(){
        List<Account> acclist = [Select id,Industry,BillingCountry,OP4I_Sales_Segment__c From Account where OP4I_Sales_Segment__c != ''];
        List<blng__Payment__c> paylist =[Select id,name,blng__Account__c,blng__Amount__c,CurrencyIsoCode From blng__Payment__c];
        update paylist;
        
        System.assertNotEquals(paylist.size(), null);
    }
}