force-app/main/default/objects/Account/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <label>OP4I Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>01-Legal NA North</fullName>
            </value>
            <value>
                <fullName>01-Legal NA West</fullName>
            </value>
            <value>
                <fullName>01-PS NA North</fullName>
            </value>
            <value>
                <fullName>02-Legal NA East</fullName>
            </value>
            <value>
                <fullName>02-Legal NA South</fullName>
            </value>
            <value>
                <fullName>02-PS NA South/APAC</fullName>
            </value>
            <value>
                <fullName>03-Legal EMEA</fullName>
            </value>
            <value>
                <fullName>03-PS EMEA</fullName>
            </value>
            <value>
                <fullName>04-Legal APAC</fullName>
            </value>
            <value>
                <fullName>05-Legal Large Accounts</fullName>
            </value>
            <value>
                <fullName>06-Accounting/Consulting</fullName>
            </value>
            <value>
                <fullName>07-Corporate Legal</fullName>
            </value>
            <value>
                <fullName>08-FS NA East New Sales</fullName>
            </value>
            <value>
                <fullName>04 - FS NA New Sales</fullName>
                <isActive>false</isActive>
                <label>08-FS NA New Sales</label>
            </value>
            <value>
                <fullName>05 - FS EMEA New Sales</fullName>
                <isActive>false</isActive>
                <label>09-FS EMEA New Sales</label>
            </value>
            <value>
                <fullName>09-FS NA West New Sales</fullName>
            </value>
            <value>
                <fullName>06 - FS Account Management</fullName>
                <isActive>false</isActive>
                <label>10-FS Account Management</label>
            </value>
            <value>
                <fullName>10-FS APAC New Sales</fullName>
            </value>
            <value>
                <fullName>11-FS EMEA New Sales</fullName>
            </value>
            <value>
                <fullName>12-FS AM Core</fullName>
            </value>
            <value>
                <fullName>13-FS AM Enterprise</fullName>
            </value>
            <value>
                <fullName>14-FS AM EMEA</fullName>
            </value>
            <value>
                <fullName>15-FS AM Portfolio</fullName>
            </value>
            <value>
                <fullName>16-FS AM APAC</fullName>
            </value>
            <value>
                <fullName>17-Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/Approvers_Matrix__c.object-meta.xml
<CustomObject>
    <label>Approver Matrix</label>
    <nameField>
        <label>Approvers Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approvers_Matrix__c/fields/Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>Sales_Segment__c</fullName>
    <label>Sales Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/blng__CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/blng__CreditNote__c/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>created for SF-NS integration for BIZ-47358</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/blng__Payment__c/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>created for SF-NS integration for BIZ-47358</description>
    <label>Subsidiary</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <formula>SBQQ__Quote__r.OP4I_Sales_Segment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Sales Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/OSA_Type__c.field-meta.xml
<CustomField>
    <fullName>OSA_Type__c</fullName>
    <description>We use OSA documents for both master contracts, and for addenda or revisions to those contracts. This field tells you what type this OSA is.</description>
    <inlineHelpText>We use OSA documents for both master contracts, and for addenda or revisions to those contracts. This field tells you what type this OSA is.</inlineHelpText>
    <label>OSA Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Master Contract</fullName>
                <default>true</default>
                <label>Master Contract</label>
            </value>
            <value>
                <fullName>Addendum or Revision</fullName>
            </value>
            <value>
                <fullName>Services Change Order</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Services Change Order (Internal)</fullName>
            </value>
            <value>
                <fullName>Legacy Rekoop Paper</fullName>
            </value>
            <value>
                <fullName>OnePlace Legacy Agreement</fullName>
            </value>
            <value>
                <fullName>Repstor Legacy Agreement</fullName>
            </value>
            <value>
                <fullName>DealCloud Legacy</fullName>
            </value>
            <value>
                <fullName>Billstream Legacy Agreement</fullName>
            </value>
            <value>
                <fullName>Legacy Polar Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>This field denotes the Billing Subsidiary for this contract for the Account to Customer sync in NetSuite,</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Services Only</fullName>
            </value>
            <value>
                <fullName>Software Only</fullName>
            </value>
            <value>
                <fullName>Software Co-Term</fullName>
            </value>
            <value>
                <fullName>Services Change Order</fullName>
            </value>
            <value>
                <fullName>Services Change Order (Internal)</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Repstor G-Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>This field will be used to send data to Integration system;BIZ-51285</description>
    <formula>SBQQ__PrimaryQuote__r.OP4I_Sales_Segment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OP4I Sales Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>Holds the Sales Segment Values from OP4I Deal</description>
    <label>OP4I Sales Segment</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>To display OP4I Sales Segment of User. Created as part of BIZ-50210.</description>
    <label>OP4I Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Op4I_Sales_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Op4I_Sales_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01-Legal NA West</fullName>
    </customValue>
    <customValue>
        <fullName>02-Legal NA East</fullName>
    </customValue>
    <customValue>
        <fullName>03-Legal EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>04-Legal APAC</fullName>
    </customValue>
    <customValue>
        <fullName>05-Legal Connected Firms</fullName>
    </customValue>
    <customValue>
        <fullName>06-Legal Mid-Market</fullName>
    </customValue>
    <customValue>
        <fullName>07-Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>08-Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>09-Corporates New Sales</fullName>
    </customValue>
    <customValue>
        <fullName>10-Corporates AM</fullName>
    </customValue>
    <customValue>
        <fullName>11-FS New Sales NA IB/RE</fullName>
    </customValue>
    <customValue>
        <fullName>12-FS New Sales NA PCM East</fullName>
    </customValue>
    <customValue>
        <fullName>13-FS New Sales NA PCM West</fullName>
    </customValue>
    <customValue>
        <fullName>14-FS New Sales EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>15-FS New Sales APAC</fullName>
    </customValue>
    <customValue>
        <fullName>16-FS AM NA IB/RE</fullName>
    </customValue>
    <customValue>
        <fullName>17-FS AM NA PCM East</fullName>
    </customValue>
    <customValue>
        <fullName>18-FS AM NA PCM Central</fullName>
    </customValue>
    <customValue>
        <fullName>19-FS AM NA PCM West</fullName>
    </customValue>
    <customValue>
        <fullName>20-FS AM EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>21-FS AM APAC</fullName>
    </customValue>
    <customValue>
        <fullName>22-FS Strategics NA</fullName>
    </customValue>
    <customValue>
        <fullName>24-Corporates Partners AM</fullName>
    </customValue>
    <customValue>
        <fullName>23-Corporates EMEA AM</fullName>
    </customValue>
    <customValue>
        <fullName>01-PS NA North</fullName>
    </customValue>
    <customValue>
        <fullName>02-PS NA South/APAC</fullName>
    </customValue>
    <customValue>
        <fullName>03-PS EMEA</fullName>
    </customValue>
    <customValue>
        <fullName>08-FS NA East New Sales</fullName>
    </customValue>
    <customValue>
        <fullName>09-FS NA West New Sales</fullName>
    </customValue>
    <customValue>
        <fullName>10-FS APAC New Sales</fullName>
    </customValue>
    <description>Op4I Sales Segment</description>
    <masterLabel>Op4I Sales Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Subsidiary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01:200 Integration Appliance (US)</fullName>
        <default>true</default>
        <label>01:200 Integration Appliance (US)</label>
    </customValue>
    <customValue>
        <fullName>05:400 TFG - US</fullName>
    </customValue>
    <customValue>
        <fullName>06:700 Rekoop Limited (UK)</fullName>
    </customValue>
    <customValue>
        <fullName>09:750 Rekoop Pty Limited (AUS)</fullName>
    </customValue>
    <customValue>
        <fullName>23:Gwabbit</fullName>
    </customValue>
    <customValue>
        <fullName>35:Repstor Limited</fullName>
    </customValue>
    <customValue>
        <fullName>37:Repstor, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>18:DealCloud, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>28:OnePlace Pte Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>42:Paragon Data Labs, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>22:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>22:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>Polar Placeholder</fullName>
        <isActive>false</isActive>
        <label>Polar Placeholder</label>
    </customValue>
    <description>Will be used in Account,Contract, Quote &amp; Order created as part of BIZ-47396 story</description>
    <masterLabel>Subsidiary</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IntappTestObjectFactory.cls
public with sharing class IntappTestObjectFactory {
    
    
    public static User createUser(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User user = (User) SmartFactory.createSObject('User');
        user.Alias = 'standt'; 
        user.Email='standarduser@intapp.com'; 
        user.EmailEncodingKey='UTF-8'; 
        user.LastName='Testing';
        user.LanguageLocaleKey='en_US'; 
        user.LocaleSidKey='en_US'; 
        user.ProfileId = p.Id; 
        user.TimeZoneSidKey='America/Los_Angeles'; 
        user.UserName='standarduser@intapp.com';
        return user;
    }
    
    public static Subscription__c createSubscription(Boolean isInsert)
    {
        Subscription__c subscription = (Subscription__c) SmartFactory.createSObject('Subscription__c');
        if (isInsert) {
            insert subscription;
        }
        return subscription;
    }
    
    public static Account createAccount(Boolean isInsert)
    {
        Account account = (Account) SmartFactory.createSObject('Account');
        account.Name = 'Test Account';
        account.BillingCountry = 'India';
        account.BillingState = 'Punjab';
        account.Industry = 'Chemicals';
        account.CurrencyIsoCode = 'USD';
        account.SBQQ__RenewalModel__c = 'Contract Based';
        account.OP4I_Sales_Segment__c = '03-Legal EMEA';
        if (isInsert) {
            insert account;
        }
        return account;
    }
    
    public static Account createAccount()
    {
        return createAccount(false);
    }
    
    public static Invoice__c createInvoice(Boolean isInsert)
    {
        Invoice__c i = (Invoice__c) SmartFactory.createSObject('Invoice__c');
        if (isInsert)
        {
            insert i;
        }
        return i;
    }
    
    public static Contract createContract(Id accountID)
    {
        Contract c = (Contract) SmartFactory.createSObject('Contract');
        c.AccountId = accountID;
        c.Name='test contract';
        c.Status='Specialist Approval Needed';
        c.StartDate=Date.TODAY();
        c.EndDate=Date.Today().addDays(5);
        c.Type__c='Standard';
        c.OSA_Type__c='Other';
        c.Subsidiary__c = '01:200 Integration Appliance (US)';
        return c;
    }
    
    public static Contact createContact()
    {
        return createContact(false);
    }
    
    public static Contact createContact(Boolean isInsert)
    {
        Contact contact = (Contact) SmartFactory.createSObject('Contact');
        contact.FirstName = 'Test First';
        contact.LastName = 'Test Last';
        contact.CurrencyIsoCode = 'USD';
        if (isInsert) {
            insert contact;
        }
        return contact;
    }
    
    public static Opportunity createOpportunity()
    {
        Opportunity opp = (Opportunity) SmartFactory.createSObject('Opportunity');
        opp.Name = 'Test Opportunity';
        opp.StageName='Evaluation of Options';
        opp.CloseDate=System.today();
        opp.Requested_Contract_Expiration__c = Date.today();
        opp.Initial_Software_Term_Length_Months__c = 12;        
        opp.Type = 'Accounting Adjustment';
        return opp;
    }
    
    public static SBQQ__Quote__c createSBQQQuote()
    {
        SBQQ__Quote__c sbqqQuote = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
        return sbqqQuote;
    }
    
    public static Approvers_Matrix__c createApproversMatrix(){
        Approvers_Matrix__c approversMatrix = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        approversMatrix.Sales_Segment__c = '03-Legal EMEA';
        approversMatrix.Approver_Role__c = 'Segment Lead';
        return approversMatrix;
    }
    
    public static Item_Master_Product__c createItemMaster(Boolean isInsert) {
        Item_Master_Product__c item   = new Item_Master_Product__c();
        item.Item_Name__c  = 'test name';
        item.CurrencyIsoCode = 'USD';
        
        if(isInsert) {
            insert item;
        }
        return item;
    }
    
    public static ACV_Allocation__c createAcvAllocation(Id itemMaster , Boolean isInsert) {
        ACV_Allocation__c acvLocation   = new ACV_Allocation__c();
        acvLocation.Product_Line__c = 'Wall Builder';
        acvLocation.Item_Master_Product__c = itemMaster;
        acvLocation.CurrencyIsoCode = 'USD';
        
        if(isInsert) {
            insert acvLocation;
        }
        return acvLocation;
    }
    
    public static Product2 createProduct(Boolean isInsert) {
        Product2 prod = new Product2();
        prod.Name = 'Test Prd1';
        prod.Family = 'Major';
        prod.IsActive = true;
        prod.ProductCode = '1234';
        if(isInsert) {
            insert prod;
        }
        return prod;
    }
    
    public static OpportunityLineItem createOpportunityLineItem(Id oppId, Id pbEntryId, double unitPrice, Boolean isInsert) {
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.opportunityid = oppId; 
        oli.pricebookentryid = pbEntryId; 
        oli.unitprice = unitPrice;
        oli.quantity  = 2;
        if(isInsert) {
            insert oli;
        }
        return oli;
    }
    
    public static Campaign createCampaign(Boolean isInsert) {
        Campaign cmp = new Campaign();
        cmp.Name = 'Test campaign';
        
        if(isInsert) {        
            insert cmp;   
        }
        return cmp; 
    }
    public static blng__Payment__c createPayment()
    {
        blng__Payment__c payment = (blng__Payment__c) SmartFactory.createSObject('blng__Payment__c');
        return payment;
    }
        public static blng__CreditNote__c createCreditnote()
    {
        blng__CreditNote__c creditnote = (blng__CreditNote__c) SmartFactory.createSObject('blng__CreditNote__c');
        return creditnote;
    }
}