force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Governance</fullName>
                <default>true</default>
                <label>Pending Governance</label>
            </value>
            <value>
                <fullName>Verification Approved</fullName>
            </value>
            <value>
                <fullName>Verification Declined</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Outstanding_Balance__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance__c</fullName>
    <label>Outstanding Balance(Expiring on Aug 2)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Sales_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Type__c</fullName>
    <label>Sales Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>New license sale</fullName>
            </value>
            <value>
                <fullName>Services Agreement</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>DTE Usage</fullName>
            </value>
            <value>
                <fullName>RollCall Usage</fullName>
            </value>
            <value>
                <fullName>Services Agreement–T&amp;M</fullName>
            </value>
            <value>
                <fullName>Services Agreement-Upgrade</fullName>
            </value>
            <value>
                <fullName>Comprehensive Mobile</fullName>
            </value>
            <value>
                <fullName>Evaulation Program</fullName>
            </value>
            <value>
                <fullName>DTE Axiom Upgrade</fullName>
            </value>
            <value>
                <fullName>Usage</fullName>
            </value>
            <value>
                <fullName>Additional DTE Licenses</fullName>
            </value>
            <value>
                <fullName>Renewal-Exception</fullName>
            </value>
            <value>
                <fullName>New Hardware</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status (Expiring on Aug 2)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credited in Full</fullName>
            </value>
            <value>
                <fullName>Partially Credited</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Paid In Full</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoicePastDueNotificationWebService.cls
/********************************************************************************     
 *  Name             :  InvoicePastDueNotificationWebService
 *  Author           :  Intapp
 *  Description      :  Utility class to send out invoice past due notifications. Executed via IB Web Service Action
 *  Change history   :
 *  Date            Author                      Description
 *  06/01/15        Alan Westley                Moved functionality to web service class for IB call 
 ********************************************************************************/
global class InvoicePastDueNotificationWebService {
/*
    webService static String Send30DayNotifications(Integer amount) {
        EmailTemplate et = [SELECT id FROM EmailTemplate WHERE Name = 'Invoice Past Due 30 Days'];
        
        Id oweaID = null;
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'jason.wood@intapp.com'];
        if (owea.size() > 0) {
            oweaID = owea.get(0).Id;
        }
        
        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
        List<Invoice__c> invoices = Database.query('SELECT Id, Account__r.OwnerId, Sales_Order_Type__c, CRD_Email__c FROM Invoice__c ' +
            'WHERE Status__c = \'Open\' and Outstanding_Balance__c > USD' + amount + ' and Due_Date__c = N_DAYS_AGO:30');
        for(Invoice__c invoice: invoices)
        {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); // new mail object
            
            if (oweaID != null) {
                mail.setOrgWideEmailAddressId(oweaID);
            } 
            else {
                mail.setSenderDisplayName('Jason Wood');//Sender would be owner of Profile
            }
            mail.setWhatId(invoice.Id);
            mail.setTargetObjectId('0035000001u6umd'); //Send to Jason Wood
            mail.setToAddresses(new String[]{'ar@intapp.com'});

            //if (invoice.Sales_Order_Type__c == 'Renewal') {
            //    mail.setTargetObjectId(invoice.CRD_Email__c);
            //}
            //else {
            //    mail.setTargetObjectId(invoice.Account__r.OwnerId); //target to Account Owner
            //}

            mail.setTemplateId(et.id);         
            mail.setSaveAsActivity(false);
            messages.add(mail);
        }
        
        if (messages.size() > 0) {
            Messaging.sendEmail(messages);  //send emails
            return messages.size() + ' emails sent for 30 day';
        }
        else {
            return 'No emails sent for 30 day';
        }
    }

    webService static String  Send60DayNotifications(Integer amount) {
        EmailTemplate et = [SELECT id FROM EmailTemplate WHERE Name = 'Invoice Past Due 60 Days'];

        Id oweaID = null;
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'jason.wood@intapp.com'];
        if (owea.size() > 0) {
            oweaID = owea.get(0).Id;
        }

        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
        List<Invoice__c> invoices = Database.query('SELECT Id, Account__r.OwnerId, Sales_Order_Type__c, CRD_Email__c FROM Invoice__c ' +
            'WHERE Status__c = \'Open\' and Outstanding_Balance__c > USD' + amount + ' and Due_Date__c = N_DAYS_AGO:60');
        for(Invoice__c invoice: invoices)
        {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); // new mail object
             
            if (oweaID != null) {
                mail.setOrgWideEmailAddressId(oweaID);
            } 
            else {
                mail.setSenderDisplayName('Jason Wood');//Sender would be owner of Profile
            }
            
            mail.setWhatId(invoice.Id);
            mail.setTargetObjectId('0035000001u6umd'); //Send to Jason Wood
            mail.setToAddresses(new String[]{'ar@intapp.com'});

            if (invoice.Sales_Order_Type__c == 'Renewal') {
                mail.setCcAddresses(new String[]{'eldean.ward@intapp.com',invoice.CRD_Email__c});
            }
            //else {
            //    mail.setTargetObjectId(invoice.Account__r.OwnerId); //target to receipient
            //    mail.setToAddresses(new String[]{'dan.tacone@intapp.com'});
            //    //Add RVP
            //}

            mail.setTemplateId(et.id);           // pull the email template through id
            mail.setSaveAsActivity(false);
            messages.add(mail);
        }
        
        if (messages.size() > 0) {
            Messaging.sendEmail(messages);  //send emails
            return messages.size() + ' emails sent for 60 day';
        }
        else {
            return 'No emails sent for 60 day';
        }
    }

    webService static String Send90DayNotifications(Integer amount) {
        EmailTemplate et = [SELECT id FROM EmailTemplate WHERE Name = 'Invoice Past Due 90 Days'];
        
        Id oweaID = null;
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'jason.wood@intapp.com'];
        if (owea.size() > 0) {
            oweaID = owea.get(0).Id;
        }

        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
        List<Invoice__c> invoices = Database.query('SELECT Id, Account__r.OwnerId, Sales_Order_Type__c, CRD_Email__c FROM Invoice__c ' + 
            'WHERE Status__c = \'Open\' and Outstanding_Balance__c > USD' + amount + ' and Due_Date__c = N_DAYS_AGO:90');
        for(Invoice__c invoice: invoices)
        {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); // new mail object
             
            if (oweaID != null) {
                mail.setOrgWideEmailAddressId(oweaID);
            } 
            else {            
                mail.setSenderDisplayName('Jason Wood');//Sender would be owner of Profile
            }
            
            mail.setWhatId(invoice.Id);
            mail.setTargetObjectId('0035000001u6umd'); //Send to Jason Wood
            mail.setToAddresses(new String[]{'ar@intapp.com'});
       
            if (invoice.Sales_Order_Type__c == 'Renewal') {
                mail.setCcAddresses(new String[]{'eldean.ward@intapp.com',invoice.CRD_Email__c});
            }
            //else {
            //    mail.setTargetObjectId(invoice.Account__r.OwnerId); //target to receipient
            //    mail.setToAddresses(new String[]{'dan.tacone@intapp.com','cteam@integrationappliance.com'});
            //    //Add RVP
            //}

            mail.setTemplateId(et.id);           // pull the email template through id
            mail.setSaveAsActivity(false);
            messages.add(mail);
        }
        
        if (messages.size() > 0) {
            Messaging.sendEmail(messages);  //send emails
            return messages.size() + ' emails sent for 90 day';
        }
        else {
            return 'No emails sent for 90 day';
        }
    }  
    */
}