force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Governance</fullName>
                <default>true</default>
                <label>Pending Governance</label>
            </value>
            <value>
                <fullName>Verification Approved</fullName>
            </value>
            <value>
                <fullName>Verification Declined</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <label>Support Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard (Silver)</fullName>
                <default>true</default>
                <label>Standard (Silver)</label>
            </value>
            <value>
                <fullName>Premium (Gold)</fullName>
            </value>
            <value>
                <fullName>Premium (Platinum)</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PSCase_Kickoff_Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>PSCase_Kickoff_Meeting_Date__c</fullName>
    <label>Kickoff Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Executive_Support_Case.recordType-meta.xml
<RecordType>
    <fullName>Executive_Support_Case</fullName>
    <active>true</active>
    <businessProcess>Support</businessProcess>
    <label>Executive Support Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>Support</businessProcess>
    <description>Customer assistance, from requests, pro bono, and asking for favors</description>
    <label>Support</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Survey.recordType-meta.xml
<RecordType>
    <fullName>Survey</fullName>
    <active>true</active>
    <businessProcess>Survey</businessProcess>
    <description>For use with surveys</description>
    <label>Survey</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Product_Line__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is used to determine if this field should be available for use in the Product Line lookup fields.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Ownership Details</relationshipLabel>
    <relationshipName>Product_Ownership_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>SC-000016</description>
    <label>Product Line (EXPIRING 3/8)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conflicts</fullName>
            </value>
            <value>
                <fullName>Experience</fullName>
            </value>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
                <label>Integrate</label>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Terms</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>Walls</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
                <isActive>false</isActive>
                <label>Third Party Product - Experience</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Product_line_link__c.field-meta.xml
<CustomField>
    <fullName>Product_line_link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Product Ownership Details</relationshipLabel>
    <relationshipName>Product_Ownership_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Own it</fullName>
            </value>
            <value>
                <fullName>Own Partial</fullName>
            </value>
            <value>
                <fullName>Own it - Limited License</fullName>
            </value>
            <value>
                <fullName>Own it - Trial</fullName>
            </value>
            <value>
                <fullName>Entitled</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Own it - Bridgeway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <label>Support Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard (Silver)</fullName>
                <default>true</default>
                <label>Standard (Silver)</label>
            </value>
            <value>
                <fullName>Premium (Gold)</fullName>
            </value>
            <value>
                <fullName>Premium (Platinum)</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Gwabbit Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTriggerHandlerTest.cls
@isTest
public class CaseTriggerHandlerTest 
{
    static testMethod void TestMethod1()
    {
        String RecordTypeNme = Schema.SObjectType.case.getRecordTypeInfosByDeveloperName().get('Survey').getRecordTypeId();  
        String RecordTypeNmeExe = Schema.SObjectType.case.getRecordTypeInfosByDeveloperName().get('Executive_Support_Case').getRecordTypeId();      
        Account accObj = new Account();
        accObj.Name = 'TestAccount';
        accObj.Type = 'Prospect';
        insert accObj;
        
        Contact conObj = new Contact();
        conObj.lastname = 'TestContact';
        conObj.AccountId = accObj.id;
        insert conObj;
        
        Product_Line__c pli = new Product_Line__c();
        pli.Name = 'Conflicts';
        pli.Active__c = true;
        insert pli;
        
        Product_Ownership_Detail__c pOwn1 = new Product_Ownership_Detail__c();
        pOwn1.Account_Name__c =  accObj.id;
        pOwn1.Product_line_link__c = pli.id;
        pOwn1.Support_Level__c = 'Standard (Silver)';
        pOwn1.Status__c = 'Own it'; 
        insert pOwn1; 
        
        Product_Ownership_Detail__c pOwn2 = new Product_Ownership_Detail__c();
        pOwn2.Account_Name__c =  accObj.id;
        pOwn2.Product_line_link__c = pli.id;
        pOwn2.Support_Level__c = 'Premium (Platinum)';
        pOwn2.Status__c = 'Own it'; 
        insert pOwn2;
        
        Case cseObj1 = new Case();
        cseObj1.AccountId = accObj.Id;
        cseObj1.RecordTypeId = RecordTypeNme;
        cseObj1.PSCase_Kickoff_Meeting_Date__c = system.today();
        cseObj1.Support_Level_Conflicts_New__c = 'Test Support Level';
        insert cseObj1; 
        
        System.assertEquals(system.today(), cseObj1.PSCase_Kickoff_Meeting_Date__c);
        
        Case cseObj2 = new Case();
        cseObj2.AccountId = accObj.Id;
        cseObj2.RecordTypeId = RecordTypeNmeExe;
        cseObj2.Survey_ContactID__c = conObj.id;
        insert cseObj2;
        
        
        
    } 
    
    static testMethod void TestMethod2()
    {
        List<case> lstOfCases = new List<case>();
        Map<Id,Case> mapOfCases = new Map<Id,Case>();
        String RecordTypeNme = Schema.SObjectType.case.getRecordTypeInfosByDeveloperName().get('Survey').getRecordTypeId();       
        Account accObj = new Account();
        accObj.Name = 'TestAccount';
        accObj.Type = 'Prospect';
        insert accObj;
        
        Contact conObj = new Contact();
        conObj.lastname = 'TestContact';
        conObj.AccountId = accObj.id;
        insert conObj;
        
        Product_Line__c pli = new Product_Line__c();
        pli.Name = 'Test PLI';
        pli.Active__c = true;
        insert pli;
        
        Product_Ownership_Detail__c pOwn1 = new Product_Ownership_Detail__c();
        pOwn1.Account_Name__c =  accObj.id;
        pOwn1.Product_line_link__c = pli.id;
        pOwn1.Support_Level__c = 'Premium (Platinum)';
        pOwn1.Status__c = 'Own it'; 
        insert pOwn1; 
        
        Product_Ownership_Detail__c pOwn2 = new Product_Ownership_Detail__c();
        pOwn2.Account_Name__c =  accObj.id;
        pOwn2.Product_line_link__c = pli.id;
        pOwn2.Support_Level__c = 'Standard (Silver)';
        pOwn2.Status__c = 'Own it'; 
        insert pOwn2;   
        
        Case cseObj = new Case();
        cseObj.AccountId = accObj.Id;
        cseObj.RecordTypeId = RecordTypeNme;
        cseObj.PSCase_Kickoff_Meeting_Date__c = system.today() + 1;
        insert cseObj;
        
        System.assertEquals(system.today() + 1, cseObj.PSCase_Kickoff_Meeting_Date__c);
        lstOfCases.add(cseObj);
        mapOfCases.put(cseObj.id,cseObj);
        
        CaseTriggerHandler.AfterUnDelete(lstOfCases,mapOfCases);
        CaseTriggerHandler.UpdateSupportLevels(lstOfCases);
        delete cseObj;
        
    }
}