force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Governance</fullName>
                <default>true</default>
                <label>Pending Governance</label>
            </value>
            <value>
                <fullName>Verification Approved</fullName>
            </value>
            <value>
                <fullName>Verification Declined</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <label>Support Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard (Silver)</fullName>
                <default>true</default>
                <label>Standard (Silver)</label>
            </value>
            <value>
                <fullName>Premium (Gold)</fullName>
            </value>
            <value>
                <fullName>Premium (Platinum)</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Confidence_in_Completion_Date_Prior__c.field-meta.xml
<CustomField>
    <fullName>Confidence_in_Completion_Date_Prior__c</fullName>
    <description>This is a hidden field used to store the prior value of the Confidence in Completion Date.  This field is used in the E-Mail Alerts that are sent when the field changes.</description>
    <label>Confidence in Completion Date - Prior</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/DateOpen__c.field-meta.xml
<CustomField>
    <fullName>DateOpen__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Project_Exp_Compl_Date_Prior__c.field-meta.xml
<CustomField>
    <fullName>Project_Exp_Compl_Date_Prior__c</fullName>
    <description>This is a hidden field and used to store the previous value of the Estimated Completion Date prior to it&apos;s most recent change.  This is used in the E-Mail Alerts which are sent when the main field changes.</description>
    <label>Project - Exp Compl Date - Prior</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/PSCase_Confidence_in_Completion__c.field-meta.xml
<CustomField>
    <fullName>PSCase_Confidence_in_Completion__c</fullName>
    <description>This is the Project Manager&apos;s assessment as to if the Estimated Completion Date will be hit.  This field is key in generating the Profesional Services Forecast reports.</description>
    <label>Confidence in Completion Date</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PSCase_Kickoff_Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>PSCase_Kickoff_Meeting_Date__c</fullName>
    <label>Kickoff Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/PSCase_Project_Exp_Compl_Date__c.field-meta.xml
<CustomField>
    <fullName>PSCase_Project_Exp_Compl_Date__c</fullName>
    <defaultValue>DATE(2099,9,9)</defaultValue>
    <description>This is the expected date the project will complete.  This field is key in generating the Profesional Services Forecast reports.</description>
    <label>Project - Exp Compl Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Survey_ACCalculated__c.field-meta.xml
<CustomField>
    <fullName>Survey_ACCalculated__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey_ACCalculated</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Survey_ACCalculated)</relationshipLabel>
    <relationshipName>AdoptionContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Survey_AccountCalculated__c.field-meta.xml
<CustomField>
    <fullName>Survey_AccountCalculated__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey_AccountCalculated</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>SurveyAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Survey_PC_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Survey_PC_Calculated__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Principal Consultant Calculated</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Survey Principal Consultant)</relationshipLabel>
    <relationshipName>CasesPC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Survey_PMCalculated__c.field-meta.xml
<CustomField>
    <fullName>Survey_PMCalculated__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey_PMCalculated</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Survey_PMCalculated)</relationshipLabel>
    <relationshipName>PMContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Survey_ProjectCalculated__c.field-meta.xml
<CustomField>
    <fullName>Survey_ProjectCalculated__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey_ProjectCalculated</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>SurveyProject</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Survey_SA_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Survey_SA_Calculated__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Solution Architect Calculated</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Survey Solution Architect Calculated)</relationshipLabel>
    <relationshipName>CasesSA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Survey_SECalculated__c.field-meta.xml
<CustomField>
    <fullName>Survey_SECalculated__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey_SECalculated</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>Support</businessProcess>
    <description>Customer assistance, from requests, pro bono, and asking for favors</description>
    <label>Support</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Survey.recordType-meta.xml
<RecordType>
    <fullName>Survey</fullName>
    <active>true</active>
    <businessProcess>Survey</businessProcess>
    <description>For use with surveys</description>
    <label>Survey</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Ownership Details</relationshipLabel>
    <relationshipName>Product_Ownership_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Product_line_link__c.field-meta.xml
<CustomField>
    <fullName>Product_line_link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Product Ownership Details</relationshipLabel>
    <relationshipName>Product_Ownership_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Own it</fullName>
            </value>
            <value>
                <fullName>Own Partial</fullName>
            </value>
            <value>
                <fullName>Own it - Limited License</fullName>
            </value>
            <value>
                <fullName>Own it - Trial</fullName>
            </value>
            <value>
                <fullName>Entitled</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Own it - Bridgeway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Ownership_Detail__c/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <label>Support Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard (Silver)</fullName>
                <default>true</default>
                <label>Standard (Silver)</label>
            </value>
            <value>
                <fullName>Premium (Gold)</fullName>
            </value>
            <value>
                <fullName>Premium (Platinum)</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Gwabbit Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
/********************************************************************************     
 *  Name             :  CaseTriggerHandler
 *  Author           :  Hiforte Technologies
 *  Description      :  1. Identifies if an Account has Active projects, for Cases
 *                                  
 *  Change history   :
 *  Date                Author                          Description
 *  02/24/14        Vasu Pulipati                   Created
 *  05/14/19        Venkat                          Added before insert and update functions
 *  05/14/19        Venkat                          Added functionality to update support levels
 ********************************************************************************/
public with sharing class CaseTriggerHandler {
    public static void beforeInsert(List<Case> newCases){  
        updateOpenDate(newCases);
        UpdateSupportLevels(newCases);
        surveyCaseUpdateFields(newCases);
    }
    
    public static void beforeUpdate(List<Case> newCases, Map<ID, Case> newCaseMap,  List<Case> oldCases, Map<ID,Case> oldCaseMap){
       
        updateProjectDates(newCases, oldCases, oldCaseMap);
        updateOpenDate(newCases);  
        UpdateSupportLevels(newCases);
        surveyCaseUpdateFields(newCases);
    }
    
    public static void afterInsert(List<Case> newCases, Map<ID, Case> newCaseMap){
        if(!newCases.IsEmpty())
        {           
         hotListCaseCount(newCases);
        }
        
    }
    
    public static void afterUpdate(List<Case> newCases, Map<ID, Case> newCaseMap,  List<Case> oldCases, Map<ID, Case> oldCaseMap){
        if(!newCases.IsEmpty())
        {           
         hotListCaseCount(newCases);
        }
        
    }
    
    public static void afterDelete(List<Case> oldCases, Map<ID, Case> oldCaseMap){
        if(!oldCases.IsEmpty())
        {           
         hotListCaseCount(oldCases);
        }
        
    }
    
    public static void afterUnDelete(List<Case> newCases, Map<ID, Case> newCaseMap){
        if(!newCases.IsEmpty())
        {           
         hotListCaseCount(newCases);
        }
    }
    /*FreshDesk# - 33979*/
    public static void updateSupportLevels(List<Case> cases){
        //Get all case fields to check if the support level fields exists - this is done to dynamically add values to support level fields
        Set<String> caseFields = Schema.SObjectType.Case.fields.getMap().keySet();
        
        //Set Service Level Priority
        Map<String, Integer> mapSupportLevelSupportLevelPriority = new Map<String, Integer>{'Lapsed'=>0, 'LegalKey'=>1, 'Standard (Silver)'=>2, 'Premium (Gold)'=>3, 'Premium (Platinum)'=>4};
        
        //Container for all the accounts related to case
        Set<Id> accountIds = new Set<Id>();
        
        //Map of Map => Example, [0015000000cFGEd = (Time = Standard (Silver), Walls = Premium (Gold))]
        Map<Id, Map<String, String>> mapAccountsWithMapOfProductLineandServiceLevel = new Map<Id, Map<String, String>>();
        
        //Get all unique accounts related to cases
        for(Case c: Cases){
            if(!c.IsClosed){
                AccountIds.add(c.AccountId);
            }
        }
        
        System.debug('Checkpoint 1 ' + AccountIds );
        
        //Loop over all valid PODs related to the Accounts we got in the previous step - 
        for(Product_Ownership_Detail__c pOD: [SELECT Account_Name__c, Product_line_link__c, Product_line_link__r.Name, Support_Level__c 
                                              FROM Product_Ownership_Detail__c 
                                              WHERE Account_Name__c in : AccountIds
                                              AND Product_line_link__c != null
                                              AND Support_Level__c != null
                                              AND Status__c NOT IN ('Lapsed','Converted','Entitled')]){
            
            String productLineName = POD.Product_line_link__c != null ? POD.Product_line_link__r.Name: '';
            
            ProductLineName = ProductLineName.contains(' - Cloud')? ProductLineName.split(' - ')[0]: ProductLineName;
            System.debug('Checkpoint 1.1 ' +  ProductLineName);
            
            //Contruct Map of maps = Example, [0015000000cFGEd = (Time = Standard (Silver), Walls = Premium (Gold))]
            //If Map contains the account already, allow in - If not go to else at 91
            if(mapAccountsWithMapOfProductLineandServiceLevel.containsKey(POD.Account_Name__c)){
                //If Map contains the product line already, allow in - If not go to else at 87
                if(mapAccountsWithMapOfProductLineandServiceLevel.get(POD.Account_Name__c).containsKey(ProductLineName)){
                    //Its time to check if the already existing product line has a lesser service level
                    if(mapSupportLevelSupportLevelPriority.containsKey(mapAccountsWithMapOfProductLineandServiceLevel.get(POD.Account_Name__c).get(ProductLineName)) &&
                       mapSupportLevelSupportLevelPriority.containsKey(POD.Support_Level__c) &&
                       mapSupportLevelSupportLevelPriority.get(POD.Support_Level__c) > mapSupportLevelSupportLevelPriority.get(mapAccountsWithMapOfProductLineandServiceLevel.get(POD.Account_Name__c).get(ProductLineName))){
                           System.debug('Checkpoint 1.1.1 - We have already encountered this product line before and the service level is lower than ' + POD.Support_Level__c);
                           mapAccountsWithMapOfProductLineandServiceLevel.get(POD.Account_Name__c).put(ProductLineName, POD.Support_Level__c);
                       }
                }
                else{
                    mapAccountsWithMapOfProductLineandServiceLevel.get(POD.Account_Name__c).put(ProductLineName, POD.Support_Level__c);
                }
            }
            else{
                mapAccountsWithMapOfProductLineandServiceLevel.put(POD.Account_Name__c, new Map<String, String> {ProductLineName => POD.Support_Level__c});
            }
        }
        
        
        //Loop over all the cases
        for(Case c: Cases){
            if(!mapAccountsWithMapOfProductLineandServiceLevel.containsKey(c.AccountId) || mapAccountsWithMapOfProductLineandServiceLevel.get(c.AccountId) == null){
                continue;
            }
            System.debug('Checkpoint 2 - For Account '+ c.AccountId + ', the PODS are ' + mapAccountsWithMapOfProductLineandServiceLevel.get(c.AccountId));
        
            for(String productLine: mapAccountsWithMapOfProductLineandServiceLevel.get(c.AccountId).keyset()){
                //Form the name of the case field that needs to be populated - example: Support_Level_Conflicts_New__c - Make sure the field name contains the exact product line name
                String supportFieldName = 'Support_Level_' + ProductLine + '_New__c';
                
                System.debug('Checkpoint 3 - ' + SupportFieldName + '? = ' + CaseFields.contains(SupportFieldName.trim().toLowerCase()));
                
                //Check if the case object has this field
                if(!CaseFields.contains(SupportFieldName.trim().toLowerCase())){ 
                    continue;
                }
                
                //Check if there is already a value on this field and if it is correct                  
                if(c.get(SupportFieldName) != mapAccountsWithMapOfProductLineandServiceLevel.get(c.AccountId).get(ProductLine)){    
                    c.put(SupportFieldName, mapAccountsWithMapOfProductLineandServiceLevel.get(c.AccountId).get(ProductLine)); 
                    System.debug('Checkpoint 4 - ' + c.get(SupportFieldName));
                }
            }
        }
        
        if(!Trigger.isExecuting){
            update Cases;
        }
    }
    
    public static void hotListCaseCount(List<Case> newCases)
    {
        
        // get list of accounts
        Set<ID> acctIds = new Set<ID>();
        List<Account> acctsToRollup = new List<Account>();
        
        if(!newCases.IsEmpty())
        {   
            for (Case cse : newCases) {
                acctIds.add(cse.AccountId);
            }
        }
        
        if(acctIds!=null)
        {           
        for (AggregateResult ar : [SELECT AccountId AcctId, Count(id) CaseCount 
                               FROM Case 
                               where AccountId in :acctIds and Record_Type_Name__c = 'Executive Support' and
                               Status not in ('Closed - Resolved','Closed - Unresolved','Abandoned','Escalated to Engineering')
                               GROUP BY AccountId]){
        Account accObj = new Account();
        accObj.Id = (Id) ar.get('AcctId'); //---> handy trick for updates, set the id and update
        if (accObj.Hot_List_Case_Count__c != (Integer) ar.get('CaseCount'))
        {
        accObj.Hot_List_Case_Count__c = (Integer) ar.get('CaseCount');
        acctsToRollup.add(accObj);
        }
    }
                                                                     
        update acctsToRollup;       
        
    }
}
    
    public static void surveyCaseUpdateFields(List<Case> newCases)
    {
        string label = System.label.CaseIdLabel;
      // Update the Contact on the Survey Case
      if(!newCases.IsEmpty())
      {
          for(case myCase : newCases)
          {
              if ( myCase.Record_Type_Name__c == 'Survey' && myCase.Survey_ContactID__c != null && myCase.ContactID == null ) 
                  {
                  myCase.ContactId = myCase.Survey_ContactID__c;
                  }
                // Update the Associated Project on the Survey Case
                if ( myCase.Record_Type_Name__c == 'Survey' && myCase.Survey_AssociatedCase_Temp__c != null && myCase.Survey_ProjectCalculated__c == null && myCase.Survey_AssociatedMilestone__c != null) 
                  {
                  myCase.Survey_ProjectCalculated__c = myCase.Survey_AssociatedCase_Temp__c;
                  }
                // Update the SE on the Survey Case
                if ( myCase.Record_Type_Name__c == 'Survey' && myCase.Survey_EngineerName__c != null && myCase.Survey_SECalculated__c == null && myCase.Survey_AssociatedMilestone__c != null) 
                  {
                  myCase.Survey_SECalculated__c = myCase.Survey_EngineerName__c;
                  }
                // Update the Adoption Consultant on the Survey Case
                if ( myCase.Record_Type_Name__c == 'Survey' && myCase.Survey_AdoptionConsultant__c != null && myCase.Survey_ACCalculated__c == null && myCase.Survey_AssociatedMilestone__c != null) 
                  {
                  myCase.Survey_ACCalculated__c = myCase.Survey_AdoptionConsultant__c;
                  }
                // Update the Project Manager on the Survey Case
                if ( myCase.Record_Type_Name__c == 'Survey' && myCase.Survey_ProjectManagerName__c != null && myCase.Survey_ProjectManagerName__c != label && myCase.Survey_PMCalculated__c == null && myCase.Survey_AssociatedMilestone__c != null) 
                  {
                  myCase.Survey_PMCalculated__c = myCase.Survey_ProjectManagerName__c;
                  }            
                // Update the Account on the Survey Case
                if ( myCase.Record_Type_Name__c == 'Survey' && myCase.Survey_FirmName__c != null && myCase.Survey_AccountCalculated__c == null && myCase.Survey_AssociatedMilestone__c != null) 
                  {
                  myCase.Survey_AccountCalculated__c = myCase.Survey_FirmName__c;
                  } 
                // Update the Principal Consultant on the Survey Case
                if ( myCase.Record_Type_Name__c == 'Survey' && myCase.Survey_Principal_Consultant_Name__c != null && myCase.Survey_Principal_Consultant_Name__c != label && myCase.Survey_PC_Calculated__c == null && myCase.Survey_AssociatedMilestone__c != null) 
                  {
                  myCase.Survey_PC_Calculated__c = myCase.Survey_Principal_Consultant_Name__c;
                  }
                    // Update the Principal Consultant on the Survey Case
                if ( myCase.Record_Type_Name__c == 'Survey' && myCase.Survey_Solution_Architect_Name__c != null && myCase.Survey_Solution_Architect_Name__c != label && myCase.Survey_SA_Calculated__c == null && myCase.Survey_AssociatedMilestone__c != null) 
                  {
                  myCase.Survey_SA_Calculated__c = myCase.Survey_Solution_Architect_Name__c;
                  }
            }         
        } 
    }
    
    public static void updateOpenDate(List<Case> newCases)
    {
        if(!newCases.IsEmpty())
        {   
            for(case caseObj : newCases)
            {   
             if( caseObj.PSCase_Kickoff_Meeting_Date__c != null && caseObj.DateOpen__C == null ) 
              {
               caseObj.DateOpen__C = caseObj.PSCase_Kickoff_Meeting_Date__c;
              } 
            }
        }       
        
    }
    
    public static void updateProjectDates(List<Case> newCases,  List<Case> oldCases, Map<ID,Case> oldCaseMap)
    {
        if(!newCases.IsEmpty())
        {
            for(case caseObj : newCases)
            {   
            caseObj.Project_Exp_Compl_Date_Prior__c = oldCaseMap.get(caseObj.id).PSCase_Project_Exp_Compl_Date__c;
            caseObj.Confidence_in_Completion_Date_Prior__c = oldCaseMap.get(caseObj.id).PSCase_Confidence_in_Completion__c; 
            }
        }       
        
    }
    
}