force-app/main/default/objects/Account/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the Account with whom we have the billing relationship.</inlineHelpText>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
            <value>
                <fullName>ACV Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>This field denotes the Billing Subsidiary for this contract for the Account to Customer sync in NetSuite,</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Associated_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated OSA</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semiannual</fullName>
            </value>
            <value>
                <fullName>Quarterly Y1 Only</fullName>
            </value>
            <value>
                <fullName>Semi-annual Y1 Only</fullName>
            </value>
            <value>
                <fullName>Invoice Plan</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>No Software</fullName>
            </value>
            <value>
                <fullName>XXXXX</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/DLI_Product__c.field-meta.xml
<CustomField>
    <fullName>DLI_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DLI Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OP4I Entitlement Views (DLI Product)</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/DLIP_Product__c.field-meta.xml
<CustomField>
    <fullName>DLIP_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DLIP Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OP4I Entitlement Views (DLIP Product)</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Include_in_Select_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Select_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in Select Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Created</fullName>
            </value>
            <value>
                <fullName>Quote Created</fullName>
            </value>
            <value>
                <fullName>Parent Quote Line Created</fullName>
            </value>
            <value>
                <fullName>Order and OLI created</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Activated</fullName>
            </value>
            <value>
                <fullName>Child Quote Line Created</fullName>
            </value>
            <value>
                <fullName>ACV Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>OP4I Entitlement Views</relationshipLabel>
    <relationshipName>OP4I_Entitlement_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OP4I_Entitlement_View__c/fields/Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price__c</fullName>
    <label>Sale Price</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>This is the date that the billing pause ends and the billing restarts.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Migration_Contract__c.field-meta.xml
<CustomField>
    <fullName>Migration_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Migration Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Migration Contract)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>This is the date the the billing pause begins.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Populate Subsidiary value from related contract created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Services Discount</fullName>
            </value>
            <value>
                <fullName>Software Discount (Recurring)</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Training Discount</fullName>
            </value>
            <value>
                <fullName>Early Adopter</fullName>
            </value>
            <value>
                <fullName>Software Discount (One-Time)</fullName>
            </value>
            <value>
                <fullName>Tax Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>The record type to be used for products such as Wall Builder</description>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Include_in_Select_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Select_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in Select Bundle?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Migration_Contract__c.field-meta.xml
<CustomField>
    <fullName>Migration_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Migration Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quotes (Migration Contract)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__BillingFrequency__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__BillingFrequency__c</fullName>
    <description>Defines the billing frequency.</description>
    <inlineHelpText>Defines the billing frequency.</inlineHelpText>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Initial license term (in months). By default, this will be populated to 12 months. It can be overwritten by Contract Ops.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <description>Track subsidiaries created as part of BIZ-47396 story</description>
    <label>Subsidiary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsidiary</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Subsidiary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01:200 Integration Appliance (US)</fullName>
        <default>true</default>
        <label>01:200 Integration Appliance (US)</label>
    </customValue>
    <customValue>
        <fullName>05:400 TFG - US</fullName>
    </customValue>
    <customValue>
        <fullName>06:700 Rekoop Limited (UK)</fullName>
    </customValue>
    <customValue>
        <fullName>09:750 Rekoop Pty Limited (AUS)</fullName>
    </customValue>
    <customValue>
        <fullName>23:Gwabbit</fullName>
    </customValue>
    <customValue>
        <fullName>35:Repstor Limited</fullName>
    </customValue>
    <customValue>
        <fullName>37:Repstor, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>18:DealCloud, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>28:OnePlace Pte Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>42:Paragon Data Labs, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>22:Paragon Data Labs, Inc.</fullName>
        <isActive>false</isActive>
        <label>22:Paragon Data Labs, Inc.</label>
    </customValue>
    <customValue>
        <fullName>Polar Placeholder</fullName>
        <isActive>false</isActive>
        <label>Polar Placeholder</label>
    </customValue>
    <description>Will be used in Account,Contract, Quote &amp; Order created as part of BIZ-47396 story</description>
    <masterLabel>Subsidiary</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteLinesParentMigrationBatchTest.cls
/********************************************************************************     
 *  Name             :  OpportunityQuoteMigrationBatch
 *  Author           :  Snehal Choudhary
 *  Description      :  Test Class for OpportunityQuoteMigrationBatch
 *                   
 *  Change history   :
 *  Date               Author             Description
 *  02/11/2023    Snehal Choudhary          Created
 ********************************************************************************/

@isTest
private class QuoteLinesParentMigrationBatchTest {
  @testSetup static void setup() {
    Account acc = IntappTestObjectFactory.createaccount(true);
    Account billingAccount = IntappTestObjectFactory.createaccount(true);
        
    blng__BillingRule__c billRule = new blng__BillingRule__c();
    billRule.Name = 'Bill Rule1';
    billRule.blng__InitialBillingTrigger__c = 'Order Product Activation Date';
    billRule.blng__PartialPeriodTreatment__c = 'Separate';
    billRule.blng__PeriodTreatmentForBTDO__c = 'Exclude Billing Day of Month';
    billRule.blng__GenerateInvoices__c = 'No';
    billRule.blng__Active__c = true;
    insert billRule;
    
    blng__RevenueRecognitionRule__c rrObj = new blng__RevenueRecognitionRule__c();
    rrObj.blng__Active__c = true;
    rrObj.blng__CreateRevenueSchedule__c = 'No';
    insert rrObj;
    
    blng__TaxRule__c taxRuleObj = new blng__TaxRule__c();
    taxRuleObj.blng__Active__c = true;
    taxRuleObj.blng__TaxableYesNo__c = 'No';
    insert taxRuleObj;
    
    Product2 prodObj1 = IntappTestObjectFactory.createProduct(true);
    prodObj1.Name = 'TestProd';
    update prodObj1;
    
    Product2 prodObj = IntappTestObjectFactory.createProduct(true);
    prodObj.Name = 'Intapp Select Bundle';
    update prodObj;
    
    Contract con = IntappTestObjectFactory.createcontract(acc.Id);
    con.Billing_Account__c = billingAccount.Id;
    insert con;
    
    SBQQ__Quote__c quoteObj = IntappTestObjectFactory.createSBQQQuote();
    insert quoteObj;
    
    OP4I_Entitlement_View__c entitlement = new OP4I_Entitlement_View__c();
    entitlement.Associated_OSA__c = con.id;
    entitlement.Start_Date__c = Date.newInstance(2021, 4, 1);
    entitlement.End_Date__c = Date.newInstance(2022, 3, 31);
    entitlement.Sale_Price__c = 20.22;
    entitlement.Product_Type__c = 'Software';
    entitlement.DLI_Product__c = prodObj.id;
    entitlement.DLIP_Product__c = prodObj.id;
    entitlement.Billing_Frequency__c = 'Annual';
    entitlement.Quote__c = quoteObj.Id;
    insert entitlement;
    }  
  
  @isTest 
  private static void testMethod1() {
    test.startTest();
    List<Contract> lstOfContracts = new List<Contract>();
    product2 prodTest = [Select Id FROM Product2 WHERE Name = 'TestProd' LIMIT 1] ;
    blng__BillingRule__c billRule = [Select Id FROM blng__BillingRule__c WHERE Name = 'Bill Rule1' LIMIT 1] ;
    blng__RevenueRecognitionRule__c revRule = [Select Id FROM blng__RevenueRecognitionRule__c LIMIT 1] ;
    blng__TaxRule__c taxRule = [Select Id FROM blng__TaxRule__c LIMIT 1] ;
    prodTest.IsActive = true;
    prodTest.blng__BillingRule__c = billRule.Id;
    prodTest.blng__RevenueRecognitionRule__c = revRule.Id;
    prodTest.blng__TaxRule__c = taxRule.Id;
    prodTest.SBQQ__SubscriptionPricing__c = 'Fixed Price';
    prodTest.SBQQ__SubscriptionTerm__c = 12;
    prodTest.SBQQ__SubscriptionType__c = 'Renewable';
    prodTest.SBQQ__ChargeType__c = 'Recurring';
    prodTest.SBQQ__BillingFrequency__c = 'Annual';
    prodTest.SBQQ__BillingType__c = 'Arrears';
    update prodTest;

    Contract contr = [Select Id FROM Contract LIMIT 1];
    contr.Status = 'Activated';
    lstOfContracts.add(contr);
    update lstOfContracts;
    lstOfContracts[0].Status = 'In Force';
    lstOfContracts[0].Subsidiary__c = '05:400 TFG - US';
    lstOfContracts[0].Processing_Status__c = 'Quote Created';
    update lstOfContracts[0];

    SBQQ__Quote__c quoteObj = [Select Id FROM SBQQ__Quote__c LIMIT 1];
    quoteObj.Migration_Contract__c = lstOfContracts[0].id;
    update quoteObj;
    
    Opportunity oppObj = IntappTestObjectFactory.createOpportunity();   
    oppObj.Migration_Contract__c = lstOfContracts[0].id;
    insert oppObj;
    
    QuoteLinesParentMigrationBatch qliObj = new QuoteLinesParentMigrationBatch();
    database.executebatch(qliObj,1); 
    test.stopTest(); 
    Contract contrUpd = [Select Id,Processing_Status__c FROM Contract WHERE Id =: lstOfContracts[0].Id LIMIT 1];
    System.assertEquals('Parent Quote Line Created',contrUpd.Processing_Status__c);   
  }
  
  @isTest 
  private static void testMethod2() {
    test.startTest();
    List<Contract> lstOfContracts = new List<Contract>();
    product2 prodTest = [Select Id FROM Product2 WHERE Name = 'Intapp Select Bundle' LIMIT 1] ;
    blng__BillingRule__c billRule = [Select Id FROM blng__BillingRule__c WHERE Name = 'Bill Rule1' LIMIT 1] ;
    blng__RevenueRecognitionRule__c revRule = [Select Id FROM blng__RevenueRecognitionRule__c LIMIT 1] ;
    blng__TaxRule__c taxRule = [Select Id FROM blng__TaxRule__c LIMIT 1] ;
    prodTest.IsActive = true;
    prodTest.blng__BillingRule__c = billRule.Id;
    prodTest.blng__RevenueRecognitionRule__c = revRule.Id;
    prodTest.blng__TaxRule__c = taxRule.Id;
    prodTest.SBQQ__SubscriptionPricing__c = 'Fixed Price';
    prodTest.SBQQ__SubscriptionTerm__c = 12;
    prodTest.SBQQ__SubscriptionType__c = 'Renewable';
    prodTest.SBQQ__ChargeType__c = 'Recurring';
    prodTest.SBQQ__BillingFrequency__c = 'Annual';
    prodTest.SBQQ__BillingType__c = 'Arrears';
    update prodTest;

    Contract contr = [Select Id,contractNumber FROM Contract LIMIT 1];
    contr.Status = 'Activated';
    lstOfContracts.add(contr);
    update lstOfContracts;
    lstOfContracts[0].Status = 'In Force';
    lstOfContracts[0].Subsidiary__c = '05:400 TFG - US';
    lstOfContracts[0].Processing_Status__c = 'Quote Created';
    update lstOfContracts[0];

    SBQQ__Quote__c quoteObj = [Select Id FROM SBQQ__Quote__c LIMIT 1];
    quoteObj.Migration_Contract__c = lstOfContracts[0].id;
    update quoteObj;
    
    Opportunity oppObj = IntappTestObjectFactory.createOpportunity();   
    oppObj.Migration_Contract__c = lstOfContracts[0].id;
    insert oppObj;
    
    OP4I_Entitlement_View__c entitlementUpd = [Select Id,Include_in_Select_Bundle__c FROM OP4I_Entitlement_View__c LIMIT 1];
    entitlementUpd.Include_in_Select_Bundle__c = true;
    update entitlementUpd;
    
    List<string> lstOfContractNumbers = new List<String>();
    lstOfContractNumbers.add(lstOfContracts[0].ContractNumber);
    
    QuoteLinesParentMigrationBatch qliObj = new QuoteLinesParentMigrationBatch(lstOfContractNumbers);
    database.executebatch(qliObj,1);
    test.stopTest();  
    Contract contrUpd = [Select Id,Processing_Status__c FROM Contract WHERE Id =: lstOfContracts[0].Id LIMIT 1];
    System.assertEquals('Parent Quote Line Created',contrUpd.Processing_Status__c);   
  }
  
  @isTest 
  private static void testMethod3() {
    test.startTest();
    List<Contract> lstOfContracts = new List<Contract>();
    product2 prodTest = [Select Id FROM Product2 WHERE Name = 'TestProd' LIMIT 1] ;
    blng__BillingRule__c billRule = [Select Id FROM blng__BillingRule__c WHERE Name = 'Bill Rule1' LIMIT 1] ;
    blng__RevenueRecognitionRule__c revRule = [Select Id FROM blng__RevenueRecognitionRule__c LIMIT 1] ;
    blng__TaxRule__c taxRule = [Select Id FROM blng__TaxRule__c LIMIT 1] ;
    prodTest.IsActive = true;
    prodTest.blng__BillingRule__c = billRule.Id;
    prodTest.blng__RevenueRecognitionRule__c = revRule.Id;
    prodTest.blng__TaxRule__c = taxRule.Id;
    prodTest.SBQQ__SubscriptionPricing__c = 'Fixed Price';
    prodTest.SBQQ__SubscriptionTerm__c = 12;
    prodTest.SBQQ__SubscriptionType__c = 'Renewable';
    prodTest.SBQQ__ChargeType__c = 'Recurring';
    prodTest.SBQQ__BillingFrequency__c = 'Annual';
    prodTest.SBQQ__BillingType__c = 'Arrears';
    update prodTest;

    Contract contr = [Select Id,contractNumber FROM Contract LIMIT 1];
    contr.Status = 'Activated';
    lstOfContracts.add(contr);
    update lstOfContracts;
    lstOfContracts[0].Status = 'In Force';
    lstOfContracts[0].Subsidiary__c = '05:400 TFG - US';
    lstOfContracts[0].Processing_Status__c = 'Quote Created';
    update lstOfContracts[0];

    SBQQ__Quote__c quoteObj = [Select Id FROM SBQQ__Quote__c LIMIT 1];
    quoteObj.Migration_Contract__c = lstOfContracts[0].id;
    update quoteObj;
    
    Opportunity oppObj = IntappTestObjectFactory.createOpportunity();   
    oppObj.Migration_Contract__c = lstOfContracts[0].id;
    insert oppObj;
    
    OP4I_Entitlement_View__c entitlementUpd = [Select Id,Start_Date__c,End_Date__c FROM OP4I_Entitlement_View__c LIMIT 1];
    entitlementUpd.Start_Date__c = null;
    entitlementUpd.End_Date__c = null;
    update entitlementUpd;
    
    List<string> lstOfContractNumbers = new List<String>();
    lstOfContractNumbers.add(lstOfContracts[0].ContractNumber);
    
    QuoteLinesParentMigrationBatch qliObj = new QuoteLinesParentMigrationBatch(lstOfContractNumbers);
    database.executebatch(qliObj,1); 
    test.stopTest(); 
    Contract contrUpd = [Select Id,Processing_Status__c FROM Contract WHERE Id =: lstOfContracts[0].Id LIMIT 1];
    System.assertEquals('Parent Quote Line Created',contrUpd.Processing_Status__c);   
  }
}