force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4IDealID__c.field-meta.xml
<CustomField>
    <fullName>OP4IDealID__c</fullName>
    <description>This is a reference ID of Deal ID</description>
    <externalId>true</externalId>
    <label>OP4I Deal ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OP4IQuoteController.cls
public class OP4IQuoteController {
    public string message {get;set;}
    
    public OP4IQuoteController() {
        message = 'Processing your request...';
    }
    

    public PageReference initialize() {
        String dealId  = ApexPages.currentPage().getParameters().get('dealId');
        String accId  = ApexPages.currentPage().getParameters().get('accid');
        String oppId  = ApexPages.currentPage().getParameters().get('oppid');

        system.debug('dealId--->'+dealId);
        
        PageReference opportunityPage;
        List<Opportunity> opportunityList;
        if (string.isNotBlank(oppId)) {
            opportunityList = [
                SELECT Id
                        , AccountId
                        , Pricebook2Id
                    FROM Opportunity
                WHERE Id = :oppId
            ];
        }

        if (opportunityList != null && opportunityList.size() > 0) {
            opportunityPage = new PageReference('/'+oppId);
        } else {

            if (string.isNotBlank(oppId)) {
                message = 'Not able to locate opportunity, please make sure oppid is valid...';
            } else {

                List<SBQQ__Quote__c> quoteList;
                if (string.isNotBlank(dealId)) {
                    quoteList = [
                        SELECT Id
                            , OP4IDealID__c
                            , SBQQ__Opportunity2__c
                        FROM SBQQ__Quote__c
                        WHERE OP4IDealID__c = :dealId
                    ];
                }
                
                if (quoteList != null && quoteList.size() > 0){
                    opportunityPage = new PageReference('/'+quoteList[0].SBQQ__Opportunity2__c);
                } else {
                    List<Account> accountList;
                    if (string.isNotBlank(accId)) {
                        accountList = [
                            SELECT Id
                                , Name
                            FROM Account
                            WHERE Id = :accId
                        ];
                    }

                    if (accountList != null && accountList.size() > 0) {
                        Opportunity opportunity = createOpportunity(accountList[0]);
                        opportunityPage = new PageReference('/'+opportunity.Id);
                    } else {
                        message = 'Not able to locate account, please make sure accid is present and its valid...';
                    }
                }
            }
        }

        return opportunityPage;    
    }

    public static Opportunity createOpportunity(Account account) {
        Opportunity opportunity = new Opportunity();
        opportunity.accountId = account.Id;
        opportunity.name = account.Name;
        opportunity.closeDate = date.today().toStartOfMonth().addMonths(1).addDays(-1);
        opportunity.stageName = 'Qualify';
        insert opportunity;
        return opportunity;
    }

}