force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__TermCondition__c/fields/SBQQ__Operator__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Operator__c</fullName>
    <description>The operator for this field.</description>
    <inlineHelpText>Choose the operator for the field.</inlineHelpText>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
            </value>
            <value>
                <fullName>not equals</fullName>
            </value>
            <value>
                <fullName>less than</fullName>
            </value>
            <value>
                <fullName>less or equals</fullName>
            </value>
            <value>
                <fullName>greater than</fullName>
            </value>
            <value>
                <fullName>greater or equals</fullName>
            </value>
            <value>
                <fullName>starts with</fullName>
            </value>
            <value>
                <fullName>ends with</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
            <value>
                <fullName>does not contain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__TermCondition__c/fields/SBQQ__TestedField__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__TestedField__c</fullName>
    <description>Field on quote object used for testing this condition.</description>
    <inlineHelpText>Field on quote object used for testing this condition.</inlineHelpText>
    <label>Tested Field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account_country__c</fullName>
            </value>
            <value>
                <fullName>Account_Type__c</fullName>
            </value>
            <value>
                <fullName>Advanced_Flow_Products__c</fullName>
            </value>
            <value>
                <fullName>Advanced_Intake_Products__c</fullName>
            </value>
            <value>
                <fullName>after_hours_work_price_for_quote_terms__c</fullName>
            </value>
            <value>
                <fullName>Agree_to_Press_Release__c</fullName>
            </value>
            <value>
                <fullName>Cancellation_terms__c</fullName>
            </value>
            <value>
                <fullName>Conflicts_Products__c</fullName>
            </value>
            <value>
                <fullName>Contains_CR_01539__c</fullName>
            </value>
            <value>
                <fullName>Contract_Master_Terms__c</fullName>
            </value>
            <value>
                <fullName>Contract_Term_Version__c</fullName>
            </value>
            <value>
                <fullName>Contract_Type__c</fullName>
            </value>
            <value>
                <fullName>CurrencyIsoCode</fullName>
            </value>
            <value>
                <fullName>Customer_owns_Integrate__c</fullName>
            </value>
            <value>
                <fullName>Customer Amount</fullName>
            </value>
            <value>
                <fullName>D_B__c</fullName>
            </value>
            <value>
                <fullName>Engagement_Letter_Products__c</fullName>
            </value>
            <value>
                <fullName>Exclude_Product_Specific_Language__c</fullName>
            </value>
            <value>
                <fullName>Experience_Products__c</fullName>
            </value>
            <value>
                <fullName>Extended_Initial_Term__c</fullName>
            </value>
            <value>
                <fullName>First_Segment_Months__c</fullName>
            </value>
            <value>
                <fullName>Flow_Enterprise_Products__c</fullName>
            </value>
            <value>
                <fullName>Include_Master_Term_Tax_Language__c</fullName>
            </value>
            <value>
                <fullName>Initial_Term_Discount__c</fullName>
            </value>
            <value>
                <fullName>Intake_Products__c</fullName>
            </value>
            <value>
                <fullName>Legacy_Relationships_Products__c</fullName>
            </value>
            <value>
                <fullName>License_Basis__c</fullName>
            </value>
            <value>
                <fullName>Line_of_Business__c</fullName>
            </value>
            <value>
                <fullName>List Amount</fullName>
            </value>
            <value>
                <fullName>master_product_pins_from_all_quote_lines__c</fullName>
            </value>
            <value>
                <fullName>SBQQ__ProductCode__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EvaluateTermCondition.cls
public without sharing class EvaluateTermCondition {
    private SBQQ__TermCondition__c termCondition;
    public SBQQ__Quote__c quote;
    public Set<String> productCodes;
    public Boolean result { get; set; }
    public Boolean isEvaluated {private set;}

    public EvaluateTermCondition(SBQQ__TermCondition__c termCondition, SBQQ__Quote__c quote, Set<String> productCodes) {
        this.termCondition = termCondition;
        this.quote = quote;
        this.productCodes = productCodes;
        this.isEvaluated = false;
    }

    public void evaluate() {
        // Logic to evaluate a single condition and then set result to true or false and isEvaluated to true
        
        if(!termCondition.SBQQ__TestedField__c.equalsIgnoreCase('SBQQ__ProductCode__c')) { 
        	String valueToTest = String.valueOf(getValueToTest());
        switch on termCondition.SBQQ__Operator__c {
            when 'equals' {
                result = evaluateEqualTo(valueToTest, String.valueOf(termCondition.SBQQ__Value__c));
            }
            when 'not equals' {
                result = evaluateNotEqualTo(valueToTest, String.valueOf(termCondition.SBQQ__Value__c));
            }
            when 'greater than' {
                try {
                    result = evaluateGreaterThan(Decimal.valueOf(valueToTest), Decimal.valueOf(termCondition.SBQQ__Value__c));
                } catch(Exception e) {
                    result = false;
                }
            }
            when 'greater or equals' {
                try {
                    result = evaluateGreaterThanOrEqualtTo(Decimal.valueOf(valueToTest), Decimal.valueOf(termCondition.SBQQ__Value__c));
                } catch(Exception e) {
                    result = false;
                }
            }
            when 'less than' {
                try {
                    result = evaluateLessThan(Decimal.valueOf(valueToTest), Decimal.valueOf(termCondition.SBQQ__Value__c));
                } catch(Exception e) {
                    result = false;
                }
            }
            when 'less or equals' {
                try {
                    result = evaluateLessThanOrEqualtTo(Decimal.valueOf(valueToTest), Decimal.valueOf(termCondition.SBQQ__Value__c));
                } catch(Exception e) {
                    result = false;
                }
            }
            when 'starts with' {
                //result = evaluateIsBlank(valueToTest);
            }
            when 'ends with' {
                //result = evaluateIsNotBlank(valueToTest);
            }
            when 'contains' {
                result = evaluateContains(valueToTest, String.valueOf(termCondition.SBQQ__Value__c));
            }
            when 'does not contain' {
                result = !(evaluateContains(valueToTest, String.valueOf(termCondition.SBQQ__Value__c)));
            }
        }
        } else {
            switch on termCondition.SBQQ__Operator__c {
            when 'contains' {
            	result = productCodes.contains(String.valueOf(termCondition.SBQQ__Value__c));
            }
                when 'does not contain' {
                result = !(productCodes.contains(String.valueOf(termCondition.SBQQ__Value__c)));
            }
            }
        }
        this.isEvaluated = true;
    }

    /*
     * Private methods
     */

    private Object getValueToTest() {
        
        String testedObject = 'SBQQ__Quote__c';
        String testedField = termCondition.SBQQ__TestedField__c; 
        Object valueToTest;
        switch on testedObject {
            when 'SBQQ__Quote__c' {               
                valueToTest = quote.get(testedField);
            }
        }
        return valueToTest;
    }

    private Boolean evaluateEqualTo(String fieldValue, String value) {
        return fieldValue == value;
    }

    private Boolean evaluateNotEqualTo(String fieldValue, String value) {
        return fieldValue != value;
    }

    private Boolean evaluateGreaterThan(Decimal fieldValue, Decimal value) {
        return fieldValue > value;
    }

    private Boolean evaluateGreaterThanOrEqualtTo(Decimal fieldValue, Decimal value) {
        return fieldValue >= value;
    }

    private Boolean evaluateLessThan(Decimal fieldValue, Decimal value) {
        return fieldValue < value;
    }

    private Boolean evaluateLessThanOrEqualtTo(Decimal fieldValue, Decimal value) {
        return fieldValue <= value;
    }

    private Boolean evaluateIsBlank(String fieldValue) {
        return String.isBlank(fieldValue);
    }

    private Boolean evaluateIsNotBlank(String fieldValue) {
        return String.isNotBlank(fieldValue);
    }

    private Boolean evaluateContains(String fieldValue, String value) {
        if(String.isNotBlank(fieldValue)) {
            return fieldValue.contains(value);
        }
        else {
        	return false;
        }
    }

    /*private Boolean evaluateIsChanged(String newFieldValue, String oldFieldValue) {
        return newFieldValue != oldFieldValue;
    }*/
}