force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>Custom Field created according to User story BIZ-45119.</description>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquired_Contract</fullName>
        <label>Acquired Contract</label>
    </customValue>
    <customValue>
        <fullName>Add-On</fullName>
        <label>Add-On Amendment</label>
    </customValue>
    <customValue>
        <fullName>Cancellation</fullName>
    </customValue>
    <customValue>
        <fullName>Contract_Replacement</fullName>
        <label>Contract Replacement</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
    </customValue>
    <customValue>
        <fullName>New_Software</fullName>
        <label>New Software</label>
    </customValue>
    <customValue>
        <fullName>NextYear_MultiYear</fullName>
        <label>Next Year, Multi-Year</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PlatformConversion_INTERNAL</fullName>
        <label>Platform Conversion - Internal</label>
    </customValue>
    <customValue>
        <fullName>Platform_Fee</fullName>
        <label>Platform Fee</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Services_Only</fullName>
        <label>Services Only</label>
    </customValue>
    <customValue>
        <fullName>Services_Replacement</fullName>
        <label>Services Replacement</label>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
    </customValue>
    <description>Modified as part of BIZ-46501</description>
    <masterLabel>Deal Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/SingleQuoteSingleDealControllerTest.cls
/**
 * @description       : Test class for SingleQuoteSingleDealController
 * @author            : Keerthan N
 * Jira story : BIZ-45097,BIZ-46504
**/
@isTest
public class SingleQuoteSingleDealControllerTest {
    
    @testSetup
    public static void setup(){
        List<Account> accList = TestDataFactory.createAccount(1,True);
    }
    
    @istest
    private static void checkAndCreateQuoteTest(){
        List<Account> accList = [Select Id,Name From Account Limit 1];
        Test.startTest();
        SingleQuoteSingleDealController.checkAndCreateQuote('deal123',accList[0].Id,'New_Software','USD','Y');
        SingleQuoteSingleDealController.checkAndCreateQuote('deal123',accList[0].Id,'New_Software','USD','Y');
        SingleQuoteSingleDealController.checkAndCreateQuote('test123','deal123','New_Software','USD','Y');
        Test.stopTest();
        List<Opportunity> oppList = [Select Id,Name From Opportunity Limit 1];
        List<SBQQ__Quote__c> quoteList = [Select Id,Name From SBQQ__Quote__c Limit 1];
        Assert.isTrue(quoteList.size() > 0, 'Quote Inserted');
    }
    @istest
    private static void checkAndCreateQuoteUpdateTest(){
        List<Account> accList = [Select Id,Name From Account Limit 1];
        Test.startTest();
        SingleQuoteSingleDealController.checkAndCreateQuote('deal123',accList[0].Id,'New_Software','','N');
        SingleQuoteSingleDealController.checkAndCreateQuote('deal123',accList[0].Id,'Renewal','','N');
        Test.stopTest();
        List<SBQQ__Quote__c> quoteList = [Select Id,Name, Deal_Type__c From SBQQ__Quote__c Limit 1];
        Assert.isTrue(quoteList.size() > 0, 'Quote Inserted');
        Assert.areEqual('Renewal', quoteList[0].Deal_Type__c);
    }
}