force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Submission</fullName>
                <default>true</default>
                <label>Pending Submission</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignDefaultApproversController.cls
public class AssignDefaultApproversController {
    String contractId;
    public boolean isError {get; set;}
    //public Flow.Interview.Contract_Approvers_Assignment_Flow flow;
    private final String APPROVAL_STATUS_PENDING = 'Pending';
    private final String APPROVAL_STATUS_APPROVED = 'Approved';
    
    ApexPages.StandardController standardController;

    public AssignDefaultApproversController(ApexPages.StandardController standardController){
        this.standardController = standardController;
        contractId = ApexPages.currentPage().getParameters().get('id');
        isError = false;
    }
    
    public PageReference doProcessContractDefaultApprovers(){
        
        try{
            Contract contract = [SELECT Id
                                 , Approval_Status__c
                                 , SBQQ__Quote__r.ApprovalStatus__c 
                                FROM Contract
                                WHERE Id = :contractId LIMIT 1];
            
            if(contract.SBQQ__Quote__c == null 
               || (contract.SBQQ__Quote__r.ApprovalStatus__c != APPROVAL_STATUS_APPROVED 
                  && contract.SBQQ__Quote__r.ApprovalStatus__c != APPROVAL_STATUS_PENDING)){
                isError = true;
                String errorMsg = System.Label.Error_on_Contract_Assigned;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, errorMsg));
            }
            else if(contract.Approval_Status__c == APPROVAL_STATUS_PENDING){
                isError = true;
                String errorMsg1 = System.Label.Error_on_Approval_Status;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, errorMsg1));
            }
            else{
                map<String, String> recordMap = new map<String, String>();
                recordMap.put('recordId', contractId);
                // flow = new Flow.Interview.Contract_Approvers_Assignment_Flow(recordMap);
                // flow.start();
                PageReference pageref = new PageReference('/'+contractId);
                pageref.setRedirect(true);
                return pageref;
            }
            
            return null;
        }
        catch(Exception ex){
            isError = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, ex.getMessage() ));
        }
        return null;
    }
    
    public PageReference goBack(){
        PageReference pageref = new PageReference('/'+contractId);
        pageref.setRedirect(true);
        return pageref;
    }
}