force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Submission</fullName>
                <default>true</default>
                <label>Pending Submission</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/COO__c.field-meta.xml
<CustomField>
    <fullName>COO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>COO</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <inlineHelpText>&apos;First invoice period (number of months)</inlineHelpText>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Industry_President__c.field-meta.xml
<CustomField>
    <fullName>Industry_President__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry President</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Industry_Sales_Lead__c.field-meta.xml
<CustomField>
    <fullName>Industry_Sales_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry Sales Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Sales_Segment__c</fullName>
    <description>Holds the Sales Segment Values from OP4I Deal</description>
    <label>OP4I Sales Segment</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__FirstSegmentTermEndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__FirstSegmentTermEndDate__c</fullName>
    <description>Used with multi-segment Products to prorate first segment.</description>
    <inlineHelpText>For multi-segment Products, enter the end date in order to prorate first segment.</inlineHelpText>
    <label>First Segment Term End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Segment_Lead__c.field-meta.xml
<CustomField>
    <fullName>Segment_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Services_Segment_Lead__c.field-meta.xml
<CustomField>
    <fullName>Services_Segment_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Services Segment Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SVP_Sales__c.field-meta.xml
<CustomField>
    <fullName>SVP_Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP Sales</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SVP_Services__c.field-meta.xml
<CustomField>
    <fullName>SVP_Services__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP Services</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandler.cls
public class QuoteTriggerHandler {
    
   public static void processRecordsBeforeInsert(List<SBQQ__Quote__c> quotes){

            Set<String> salesSegments = new Set<String>();
        for(SBQQ__Quote__c quote : quotes){
            salesSegments.add(quote.OP4I_Sales_Segment__c);    
        }
        
        Map<String, ApproverUsers> approverUsersMap = ApproverMatrixService.getApproverUsers(salesSegments) ;
        
        for(SBQQ__Quote__c quote : quotes){
        
        /** Changes BIZ-723 : Start **/             
             // Added to Set "First Segment Term End Date" -sun
             /*MDQIssueCommenting
             if (quote.First_Segment_Months__c != null && quote.SBQQ__StartDate__c != null){
                 quote.SBQQ__FirstSegmentTermEndDate__c = quote.SBQQ__StartDate__c.addMonths(Integer.valueOf(quote.First_Segment_Months__c))-1 ;
             } */   
       /**Changes BIZ-723 : End **/
            
            if(approverUsersMap.Containskey(quote.OP4I_Sales_Segment__c)){                
            
            ApproverUsers approverUsers = approverUsersMap.get(quote.OP4I_Sales_Segment__c);
            quote.COO__c = approverUsers.COO;
            quote.SVP_Services__c = approverUsers.SVP_Services;
            quote.Segment_Lead__c = approverUsers.Segment_Lead;
            quote.Industry_Sales_Lead__c = approverUsers.Industry_Sales_Lead;
            quote.SVP_Sales__c = approverUsers.SVP_Sales;
            quote.Industry_President__c = approverUsers.Industry_President;
            quote.Services_Segment_Lead__c = approverUsers.Services_Segment_Lead;
            }
        }
        
 }

    public static void processRecordsBeforeUpdate(Map<Id, SBQQ__Quote__c> oldQuotesMap, Map<Id, SBQQ__Quote__c> newQuotesMap){
        
        /** Changes BIZ-723 : Start **/
        /*MDQIssueCommenting     
        for(SBQQ__Quote__c quote : newQuotesMap.values()){
             // Added to Set "First Segment Term End Date" -sun
            SBQQ__Quote__c quoteOld = oldQuotesMap.get(quote.Id);
             if (quote.First_Segment_Months__c != null && quote.SBQQ__StartDate__c != null && 
                 (quote.First_Segment_Months__c != quoteOld.First_Segment_Months__c  || quote.SBQQ__StartDate__c  != quoteOld.SBQQ__StartDate__c)
             ){
                     quote.SBQQ__FirstSegmentTermEndDate__c = quote.SBQQ__StartDate__c.addMonths(Integer.valueOf(quote.First_Segment_Months__c))-1 ;
             }           
            
        }*/    
        /** Changes BIZ-723 : End **/   
        // Set of all the sales segments which got changed.
        Set<String> salesSegments = new Set<String>();
        
        // Re-assign approvers only to only quotes where sales segment changed.
        List<Id> quoteIdsToBeProcessed = new List<Id>();

        Generic_Key_Value_Setting__mdt approvalErrorMaxRetrySetting = Generic_Key_Value_Setting__mdt.getInstance('Approval_Error_Max_Retry');
        Integer approvalErrorMaxRetry = Integer.valueOf(approvalErrorMaxRetrySetting.Value__c);
                    
        
        // Loop through all the new quotes and get the set of sales segment and 
        // the quotes to be processed 
        for(Id quoteId : newQuotesMap.keySet()){
            System.debug ('Logging status ' + oldQuotesMap.get(quoteId).ApprovalStatus__c + ' Newstatus ' + newQuotesMap.get(quoteId).ApprovalStatus__c + ' counter '+newQuotesMap.get(quoteId).Counter__c );

            if(oldQuotesMap.get(quoteId).ApprovalStatus__c == 'Error'
                && newQuotesMap.get(quoteId).ApprovalStatus__c == 'Pending'
                && newQuotesMap.get(quoteId).Counter__c >= approvalErrorMaxRetry){
                    SBQQ__Quote__c quote = newQuotesMap.get(quoteId);
                    quote.Counter__c = 0;
                }

            if(oldQuotesMap.get(quoteId).OP4I_Sales_Segment__c 
                != newQuotesMap.get(quoteId).OP4I_Sales_Segment__c){
                    salesSegments.add(newQuotesMap.get(quoteId).OP4I_Sales_Segment__c);
                    quoteIdsToBeProcessed.add(quoteId);
                }
        }
        
        // get the map of sales segment and the related approvers
        Map<String, ApproverUsers> approverUsersMap = ApproverMatrixService.getApproverUsers(salesSegments) ;
        
        // Loop through all the quotes to be processed.
        // Get the new quote from the map.
        // Assign the value from the 'sales segment to approvers map'.
        for(Id quoteId : quoteIdsToBeProcessed){
            SBQQ__Quote__c quote = newQuotesMap.get(quoteId);
            ApproverUsers approverUsers = approverUsersMap.get(quote.OP4I_Sales_Segment__c);
            
            if(approverUsers != null) {
            quote.COO__c = approverUsers.COO;
            quote.SVP_Services__c = approverUsers.SVP_Services;
            quote.Segment_Lead__c = approverUsers.Segment_Lead;
            quote.Industry_Sales_Lead__c = approverUsers.Industry_Sales_Lead;
            quote.SVP_Sales__c = approverUsers.SVP_Sales;
            quote.Industry_President__c = approverUsers.Industry_President;
            quote.Services_Segment_Lead__c = approverUsers.Services_Segment_Lead;  
            }
        }
    } 

    public Static void quoteAfterInsert(list<SBQQ__Quote__c> quoteNewList) {
        IntegrationUtility.publishEligibleSobjectRecords(quoteNewList,null,'SBQQ__Quote__c');
    }
    
    public Static void quoteAfterUpdate(list<SBQQ__Quote__c> quoteNewList,Map<Id,SBQQ__Quote__c> quoteOldMap) {
        IntegrationUtility.publishEligibleSobjectRecords(quoteNewList,quoteOldMap,'SBQQ__Quote__c');
    }
    
    
    
}