force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Extended_Initial_Term__c.field-meta.xml
<CustomField>
    <fullName>Extended_Initial_Term__c</fullName>
    <formula>IF(SBQQ__SubscriptionTerm__c&gt;12,TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Extended Initial Term?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Bundle_Products__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Products__c</fullName>
    <label>Bundle Products</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Bundle_Products_Extn2__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Products_Extn2__c</fullName>
    <label>Bundle Products Extn2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Bundle_Products_Extn3__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Products_Extn3__c</fullName>
    <label>Bundle Products Extn3</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Customer_Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Customer_Grand_Total__c</fullName>
    <label>Customer Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Extended_Initial_Term__c.field-meta.xml
<CustomField>
    <fullName>Extended_Initial_Term__c</fullName>
    <formula>SBQQ__Quote__r.Extended_Initial_Term__c</formula>
    <label>Extended Initial Term</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Is_Bundle_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_Bundle_Product__c</fullName>
    <formula>SBQQ__Product__r.Bundle_product__c 
/*

IF(ISBLANK(SBQQ__RequiredBy__c) &amp;&amp;
  or(
 Product_Group__c=&quot;Solutions &amp; Bundles&quot;,
 SBQQ__ProductCode__c = &quot;BU-01408&quot;
 ),
TRUE, FALSE)
*/
/*
IF(ISBLANK(SBQQ__RequiredBy__c) &amp;&amp;
License_Product__c=FALSE &amp;&amp; Product_Group__c=&quot;Solutions &amp; Bundles&quot;,
TRUE, FALSE)
*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Bundle Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Monthly_Net_Price_Currency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Net_Price_Currency__c</fullName>
    <description>Used to map value from Quote Line to Opportunity Product</description>
    <formula>List_Price_Text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/OSA_List_Price__c.field-meta.xml
<CustomField>
    <fullName>OSA_List_Price__c</fullName>
    <label>OSA List Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Parent_of_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Parent_of_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicator field for Parent Static and Select Bundle, created as per BIZ-48496</description>
    <label>Parent of Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Print_at_Quote__c.field-meta.xml
<CustomField>
    <fullName>Print_at_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Print at Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Services Discount</fullName>
            </value>
            <value>
                <fullName>Software Discount (One-Time)</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
    <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SegmentIndex__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SegmentIndex__c</fullName>
    <description>For multi-segmented Products, Index representing this Quote Line&apos;s position in the segment table.</description>
    <inlineHelpText>For multi-segmented Products, Index representing this Quote Line&apos;s position in the segment table.</inlineHelpText>
    <label>Segment Index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SegmentIndex_Year__c.field-meta.xml
<CustomField>
    <fullName>SegmentIndex_Year__c</fullName>
    <formula>IF( (SBQQ__Quote__r.SegmentIndex_Max_Value__c=0 || (SBQQ__Quote__r.SegmentIndex_Max_Value__c&gt;0 &amp;&amp; SBQQ__RequiredBy__c = NULL ) || SBQQ__RequiredBy__c != NULL) &amp;&amp; SBQQ__SegmentIndex__c == 0, 1, SBQQ__SegmentIndex__c )

/*
IF( (SBQQ__Quote__r.Extended_Initial_Term__c = FALSE || (SBQQ__Quote__r.Extended_Initial_Term__c = TRUE  &amp;&amp; SBQQ__RequiredBy__c = NULL ) ||  SBQQ__RequiredBy__c != NULL) &amp;&amp; SBQQ__SegmentIndex__c == 0,  1,  SBQQ__SegmentIndex__c   )

*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SegmentIndex (Year)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Skip_OP4I_Sync__c.field-meta.xml
<CustomField>
    <fullName>Skip_OP4I_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To bypass integration for static bundle child products;BIZ-49254</description>
    <label>Skip OP4I Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuoteLineTriggerHandler.cls
public class QuoteLineTriggerHandler {
    
    public Static void quoteLineAfterInsert(list<SBQQ__QuoteLine__c> credNewList) {
        IntegrationUtility.publishEligibleSobjectRecords(credNewList,null,'SBQQ__QuoteLine__c');
    }
    
    public Static void quoteLineAfterUpdate(list<SBQQ__QuoteLine__c> credNewList,Map<Id,SBQQ__QuoteLine__c> credOldMap) {
        
        IntegrationUtility.publishEligibleSobjectRecords(credNewList,credOldMap,'SBQQ__QuoteLine__c');
    }
    
    public Static void quoteLineAfterDelete(Map<Id,SBQQ__QuoteLine__c> credOldMap){
        set<string> sbqqRequiredByLst = new set<string>();
    	set<string> sbqqQuoteLst = new set<string>(); 
    	set<string> sbqqRequiredByNameLst = new set<string>();
    	list<SBQQ__QuoteLine__c> quoteLineLst =  new list<SBQQ__QuoteLine__c>();
    	map<Id,SBQQ__Quote__c> mapOfQuote = new map<Id,SBQQ__Quote__c>();
        
        for(SBQQ__QuoteLine__c quoteLine : credOldMap.values()){
            if(quoteLine.SBQQ__RequiredBy__c != null && !quoteLine.Is_Bundle_Product__c){
               sbqqRequiredByLst.add(quoteLine.SBQQ__RequiredBy__c);
               sbqqQuoteLst.add(quoteLine.SBQQ__Quote__c);
            }
        }
        if(sbqqRequiredByLst.size()>0){ 
        mapOfQuote = new map<Id,SBQQ__Quote__c>([SELECT Id,Name,Extended_Initial_Term__c FROM SBQQ__Quote__c where Id IN: sbqqQuoteLst]);
        quoteLineLst = [SELECT SBQQ__CustomerTotal__c, Customer_Grand_Total__c, SBQQ__Discount__c, Bundle_Products__c, Bundle_Products_Extn2__c, Bundle_Products_Extn3__c, Is_Bundle_Product__c,Id,Monthly_Unit_Price__c,Monthly_Net_Price_Currency__c,Name,Product_Type__c,SBQQ__EndDate__c,SBQQ__ListPrice__c,SBQQ__Product__c, SBQQ__Product__r.ProductCode, SBQQ__Product__r.Name,Item_Master_Name__c,SBQQ__Quantity__c,SBQQ__Quote__c,SBQQ__Quote__r.Extended_Initial_Term__c,SBQQ__SegmentIndex__c,SegmentIndex_Year__c, SBQQ__StartDate__c, Quote_Segment__c, SBQQ__RequiredBy__c, Print_at_Quote__c, OSA_List_Price__c, SBQQ__ListTotal__c,Monthly_Unit_List_Price__c,Total_List_Price__c    FROM SBQQ__QuoteLine__c where SBQQ__RequiredBy__c IN:SBQQRequiredByLst OR ID IN:sbqqRequiredByLst];
    } 
    	if(quoteLineLst.size()>0){
        QuoteLineItemHandler.updateQuoteLine(quoteLineLst, mapOfQuote); 
    	}
    }
    public static void avoidReoccuranceUpdateMethod(list<SBQQ__QuoteLine__c> credNewList,Map<Id,SBQQ__QuoteLine__c> credOldMap){
        boolean processRecords = false;
        set<string> sbqqRequiredByLst = new set<string>();
    	set<string> sbqqRequiredByNameLst = new set<string>();
    	set<string> sbqqQuoteLst = new set<string>();
        list<SBQQ__QuoteLine__c> quoteLineRecList =  new list<SBQQ__QuoteLine__c>();
    	list<SBQQ__QuoteLine__c> quoteLineLst =  new list<SBQQ__QuoteLine__c>();
    	map<Id,SBQQ__Quote__c> mapOfQuote = new map<Id,SBQQ__Quote__c>();
        
        for(SBQQ__QuoteLine__c quoteLine : quoteLineRecList){
           if(!QuoteLineItemHandler.processedRecordSet.contains(quoteLine.Id)){
              QuoteLineItemHandler.processedRecordSet.add(quoteLine.Id);
              quoteLineRecList.add(quoteLine);
              processRecords = true;
           }else{
             processRecords = false;
           }
       }
       if(processRecords==true){
            for(SBQQ__QuoteLine__c quoteLine : quoteLineRecList){
            if(quoteLine.SBQQ__RequiredBy__c != null && ! quoteLine.Is_Bundle_Product__c &&
               !quoteLine.Parent_of_Bundle__c && !quoteLine.Skip_OP4I_Sync__c){
                sbqqRequiredByLst.add(quoteLine.SBQQ__RequiredBy__c);
                sbqqQuoteLst.add(quoteLine.SBQQ__Quote__c);
            }
         }   
       }
        if(sbqqRequiredByLst.size()>0){ 
        mapOfQuote = new map<Id,SBQQ__Quote__c>([SELECT Id,Name,Extended_Initial_Term__c FROM SBQQ__Quote__c where Id IN: sbqqQuoteLst]);
        quoteLineLst = [SELECT SBQQ__CustomerTotal__c, Customer_Grand_Total__c, SBQQ__Discount__c, Bundle_Products__c, Bundle_Products_Extn2__c, Bundle_Products_Extn3__c, Is_Bundle_Product__c,Id,Monthly_Unit_Price__c,Monthly_Net_Price_Currency__c,Name,Product_Type__c,SBQQ__EndDate__c,SBQQ__ListPrice__c,SBQQ__Product__c, SBQQ__Product__r.ProductCode, SBQQ__Product__r.Name,Item_Master_Name__c,SBQQ__Quantity__c,SBQQ__Quote__c,SBQQ__Quote__r.Extended_Initial_Term__c,SBQQ__SegmentIndex__c,SegmentIndex_Year__c, SBQQ__StartDate__c, Quote_Segment__c, SBQQ__RequiredBy__c, Print_at_Quote__c, OSA_List_Price__c, SBQQ__ListTotal__c,Monthly_Unit_List_Price__c,Total_List_Price__c    FROM SBQQ__QuoteLine__c where SBQQ__RequiredBy__c IN:SBQQRequiredByLst OR ID IN:sbqqRequiredByLst];
    } 
    	if(quoteLineLst.size()>0){
        QuoteLineItemHandler.updateQuoteLine(quoteLineLst, mapOfQuote); 
    	}
    }
    public static void avoidReoccuranceInsertMethod(list<SBQQ__QuoteLine__c> credNewList){
        list<decimal> segmentLst = new list<decimal>();
    	set<string> sbqqRequiredByLst = new set<string>();
    	set<string> sbqqRequiredByNameLst = new set<string>();
    	set<string> sbqqQuoteLst = new set<string>();
        list<SBQQ__QuoteLine__c> quoteLineRecList =  new list<SBQQ__QuoteLine__c>();
    	list<SBQQ__QuoteLine__c> quoteLineLst =  new list<SBQQ__QuoteLine__c>();
    	map<Id,SBQQ__Quote__c> mapOfQuote = new map<Id,SBQQ__Quote__c>();
        for(SBQQ__QuoteLine__c quoteLine : quoteLineRecList){
        
            if(quoteLine.SBQQ__RequiredBy__c != null && ! quoteLine.Is_Bundle_Product__c 
              && !quoteLine.Parent_of_Bundle__c && !quoteLine.Skip_OP4I_Sync__c){
                sbqqRequiredByLst.add(quoteLine.SBQQ__RequiredBy__c);
                sbqqQuoteLst.add(quoteLine.SBQQ__Quote__c);
            }             
        }
        if(sbqqRequiredByLst.size()>0){ 
        mapOfQuote = new map<Id,SBQQ__Quote__c>([SELECT Id,Name,Extended_Initial_Term__c FROM SBQQ__Quote__c where Id IN: sbqqQuoteLst]);
        quoteLineLst = [SELECT SBQQ__CustomerTotal__c, Customer_Grand_Total__c, SBQQ__Discount__c, Bundle_Products__c, Bundle_Products_Extn2__c, Bundle_Products_Extn3__c, Is_Bundle_Product__c,Id,Monthly_Unit_Price__c,Monthly_Net_Price_Currency__c,Name,Product_Type__c,SBQQ__EndDate__c,SBQQ__ListPrice__c,SBQQ__Product__c, SBQQ__Product__r.ProductCode, SBQQ__Product__r.Name,Item_Master_Name__c,SBQQ__Quantity__c,SBQQ__Quote__c,SBQQ__Quote__r.Extended_Initial_Term__c,SBQQ__SegmentIndex__c,SegmentIndex_Year__c, SBQQ__StartDate__c, Quote_Segment__c, SBQQ__RequiredBy__c, Print_at_Quote__c, OSA_List_Price__c, SBQQ__ListTotal__c,Monthly_Unit_List_Price__c,Total_List_Price__c    FROM SBQQ__QuoteLine__c where SBQQ__RequiredBy__c IN:SBQQRequiredByLst OR ID IN:sbqqRequiredByLst];
    	} 
    	if(quoteLineLst.size()>0){
       QuoteLineItemHandler.updateQuoteLine(quoteLineLst, mapOfQuote); 
    	}
    }
}