force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Status__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Status__c</fullName>
    <defaultValue>&quot;Not Synced&quot;</defaultValue>
    <label>OP4I Status</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Stage__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stage__c</fullName>
    <description>Sales user should be able to move a Quote to the Pricing Proposal stage when ready to create a Pricing Proposal Document, built as per BIZ-45102
Updated for story BIZ-49730..</description>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Configure Products</fullName>
                <default>true</default>
                <label>Configure Products</label>
            </value>
            <value>
                <fullName>Pricing Proposal</fullName>
            </value>
            <value>
                <fullName>Finalize OSA</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Contract Executed</fullName>
            </value>
            <value>
                <fullName>Closed-Lost</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Forecast</fullName>
                <isActive>false</isActive>
                <label>Forecast</label>
            </value>
            <value>
                <fullName>OSA</fullName>
                <isActive>false</isActive>
                <label>OSA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteSaveAndForecastController.cls
/**
 * @description       : Controller class for QuoteSaveAndForecast LWC Component
 * @author            : Keerthan N
 * Jira story : BIZ-45100
**/
public without sharing class QuoteSaveAndForecastController {

    //Method to update Quote Stage. Created as part of BIZ-45100.
    @AuraEnabled
    public static String updateQuote(String recordId){
            try{
                String draft = System.Label.Draft;
                List<SBQQ__Quote__c> quoteList = [Select Id,SBQQ__LineItemCount__c,Quote_Stage__c,OP4I_Status__c From SBQQ__Quote__c Where Id =: recordId And Quote_Stage__c=:draft And  SBQQ__LineItemCount__c > 0 Limit 1];
                if(quoteList.size() > 0 &&  !quoteList[0].Quote_Stage__c.equalsIgnoreCase(System.Label.Configure_Products)){
                    SBQQ__Quote__c quoteRec = quoteList[0];
                    quoteRec.Quote_Stage__c = System.Label.Configure_Products;
                    quoteRec.OP4I_Status__c = 'Request Submitted';
                    update quoteRec;  
                    return 'success';
                }
                return 'no_update';
            }
            catch(Exception e){
                //System.debug('Exception :'+e);
                return 'error';
            }
    }
}