force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4IDealID__c.field-meta.xml
<CustomField>
    <fullName>OP4IDealID__c</fullName>
    <description>This is a reference ID of Deal ID</description>
    <externalId>true</externalId>
    <label>OP4I Deal ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OP4IQuoteControllerV2Test.cls
@isTest
public class OP4IQuoteControllerV2Test {
    @isTest
    private static void accountIdTest() {
        Account account = new Account();
        account.Name = 'Test Account';
        insert account;
        ApexPages.currentPage().getParameters().put('accid',account.Id);
        ApexPages.currentPage().getParameters().put('dealId','1234');
        Test.startTest();
        OP4IQuoteControllerV2 controller = new OP4IQuoteControllerV2();
        Pagereference page = controller.initialize();
        
        Opportunity opportunity = [Select id from Opportunity];
        ApexPages.currentPage().getParameters().put('oppid',opportunity.Id);
        page = controller.initialize();
        Test.stopTest();
        system.assertEquals(true, opportunity.Id != null);
	}
    
    @isTest
    private static void oppidTest() {
        Account account = new Account();
        account.Name = 'Test Account';
        insert account;
        Opportunity opportunity = new Opportunity();
        opportunity.accountId = account.Id;
        opportunity.name = account.Name;
        opportunity.closeDate = date.today().toStartOfMonth().addMonths(1).addDays(-1);
        opportunity.stageName = 'Qualify';
        insert opportunity;
        ApexPages.currentPage().getParameters().put('dealId','1234');
        ApexPages.currentPage().getParameters().put('oppid',opportunity.Id);
        Test.startTest();
        OP4IQuoteControllerV2 controller = new OP4IQuoteControllerV2();
        Pagereference page = controller.initialize();
        Test.stopTest();
        SBQQ__Quote__c[] quoteList = [
            SELECT Id
                , OP4IDealID__c
                , SBQQ__Opportunity2__c
            FROM SBQQ__Quote__c
        ];
        system.assertEquals(1,quoteList.size());

    }
    
    @isTest
    private static void invalidDealidTest() {
        Account account = new Account();
        account.Name = 'Test Account';
        insert account;
        ApexPages.currentPage().getParameters().put('dealId','1234');
        Test.startTest();
        OP4IQuoteControllerV2 controller = new OP4IQuoteControllerV2();
        Pagereference page = controller.initialize();
        Test.stopTest();
        system.assertEquals('Not able to locate account, please make sure accid is present and its valid...',controller.message);

    }
}