force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteTerm__c/SBQQ__QuoteTerm__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteTermHelp</customHelpPage>
    <description>Legal term printed on quote document.</description>
    <label>Quote Term</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>Term #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__TermCondition__c/fields/SBQQ__Operator__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Operator__c</fullName>
    <description>The operator for this field.</description>
    <inlineHelpText>Choose the operator for the field.</inlineHelpText>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
            </value>
            <value>
                <fullName>not equals</fullName>
            </value>
            <value>
                <fullName>less than</fullName>
            </value>
            <value>
                <fullName>less or equals</fullName>
            </value>
            <value>
                <fullName>greater than</fullName>
            </value>
            <value>
                <fullName>greater or equals</fullName>
            </value>
            <value>
                <fullName>starts with</fullName>
            </value>
            <value>
                <fullName>ends with</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
            <value>
                <fullName>does not contain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__TermCondition__c/fields/SBQQ__TestedField__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__TestedField__c</fullName>
    <description>Field on quote object used for testing this condition.</description>
    <inlineHelpText>Field on quote object used for testing this condition.</inlineHelpText>
    <label>Tested Field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account_country__c</fullName>
            </value>
            <value>
                <fullName>Account_Type__c</fullName>
            </value>
            <value>
                <fullName>Advanced_Flow_Products__c</fullName>
            </value>
            <value>
                <fullName>Advanced_Intake_Products__c</fullName>
            </value>
            <value>
                <fullName>after_hours_work_price_for_quote_terms__c</fullName>
            </value>
            <value>
                <fullName>Agree_to_Press_Release__c</fullName>
            </value>
            <value>
                <fullName>Cancellation_terms__c</fullName>
            </value>
            <value>
                <fullName>Conflicts_Products__c</fullName>
            </value>
            <value>
                <fullName>Contains_CR_01539__c</fullName>
            </value>
            <value>
                <fullName>Contract_Master_Terms__c</fullName>
            </value>
            <value>
                <fullName>Contract_Term_Version__c</fullName>
            </value>
            <value>
                <fullName>Contract_Type__c</fullName>
            </value>
            <value>
                <fullName>CurrencyIsoCode</fullName>
            </value>
            <value>
                <fullName>Customer_owns_Integrate__c</fullName>
            </value>
            <value>
                <fullName>Customer Amount</fullName>
            </value>
            <value>
                <fullName>D_B__c</fullName>
            </value>
            <value>
                <fullName>Engagement_Letter_Products__c</fullName>
            </value>
            <value>
                <fullName>Exclude_Product_Specific_Language__c</fullName>
            </value>
            <value>
                <fullName>Experience_Products__c</fullName>
            </value>
            <value>
                <fullName>Extended_Initial_Term__c</fullName>
            </value>
            <value>
                <fullName>First_Segment_Months__c</fullName>
            </value>
            <value>
                <fullName>Flow_Enterprise_Products__c</fullName>
            </value>
            <value>
                <fullName>Include_Master_Term_Tax_Language__c</fullName>
            </value>
            <value>
                <fullName>Initial_Term_Discount__c</fullName>
            </value>
            <value>
                <fullName>Intake_Products__c</fullName>
            </value>
            <value>
                <fullName>Legacy_Relationships_Products__c</fullName>
            </value>
            <value>
                <fullName>License_Basis__c</fullName>
            </value>
            <value>
                <fullName>Line_of_Business__c</fullName>
            </value>
            <value>
                <fullName>List Amount</fullName>
            </value>
            <value>
                <fullName>master_product_pins_from_all_quote_lines__c</fullName>
            </value>
            <value>
                <fullName>SBQQ__ProductCode__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Term_Quote__c/Term_Quote__c.object-meta.xml
<CustomObject>
    <description>Junction object of SBQQ__Quote__c and SBQQ__QuoteTerm__c usied to generate terms for specific quote</description>
    <label>Term Quote</label>
    <nameField>
        <displayFormat>TQ-{000000}</displayFormat>
        <label>Term Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Term Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Term_Quote__c/fields/Modified__c.field-meta.xml
<CustomField>
    <fullName>Modified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Modified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Term_Quote__c/fields/Print_Order__c.field-meta.xml
<CustomField>
    <fullName>Print_Order__c</fullName>
    <label>Print Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Term_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Term Quotes</relationshipLabel>
    <relationshipName>Term_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Term_Quote__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Term</label>
    <referenceTo>SBQQ__QuoteTerm__c</referenceTo>
    <relationshipLabel>Term Quotes</relationshipLabel>
    <relationshipName>Term_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Term_Quote__c/fields/Validator_Modified__c.field-meta.xml
<CustomField>
    <fullName>Validator_Modified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Developed as a part of story BIZ-49529.This checkbox has been created to identify the term updated by validator.</description>
    <label>Validator Modified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuoteTermValidator.cls
// QuoteTermValidator
public without sharing class QuoteTermValidator {
    @AuraEnabled
    public static String generateQuoteTerms(Id quoteId){
        String message='';
        try {
        if(quoteId != null) {
        Map<Id, SBQQ__QuoteTerm__c> quoteTermMap = getAllQuoteTerms();
        List<String> quoteFields = getQuoteFields(quoteTermMap.values());
        SBQQ__Quote__c quoteDetails = getQuoteDetails(quoteId, quoteFields);
        List<Term_Quote__c> termsToCreate = evaluateTermConditions(quoteTermMap, quoteDetails); 
        System.debug('final termsToCreate'+ termsToCreate);    
        List<Term_Quote__c> existingTermsOnQuote = getExistingTerms(quoteId);
        QuoteTermCreator.consolidateOldAndNew(termsToCreate, existingTermsOnQuote);
        System.debug('termsToCreate><><>'+termsToCreate);
        /*if(!termsToCreate.isEmpty()) {
            insert termsToCreate;
        }*/
            message = 'Quote Terms are generated.';
        }
        } catch(Exception ex) {
            System.debug('Error Occurred: '+ex.getMessage());
        }
        return message;
    }
    
    private static Map<Id, SBQQ__QuoteTerm__c> getAllQuoteTerms() {
        Map<Id, SBQQ__QuoteTerm__c> quoteTermMap = new Map<Id, SBQQ__QuoteTerm__c>([SELECT Id, SBQQ__Body__c, SBQQ__PrintOrder__c, SBQQ__ConditionsMet__c, SBQQ__AdvancedCondition__c,(SELECT Id, SBQQ__Index__c, SBQQ__Operator__c, SBQQ__TestedField__c, SBQQ__TestedVariable__c, SBQQ__Value__c FROM SBQQ__UseConditions__r) FROM SBQQ__QuoteTerm__c WHERE SBQQ__Quote__c = null AND SBQQ__Active__c = true]);
        return quoteTermMap;
    }
    
    private static SBQQ__Quote__c getQuoteDetails(Id quoteId, List<String> quoteFields) {
    	String query = 'SELECT '+String.join(quoteFields, ',')+', (Select Id, SBQQ__ProductCode__c FROM SBQQ__LineItems__r) FROM SBQQ__Quote__c WHERE Id=: quoteId';
        System.debug('query>>>'+query);
        List<SBQQ__Quote__c> quoteList = Database.query(query);
        
        return quoteList[0];
    }
	
    private static List<String> getQuoteFields(List<SBQQ__QuoteTerm__c> terms) {
        List<String> fieldSet = new List<String>();
        Schema.SObjectType targetType = Schema.getGlobalDescribe().get('SBQQ__Quote__c');
		Map<String, Schema.SObjectField> fieldMap = targetType.getDescribe().fields.getMap();
        for (Schema.SObjectField field : fieldMap.values()) {
             fieldSet.add(field.getDescribe().getName());
         }
        /*for(SBQQ__QuoteTerm__c term : terms) {
            for(SBQQ__TermCondition__c condition: term.SBQQ__UseConditions__r) {
                if(!condition.SBQQ__TestedField__c.equalsIgnoreCase('SBQQ__ProductCode__c')) {
                    fieldSet.add(condition.SBQQ__TestedField__c);
                }
            }
        }*/
        return fieldSet;
    }
    
    private static List<Term_Quote__c> evaluateTermConditions(Map<Id, SBQQ__QuoteTerm__c> quoteTermMap, SBQQ__Quote__c quoteDetails) {
        List<Term_Quote__c> termsToCreate = new List<Term_Quote__c>();
        Set<String> productCodes = new Set<String>();
        if(quoteDetails!= null && !quoteDetails.SBQQ__LineItems__r.isEmpty()) {
            System.debug('quoteDetails'+quoteDetails);
            for(SBQQ__QuoteLine__c quoteLine :quoteDetails.SBQQ__LineItems__r) {
                System.debug('quoteLine'+quoteLine);
                productCodes.add(quoteLine.SBQQ__ProductCode__c);
            }
        }
        for(SBQQ__QuoteTerm__c term : quoteTermMap.values()) {
                System.debug('QuoteTermValidator-term'+term);
                System.debug('quoteDetails'+quoteDetails);
                System.debug('productCodes'+productCodes);
                ConditionEvaluator evaluateConditions = new ConditionEvaluator(term, quoteDetails, productCodes);  
                //System.debug('term'+term);
            	Term_Quote__c termquote = evaluateConditions.evaluateConditionsAndInstantiateQuoteTerm();
                System.debug('termquote'+termquote);
            if(termquote!= null) {
                termsToCreate.add(termquote);
                System.debug('if not null termsToCreate->'+termquote);
            }
        }        
        System.debug('termsToCreate--->'+termsToCreate);
        return termsToCreate;
        
    }
    
    private static List<Term_Quote__c> getExistingTerms(Id quoteId) {
        return [SELECT Id, Term__c, Quote__c, Body__c, Print_Order__c,Validator_Modified__c, Modified__c FROM Term_Quote__c WHERE Quote__c =: quoteId];
    }
    
}