force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendAttachmentsWithEmailsTest.cls
/**
 * @description       : Test class for SendAttachmentsWithEmails
 * @author            : Rajani Peddinti
 * Jira story : BIZ-48394
**/
@isTest
public class SendAttachmentsWithEmailsTest {

    @istest
    private static void setControllerValue(){
        
        List<Account> accList = TestDataFactory.createAccount(1,True);
        Id pricebookId = Test.getStandardPricebookId();
        
        List<Opportunity> opp = TestDataFactory.createOppty(1,accList[0].Id,false);
      	insert opp;
        
        List<SBQQ__Quote__c> lstOfQuote = TestDataFactory.createQuote(1,opp[0].Id,false);
        lstOfQuote[0].SBQQ__Account__c = accList[0].Id;
        insert lstOfQuote;
                   
        ContentVersion contentVersion = new ContentVersion(
                    Title          = 'Pricing Proposal',
                    PathOnClient   = 'Pic.jpg',
                    VersionData    = Blob.valueOf('Test Content'),
                    IsMajorVersion = true);
            		insert contentVersion;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        List<ContentDocumentLink> cdoclink1 = TestDataFactory.createContentDocLink(1, String.valueof(lstOfQuote[0].Id), String.valueof(documents[0].Id), false);
      	insert cdoclink1;
                
        Test.startTest();
       	SendAttachmentsWithEmails attachmentEmail = new SendAttachmentsWithEmails();
        attachmentEmail.setControllerValue(lstOfQuote[0].Id);        
        
        attachmentEmail.getControllerValue();
        Test.stopTest();
        System.assertEquals(cdoclink1[0].linkedEntityId, lstOfQuote[0].Id);
        
    }

}