force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/First_Segment_Months__c.field-meta.xml
<CustomField>
    <fullName>First_Segment_Months__c</fullName>
    <inlineHelpText>&apos;First invoice period (number of months)</inlineHelpText>
    <label>First Segment Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4IDealID__c.field-meta.xml
<CustomField>
    <fullName>OP4IDealID__c</fullName>
    <description>This is a reference ID of Deal ID</description>
    <externalId>true</externalId>
    <label>OP4I Deal ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Payment_Term_Software__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Software__c</fullName>
    <formula>IF(ISPICKVAL(Software_Payment_Terms__c, &apos;Other&apos;) , &apos;XXXX&apos;, TEXT(Software_Payment_Terms__c) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Term Software</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Initial license term (in months). By default, this will be populated to 12 months. It can be overwritten by Contract Ops.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OP4IQuoteControllerV2.cls
public with sharing class OP4IQuoteControllerV2 {
    public string message {get;set;}
    
    public OP4IQuoteControllerV2() {
        message = 'Processing your request...';
    }
    

    public PageReference initialize() {
        String dealId  = ApexPages.currentPage().getParameters().get('dealId');
        String accId  = ApexPages.currentPage().getParameters().get('accid');
        String oppId  = ApexPages.currentPage().getParameters().get('oppid');

        system.debug('dealId--->'+dealId);
        
        PageReference quotePage;
        List<SBQQ__Quote__c> quoteList;
        if (string.isNotBlank(dealId)) {
            quoteList = [
                SELECT Id
                    , OP4IDealID__c
                    , SBQQ__Opportunity2__c
                FROM SBQQ__Quote__c
                WHERE OP4IDealID__c = :dealId
            ];
        }
        
        if (quoteList != null && quoteList.size() > 0){
            quotePage = new PageReference('/'+quoteList[0].Id);
        } else {
            //check if opportunity present
            List<Opportunity> opportunityList;
            if (string.isNotBlank(oppId)) {
                opportunityList = [
                    SELECT Id
                            , AccountId
                            , Pricebook2Id
                        FROM Opportunity
                    WHERE Id = :oppId
                ];
            }

            if (opportunityList != null && opportunityList.size() > 0) {
                //create quote;
                string quoteId = createQuote(opportunityList[0],dealId);
                quotePage = new PageReference('/'+quoteId);
            } else {
                //check for account
                List<Account> accountList;
                if (string.isNotBlank(accId)) {
                    accountList = [
                        SELECT Id
                             , Name
                          FROM Account
                         WHERE Id = :accId
                    ];
                }

                if (accountList != null && accountList.size() > 0) {
                    //create opportunity
                    Opportunity opportunity = createOpportunity(accountList[0]);

                    //create quote
                    string quoteId = createQuote(opportunity,dealId);
                    quotePage = new PageReference('/'+quoteId);
                } else {
                    message = 'Not able to locate account, please make sure accid is present and its valid...';
                }

            }
        }

        return quotePage;    
    }

    public static Opportunity createOpportunity(Account account) {
        Opportunity opportunity = new Opportunity();
        opportunity.accountId = account.Id;
        opportunity.name = account.Name;
        opportunity.closeDate = date.today().toStartOfMonth().addMonths(1).addDays(-1);
        opportunity.stageName = 'Qualify';
        insert opportunity;
        return opportunity;
    }

    public static Id createQuote(
        Opportunity opportunity,
        string dealId
    ) {
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        quote.SBQQ__Opportunity2__c = opportunity.Id;
        quote.SBQQ__PriceBook__c = opportunity.Pricebook2Id;
        quote.SBQQ__Account__c = opportunity.AccountId;
        quote.OP4IDealID__c = dealId;
        //quote.SBQQ__SubscriptionTerm__c = string.isNotBlank(term)? Integer.valueOf(term) : 12;
        //quote.First_Segment_Months__c = string.isNotBlank(firstTerm)? Integer.valueOf(firstTerm) : 12;
        //quote.Payment_Term_Software__c = paymentTerm;
        insert quote;
        return quote.Id;
    }
}