force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/OP4I_Status__c.field-meta.xml
<CustomField>
    <fullName>OP4I_Status__c</fullName>
    <defaultValue>&quot;Not Synced&quot;</defaultValue>
    <label>OP4I Status</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Stage__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stage__c</fullName>
    <description>Sales user should be able to move a Quote to the Pricing Proposal stage when ready to create a Pricing Proposal Document, built as per BIZ-45102
Updated for story BIZ-49730..</description>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Configure Products</fullName>
                <default>true</default>
                <label>Configure Products</label>
            </value>
            <value>
                <fullName>Pricing Proposal</fullName>
            </value>
            <value>
                <fullName>Finalize OSA</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Contract Executed</fullName>
            </value>
            <value>
                <fullName>Closed-Lost</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Forecast</fullName>
                <isActive>false</isActive>
                <label>Forecast</label>
            </value>
            <value>
                <fullName>OSA</fullName>
                <isActive>false</isActive>
                <label>OSA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/QuoteSaveAndForecastControllerTest.cls
/**
 * @description       : Test class for QuoteSaveAndForecastController
 * @author            : Kesav Das
 * Jira story : BIZ-45100
**/
@isTest
private class QuoteSaveAndForecastControllerTest {

@testsetup
public static void testsetup(){
    List<Account> createdAccountsList = TestDataFactory.createAccount(1,true);
    List<Opportunity> createOpptyList = TestDataFactory.createOppty(1,createdAccountsList[0].id,true);
    List<SBQQ__Quote__c> createQuoteList = TestDataFactory.createQuote(1,createOpptyList[0].id,true);
    List<Product2> productList = TestDataFactory.createProduct(1,true);
    List<SBQQ__QuoteLine__c> createQuoteLineList = TestDataFactory.createQuoteLine(1,createQuoteList[0].id,productList[0].id,true);
}

@isTest
static void testUpdateQuote() {
    SBQQ__Quote__c testQuote = [SELECT Id, Quote_Stage__c, OP4I_Status__c, SBQQ__LineItemCount__c FROM SBQQ__Quote__c limit 1];
    Test.startTest();
    QuoteSaveAndForecastController.updateQuote(testQuote.Id);
    testQuote.Quote_Stage__c= System.Label.Configure_Products;
    update testQuote;
    QuoteSaveAndForecastController.updateQuote(testQuote.Id);
    Assert.isTrue(testQuote.Quote_Stage__c == System.Label.Configure_Products, 'Quote Updated');
    Test.stopTest();
}

}