force-app/main/default/objects/Intapp_Settings__c/fields/Contact_Role_Validation_Contact_Types__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role_Validation_Contact_Types__c</fullName>
    <description>To add multiple values, use &quot;;&quot; as separator</description>
    <inlineHelpText>To add multiple values, use &quot;;&quot; as separator</inlineHelpText>
    <label>Contact Role Validation - Contact Types</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Intapp_Settings__c/fields/Contact_Role_Validation_Exclude_stages__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role_Validation_Exclude_stages__c</fullName>
    <inlineHelpText>Add values from Proposed stage field on  &quot;Opp&quot; - when the proposed stage is changed from Target Account to any of these stages, the validation would not fire. Add new values separated with a &quot;;&quot;</inlineHelpText>
    <label>Contact Role Validation - Exclude stages</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Intapp_Settings__c/fields/Contact_Role_Validation_Opp_Types__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role_Validation_Opp_Types__c</fullName>
    <description>Add new values with &apos;;&apos; in between</description>
    <inlineHelpText>Add new values with &apos;;&apos; in between</inlineHelpText>
    <label>Contact Role Validation - Opp Types</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Intapp_Settings__c/fields/contact_validation_isactive__c.field-meta.xml
<CustomField>
    <fullName>contact_validation_isactive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Contact Role Validation - Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_in_sync__c.field-meta.xml
<CustomField>
    <fullName>Project_in_sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>TRUE if Project is in sync with Open Air</description>
    <inlineHelpText>TRUE if Project is in sync with Open Air</inlineHelpText>
    <label>Project in sync?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Legal_Cancellation.recordType-meta.xml
<RecordType>
    <fullName>Legal_Cancellation</fullName>
    <active>true</active>
    <businessProcess>Cancellations</businessProcess>
    <description>Use this for cancellations and any negative recurring adjustments</description>
    <label>Legal - Cancellation / Recurring Downgrade</label>
</RecordType>

force-app/main/default/objects/Opportunity_Product_Component__c/Opportunity_Product_Component__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Component</label>
    <nameField>
        <displayFormat>OPC-{0000000}</displayFormat>
        <label>Opportunity Product Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Product Components</relationshipLabel>
    <relationshipName>Opportunity_Product_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Legal - New Customer</fullName>
                <label>New Customer</label>
            </value>
            <value>
                <fullName>Legal - New Product</fullName>
                <label>New Product</label>
            </value>
            <value>
                <fullName>Legal - Add-on module</fullName>
                <label>Add-on module</label>
            </value>
            <value>
                <fullName>Legal - Assessment/POC</fullName>
                <label>Assessment/POC</label>
            </value>
            <value>
                <fullName>Legal - Recurring Adjustment</fullName>
                <label>Recurring Adjustment</label>
            </value>
            <value>
                <fullName>License Conversion - Recurring Increase</fullName>
                <label>Entitlement Conversion - Recurring Increase</label>
            </value>
            <value>
                <fullName>Legal - License Band Uplift</fullName>
                <label>License Band Uplift</label>
            </value>
            <value>
                <fullName>Legal - User Count Uplift</fullName>
                <label>User Count Uplift</label>
            </value>
            <value>
                <fullName>Legal - Acquired New Customer</fullName>
                <label>Acquired New Customer</label>
            </value>
            <value>
                <fullName>Legal - Acquired New Product</fullName>
                <label>Acquired New Product</label>
            </value>
            <value>
                <fullName>Legal - Acquired Add-on Module</fullName>
                <label>Acquired Add-on Module</label>
            </value>
            <value>
                <fullName>Legal - Additional Services</fullName>
                <label>Additional Services</label>
            </value>
            <value>
                <fullName>License Conversion - Recurring Decrease</fullName>
                <label>Entitlement Conversion - Recurring Decrease</label>
            </value>
            <value>
                <fullName>Cancellation - Customer</fullName>
            </value>
            <value>
                <fullName>Cancellation - Product</fullName>
            </value>
            <value>
                <fullName>Cancellation - Module</fullName>
            </value>
            <value>
                <fullName>Cancellation - Recurring Adjustment</fullName>
            </value>
            <value>
                <fullName>Downgrade - Product</fullName>
                <label>Entitlement Downgrade - Product</label>
            </value>
            <value>
                <fullName>Legal - User Count Decrease</fullName>
                <label>User Count Decrease</label>
            </value>
            <value>
                <fullName>Legal - CPI / Recurring Increase</fullName>
                <label>SFA / Recurring Increase</label>
            </value>
            <value>
                <fullName>Legal - Billing Restarted - Customer</fullName>
                <label>Billing Restarted - Customer</label>
            </value>
            <value>
                <fullName>Legal - Consulting Services</fullName>
                <label>Consulting Services</label>
            </value>
            <value>
                <fullName>Legal - Services Change Request</fullName>
                <label>Services Change Request</label>
            </value>
            <value>
                <fullName>Legal - Billing Paused/Restarted</fullName>
                <label>Subscription Concecession</label>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>ACV Downgrade/Partial ACV Cancellation</fullName>
                <label>Internal ACV Cancellation</label>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>ACV Recovery/Partial ACV Reinstatement</fullName>
                <label>Internal ACV Recovery</label>
            </value>
            <value>
                <fullName>New Implementation</fullName>
            </value>
            <value>
                <fullName>Platform Conversion - Increase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pse__Proj__c/fields/pse__Account__c.field-meta.xml
<CustomField>
    <fullName>pse__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>pse__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for this project (optional). If not provided, it&apos;s assumed that the record Owner is the project manager.</description>
    <label>Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects Managed</relationshipLabel>
    <relationshipName>ProjectsManaged</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open - Not Started</fullName>
                <default>true</default>
                <label>Open - Not Started</label>
            </value>
            <value>
                <fullName>Open - In Process</fullName>
            </value>
            <value>
                <fullName>Open - On Hold</fullName>
            </value>
            <value>
                <fullName>Open - Pending Closure (Completed)</fullName>
            </value>
            <value>
                <fullName>Open - Pending Closure (Cancelled)</fullName>
            </value>
            <value>
                <fullName>Open - Pending Closure (Abandoned)</fullName>
            </value>
            <value>
                <fullName>Open - Pending Closure (Transitioned to Partner)</fullName>
            </value>
            <value>
                <fullName>Closed - Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Canceled</fullName>
            </value>
            <value>
                <fullName>Closed - Abandoned</fullName>
            </value>
            <value>
                <fullName>Closed - Transitioned to Partner</fullName>
            </value>
            <value>
                <fullName>In Transition – Partner Project In Transition</fullName>
            </value>
            <value>
                <fullName>Moved to Open Air</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pse__Proj__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Earliest_Won_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Won_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Earliest Won Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Opportunity_Deletion_Notification__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Deletion_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Object Deletion Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Opportunities.cls
/********************************************************************************     
 *  Name             :  Opportunities 
 *  Author           :  Intapp
 *  Description      :  Domain class to handle business processes related to triggers. 
 *
 *  Change history   :
 *  Date            Author                      Description
 *  10/09/15        Alan Westley                Initial release (replaces OpportunityTriggerHandler, OpportunityTriggerUpdate, OpportunityTriggerHandler)
 *                                              Implemented methods:
 *                                                - UpdateSubscriptionEarliestOpportunityWonDate
 *                                                - OnCancellationSendNotificationToProjectManagers
 *                                                - OnDeletionSendNotifications
 *  7/14/17         Scott Schwarz               Commented out UpdateSubscriptionEarliestOpportunityWonDate
 *                                              Added updateOPCTypes
 *                                              Changed second input to Messaging.sendEmail to false. This allows the test class
 *                                              to not fail.
 ********************************************************************************/

public class Opportunities extends fflib_SObjectDomain 
{
    public Opportunities(List<Opportunity> records) 
    {
        super(records); 
    }
    
    public override void onBeforeInsert(){
        for(Opportunity record : (List<Opportunity>) records)
        {
            record.Project_in_sync__c = false;
        }
    }
    
    public override void onAfterInsert(){
        List<Opportunity> opportunityItemList = new List<Opportunity>();
        Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
                 .get('Migration_Opportunity').getRecordTypeId();
        for(Opportunity oppObj : (List<Opportunity>) records)
        {
          if(oppObj.RecordTypeId != oppRecordTypeId)
          {
            opportunityItemList.add(oppObj);    
          }
        }
        
        if(opportunityItemList.Size() > 0)
        {
          IntegrationUtility.publishEligibleSobjectRecords(records,null,'Opportunity');
        }
    }
    
    
    public override void onBeforeUpdate(Map<Id,SObject> existingRecords){
        for(Opportunity record : (List<Opportunity>) Records)
        {
            Opportunity oldOpp = (Opportunity) existingrecords.get(record.Id);
            if(oldOpp.IsWon == false && record.isClosed == true && record.IsWon == true)
                record.Project_in_sync__c = false;
        }
    }
    
    public override void onAfterUpdate(Map<Id,SObject> existingRecords)
    {
        // 6-14-17- SS: Removed call to UpdateSubscriptionEarliestOpportunityWonDate due to OPC project-
        // Opportunity no longer uses Subscription__c field
        // UpdateSubscriptionEarliestOpportunityWonDate(existingRecords);
        
        // Check to see if we have any Cancellation Won opportunities to process
        List<Opportunity> opps = new List<Opportunity>();
        List<Opportunity> opportunityItemList = new List<Opportunity>();
        Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
                 .get('Migration_Opportunity').getRecordTypeId();
        for (Opportunity a: (List<Opportunity>) records)
        {
            Opportunity oldOpp = (Opportunity) existingrecords.get(a.Id);
            if (a.IsWon == true && a.IsWon != oldOpp.IsWon && a.RecordType.DeveloperName == 'Legal_Cancellation')
            {
                opps.add(a);
            }
            if(a.RecordTypeId != oppRecordTypeId)
            {
              opportunityItemList.add(a);   
            }
        }
            
        if (opps.size() > 0) {
            onCancellationsendNotificationToProjectManagers(opps);
        }
        //updateOPCTypes();
        //contactRoleValidationForDNBProducts(existingRecords);
        if(opportunityItemList.Size() > 0)
        {
          IntegrationUtility.publishEligibleSobjectRecords(opportunityItemList,existingRecords,'Opportunity');
        }
    }

    public override void onAfterDelete()
    {
       onDeletionsendNotifications((List<Opportunity>) Records);
    }

    /*
    public void UpdateSubscriptionEarliestOpportunityWonDate(Map<Id,SObject> existingRecords)
    {
        List<Subscription__c> subsToUpdate = new List<Subscription__c>();
  
        for (Opportunity opp: (List<Opportunity>) Records)
          {
            if (existingRecords.size() > 0)
            {
              Opportunity oldOpp = (Opportunity) existingRecords.get(opp.Id);
              
              if (oldOpp.Subscription__c != opp.Subscription__c && oldOpp.Subscription__c != null)
              {
                Subscription__c oldSubscription = [SELECT Id, Earliest_Won_Opportunity__c FROM Subscription__c 
                    WHERE Id = :oldOpp.Subscription__c LIMIT 1];
                if (oldSubscription.Earliest_Won_Opportunity__c == oldOpp.Id)
                {
                  List<Opportunity> oldSubOpportunityList = [SELECT Id, CloseDate from Opportunity 
                                  WHERE Subscription__c = :oldOpp.Subscription__c 
                                  AND StageName = 'Closed Won' 
                                  AND Id NOT IN (:Opp.Id)
                                  ORDER BY CloseDate ASC LIMIT 1];
                  if (oldSubOpportunityList.size() > 0)
                  {

                    oldSubscription.Earliest_Won_Opportunity__c = oldSubOpportunityList[0].Id;
                    subsToUpdate.add(oldSubscription);
                  }
                }    
              }
            }
              
            if (opp.Subscription__c != null)
            {
              //Get New Subscription information
              Subscription__c newSubscription = [select Id, Earliest_Won_Opportunity__c, Earliest_Won_Opportunity__r.CloseDate 
                    FROM Subscription__c WHERE Id = :opp.Subscription__c LIMIT 1];
              if (newSubscription.Earliest_Won_Opportunity__c == null)
              {
                newSubscription.Earliest_Won_Opportunity__c = opp.Id;
                subsToUpdate.add(newSubscription);
              }
              else
              {
                if (opp.CloseDate < newSubscription.Earliest_Won_Opportunity__r.CloseDate)
                {
                  newSubscription.Earliest_Won_Opportunity__c = opp.Id;
                  subsToUpdate.add(newSubscription);
                }
              }
            }  
          }
          
          if (subsToUpdate.size() > 0)
          {
            update subsToUpdate;
          }
    }
    */

    public void onCancellationsendNotificationToProjectManagers(List<Opportunity> oppMap)
    {
        EmailTemplate et = [SELECT id FROM EmailTemplate WHERE Name = 'Opportunity Cancellation - Notify Project Managers'];
        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
        //For each account
        set<id> setOfOpptyIds = new set<Id>();
        List<pse__proj__c> projs = new List<pse__proj__c>();
        if(!oppMap.isEmpty())
        {
            for(Opportunity opp : oppMap)
            {
             setOfOpptyIds.add(opp.id);
            }
         projs = [SELECT Id, pse__Project_Manager__c, pse__Project_Manager__r.Email 
                FROM pse__proj__c where pse__Opportunity__c IN :setOfOpptyIds
                AND (NOT pse__Stage__c LIKE 'Closed%')];
            
        }
        
        for(Opportunity opp: oppMap)
        {
                List<pse__proj__c> lstOfProjects = new List<pse__proj__c>();
                for(pse__proj__c projObj :  projs)
                {
                     if(projObj.pse__Account__c == opp.AccountId)
                     lstOfProjects.add(projObj);                
                }
            
            if (lstOfProjects.size() > 0)
            {               
                for(pse__proj__c proj: lstOfProjects) {
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();             
                    //mail.setToAddresses(proj.pse__Project_Manager__r.Email);
                    mail.setTemplateId(et.Id);
                    mail.setWhatId(opp.Id);
                    mail.setTargetObjectId(proj.pse__Project_Manager__c);
                    messages.add(mail);
                }
            }
        }

        if (messages.size() > 0 ) {
            Messaging.sendEmail(messages,false);
        }
    }
    
    public void onDeletionsendNotifications(List<Opportunity> opps){
        List<String> toAddresses = new List<String>();
        for(User u: [select Email from User where Opportunity_Deletion_Notification__c = true and isActive = true]){
            toAddresses.add(u.email);
        }
        if(opps.size()>0 && toAddresses.size()>0){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(toAddresses);
            mail.setSubject('Opportunity deleted');
            mail.setSaveAsActivity(false);
            String textBody = UserInfo.getName() +' ('+ UserInfo.getUserEmail() +') deleted the following opportunities: \n';
            for(Opportunity opp: opps){
                textBody += '\n  '+ opp.Name;
            }
            mail.setPlainTextBody(textBody);
            System.debug('#### OpportunityTriggerHandler- sending notifications to: '+ toAddresses);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail},false);
        }
    }

    public void someMethod()
    {
        for(Opportunity record : (List<Opportunity>) Records)
        {
        }       
    }

    public void updateOPCTypes() {
        /*
        List<Opportunity_Product_Component__c> opcsToUpdate = new List<Opportunity_Product_Component__c>();
        for (Opportunity opp : (List<Opportunity>) Records) {
            List<Opportunity_Product_Component__c> opcsForOpportunity = [SELECT Id, Name FROM Opportunity_Product_Component__c WHERE Opportunity__c = :opp.Id];
            for (Opportunity_Product_Component__c opc : opcsForOpportunity) {
                opc.Type__c = opp.Type;
                opcsToUpdate.add(opc);
            }
        }
        update opcsToUpdate;
    
        List<Opportunity_Product_Component__c> opcsToUpdate = new List<Opportunity_Product_Component__c>();
        Map<Id, Opportunity> OppMap = new Map<Id, Opportunity>();
        
        for (Opportunity opp : (List<Opportunity>) Records) {
            OppMap.put(opp.Id, opp);    
        }
        
        for(Opportunity_Product_Component__c opc: [Select Id, Name, Type__c, Opportunity__c from Opportunity_Product_Component__c where Opportunity__c in : OppMap.keyset()]){
            if(OppMap.containsKey(opc.Opportunity__c) && OppMap.get(opc.Opportunity__c).Type != null){
                opc.Type__c = OppMap.get(opc.Opportunity__c).Type;
                opcsToUpdate.add(opc);
            }    
        }
        
        if(opcsToUpdate.size() > 0)
            update opcsToUpdate;
        */    
    }
    
    /*
    public void contactRoleValidationForDNBProducts(Map<Id,SObject> existingRecords){
        Intapp_Settings__c settings = Intapp_Settings__c.getInstance();
        //Check if custom setting is enabled
        if(!settings.contact_validation_isactive__c) return;
                
        //Get the mandatory contact role
        String mandatoryRole = settings.Contact_Role_Validation_Contact_Types__c != null? settings.Contact_Role_Validation_Contact_Types__c: 'Champion';
        
        //Get all opp types
        Set<String> oppTypes = new Set<String>();
        if(settings.Contact_Role_Validation_Opp_Types__c == null || settings.Contact_Role_Validation_Opp_Types__c == ''){
            settings.Contact_Role_Validation_Opp_Types__c = 'Third Party Product - D&B';        
        }
        
        if(settings.Contact_Role_Validation_Opp_Types__c.contains(';')){
            oppTypes.addAll(settings.Contact_Role_Validation_Opp_Types__c.split(';'));
        }
        else{
            oppTypes.add(settings.Contact_Role_Validation_Opp_Types__c);
        }
        
        //Get all excluded stages
        Set<String> excludedStages = new Set<String>();
        if(settings.Contact_Role_Validation_Exclude_stages__c == null || settings.Contact_Role_Validation_Opp_Types__c == ''){
            settings.Contact_Role_Validation_Exclude_stages__c = 'Closed Won;Closed Lost;Closed - Cancelled;Closed - Avoided Cancellation;Closed - Should Never Have Been Opened; Closed - No Decision';        
        }
        
        if(settings.Contact_Role_Validation_Exclude_stages__c.contains(';')){
            excludedStages.addAll(settings.Contact_Role_Validation_Exclude_stages__c.split(';'));
        }
        else{
            excludedStages.add(settings.Contact_Role_Validation_Exclude_stages__c);
        }
        
        System.debug('What are the opp types' + oppTypes);
        Map<Id, Boolean> opportunitiesToValidate = new Map<Id, Boolean>();
        
        for(Opportunity iteratingOpp: [Select Id, Product_Line__c, Proposed_Stage__c, StageName, Probability, isClosed, (Select Id, Role from OpportunityContactRoles) from Opportunity where Id in:(List<Opportunity>)Records ]){
            Opportunity oldRecord = (Opportunity)existingRecords.get(iteratingOpp.Id);
            System.debug('Does Opp type contain D&B? ' + oppTypes.contains(iteratingOpp.Product_Line__c));
            System.debug('Is the Opp Closed? ' + iteratingOpp.isClosed + ', Then Probabilty = ' + iteratingOpp.Probability);
            System.debug('The old probabilty was = ' + oldRecord.Probability);
            
            //Check to see if this opportunity qualifies for validation - Check if this is D&B product, the Opportunity is not closed but the probability is more than 0
            if(!oppTypes.contains(iteratingOpp.Product_Line__c) 
               || iteratingOpp.isClosed 
               || excludedStages.contains(iteratingOpp.Proposed_Stage__c)
               || iteratingOpp.Proposed_Stage__c == 'Target Account' /*iteratingOpp.Probability == 0*/ 
             //|| !existingRecords.containsKey(iteratingOpp.Id) 
             //|| oldRecord.Proposed_Stage__c != 'Target Account' /*oldRecord.Probability > 0*/){
              /*  opportunitiesToValidate.put(iteratingOpp.Id, false);
                continue;                                    
            }
            
            if(!opportunitiesToValidate.containsKey(iteratingOpp.Id))
                opportunitiesToValidate.put(iteratingOpp.Id, true);
            
            for(OpportunityContactRole iteratingContactRole: iteratingOpp.OpportunityContactRoles){
                if(opportunitiesToValidate.get(iteratingOpp.Id) && mandatoryRole.contains(iteratingContactRole.Role)){
                    opportunitiesToValidate.put(iteratingOpp.Id, false);
                }
            }
        }
        
        for(Opportunity iteratingOpp: (List<Opportunity>)Records){
            if(opportunitiesToValidate.containsKey(iteratingOpp.Id) && opportunitiesToValidate.get(iteratingOpp.Id)){
                iteratingOpp.addError(settings.Contact_Role_Validation_Error_Text__c);
            }
        }
    }
*/
    
    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new Opportunities(sObjectList);
        }
    }   
}