force-app/main/default/objects/T_Invoice_NewTemp__c/T_Invoice_NewTemp__c.object-meta.xml
<CustomObject>
    <label>T_Invoice_NewTemp</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>T_Invoice_Oct3</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T_Invoice_NewTemp</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/T_Invoice_NewTemp__c/fields/Invoice_Sent__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoice Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Invoice_Sent__c/T_Invoice_Sent__c.object-meta.xml
<CustomObject>
    <label>T_Invoice_Sent</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>T_Invoice_Sent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T_Invoice_Sent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/T_Invoice_Sent__c/fields/Internal_Id__c.field-meta.xml
<CustomField>
    <fullName>Internal_Id__c</fullName>
    <label>Internal Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceSentBatch.cls
global with sharing class InvoiceSentBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = '' 
            + ' SELECT Id'
            + '      , Internal_Id__c'
            + '      , Count__c'
            + '   FROM T_Invoice_Sent__c'
            + '  WHERE Internal_Id__c != null'
            + '    AND Count__c > 0';  
            
        return Database.getQueryLocator(query);  
    }

    global void execute(Database.BatchableContext bc, List<T_Invoice_Sent__c> invoiceSentList){
        set<string> internalIds = new set<string>();
        for (T_Invoice_Sent__c invoiceSent : invoiceSentList) {
            internalIds.add(invoiceSent.Internal_Id__c);
        }

        if (!internalIds.isEmpty()) {
            List<T_Invoice_NewTemp__c> invoiceList = [
                SELECT Id
                     , internal_Id__c
                     , invoice_sent__c
                  FROM T_Invoice_NewTemp__c
                 WHERE internal_Id__c IN :internalIds
            ];
            if (!invoiceList.isEmpty()) {
                for (T_Invoice_NewTemp__c invoice : invoiceList) {
                    invoice.invoice_sent__c = true;
                }

                HandleCustomException.logDatabaseErrors(Database.update(invoiceList,false));
            }
        }
    }

    global void finish(Database.BatchableContext bc){
       
    }
}