force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created for POC, will hold Account information</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Captures full Address of the Account</description>
    <label>Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Default Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReportToAddressBatchTest.cls
@isTest
public class ReportToAddressBatchTest {
    
    @isTest
    static void testMethod1() {
        // Create accounts
        List<Account> testAccts = new List<Account>();
        Account testAccts01 = new Account();
        testAccts01.Name = 'Test Address Account 001';
        testAccts01.BillingCity = 'Arlington';
        testAccts01.ShippingCity = 'Chicago';
        testAccts01.BillingCountry = 'USA';
        testAccts01.ShippingCountry = 'USA';
        testAccts01.BillingStreet = '4148 Coulter Lane';
        testAccts01.ShippingStreet = '4028 Jewell Road';
        testAccts01.BillingState = 'Alaska';
        testAccts01.ShippingState = 'Alabama';
        testAccts01.BillingPostalCode =  '23005';
        testAccts01.ShippingPostalCode = '55404';
        testAccts.add(testAccts01);
        
        Account testAccts02 = new Account();
        testAccts02.Name = 'Test Address Account 002';
        testAccts02.BillingCity = 'Arlington';
        testAccts02.ShippingCity = 'Arlington';
        testAccts02.BillingCountry = 'United States';
        testAccts02.ShippingCountry = 'United States';
        testAccts02.BillingStreet = '4148 Coulter Lane';
        testAccts02.ShippingStreet = '4148 Coulter Lane';
        testAccts02.BillingState = 'Alabama';
        testAccts02.ShippingState = 'Alabama';
        testAccts02.BillingPostalCode =  '23005';
        testAccts02.ShippingPostalCode = '23005';
        testAccts.add(testAccts02);


        Account testAccts03 = new Account();
        testAccts03.Name = 'Test Address Account 002';
        testAccts03.BillingCity = 'Arlington';
        testAccts03.ShippingCity = 'Arlington';
        testAccts03.BillingCountry = 'United States';
        testAccts03.ShippingCountry = 'United States';
        testAccts03.BillingStreet = '5012 Coulter Lane';
        testAccts03.ShippingStreet = '5012 Coulter Lane';
        testAccts03.BillingState = 'Alabama';
        testAccts03.ShippingState = 'Alabama';
        testAccts03.BillingPostalCode =  '23005';
        testAccts03.ShippingPostalCode = '23005';
        testAccts.add(testAccts03);

        insert testAccts;

        Address__c address = new Address__c();
        address.Address__Street__s = '5012 Coulter Lane';
        address.Address__City__s = 'Arlington';
        address.Address__StateCode__s = 'AL';
        address.Address__CountryCode__s = 'US';
        address.Address__PostalCode__s = '23005';
        address.Type__c = 'Billing';
        address.Account__c = testAccts03.Id;
        insert address;
        
        // Create Opportunity
        List<Opportunity> opportunityList = new List<Opportunity>();
        for(Integer i=0;i<3;i++) {
            Opportunity opportunity = new Opportunity(
                Name = 'TestOpportunity'+i
                , CurrencyIsoCode = 'USD'
                , Type = 'Legal - Acquired New Product'
                , CloseDate = System.today()
                , StageName = 'Closed Won'
            );
            opportunity.AccountId = testAccts[i].Id;
            opportunityList.add(opportunity);
        }
        
        insert opportunityList;
        
        Test.startTest();
        ReportToAddressBatch reportToAddressBatchObj = new ReportToAddressBatch(null);
        Database.executeBatch(reportToAddressBatchObj);
        Test.stopTest();
        System.assertEquals(4,[Select id from Address__c].size());
    }
}