force-app/main/default/objects/Services_SOW__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SOW</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Services_SOW__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product (Expiring 11/13/2018)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intapp Flow</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Open: Conflicts</fullName>
            </value>
            <value>
                <fullName>Intapp Open: Intake</fullName>
            </value>
            <value>
                <fullName>Intapp Open: Intake (Engagement Letters)</fullName>
            </value>
            <value>
                <fullName>Intapp Open: Terms of Business</fullName>
            </value>
            <value>
                <fullName>Intapp Time: Capture</fullName>
            </value>
            <value>
                <fullName>Intapp Time: Compliance</fullName>
            </value>
            <value>
                <fullName>Intapp Time: Core Management</fullName>
            </value>
            <value>
                <fullName>Intapp Time: Legacy Axiom Mobility</fullName>
            </value>
            <value>
                <fullName>Intapp Time: Legacy DTE</fullName>
            </value>
            <value>
                <fullName>Intapp Time: Legacy DTE Axiom</fullName>
            </value>
            <value>
                <fullName>Intapp Time: Mobility</fullName>
            </value>
            <value>
                <fullName>Intapp Time: Total Time Management</fullName>
            </value>
            <value>
                <fullName>Intapp Time: Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>CG Analyze</fullName>
            </value>
            <value>
                <fullName>CG Flow</fullName>
            </value>
            <value>
                <fullName>CG Protect</fullName>
            </value>
            <value>
                <fullName>LegalKEY</fullName>
            </value>
            <value>
                <fullName>RollCall</fullName>
            </value>
            <value>
                <fullName>Rekoop</fullName>
            </value>
            <value>
                <fullName>Intapp Open: Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms of Business - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Services_SOW__c/fields/Recurring_Involved__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Involved__c</fullName>
    <label>Recurring Involved?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Services_SOW__c/fields/Requesting_Employee__c.field-meta.xml
<CustomField>
    <fullName>Requesting_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requesting Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SOW1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Services_SOW__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Returned to Requesting Employee for Edits</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>SOW Completed</fullName>
            </value>
            <value>
                <fullName>Out-of-date</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>SOW Modified</fullName>
            </value>
            <value>
                <fullName>Scoping in Progress</fullName>
            </value>
            <value>
                <fullName>SOW documentation in progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Services_SOW__c/fields/Time_Questionnaire_Available__c.field-meta.xml
<CustomField>
    <fullName>Time_Questionnaire_Available__c</fullName>
    <label>Time Questionnaire  Available</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServicesSOW.cls
global class ServicesSOW {

    public class FlowRequestResponse {
        public String createdBy;
        public String id;
        public String name;
        public String requestType;
        public String status;
    }
    
    public ServicesSOW() {
    }

    public static String createFlowRequestWithDefaultFieldsHelper(String opportunityId, Boolean isTesting) {
        HttpRequest req = new HttpRequest();
        Opportunity o = [select Type from Opportunity where Id = :opportunityId LIMIT 1];
        String workFlow;
        if (o.Type.contains('Change Request'))
            workFlow = 'Services%20SOW-%20Change%20Request';
        else
            workFlow = 'Services%20SOW-%20Not%20Change%20Request';
        System.debug(workFlow);
        req.setEndpoint('https://intappprod.open.intapp.com/api/api/intake/v1/requests?workflowDefinitionName='+workFlow);
        req.setMethod('POST');
        req.setHeader('content-type', 'application/json');
        if (IsTesting == false)
            req.setHeader('Authorization','Bearer ' + ServicesSOWOAuth.getAuthToken());
        ServicesSOWDataMapper mapper = new ServicesSOWDataMapper(opportunityId);
        req.setBody(mapper.getMappings());
        Http http = new Http();
        HTTPResponse res;
        try {
            res = http.send(req);
        } catch (Exception e) {
            return 'HTTP_ERROR';
        }
        System.debug(res.getStatus());
        if (res.getStatus() != 'OK')
            return 'HTTP_ERROR';
        else if ( (UserInfo.getName() != 'Scott Schwarz') && (UserInfo.getName() != 'Kevin Ehrie') )
            return 'FEATURE_NOT_AVAILABLE_ERROR';
        else {
            FlowRequestResponse f = (FlowRequestResponse)JSON.deserialize(res.getBody(),FlowRequestResponse.class);
            return f.id;
        }
    }

    webservice static String createFlowRequestWithDefaultFields(String opportunityId) {
        return createFlowRequestWithDefaultFieldsHelper(opportunityId,false);
    }
   
    public static String createSFServicesSOWObjectHelper(String fieldData) {
        fieldData = '{"answers": ' + fieldData + '}';
        Services_SOW__c servicesSOW = new Services_SOW__c();
        String answerString = null;
        Boolean IdFieldFound = false;
        
        ServicesSOWAnswers answers = (ServicesSOWAnswers)JSON.deserialize(fieldData,ServicesSOWAnswers.class);
        for (ServicesSOWAnswer answer: answers.answers) {
            answerString = null;
            if (answer.questionName == 'SFAccountId') {
                servicesSOW.put('Account__c',answer.textAnswer);
                IDFieldFound = true;
                }
            else if (answer.questionName == 'SFEmployeeId') {
                servicesSOW.put('Requesting_Employee__c',answer.textAnswer);
                IDFieldFound = true;
                }
            else if (answer.questionName == 'Time_Questionnaire_Available_Bounding__c')
                IDFieldFound = true;
            else if ( (answer.questionName == 'Does_New_Solution_Integrate_With_Existing_Sol') || (answer.questionName == 'Project_Has_Required_Go_Live_Date') )
                IDFieldFound = true;
            else {
                if (answer.textAnswer != null)
                    answerString = answer.textAnswer;
                if (answer.numericAnswer != null)
                    answerString = answer.numericAnswer; 
                else if (answer.booleanAnswer != null)
                    answerString = answer.booleanAnswer;
                else if (answer.dateAnswer != null)
                    answerString = answer.dateAnswer; 
                else if (answer.textListAnswer != null)
                    answerString = answer.textListAnswer[0];
                if ( (answerString != null) && (answerString != '(Select)') && (!IDFieldFound) ){  
                    String s = (String)servicesSOW.put(answer.questionName,answerString);
                    }
            }
        }
        servicesSOW.put('Status__c','Submitted');
        if ( (servicesSOW.get('Product__c') != null) && (servicesSOW.get('Recurring_Involved__c') != null) ) {
            String servicesSOWProduct = (String)(servicesSOW.get('Product__c'));
            if ( (servicesSOWProduct.contains('Time')) && (servicesSOW.get('Recurring_Involved__c') == 'Yes') )
                servicesSOW.put('Time_Questionnaire_Available__c','Yes');
            }
        insert servicesSOW;
        return 'a';
    }
   
    webservice static String createSFServicesSOWObject(String fieldData) {
        return createSFServicesSOWObjectHelper(fieldData);    
    }
   

}