force-app/main/default/objects/Opportunity/fields/Associated_Contract_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contract_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the Contract record for this Opportunity?</description>
    <inlineHelpText>What is the Contract record for this Opportunity?</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Correct)</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__MasterContract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__MasterContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master contract with which subscription products in this quote are to be co-terminated.</description>
    <inlineHelpText>Associated OSA for this Opportunity.</inlineHelpText>
    <label>Master Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.SBQQ__Evergreen__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Co-Terminated Quotes</relationshipLabel>
    <relationshipName>CoTerminatedQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateContractFromQuoteController.cls
public class CreateContractFromQuoteController {
	
    String quoteId;
    public boolean isError {get; set;}
    public String msgToDisplay {get; set;}
 	ApexPages.StandardController sc;

    public CreateContractFromQuoteController(ApexPages.StandardController sc){
        this.sc = sc;
        quoteId = ApexPages.currentPage().getParameters().get('id');
        isError = false;
        
        if(quoteId != null){
            SBQQ__Quote__c quote = [SELECT Id
                                        , SBQQ__MasterContract__c
                                        FROM SBQQ__Quote__c
                                        WHERE Id = :quoteId 
                                        LIMIT 1];
            
            if (quote.SBQQ__MasterContract__c != null){
                msgToDisplay = 'Retrieving Contract.';
            }
            else{
                msgToDisplay = 'Creating Contract.';
            }
        }
    }
    
    public PageReference createContractOnQuote(){
        
        try{
            
            SBQQ__Quote__c quote = [SELECT Id
                                    , SBQQ__Account__c
                                 	, SBQQ__Opportunity2__c
                                    , SBQQ__Opportunity2__r.Name
                                    , SBQQ__MasterContract__c
                                    FROM SBQQ__Quote__c
                                    WHERE Id = :quoteId 
                                    LIMIT 1];
            
            if (quote.SBQQ__MasterContract__c != null){
                PageReference pageref = new PageReference('/'+ quote.SBQQ__MasterContract__c + '?retURL=' + quote.SBQQ__MasterContract__c);
                pageref.setRedirect(true);
                
                return pageref;
            }
            else{
            	Contract contract = new Contract(Name = quote.SBQQ__Opportunity2__r.Name, SBQQ__Quote__c = quoteId, AccountId = quote.SBQQ__Account__c, SBQQ__Opportunity__c = quote.SBQQ__Opportunity2__c);
            	insert contract;
                        
                Opportunity opportunity = new Opportunity(Id = quote.SBQQ__Opportunity2__c, Associated_Contract_OSA__c = contract.Id);
                update opportunity;
                
                PageReference pageref = new PageReference('/'+ contract.Id + '/e?retURL=' + contract.Id);
                pageref.setRedirect(true);
                return pageref;
            }

        }
        catch(Exception ex){
            isError = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, String.valueOf(ex.getLineNumber()) ));
        }
        return null;
    }
    
    public PageReference goBack(){       
        PageReference pageref = new PageReference('/'+quoteId);
        pageref.setRedirect(true);
        return pageref;
    }
}