force-app/main/default/objects/Opportunity/fields/Maintenance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Amount__c</fullName>
    <description>This field shows CHANGES to the annual recurring amount commitment for the referenced product. The value can be positive, if the closed-won opportunity increases the annual recurring commitment, or negative, if the closed-won opportunity decreases the annual recurring commitment.</description>
    <inlineHelpText>This field shows CHANGES to the annual recurring commitment for the referenced product. The value is positive, if the closed-won opportunity increases the annual commitment, or negative, if the closed-won opportunity decreases the annual commitment.</inlineHelpText>
    <label>Recurring Amount Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/Opportunity_Product_Component__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Component</label>
    <nameField>
        <displayFormat>OPC-{0000000}</displayFormat>
        <label>Opportunity Product Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Product Components</relationshipLabel>
    <relationshipName>Opportunity_Product_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Recurring_Amount_Change__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Amount_Change__c</fullName>
    <label>Recurring Amount Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Batch_Historical_UpdateOppRAC.cls
public class Batch_Historical_UpdateOppRAC implements Database.Batchable<SObject> {
    public String query;
    public Set<Integer> batchToSkip = new Set<Integer>();
    public Integer batch_number = 0; 
    
    public Batch_Historical_UpdateOppRAC(String query, Set<Integer> bToSkip) {
        this.query = query;
        this.batchToSkip = bToSkip;
    }
    
    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext context, List<SObject> scope) {
        List<Opportunity> listToUpdate = new List<Opportunity>();
        batch_number ++;
        String listWithProblem = '';
        for(Opportunity opp: (List<Opportunity>) scope){
            Decimal totalRAC = 0;
            for(Opportunity_Product_Component__c  opc: opp.Opportunity_Product_Components__r){
                if(opc.Recurring_Amount_Change__c != null)
                totalRAC += opc.Recurring_Amount_Change__c;
            }
            opp.Maintenance_Amount__c = totalRAC;
            listWithProblem +=  Opp.Id + '<br/>\r\n';
            listToUpdate.add(opp);
        }
        
        if(batchToSkip != null && batchToSkip.contains(batch_number)){
          Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject('Batch # ' + batch_number);
            mail.setHtmlBody(listWithProblem);
            mail.setToAddresses(new List<String>{'venkat.sriram@intapp.com'});
            List<Messaging.SingleEmailMessage> Mails = new List<Messaging.SingleEmailMessage>();
            Mails.add(mail);
            Messaging.sendEmail(Mails);   
        }
              
        if(batchToSkip == null || !batchToSkip.contains(batch_number))
            list<Database.SaveResult> results = Database.update(listToUpdate, false);
    }
    
    public void finish(Database.BatchableContext context) {
        
    }


}