force-app/main/default/objects/Opportunity/fields/Maintenance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Amount__c</fullName>
    <description>This field shows CHANGES to the annual recurring amount commitment for the referenced product. The value can be positive, if the closed-won opportunity increases the annual recurring commitment, or negative, if the closed-won opportunity decreases the annual recurring commitment.</description>
    <inlineHelpText>This field shows CHANGES to the annual recurring commitment for the referenced product. The value is positive, if the closed-won opportunity increases the annual commitment, or negative, if the closed-won opportunity decreases the annual commitment.</inlineHelpText>
    <label>Recurring Amount Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_Product_Lines__c.field-meta.xml
<CustomField>
    <fullName>Opp_Product_Lines__c</fullName>
    <description>Used in reporting - A list of unique product lines from OPCs under this Opportunity</description>
    <inlineHelpText>Used in reporting - A list of unique product lines from OPCs under this Opportunity</inlineHelpText>
    <label>Opportunity Product Lines (Text)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Conflicts - On Prem</fullName>
                <color>#E27001</color>
                <label>Conflicts - On Prem</label>
            </value>
            <value>
                <fullName>Intake - On Prem</fullName>
                <color>#E27001</color>
                <label>Intake - On Prem</label>
            </value>
            <value>
                <fullName>Records Management</fullName>
                <color>#E27001</color>
                <label>Records Management</label>
            </value>
            <value>
                <fullName>TFG - Legacy</fullName>
                <color>#E27001</color>
                <label>TFG - Legacy</label>
            </value>
            <value>
                <fullName>Terms - On Prem</fullName>
                <color>#E27001</color>
                <label>Terms - On Prem</label>
            </value>
            <value>
                <fullName>Terms - Cloud</fullName>
                <color>#E27001</color>
                <label>Terms - Cloud</label>
            </value>
            <value>
                <fullName>LegalKey - Legacy</fullName>
            </value>
            <value>
                <fullName>Experience - On Prem</fullName>
            </value>
            <value>
                <fullName>Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Multiple Products - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>L&amp;P - Cloud</fullName>
            </value>
            <value>
                <fullName>Relationships - On Prem</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - On Prem</fullName>
            </value>
            <value>
                <fullName>Multiple Products - Cloud</fullName>
            </value>
            <value>
                <fullName>Time - On Prem</fullName>
            </value>
            <value>
                <fullName>Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Walls - On Prem</fullName>
            </value>
            <value>
                <fullName>Integrate - On Prem</fullName>
            </value>
            <value>
                <fullName>DealCloud - Cloud</fullName>
            </value>
            <value>
                <fullName>OPIS - Cloud</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Integration Service - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_LineNew__c.field-meta.xml
<CustomField>
    <fullName>Product_LineNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line New IGNORE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Opportunities (Product Line)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/Opportunity_Product_Component__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Component</label>
    <nameField>
        <displayFormat>OPC-{0000000}</displayFormat>
        <label>Opportunity Product Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Product Components</relationshipLabel>
    <relationshipName>Opportunity_Product_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open Sandbox</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing</fullName>
            </value>
            <value>
                <fullName>Intapp Time</fullName>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Records Management</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Replicate</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>PSP</fullName>
            </value>
            <value>
                <fullName>Third Party Connectors</fullName>
            </value>
            <value>
                <fullName>Relationships</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Product_LineNew__c.field-meta.xml
<CustomField>
    <fullName>Product_LineNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Opportunity Product Components (Product Line)</relationshipLabel>
    <relationshipName>Opportunity_Product_Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Recurring_Amount_Change__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Amount_Change__c</fullName>
    <label>Recurring Amount Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Legal - New Customer</fullName>
                <label>New Customer</label>
            </value>
            <value>
                <fullName>Legal - New Product</fullName>
                <label>New Product</label>
            </value>
            <value>
                <fullName>Legal - Add-on module</fullName>
                <label>Add-on module</label>
            </value>
            <value>
                <fullName>Legal - Assessment/POC</fullName>
                <label>Assessment/POC</label>
            </value>
            <value>
                <fullName>Legal - Recurring Adjustment</fullName>
                <label>Recurring Adjustment</label>
            </value>
            <value>
                <fullName>License Conversion - Recurring Increase</fullName>
                <label>Entitlement Conversion - Recurring Increase</label>
            </value>
            <value>
                <fullName>Legal - License Band Uplift</fullName>
                <label>License Band Uplift</label>
            </value>
            <value>
                <fullName>Legal - User Count Uplift</fullName>
                <label>User Count Uplift</label>
            </value>
            <value>
                <fullName>Legal - Acquired New Customer</fullName>
                <label>Acquired New Customer</label>
            </value>
            <value>
                <fullName>Legal - Acquired New Product</fullName>
                <label>Acquired New Product</label>
            </value>
            <value>
                <fullName>Legal - Acquired Add-on Module</fullName>
                <label>Acquired Add-on Module</label>
            </value>
            <value>
                <fullName>Legal - Additional Services</fullName>
                <label>Additional Services</label>
            </value>
            <value>
                <fullName>License Conversion - Recurring Decrease</fullName>
                <label>Entitlement Conversion - Recurring Decrease</label>
            </value>
            <value>
                <fullName>Cancellation - Customer</fullName>
            </value>
            <value>
                <fullName>Cancellation - Product</fullName>
            </value>
            <value>
                <fullName>Cancellation - Module</fullName>
            </value>
            <value>
                <fullName>Cancellation - Recurring Adjustment</fullName>
            </value>
            <value>
                <fullName>Downgrade - Product</fullName>
                <label>Entitlement Downgrade - Product</label>
            </value>
            <value>
                <fullName>Legal - User Count Decrease</fullName>
                <label>User Count Decrease</label>
            </value>
            <value>
                <fullName>Legal - CPI / Recurring Increase</fullName>
                <label>SFA / Recurring Increase</label>
            </value>
            <value>
                <fullName>Legal - Billing Restarted - Customer</fullName>
                <label>Billing Restarted - Customer</label>
            </value>
            <value>
                <fullName>Legal - Consulting Services</fullName>
                <label>Consulting Services</label>
            </value>
            <value>
                <fullName>Legal - Services Change Request</fullName>
                <label>Services Change Request</label>
            </value>
            <value>
                <fullName>Legal - Billing Paused/Restarted</fullName>
                <label>Subscription Concecession</label>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>ACV Downgrade/Partial ACV Cancellation</fullName>
                <label>Internal ACV Cancellation</label>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>ACV Recovery/Partial ACV Reinstatement</fullName>
                <label>Internal ACV Recovery</label>
            </value>
            <value>
                <fullName>New Implementation</fullName>
            </value>
            <value>
                <fullName>Platform Conversion - Increase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OPC_TriggerHandler.cls
public class OPC_TriggerHandler {
    
    public static void beforeInsert(List<Opportunity_Product_Component__c> Records){
        updateType(Records);
    }
    
    public static void afterInsert(List<Opportunity_Product_Component__c> Records){
        updateRAC_onOpp(Records, null, false);
    }
    
    public static void afterUpdate(List<Opportunity_Product_Component__c> Records, Map<Id, Opportunity_Product_Component__c> oldRecords){
        updateRAC_onOpp(Records, oldRecords, false);
    }
    
    public static void afterDelete(List<Opportunity_Product_Component__c> Records){
      updateRAC_onOpp(Records, null, true);
    }    
    
    public static void updateRAC_onOpp(List<Opportunity_Product_Component__c> opcs, Map<Id, Opportunity_Product_Component__c> oldRecords, Boolean isDelete){
        if(RecursionHandler.checkRecursion()){
            return;
        }
        Map<Id, Decimal> Map_OppId_RACUpdate = new Map<Id, Decimal>();
        List<Opportunity> list_ToUpdate = new List<Opportunity>();
        
        for(Opportunity_Product_Component__c opc : opcs){
            Decimal RAC = 0;
            
            if(Map_OppId_RACUpdate.containsKey(opc.Opportunity__c)){
              RAC = Map_OppId_RACUpdate.get(opc.Opportunity__c);
            }
            
            Decimal opc_RAC = opc.Recurring_Amount_Change__c == null ? 0 : opc.Recurring_Amount_Change__c;
            
            RAC += opc_RAC; 
                
            Map_OppId_RACUpdate.put(opc.Opportunity__c, RAC);
        }
        
        for(Opportunity opp: [Select Id, Maintenance_Amount__c, Opp_Product_Lines__c,
                             (Select Id, Recurring_Amount_Change__c,Product_Line__c, Product_LineNew__c, Product_LineNew__r.Name from Opportunity_Product_Components__r) 
                              FROM Opportunity where Id in : Map_OppId_RACUpdate.keySet()]){
            opp.Maintenance_Amount__c = 0;
            //opp.Opportunity_Product_Lines__c = '';
            opp.Opp_Product_Lines__c = '';
            for(Opportunity_Product_Component__c opc: opp.Opportunity_Product_Components__r){
                //OPP RAC
                opp.Maintenance_Amount__c += opc.Recurring_Amount_Change__c == null ? 0 : opc.Recurring_Amount_Change__c;
                
                //OPP PROD LINES (TEXT)
                /*
                  if(opc.Product_Line__c != null && !opp.Opp_Product_Lines__c.contains(opc.Product_Line__c))
                    opp.Opp_Product_Lines__c += opc.Product_Line__c + ';';
                */
                
                if(opc.Product_LineNew__c == null && !opp.Opp_Product_Lines__c.contains('Other')){
                    opp.Opp_Product_Lines__c += 'Other;';
                }
                else if(opc.Product_LineNew__c != null && opc.Product_LineNew__r.Name != null && !opp.Opp_Product_Lines__c.contains(opc.Product_LineNew__r.Name)){
                    opp.Opp_Product_Lines__c += opc.Product_LineNew__r.Name + ';';
                }
            }
                                  
            opp.Opp_Product_Lines__c = opp.Opp_Product_Lines__c.removeEnd(';');
            list_ToUpdate.add(opp);
        }
        
        if(list_ToUpdate.size() > 0) update list_ToUpdate;
        
    }
    
    private static void updateType(List<Opportunity_Product_Component__c> opcs){
        Map<Id, Opportunity> OppsWithType = new Map<Id, Opportunity>();
        
        //Get all Opportunities into the above map
        for(Opportunity_Product_Component__c opc: opcs){
            OppsWithType.put(opc.Opportunity__c, null);
        }
        
        //Query for type of the opportunities
        for(Opportunity opp: [Select Id, Type from Opportunity where Id in : OppsWithType.keySet()]){
            OppsWithType.put(opp.Id, opp);
        }
        
        for(Opportunity_Product_Component__c opc: opcs){
            if(OppsWithType.containskey(opc.Opportunity__c))
                opc.Type__c = OppsWithType.get(opc.Opportunity__c).Type;
        }
    }
}