force-app/main/default/objects/Opportunity/fields/Opp_Product_Lines__c.field-meta.xml
<CustomField>
    <fullName>Opp_Product_Lines__c</fullName>
    <description>Used in reporting - A list of unique product lines from OPCs under this Opportunity</description>
    <inlineHelpText>Used in reporting - A list of unique product lines from OPCs under this Opportunity</inlineHelpText>
    <label>Opportunity Product Lines (Text)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_LineNew__c.field-meta.xml
<CustomField>
    <fullName>Product_LineNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line New IGNORE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Opportunities (Product Line)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/Opportunity_Product_Component__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Component</label>
    <nameField>
        <displayFormat>OPC-{0000000}</displayFormat>
        <label>Opportunity Product Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Product Components</relationshipLabel>
    <relationshipName>Opportunity_Product_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Product_LineNew__c.field-meta.xml
<CustomField>
    <fullName>Product_LineNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Opportunity Product Components (Product Line)</relationshipLabel>
    <relationshipName>Opportunity_Product_Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_Historical_UpdateOppProdLines.cls
public class Batch_Historical_UpdateOppProdLines implements Database.Batchable<SObject>,Database.Stateful{
    public String query;
    public Integer batch_number = 0; 
    public Set<Integer> batchToSkip = new Set<Integer>();
    
    public Batch_Historical_UpdateOppProdLines(String query, Set<Integer> bToSkip) {
        this.query = query;
        this.batchToSkip = bToSkip;
    }
    
    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext context, List<SObject> scope) {
        List<Opportunity> listToUpdate = new List<Opportunity>();
        
        List<Opportunity_Product_Component__c> list_opcs = new List<Opportunity_Product_Component__c>();
        
        String listWithProblem = '';
        batch_number ++;
        
        for(Opportunity opp: [Select Id, Opp_Product_Lines__c, (Select Id, Product_LineNew__c, Product_LineNew__r.Name from Opportunity_Product_Components__r) from Opportunity where id in : scope]){
            opp.Opp_Product_Lines__c = '';
            for(Opportunity_Product_Component__c opc : opp.Opportunity_Product_Components__r){
                String opc_pl = '';
                opc_pl = opc.Product_LineNew__c != null ? opc.Product_LineNew__r.Name : 'Other';
                opp.Opp_Product_Lines__c += opc_pl + ';';
            }   
            opp.Opp_Product_Lines__c = opp.Opp_Product_Lines__c.removeEnd(';');
            listWithProblem += Opp.Id + '-' + opp.Opp_Product_Lines__c + '<br/>\r\n';
            listToUpdate.add(opp);
        }
        
        if(batchToSkip != null && batchToSkip.contains(batch_number)){
        	Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject('Batch # ' + batch_number);
            mail.setHtmlBody(listWithProblem);
            mail.setToAddresses(new List<String>{'venkat.sriram@intapp.com'});
            List<Messaging.SingleEmailMessage> Mails = new List<Messaging.SingleEmailMessage>();
            Mails.add(mail);
            Messaging.sendEmail(Mails);   
        }
        
        if(batchToSkip == null || !batchToSkip.contains(batch_number))
        //if(listToUpdate.size() > 0) update listToUpdate;
        	list<Database.SaveResult> results = Database.update(listToUpdate, false);    
        
    }
    
    public void finish(Database.BatchableContext context) {
            /*
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject('Batch # ' + batch_number);
            mail.setHtmlBody(listWithProblem);
            mail.setToAddresses(new List<String>{'venkat.sriram@intapp.com'});
            List<Messaging.SingleEmailMessage> Mails = new List<Messaging.SingleEmailMessage>();
            Mails.add(mail);
            Messaging.sendEmail(Mails);
            */
    }

}