force-app/main/default/objects/Opportunity/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <description>Practice-specific list of products.</description>
    <inlineHelpText>Select the product for this opportunity.</inlineHelpText>
    <label>Package</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Line__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Activity Tracker (ADAM)</fullName>
                <color>#A53711</color>
                <label>Activity Tracker (ADAM)</label>
            </value>
            <value>
                <fullName>Activity Tracker Pro</fullName>
            </value>
            <value>
                <fullName>Advanced Flow</fullName>
            </value>
            <value>
                <fullName>Adv Flow &amp; Adv IB</fullName>
            </value>
            <value>
                <fullName>Adv Flow and Adv Intake</fullName>
            </value>
            <value>
                <fullName>AI Module</fullName>
            </value>
            <value>
                <fullName>Bi Directional License</fullName>
            </value>
            <value>
                <fullName>Box Builder</fullName>
            </value>
            <value>
                <fullName>CG Analyze</fullName>
            </value>
            <value>
                <fullName>CG Clear</fullName>
            </value>
            <value>
                <fullName>CG Enterprise - Analyze</fullName>
            </value>
            <value>
                <fullName>CG Enterprise - Flow</fullName>
            </value>
            <value>
                <fullName>CG Enterprise - Protect</fullName>
            </value>
            <value>
                <fullName>CG Flow</fullName>
            </value>
            <value>
                <fullName>CG Hold</fullName>
            </value>
            <value>
                <fullName>CG Lateral Hire</fullName>
            </value>
            <value>
                <fullName>CG Mobile</fullName>
            </value>
            <value>
                <fullName>CG Protect</fullName>
            </value>
            <value>
                <fullName>DTE Added to Time Management</fullName>
            </value>
            <value>
                <fullName>DTE Axiom</fullName>
            </value>
            <value>
                <fullName>DTE Axiom Mobile</fullName>
            </value>
            <value>
                <fullName>DTE Legacy</fullName>
            </value>
            <value>
                <fullName>eBillingHub Module</fullName>
            </value>
            <value>
                <fullName>Experience</fullName>
            </value>
            <value>
                <fullName>Experience Cloud</fullName>
            </value>
            <value>
                <fullName>Flow &amp; IB</fullName>
            </value>
            <value>
                <fullName>Flow &amp; IB: Cloud</fullName>
            </value>
            <value>
                <fullName>Flow &amp; Intake</fullName>
            </value>
            <value>
                <fullName>Flow &amp; Intake &amp; IB</fullName>
            </value>
            <value>
                <fullName>Flow - Advanced</fullName>
            </value>
            <value>
                <fullName>Intapp Open: Intake - Engagement Letter Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Practice_Group__c.field-meta.xml
<CustomField>
    <fullName>Practice_Group__c</fullName>
    <description>Which IntApp practice group should drive strategy for this opportunity.</description>
    <inlineHelpText>Which IntApp practice group should drive strategy for this opportunity.</inlineHelpText>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operations &amp; Finance</fullName>
                <color>#78C953</color>
                <label>Operations &amp; Finance</label>
            </value>
            <value>
                <fullName>Risk &amp; Compliance</fullName>
                <color>#E27001</color>
                <label>Risk &amp; Compliance</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <color>#0B6FCE</color>
                <label>IT</label>
            </value>
            <value>
                <fullName>Multiple Products</fullName>
            </value>
            <value>
                <fullName>Knowledge &amp; Content</fullName>
            </value>
            <value>
                <fullName>Leaders &amp; Professionals</fullName>
            </value>
            <value>
                <fullName>Flow &amp; Intake Bundle</fullName>
            </value>
            <value>
                <fullName>DealCloud</fullName>
            </value>
            <value>
                <fullName>Marketing &amp; BD</fullName>
            </value>
            <value>
                <fullName>#N/A</fullName>
                <isActive>false</isActive>
                <label>#N/A</label>
            </value>
            <value>
                <fullName>Intapp Pricing</fullName>
                <isActive>false</isActive>
                <label>Intapp Pricing</label>
            </value>
            <value>
                <fullName>Risk and Compliance</fullName>
                <isActive>false</isActive>
                <label>Risk and Compliance</label>
            </value>
            <value>
                <fullName>Technology Practice</fullName>
                <isActive>false</isActive>
                <label>Technology Practice</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <isActive>false</isActive>
                <label>Unknown</label>
            </value>
            <value>
                <fullName>Wall Builder</fullName>
                <isActive>false</isActive>
                <label>Wall Builder</label>
            </value>
            <value>
                <fullName>Revenue</fullName>
                <isActive>false</isActive>
                <label>Revenue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Conflicts - On Prem</fullName>
                <color>#E27001</color>
                <label>Conflicts - On Prem</label>
            </value>
            <value>
                <fullName>Intake - On Prem</fullName>
                <color>#E27001</color>
                <label>Intake - On Prem</label>
            </value>
            <value>
                <fullName>Records Management</fullName>
                <color>#E27001</color>
                <label>Records Management</label>
            </value>
            <value>
                <fullName>TFG - Legacy</fullName>
                <color>#E27001</color>
                <label>TFG - Legacy</label>
            </value>
            <value>
                <fullName>Terms - On Prem</fullName>
                <color>#E27001</color>
                <label>Terms - On Prem</label>
            </value>
            <value>
                <fullName>Terms - Cloud</fullName>
                <color>#E27001</color>
                <label>Terms - Cloud</label>
            </value>
            <value>
                <fullName>LegalKey - Legacy</fullName>
            </value>
            <value>
                <fullName>Experience - On Prem</fullName>
            </value>
            <value>
                <fullName>Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Multiple Products - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>L&amp;P - Cloud</fullName>
            </value>
            <value>
                <fullName>Relationships - On Prem</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - On Prem</fullName>
            </value>
            <value>
                <fullName>Multiple Products - Cloud</fullName>
            </value>
            <value>
                <fullName>Time - On Prem</fullName>
            </value>
            <value>
                <fullName>Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Walls - On Prem</fullName>
            </value>
            <value>
                <fullName>Integrate - On Prem</fullName>
            </value>
            <value>
                <fullName>DealCloud - Cloud</fullName>
            </value>
            <value>
                <fullName>OPIS - Cloud</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Integration Service - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Review_Stage__c.field-meta.xml
<CustomField>
    <fullName>Review_Stage__c</fullName>
    <description>This field is used to determine how far along the review stage is for this opportunity. Typically, the proposed stage change will be discussed with a rep first, then reviewed by the appropriate Sales President.</description>
    <label>Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discussion with Seller</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RFP2__c.field-meta.xml
<CustomField>
    <fullName>RFP2__c</fullName>
    <label>RFP?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Discretionary</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Services_SOW__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SOW</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ServicesSOWTest.cls
@isTest (seeAllData = true) global class ServicesSOWTest {


   global class MockHttpResponseGenerator implements HttpCalloutMock {
        global HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"access_token":"testaccesstoken","token_type":"bearer","expires_in":86399,"refresh_token":"testrefreshtoken"}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    @future(callout=true) static void invoke2(String AccountId) {
        ServicesSOW.createSFServicesSOWObjectHelper('[ {"answerType":"text","questionName":"Account__c","textAnswer":"' + AccountId + '"} ]');
        Services_SOW__c s = [SELECT Account__r.Name FROM Services_SOW__c WHERE Account__c = :AccountId];
        System.assertEquals('testaccount-SOW test',s.Account__r.Name);
    }
    
    static void invoke(String OpportunityId, String AccountId) {
        ServicesSOW.createFlowRequestWithDefaultFieldsHelper(OpportunityId,true);
        invoke2(AccountId);
    }
    
    testmethod static void test1() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Account a = new Account();
        a.Name = 'testaccount-SOW test';
        insert a;
        Opportunity o = new Opportunity();
        o.AccountId = a.Id;
        RecordType r = [SELECT Id from RecordType WHERE Name = 'Sales - Legal' and SObjectType = 'Opportunity' LIMIT 1];
        o.RecordTypeId = r.Id;
        o.Name = 'TestOppName';
        o.Practice_Group__c = 'Risk Practice';
        o.Product_Line__c = 'Intapp Open - Intake';
        o.Package__c = 'Intapp Open: Intake - Engagement Letter Module';
        o.Type = 'Legal - New Product';
        o.RFP2__c = 'Funded';
        o.CloseDate = DateTime.newInstance(2017,1,30).date();
        o.StageName = 'TargetAccount';
        o.Review_Stage__c = 'Discussion with Seller';
        o.CurrencyIsoCode = 'USD';
        insert o;
        invoke(o.Id,a.Id);
        //System.assertNotEquals(o.Id,null);
        
    }
    
    
}