force-app/main/default/objects/Opportunity/fields/SBQQ__RenewedContract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
    <inlineHelpText>Contract being renewed by this renewal opportunity. If the several contracts roll up to this opportunity, this points at the master contract.</inlineHelpText>
    <label>Renewed Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>RenewalOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Renewal_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Quote_Type__c</fullName>
    <description>Created as part of BIZ-47716, to specify the renewal Quote type.
Auto Renewal - Created Automatically by the system when renewal quoted is selected on the contract.
Renewal-Changes - Created by cloning Auto-Renewal Quotes.
COntract consolidation - created while consolidating contracts</description>
    <label>Renewal Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto-Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal-Changes</fullName>
            </value>
            <value>
                <fullName>Consolidated-Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CloneQuoteTest.cls
/**
* @description       : Test class for CloneQuote
* @author            : Keerthan N
* Jira story : BIZ-47457
**/
@isTest
public class CloneQuoteTest {
    
    @testSetup
    public static void setup(){
        
        List<AVA_MAPPER__Entity_Use_code__c> avaList = TestDataFactory.createEntityUseCode(1,True);
        List<Account> accList = TestDataFactory.createAccount(1,False);
        accList[0].AVA_MAPPER__Entity_Use_code__c = avaList[0].Id;
        Insert accList;
        
        Id pricebookId = Test.getStandardPricebookId();
        List<Opportunity> opptyList = TestDataFactory.createOppty(2,accList[0].Id,False);
        opptyList[0].Pricebook2Id = pricebookId;
        //opptyList[1].Pricebook2Id = pricebookId;
        Insert opptyList;
        List<Product2> prodObj = TestDataFactory.createProduct(1,false);
        Insert prodObj;
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=prodObj[0].id, UnitPrice=1, IsActive=True);
        Insert pbe; 
        List<SBQQ__Quote__c> quoteList1 = TestDataFactory.createQuote(1,opptyList[0].Id,False);
        List<SBQQ__Quote__c> quoteList2 = TestDataFactory.createQuote(1,opptyList[1].Id,False);
        quoteList1[0].SBQQ__Account__c = accList[0].Id;
        quoteList1[0].Renewal_Quote_Type__c = ConstantUtilityClass.AUTORENEWAL;
        quoteList2[0].SBQQ__Account__c = accList[0].Id;
        List<SBQQ__Quote__c> updateQuote = new List<SBQQ__Quote__c>();
        updateQuote.add(quoteList1[0]);
        //updateQuote.add(quoteList2[0]);
        Insert updateQuote;
        List<SBQQ__QuoteLine__c> quoteLineList1 = TestDataFactory.createQuoteLine(1,quoteList1[0].Id,prodObj[0].Id,False);
        List<SBQQ__QuoteLine__c> quoteLineList2 = TestDataFactory.createQuoteLine(1,quoteList2[0].Id,prodObj[0].Id,False);
        List<SBQQ__QuoteLine__c> insertQL = new List<SBQQ__QuoteLine__c>();
        insertQL.add(quoteLineList1[0]);
        //insertQL.add(quoteLineList2[0]);
        Insert insertQL;
        Test.startTest();
        List<Contract> contList = TestDataFactory.createContract(2,accList[0].Id,False);
        contList[0].SBQQ__Quote__c = updateQuote[0].Id;
        //contList[1].SBQQ__Quote__c = updateQuote[1].Id;
        Insert  contList;
        //List<Opportunity> opptyList1 = [Select Id From Opportunity];
        opptyList[0].SBQQ__RenewedContract__c = contList[0].Id;
        opptyList[1].SBQQ__RenewedContract__c = contList[1].Id;
        Update opptyList;
        Test.stopTest();
    }
    
    @istest
    private static void checkAndCreateQuoteTest(){
        List<Contract> contList = [Select Id From Contract];
        /*List<Opportunity> opptyList = [Select Id From Opportunity];
        opptyList[0].SBQQ__RenewedContract__c = contList[0].Id;
        opptyList[1].SBQQ__RenewedContract__c = contList[1].Id;
        Update opptyList;*/
        List<Id> contIdList = new List<Id>();
        for(Contract con : contList){
            contIdList.add(con.Id);
        }
        List<CloneQuote.InputVariables> inputVarList = new List<CloneQuote.InputVariables>();
        CloneQuote.InputVariables inputVar = new CloneQuote.InputVariables();
        inputVar.contractIdList = contIdList;
        inputVar.startDate = system.Today()+20;
        inputVarList.add(inputVar);
        Test.startTest();
        	CloneQuote.duplicateQuote(inputVarList);
        Test.stopTest();
        List<SBQQ__Quote__c> quoteList = [Select Id,Name From SBQQ__Quote__c Where Renewal_Quote_Type__c='Consolidated-Quote' Limit 1];
        Assert.isTrue(quoteList.size() > 0, 'Quote Inserted');
    }
    
}