force-app/main/default/objects/Opportunity/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Validation_Exception__c.field-meta.xml
<CustomField>
    <fullName>Validation_Exception__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validation Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerUpdate_Test.cls
@isTest (SeeAllData = true)
private class OpportunityTriggerUpdate_Test {
	static testMethod void TestOpportunityUpdate() {
		List <Opportunity> ops = [SELECT Id from Opportunity where IntApp_Opportunity_Number__c = 'O502350'];
		if (ops.size() > 0)
		{
			Opportunity o = ops[0];
			Subscription__c sub = [select Id from Subscription__c where Name = 'S-0001107' LIMIT 1];
			o.Subscription__c = sub.Id;
			o.Validation_Exception__c = true;
			update o;
		}
	}
}