force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>The record type to be used for products such as Wall Builder</description>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>true</active>
    <description>The record type to be used for services such as implementations.</description>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/QtC_Mig_Invoice_Temp_Table__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>QtC Mig Invoice Temp Table</relationshipLabel>
    <relationshipName>QtC_Mig_Invoice_Temp_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BIZ-45643</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Dimension__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Dimension__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</description>
    <inlineHelpText>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</inlineHelpText>
    <label>Price Dimension</label>
    <referenceTo>SBQQ__Dimension__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/T_OrderLineDMSummary__c/T_OrderLineDMSummary__c.object-meta.xml
<CustomObject>
    <label>T_OrderLineDMSummary</label>
    <nameField>
        <displayFormat>ODL-{000000000}</displayFormat>
        <label>OrderLineDMSummary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T_OrderLineDMSummaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/T_OrderLineDMSummary__c/fields/NSOrderID__c.field-meta.xml
<CustomField>
    <fullName>NSOrderID__c</fullName>
    <label>NSOrderID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_OrderLineDMSummary__c/fields/SF_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Order_Id__c</fullName>
    <label>SF_Order_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/T_UpdateInvoiceHeadwtihSFOrderIdTest.cls
/**** @name        : T_UpdateInvoiceHeadwtihSFOrderIdTest
***** @author  : KPMG
***** @date  : Nov 11th, 2023
***** @description : Test Class for T_UpdateInvoiceHeadwtihSFOrderIdBatch
******/
@isTest
public class T_UpdateInvoiceHeadwtihSFOrderIdTest {
    //Test Data Setup
    @testSetup()
    public static void setupData(){
        //Creating Account
        Account  acc = new Account();
        acc.Name = 'Service Billing Testing 10/30';
        insert acc;
        
        //Creating Opp from Test Data Factory
        List<opportunity> oppList = TestDataFactory.createOppty(1,acc.Id,True);
        //Creating Quote from TestData Factory
        List<SBQQ__Quote__c> quoteList = TestDataFactory.createQuote(1,oppList[0].Id,True);
        //Creating Product from Test Data Factory
        List<Product2> prodList = TestDataFactory.createProduct(1,True);
        //Creating PriceBook from TestDataFactory
        PricebookEntry pbEntry = TestDataFactory.createPricebookEntry(prodList[0].Id,true);
        pbEntry.UnitPrice = 100;
        update pbEntry;
        //Creating Dimension from TestDataFactory
        SBQQ__Dimension__c dim = TestDataFactory.createPricebookDimension(prodList[0].Id,true);
        //Creating QuoteLine from TestDataFactory
        List<SBQQ__QuoteLine__c> quoteLineList = TestDataFactory.createQuoteLine(1,quoteList[0].Id,prodList[0].Id,true);
        //Creating order record
        Order ord = new Order();
        ord.AccountId = acc.id;
        ord.OpportunityId = oppList[0].Id;
        ord.EffectiveDate = system.today();
        ord.Status = 'Draft';
        ord.blng__BillingDayOfMonth__c = '1';
        ord.Pricebook2Id = pbEntry.Pricebook2Id;
        insert ord;
        //Creating QtC_Mig_Invoice_Temp_Table__c record
        QtC_Mig_Invoice_Temp_Table__c invTemp = new QtC_Mig_Invoice_Temp_Table__c();
        invTemp.Order__c = ord.Id;
        invTemp.Sales_Order_Internal_Id__c = '12345';
        insert invTemp;
        //Creating T_OrderLineDMSummary__c record
        T_OrderLineDMSummary__c ordLineDM = new T_OrderLineDMSummary__c();
        ordLineDM.NSOrderID__c = '12345';
        ordLineDM.SF_Order_Id__c = ord.Id;
        insert ordLineDM;
    }
    @isTest
    //Method to execute test data
    public static void updateInvoiceHeadwtihSFOrderIdBatchTest(){
        //Start Test
        test.StartTest();
        //Execute the Batch class to be tested
        T_UpdateInvoiceHeadwtihSFOrderIdBatch bc = new T_UpdateInvoiceHeadwtihSFOrderIdBatch();
        Database.executeBatch(bc);
        //Stop test
        test.StopTest();
        //Validating the results
        List<T_OrderLineDMSummary__c> orderItemList = [SELECT Id,NSOrderID__c,SF_Order_Id__c FROM T_OrderLineDMSummary__c];
        List<QtC_Mig_Invoice_Temp_Table__c> tempList = [SELECT Id,Order__c,Sales_Order_Internal_Id__c FROM QtC_Mig_Invoice_Temp_Table__c];
        if(tempList.size() > 0 && orderItemList.size() > 0 && orderItemList[0].SF_Order_Id__c != null && tempList[0].Order__c != null){
        System.assertEquals(orderItemList[0].SF_Order_Id__c,tempList[0].Order__c,'Order Populated Successfully');   
        }
    }
}