force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>The record type to be used for products such as Wall Builder</description>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>true</active>
    <description>The record type to be used for services such as implementations.</description>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Dimension__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Dimension__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</description>
    <inlineHelpText>Dimensions within an MDQ Product that all each segment to be priced independently. Each Product may contain several Price Dimensions. Yearly Price Dimensions are treated as Subscriptions.</inlineHelpText>
    <label>Price Dimension</label>
    <referenceTo>SBQQ__Dimension__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/T_OrderLineDMSummary__c/T_OrderLineDMSummary__c.object-meta.xml
<CustomObject>
    <label>T_OrderLineDMSummary</label>
    <nameField>
        <displayFormat>ODL-{000000000}</displayFormat>
        <label>OrderLineDMSummary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T_OrderLineDMSummaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/T_OrderLineDMSummary__c/fields/NS_AccountId__c.field-meta.xml
<CustomField>
    <fullName>NS_AccountId__c</fullName>
    <label>NS AccountId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_OrderLineDMSummary__c/fields/NS_OrderLine_Item__c.field-meta.xml
<CustomField>
    <fullName>NS_OrderLine_Item__c</fullName>
    <label>NS OrderLine Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_OrderLineDMSummary__c/fields/OL_End_Date__c.field-meta.xml
<CustomField>
    <fullName>OL_End_Date__c</fullName>
    <label>OL End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/T_OrderLineDMSummary__c/fields/OL_StartDate__c.field-meta.xml
<CustomField>
    <fullName>OL_StartDate__c</fullName>
    <label>OL StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/T_OrderLineDMSummary__c/fields/SF_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Order_Id__c</fullName>
    <label>SF_Order_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_OrderLineDMSummary__c/fields/SF_OrderProduct_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_OrderProduct_Id__c</fullName>
    <label>SF_OrderProduct_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/T_UpdateOrderLineSummaryBatchTest.cls
/****  Name :T_UpdateOrderLineSummaryBatchTest
***** Created By : KPMG
***** Created On : Nov 11th, 2023
***** Description : Test Class to check - T_UpdateOrderLineSummaryBatch
******/
@isTest
public class T_UpdateOrderLineSummaryBatchTest {
    //Test Data Setup
    @testSetup
    public static void setupData(){
        //Creating Account
        Account  acc = new Account();
        acc.Name = 'Service Billing Testing 10/30';
        insert acc;
        //Creating Opp from Test Data Factory
        List<opportunity> oppList = TestDataFactory.createOppty(1,acc.Id,True);
        //Creating Quote from TestData Factory
        List<SBQQ__Quote__c> quoteList = TestDataFactory.createQuote(1,oppList[0].Id,True);
        //Creating Product from Test Data Factory
        List<Product2> prodList = TestDataFactory.createProduct(1,True);
        //Creating PrizeBook from TestDataFactory
        PricebookEntry pbEntry = TestDataFactory.createPricebookEntry(prodList[0].Id,true);
        pbEntry.UnitPrice = 100;
        update pbEntry;
        //Creating Dimension from TestDataFactory
        SBQQ__Dimension__c dim = TestDataFactory.createPricebookDimension(prodList[0].Id,true);
        //Creating QuoteLine from TestDataFactory
        List<SBQQ__QuoteLine__c> quoteLineList = TestDataFactory.createQuoteLine(1,quoteList[0].Id,prodList[0].Id,true);
        //Creating order record
        Order ord = new Order();
        ord.AccountId = acc.id;
        ord.OpportunityId = oppList[0].Id;
        ord.EffectiveDate = system.today();
        ord.Status = 'Draft';
        ord.blng__BillingDayOfMonth__c = '1';
        ord.Pricebook2Id = pbEntry.Pricebook2Id;
        insert ord;
        //Creating Orderitem record
        OrderItem ordItem = new OrderItem();
        ordItem.Product2Id = prodList[0].Id;
        ordItem.OrderId = ord.Id;
        //ordItem.OrderId = '1234';
        ordItem.Quantity = 1; 
        ordItem.ServiceDate = system.today();
        ordItem.EndDate = system.today()+10;
        ordItem.SBQQ__ChargeType__c = 'Recurring';
        ordItem.PricebookEntryId = pbEntry.Id;
        system.debug('ordItem: ' + ordItem);
        insert ordItem;
        //Creating OrderLine DM Summary
        T_OrderLineDMSummary__c ordLineSummary = new T_OrderLineDMSummary__c();
        ordLineSummary.NS_AccountId__c =  acc.IntApp_Account_Number__c ;
        ordLineSummary.NS_OrderLine_Item__c = 'BU-01670-2';
        ordLineSummary.Quantity__c = 1;
        ordLineSummary.OL_StartDate__c = system.today();
        ordLineSummary.OL_End_Date__c = system.today()+10;
        ordLineSummary.SF_Order_Id__c = ord.Id;
        ordLineSummary.SF_OrderProduct_Id__c = ordItem.Id;
        insert ordLineSummary;
    }        
    @istest
    //Method to execute the test data
    public static void execute(){
        //Start Test
        Test.startTest();
        //Executing the method to be tested
        T_UpdateOrderLineSummaryBatch bc = new T_UpdateOrderLineSummaryBatch();
        Id batchId = Database.executeBatch(bc);
        System.assert(batchId!=null);
        //Stop test
        Test.stopTest();
    }
    
}