force-app/main/default/objects/blng__CreditNote__c/blng__CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/blng__CreditNote__c/fields/blng__Account__c.field-meta.xml
<CustomField>
    <fullName>blng__Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>AccountCreditNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/fields/blng__CreditNoteDate__c.field-meta.xml
<CustomField>
    <fullName>blng__CreditNoteDate__c</fullName>
    <label>Credit Note Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/fields/blng__RelatedInvoice__c.field-meta.xml
<CustomField>
    <fullName>blng__RelatedInvoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Invoice</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Draft Invoices would not be available</errorMessage>
        <filterItems>
            <field>blng__Invoice__c.blng__InvoiceStatus__c</field>
            <operation>notEqual</operation>
            <value>Draft</value>
        </filterItems>
        <infoMessage>Draft Invoices would not be available</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>InvoiceCreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/fields/NS_Credit_Note_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Credit_Note_Internal_ID__c</fullName>
    <label>NS Credit Note Internal ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/fields/T_IsMigrated__c.field-meta.xml
<CustomField>
    <fullName>T_IsMigrated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>T_IsMigrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/blng__Invoice__c/blng__Invoice__c.object-meta.xml
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/blng__Invoice__c/fields/blng__Account__c.field-meta.xml
<CustomField>
    <fullName>blng__Account__c</fullName>
    <inlineHelpText>Lookup to the Account this invoice is billed to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>AccountInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/blng__Invoice__c/fields/blng__InvoiceStatus__c.field-meta.xml
<CustomField>
    <fullName>blng__InvoiceStatus__c</fullName>
    <description>Warning: Invoice Status is an internal field. Changing it could cause basic functionality to fail or become unstable.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>blng__InvoiceStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/blng__Invoice__c/fields/NS_Inv_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Inv_Internal_ID__c</fullName>
    <label>NS Inv Internal ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/blng__InvoiceLine__c/fields/NS_Inv_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Inv_Internal_ID__c</fullName>
    <label>NS Inv Internal ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/blng__InvoiceLine__c/fields/NS_Line_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Line_ID__c</fullName>
    <label>NS Line ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QtC_Mig_CreditMemoLines_Temp_Table__c/fields/T_CreditNote__c.field-meta.xml
<CustomField>
    <fullName>T_CreditNote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T_CreditNote</label>
    <referenceTo>blng__CreditNote__c</referenceTo>
    <relationshipLabel>QtC Mig CreditMemo Lines Temp Table</relationshipLabel>
    <relationshipName>QtC_Mig_CreditMemo_Lines_Temp_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QtC_Mig_CreditMemoLines_Temp_Table__c/fields/T_Invoice__c.field-meta.xml
<CustomField>
    <fullName>T_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T_Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>QtC Mig CreditMemo Lines Temp Table</relationshipLabel>
    <relationshipName>QtC_Mig_CreditMemo_Lines_Temp_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QtC_Mig_CreditMemoLines_Temp_Table__c/fields/T_Invoice_Line__c.field-meta.xml
<CustomField>
    <fullName>T_Invoice_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T_Invoice_Line</label>
    <referenceTo>blng__InvoiceLine__c</referenceTo>
    <relationshipLabel>QtC Mig CreditMemoLines Temp Table</relationshipLabel>
    <relationshipName>QtC_Mig_CreditMemoLines_Temp_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/T_Invoice__c/T_Invoice__c.object-meta.xml
<CustomObject>
    <label>T_Invoice</label>
    <nameField>
        <label>T_Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T_Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/T_CreditMemoLinesLookupBatchTest.cls
/**** @name       	: T_CreditMemoLinesLookupBatchTest
***** @author  		: KPMG
***** @date 		: Nov 11th, 2023
***** @description  : Test Class for T_CreditMemoLinesLookupBatch ,Updating Credit Note lookup using Internal Id  
                      Updating InvoiceLines Lookup using Billing Credit Note Id and Billing Invoice Line Id 						
******/ 
@istest
//Test Class
public class T_CreditMemoLinesLookupBatchTest {
	//testData
	@isTest
    public static void creditMemoLinesLookupBatchValidate(){
        //Creating Account record
        Account acc = new Account();
        acc.name='Test';
        insert acc;
        //Creating blng__Invoice__c record
        blng__Invoice__c blngInv = new blng__Invoice__c();
        blngInv.NS_Inv_Internal_ID__c = '1234';
        blngInv.blng__Account__c = acc.Id;
        blngInv.blng__InvoiceStatus__c = 'Posted';
        blngInv.T_IsMigrated__c = True;
        insert blngInv;
        //Create Billing Inv Lines
        blng__InvoiceLine__c blngInLine = new blng__InvoiceLine__c();
        blngInLine.NS_Inv_Internal_ID__c = '1234';
        blngInLine.NS_Line_ID__c = '1';
        blngInLine.T_IsMigrated__c = true;
        blngInLine.blng__Invoice__c = blngInv.Id;
        insert blngInLine;
        
        //CreditNote
         blng__CreditNote__c blngCreditNote = new blng__CreditNote__c();
         blngCreditNote.NS_Credit_Note_Internal_ID__c = '1234';
         blngCreditNote.blng__Account__c = acc.Id;
         blngCreditNote.blng__CreditNoteDate__c = Date.TODAY();
         blngCreditNote.blng__RelatedInvoice__c = blngInv.Id;
         blngCreditNote.T_IsMigrated__c = True;
         insert blngCreditNote;
        
        //Create QtC_Mig_CreditMemoLines_Temp_Table__c data
        QtC_Mig_CreditMemoLines_Temp_Table__c tempCreditMemo = new QtC_Mig_CreditMemoLines_Temp_Table__c();
        tempCreditMemo.Internal_ID__c = '1234';
        tempCreditMemo.Invoice_Internal_Id__c = '1234';
        tempCreditMemo.Invoice_Line_ID__c = '1';
        tempCreditMemo.T_Invoice__c = blngInv.Id ;//Updating the Invoice Id
        //tempCreditMemo.T_Invoice_Line__c = blngInLine.Id; // InvoiceLineId
        //tempCreditMemo.T_CreditNote__c = blngCreditNote.Id;// CreditNoteId
        insert tempCreditMemo; 
    
        //Start test
        Test.startTest();
        //Executing the batch for test data
        T_CreditMemoLinesLookupBatch bc = new T_CreditMemoLinesLookupBatch('CreditNote');
        Database.executeBatch(bc);
        //Stop test
        Test.stopTest();
        
        //Validating the results
        List<QtC_Mig_CreditMemoLines_Temp_Table__c> tempList = [SELECT Id,T_CreditNote__c FROM QtC_Mig_CreditMemoLines_Temp_Table__c Limit 1];
        List<blng__CreditNote__c> billingCreditNote = [SELECT Id,NS_Credit_Note_Internal_ID__c FROM blng__CreditNote__c Limit 1];
        if(tempList.size() > 0 && tempList[0].T_CreditNote__c != null && billingCreditNote.size() >0 ){
           System.assertEquals(tempList[0].T_CreditNote__c,billingCreditNote[0].Id,'CreditNote Id populated successfully');
        }
    }
    //Method-2
    @isTest
    public static void creditMemoLinesLookupBatchInvoiceValidate(){
        //Creating Account record
        Account acc = new Account();
        acc.name='Test';
        insert acc;
        //Creating blng__Invoice__c record
        blng__Invoice__c blngInv = new blng__Invoice__c();
        blngInv.NS_Inv_Internal_ID__c = '1234';
        blngInv.blng__Account__c = acc.Id;
        blngInv.blng__InvoiceStatus__c = 'Posted';
        blngInv.T_IsMigrated__c = True;
        insert blngInv;
        //Create Billing Inv Lines
        blng__InvoiceLine__c blngInLine = new blng__InvoiceLine__c();
        blngInLine.NS_Inv_Internal_ID__c = '1234';
        blngInLine.NS_Line_ID__c = '1';
        blngInLine.T_IsMigrated__c = true;
        blngInLine.blng__Invoice__c = blngInv.Id;
        insert blngInLine;
        
        //CreditNote
         blng__CreditNote__c blngCreditNote = new blng__CreditNote__c();
         blngCreditNote.NS_Credit_Note_Internal_ID__c = '1234';
         blngCreditNote.blng__Account__c = acc.Id;
         blngCreditNote.blng__CreditNoteDate__c = Date.TODAY();
         blngCreditNote.blng__RelatedInvoice__c = blngInv.Id;
         blngCreditNote.T_IsMigrated__c = True;
         insert blngCreditNote;
        
        //Create QtC_Mig_CreditMemoLines_Temp_Table__c data
        QtC_Mig_CreditMemoLines_Temp_Table__c tempCreditMemo = new QtC_Mig_CreditMemoLines_Temp_Table__c();
        tempCreditMemo.Internal_ID__c = '1234';
        tempCreditMemo.Invoice_Internal_Id__c = '1234';
        tempCreditMemo.Invoice_Line_ID__c = '1';
        tempCreditMemo.T_Invoice__c = blngInv.Id ;//Updating the Invoice Id
        insert tempCreditMemo;   
        
        //Start test
        Test.startTest();
        //Executing the batch for test data
        T_CreditMemoLinesLookupBatch bc = new T_CreditMemoLinesLookupBatch('InvoiceLine');
        Database.executeBatch(bc);
        //Stop test
        Test.stopTest();
        
        //Validating the results
        List<QtC_Mig_CreditMemoLines_Temp_Table__c> tempList = [SELECT Id,T_Invoice_Line__c FROM QtC_Mig_CreditMemoLines_Temp_Table__c Limit 1];
        List<blng__InvoiceLine__c> billingInvLine = [SELECT Id FROM blng__InvoiceLine__c Limit 1];
        if(tempList.size() > 0 && tempList[0].T_Invoice_Line__c != null && billingInvLine.size() >0 ){
            System.assertEquals(tempList[0].T_Invoice_Line__c,billingInvLine[0].Id,'InvoiceLine Id populated successfully');
        }
    }
}