force-app/main/default/objects/blng__CreditNote__c/blng__CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/blng__CreditNote__c/fields/blng__Account__c.field-meta.xml
<CustomField>
    <fullName>blng__Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>AccountCreditNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/fields/blng__RelatedInvoice__c.field-meta.xml
<CustomField>
    <fullName>blng__RelatedInvoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Invoice</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Draft Invoices would not be available</errorMessage>
        <filterItems>
            <field>blng__Invoice__c.blng__InvoiceStatus__c</field>
            <operation>notEqual</operation>
            <value>Draft</value>
        </filterItems>
        <infoMessage>Draft Invoices would not be available</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>InvoiceCreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/fields/NS_Credit_Note_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Credit_Note_Internal_ID__c</fullName>
    <label>NS Credit Note Internal ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/fields/T_IsMigrated__c.field-meta.xml
<CustomField>
    <fullName>T_IsMigrated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>T_IsMigrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c/fields/T_CreditNote__c.field-meta.xml
<CustomField>
    <fullName>T_CreditNote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T_CreditNote</label>
    <referenceTo>blng__CreditNote__c</referenceTo>
    <relationshipLabel>QtC Mig CreditMemoLines Alloc Temp Table</relationshipLabel>
    <relationshipName>QtC_Mig_CreditMemoLines_Alloc_Temp_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c/fields/T_Invoice__c.field-meta.xml
<CustomField>
    <fullName>T_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T_Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>QtC Mig CreditMemoLines Alloc Temp Table</relationshipLabel>
    <relationshipName>QtC_Mig_CreditMemoLines_Alloc_Temp_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c/fields/T_MatchedWithPayCM__c.field-meta.xml
<CustomField>
    <fullName>T_MatchedWithPayCM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>T_MatchedWithPayCM?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QtC_Mig_Invoice_Lines_Temp_Table__c/fields/T_Invoice__c.field-meta.xml
<CustomField>
    <fullName>T_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T_Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>QtC Mig Invoice Lines Temp Table</relationshipLabel>
    <relationshipName>QtC_Mig_Invoice_Lines_Temp_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QtC_Mig_Invoice_Lines_Temp_Table__c/fields/T_MatchedWithPayCM__c.field-meta.xml
<CustomField>
    <fullName>T_MatchedWithPayCM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>T_MatchedWithPayCM?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Invoice__c/T_Invoice__c.object-meta.xml
<CustomObject>
    <label>T_Invoice</label>
    <nameField>
        <label>T_Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T_Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/T_CreditMemoAllocLookupBatch.cls
/**** @name        : T_CreditMemoAllocLookupBatch
***** @author      : KPMG
***** @date        : Nov 11th, 2023
***** @description : Update the QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c with the blng__CreditNote__c id in the T_CreditNote__c Field.
******/
//Credit Note Header
public class T_CreditMemoAllocLookupBatch implements Database.Batchable<sObject>,Database.Stateful {
    public List<QtC_Mig_Invoice_Temp_Table__c> count = new List<QtC_Mig_Invoice_Temp_Table__c>();
    public Set<String> noInvForLines = new Set<String>();
    public Set<String> noInvForPay = new Set<String>();
    public Set<String> noInvForPayAlloc = new Set<String>();
    public database.querylocator start(Database.BatchableContext bc)
    {
        String queryInvLine = 'Select Id,Applied_To_Internal_ID__c,T_CreditNote__c,Internal_ID__c from QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c '+
            ' where T_Invoice__c = null ';//T_MatchedWithPayCM__C = true and
        return Database.getQueryLocator(queryInvLine);
    }
    public void execute(Database.BatchableContext bc,List<QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c> invsExl)
    {
        Map<String,List<QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c>> ilineInternalIdToInvoiceMap = new Map<String,List<QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c>>();
        for(QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c i : invsExl)
        {//T_Invoice__c,Internal_ID__c --------------------TO DO with CM header Internal Id
            if (ilineInternalIdToInvoiceMap.containsKey(i.Internal_ID__c))
                ilineInternalIdToInvoiceMap.get(i.Internal_ID__c).add(i);
            else ilineInternalIdToInvoiceMap.put(i.Internal_ID__c,new List<QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c>{i});
        }
        List<blng__CreditNote__c> matchingBInv=[Select Id,NS_Credit_Note_Internal_ID__c from blng__CreditNote__c where
                                                T_IsMigrated__c = true
                                                and blng__Account__c != null
                                                and NS_Credit_Note_Internal_ID__c in :ilineInternalIdToInvoiceMap.keySet()];
        Map<String,blng__CreditNote__c> internalIdToBlngIdMap = new Map<String,blng__CreditNote__c>();
        for (blng__CreditNote__c bInv : matchingBInv) {
            internalIdToBlngIdMap.put(bInv.NS_Credit_Note_Internal_ID__c, bInv);
        }
        List<QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c> forUpdate = new List<QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c>();
        for (String internalId : ilineInternalIdToInvoiceMap.keySet()) {//QtC_Mig_Invoice_Lines_Temp_Table__c
            if (internalIdToBlngIdMap.containsKey(internalId)) {
                List<QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c> temp = ilineInternalIdToInvoiceMap.get(internalId);
                for(QtC_Mig_CreditMemoLines_Alloc_Temp_Table__c t : temp){
                    t.T_CreditNote__c = internalIdToBlngIdMap.get(internalId).Id;
                    // t.T_Invoice__c = internalIdToBlngIdMap.get(internalId).blng__RelatedInvoice__c;
                    forUpdate.add(t);
                }
            }
        }
        if(forUpdate.size()>0)
            Database.update(forUpdate);
    }
    public void finish(Database.BatchableContext bc){
    }
}