force-app/main/default/objects/blng__CreditNote__c/blng__CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/blng__CreditNote__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Added to store Approval status of the Credit Note</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/fields/blng__Status__c.field-meta.xml
<CustomField>
    <fullName>blng__Status__c</fullName>
    <inlineHelpText>Current status of the credit memo. Can be: Draft Posted Canceled</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>blng__PostingStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreditNoteTriggerHandler.cls
public class CreditNoteTriggerHandler {
    public static set<Id> publishedCreditnoteIds = new set<Id>();
    public Static void creditNoteAfterUpdate(list<blng__CreditNote__c> crednoteNewList, Map<Id,blng__CreditNote__c> crednoteOldMap) {
        if(!crednoteNewList.IsEmpty())
        {
            list<blng__CreditNote__c> creditnoteToProcessList = new list<blng__CreditNote__c>();
            for(blng__CreditNote__c credNote : crednoteNewList)
            {
                if(crednoteOldMap!=null && crednoteOldMap.containsKey(credNote.Id) &&           
                   (credNote.blng__Status__c != crednoteOldMap.get(credNote.id).blng__Status__c || 
                    credNote.Approval_Status__c != crednoteOldMap.get(credNote.id).Approval_Status__c)){
                        if(credNote.blng__Status__c == 'Posted' && credNote.Approval_Status__c == 'Approved'){
                            creditnoteToProcessList.add(credNote);
                        }
                    }   
       
            }
            if(!creditnoteToProcessList.IsEmpty() && creditnoteToProcessList.size()>0)
            {
                processEvents(creditnoteToProcessList,crednoteOldMap,true);
            }           
        }
    } 
    
    public static void processEvents(list<blng__CreditNote__c> creditnoteToProcessList,Map<Id,blng__CreditNote__c> crednoteOldMap,Boolean sendLines) {
        List<blng__CreditNote__c> creditnoteEligibleList = new List<blng__CreditNote__c>();
        List<blng__CreditNoteLine__c> creditNotelineList = new List<blng__CreditNoteLine__c>();
        set<Id> setOfCreditnoteIds = new Set<Id>();     
        if(!creditnoteToProcessList.isEmpty()) {
            IntegrationUtility.publishsObjectRecords(creditnoteToProcessList,'blng__CreditNote__c');
            if (sendLines) {
                Schema.SObjectType targetObjType = Schema.getGlobalDescribe().get('blng__CreditNoteLine__c');
                Map<String, Schema.SObjectField> fieldMap = targetObjType.getDescribe().fields.getMap();
                List<String> fields = new List<String>(fieldMap.keyset());
                String query =
                    ' SELECT ' +
                    String.join( fields, ',' ) +
                    ' FROM ' +
                    'blng__CreditNoteLine__c' +
                    ' WHERE ' +
                    ' blng__CreditNote__c IN :creditnoteToProcessList';
                query = query.remove('{');
                query = query.remove('}');
                creditNotelineList = Database.query(query);        
                if(!creditNotelineList.IsEmpty()) {
                    IntegrationUtility.publishsObjectRecords(creditNotelineList,'blng__CreditNoteLine__c');
                }   
            }     
        }
    }
}