force-app/main/default/objects/Contact/fields/Send_PSA_Dashboard__c.field-meta.xml
<CustomField>
    <fullName>Send_PSA_Dashboard__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox used to determine who should receive PSA Individual Performance Dashboard weekly email</description>
    <inlineHelpText>User should receive PSA Individual Performance Dashboard weekly email</inlineHelpText>
    <label>Send PSA Dashboard Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/PSADashboardSchedulerTest.cls
/*********************************************************************************************************     
 *  Name             :  PSADashboardSchedulerTest
 *  Author           :  Anisha Dhekne
 *  Description      :  Test class for PSADashboardScheduler
 *
 *  Change history   :
 *  Date            Author                      Description
 *  05/10/2018      Anisha Dhekne               Created
 *********************************************************************************************************/
@isTest 
private class PSADashboardSchedulerTest {

	@isTest
	private static void testName() {
		List<Contact> list_con= new List<Contact> ();
	
		Contact con = (Contact) SmartFactory.createSObject('Contact');
		//con.Id = Id;
		//con.Name = 'testName';
		con.Send_PSA_Dashboard__c = true;
		con.Email = 'anisha.dhekne@example.com';
		con.pse__Salesforce_User__c = UserInfo.getUserId();
		insert con;

		String cronExpr = '0 0 0 15 3 ? 2022';
		test.startTest();
		//Batch_ActiveCampaignCountScheduler bca = new Batch_ActiveCampaignCountScheduler();
		String jobId =	System.schedule('PSADashboardScheduler', cronExpr, new PSADashboardScheduler());
		
		test.stopTest();
	}
}