force-app/main/default/objects/Approvers_Matrix__c/Approvers_Matrix__c.object-meta.xml
<CustomObject>
    <label>Approver Matrix</label>
    <nameField>
        <label>Approvers Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approvers_Matrix__c/fields/Approver_Role__c.field-meta.xml
<CustomField>
    <fullName>Approver_Role__c</fullName>
    <label>Approver Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/fields/Approver_User__c.field-meta.xml
<CustomField>
    <fullName>Approver_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approvers_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approvers_Matrix__c/fields/Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>Sales_Segment__c</fullName>
    <label>Sales Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApproverMatrixServiceTest.cls
@isTest
public class ApproverMatrixServiceTest {
    @testSetup
    static void setupTestData(){
        List<Approvers_Matrix__c> Matrix = new List<Approvers_Matrix__c>();
        Approvers_Matrix__c AppMatrix = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix.Approver_Role__c ='SVP Services';
        AppMatrix.Approver_User__c = userinfo.getUserId();
        Matrix.add(AppMatrix);
        AppMatrix = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix.Approver_Role__c ='Services Segment Lead';
        AppMatrix.Approver_User__c = userinfo.getUserId();
        Matrix.add(AppMatrix);
        AppMatrix = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix.Approver_Role__c ='Industry President';
        AppMatrix.Approver_User__c = userinfo.getUserId();
        Matrix.add(AppMatrix);
        AppMatrix = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix.Approver_Role__c ='Industry Sales Lead';
        AppMatrix.Approver_User__c = userinfo.getUserId();
        Matrix.add(AppMatrix);
        AppMatrix = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix.Approver_Role__c ='Segment Lead';
        AppMatrix.Approver_User__c = userinfo.getUserId();
        Matrix.add(AppMatrix);
        AppMatrix = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix.Approver_Role__c ='COO';
        AppMatrix.Approver_User__c = userinfo.getUserId();
        Matrix.add(AppMatrix);
        AppMatrix = (Approvers_Matrix__c) SmartFactory.createSObject('Approvers_Matrix__c');
        AppMatrix.Sales_Segment__c ='03-Legal EMEA';
        AppMatrix.Approver_Role__c ='SVP Sales';
        AppMatrix.Approver_User__c = userinfo.getUserId();
        Matrix.add(AppMatrix);
        insert Matrix;
       
    }
    
    @isTest static void getApproverUsersList_Verify(){
        // Arrange
        List<Approvers_Matrix__c> AppMatrix1 = [Select id
                                                ,Approver_Role__c
                                                ,Sales_Segment__c
                                                ,Approver_User__c 
                                                From Approvers_Matrix__c];
        
        List<ApproverUsers> approverUsersList = new List<ApproverUsers>();
        
        // Act
        approverUsersList = ApproverMatrixService.getApproverUsersList(new List<string>{'03-Legal EMEA'});
        
        // Assert
        system.Assert(userinfo.getUserId() == approverUsersList[0].Services_Segment_Lead);
    }    
    
    @isTest static void getApproverUsers_Verify(){
        // Arrange
        List<Approvers_Matrix__c> approversMatrices = [Select id
                                                       ,Approver_Role__c
                                                       ,Sales_Segment__c
                                                       ,Approver_User__c 
                                                       From Approvers_Matrix__c
                                                       WHERE Sales_Segment__c ='03-Legal EMEA'];
        
        Map<String, ApproverUsers> approverUsersMap = new Map<String, ApproverUsers>();
        ApproverUsers currentApproversMatrix = new ApproverUsers();
		
        // Act
		approverUsersMap = ApproverMatrixService.getApproverUsers(new set<string>{'03-Legal EMEA'});

        for(Approvers_Matrix__c matrix : approversMatrices){
            if(approverUsersMap.containsKey(matrix.Sales_Segment__c)){
                currentApproversMatrix = approverUsersMap.get(matrix.Sales_Segment__c);
            }
        }
        
        // Assert
        system.Assert(userinfo.getUserId() == currentApproversMatrix.Services_Segment_Lead);
    }    
}