force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Amount_Credited__c.field-meta.xml
<CustomField>
    <fullName>Amount_Credited__c</fullName>
    <label>Amount Credited (Expiring on Aug 2)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Date_Paid__c.field-meta.xml
<CustomField>
    <fullName>Date_Paid__c</fullName>
    <label>Date Paid (Expiring on Aug 2)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/NS_Dollar_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>NS_Dollar_Amount_Paid__c</fullName>
    <label>Amount Paid (Expiring on Aug 2)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Related_OSA__c.field-meta.xml
<CustomField>
    <fullName>Related_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related OSA</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>NS Payments</relationshipLabel>
    <relationshipName>NS_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NS_Payment__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <description>Tran Date of Payment from NS</description>
    <inlineHelpText>Tran Date of Payment from NS</inlineHelpText>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestSnapshotHistoricalPaymentData.cls
@isTest 
private class TestSnapshotHistoricalPaymentData {
    
    @isTest
    private static void createSnapsnotInBatch() {
        Account a = (Account) SmartFactory.createSObject('Account');
        insert a;
        
        system.assertNotEquals(a, null, 'Account Present');
        
        Contract c = (Contract) SmartFactory.createSObject('Contract');
        c.AccountId = a.Id;
        insert c;
        
        Invoice__c i = (Invoice__c) SmartFactory.createSObject('Invoice__c');
        i.Account__c = a.Id;
        i.Related_OSA__c = c.Id;
        i.Amount_Credited__c = 100;
        i.NS_Dollar_Amount_Paid__c = 120;
        insert i;
        
        //Create payment snapshot
        String query = 'SELECT Id, Amount_Credited__c, NS_Dollar_Amount_Paid__c, CurrencyIsoCode FROM Invoice__c';
        SnapshotHistoricalPaymentData batch = new SnapshotHistoricalPaymentData(query, false, false, new Set<Id>(), false);
        Database.executeBatch(batch, 200);
    }
    
    @isTest
    private static void createSnapsnotInBatchUpdate() {
        Account a = (Account) SmartFactory.createSObject('Account');
        insert a;
        
        system.assertNotEquals(a, null, 'Account Present');
        Contract c = (Contract) SmartFactory.createSObject('Contract');
        c.AccountId = a.Id;
        insert c;
        
        Invoice__c i = (Invoice__c) SmartFactory.createSObject('Invoice__c');
        i.Account__c = a.Id;
        i.Related_OSA__c = c.Id;
        i.Amount_Credited__c = 100;
        i.NS_Dollar_Amount_Paid__c = 120;
        i.Date_Paid__c = date.today();
        insert i;
        
        NS_Payment__c j = (NS_Payment__c) SmartFactory.createSObject('NS_Payment__c');
        j.Invoice__c = i.Id;
        j.Name = 'Test';
        j.Transaction_Date__c = null;
        j.CurrencyIsoCode = 'USD';
        insert j;
        
        j.Name = 'Test2';
        update j;
        
        Test.startTest();
        //Create payment snapshot
        String query = 'SELECT Id, Amount_Credited__c, NS_Dollar_Amount_Paid__c, Date_Paid__c,CurrencyIsoCode,(Select Id,Transaction_Date__c,Invoice__c from NS_Payments__r ) FROM Invoice__c';
        SnapshotHistoricalPaymentData batch = new SnapshotHistoricalPaymentData(query, true, false, new Set<Id>(), false);
        Database.executeBatch(batch, 200);
        Test.stopTest();
        List<NS_Payment__c> paymentsToUpdate = [SELECT Id,Transaction_Date__c FROM NS_Payment__c WHERE Id =:j.Id];
        System.assertEquals(i.Date_Paid__c, paymentsToUpdate[0].Transaction_Date__c);
    } 
    
    @isTest
    private static void createSnapsnotInBatchDelete() {
        Account a = (Account) SmartFactory.createSObject('Account');
        insert a;
        
        system.assertNotEquals(a, null, 'Account Present');
        
        Contract c = (Contract) SmartFactory.createSObject('Contract');
        c.AccountId = a.Id;
        insert c;
        
        Invoice__c i = (Invoice__c) SmartFactory.createSObject('Invoice__c');
        i.Account__c = a.Id;
        i.Related_OSA__c = c.Id;
        i.Amount_Credited__c = 100;
        i.NS_Dollar_Amount_Paid__c = 120;
        i.Date_Paid__c = date.today();
        insert i;
        
        NS_Payment__c k = (NS_Payment__c) SmartFactory.createSObject('NS_Payment__c');
        k.Invoice__c = i.Id;
        k.Name = 'Test';
        k.Transaction_Date__c = null;
        insert k;
        
        delete k;
        
        //Create payment snapshot
        String query = 'SELECT Id, Amount_Credited__c, NS_Dollar_Amount_Paid__c, CurrencyIsoCode FROM Invoice__c';
        SnapshotHistoricalPaymentData batch = new SnapshotHistoricalPaymentData(query, false, false, new Set<Id>(), false);
        Database.executeBatch(batch, 200);
    }
    
    @isTest
    private static void insertNsPayment() {
        Account a = (Account) SmartFactory.createSObject('Account');
        insert a;
        
        Contract c = (Contract) SmartFactory.createSObject('Contract');
        c.AccountId = a.Id;
        insert c;
        
        Invoice__c i = (Invoice__c) SmartFactory.createSObject('Invoice__c');
        i.Account__c = a.Id;
        i.Related_OSA__c = c.Id;
        i.Amount_Credited__c = 100;
        i.NS_Dollar_Amount_Paid__c = 120;
        i.Date_Paid__c = date.today();
        insert i;
        
        NS_Payment__c d = (NS_Payment__c) SmartFactory.createSObject('NS_Payment__c');
        d.Invoice__c = i.Id;
        d.Name = 'Test';
        d.Transaction_Date__c = null;
        insert d;
        
        Test.startTest();
        //Create payment snapshot
        String query = 'SELECT Id, Amount_Credited__c, NS_Dollar_Amount_Paid__c, Date_Paid__c,CurrencyIsoCode,(Select Id,Transaction_Date__c,Invoice__c from NS_Payments__r ) FROM Invoice__c';
        SnapshotHistoricalPaymentData batch = new SnapshotHistoricalPaymentData(query, true, false, new Set<Id>(), false);
        Database.executeBatch(batch, 200);
        Test.stopTest();
        List<NS_Payment__c> paymentsToUpdate = [SELECT Id,Transaction_Date__c FROM NS_Payment__c WHERE Id =:d.Id];
        System.assertEquals(i.Date_Paid__c, paymentsToUpdate[0].Transaction_Date__c);
    }
}