force-app/main/default/objects/Opportunity_Product_Component__c/Opportunity_Product_Component__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Component</label>
    <nameField>
        <displayFormat>OPC-{0000000}</displayFormat>
        <label>Opportunity Product Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Product Components</relationshipLabel>
    <relationshipName>Opportunity_Product_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Recurring_Amount_Change__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Amount_Change__c</fullName>
    <label>Recurring Amount Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OPC_TriggerHandler_Test.cls
@isTest
public class OPC_TriggerHandler_Test {
    
	static testMethod void test_onInsert(){
            Opportunity opp = (Opportunity) SmartFactory.createSObject('Opportunity');
            insert opp;
            
            Opportunity_Product_Component__c opc = (Opportunity_Product_Component__c) SmartFactory.createSObject('Opportunity_Product_Component__c');
            opc.Recurring_Amount_Change__c = 2000;
            opc.Opportunity__c = opp.id;
            insert opc;
    }
}