force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(
  ISPICKVAL(StatusCode,&quot;Activated&quot;),
  TRUE,
  FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Associated_Contract_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contract_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the Contract record for this Opportunity?</description>
    <inlineHelpText>What is the Contract record for this Opportunity?</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Correct)</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Software Delivery Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Client Contact)</relationshipLabel>
    <relationshipName>ClientContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maintenance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Amount__c</fullName>
    <description>This field shows CHANGES to the annual recurring amount commitment for the referenced product. The value can be positive, if the closed-won opportunity increases the annual recurring commitment, or negative, if the closed-won opportunity decreases the annual recurring commitment.</description>
    <inlineHelpText>This field shows CHANGES to the annual recurring commitment for the referenced product. The value is positive, if the closed-won opportunity increases the annual commitment, or negative, if the closed-won opportunity decreases the annual commitment.</inlineHelpText>
    <label>Recurring Amount Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Conflicts - On Prem</fullName>
                <color>#E27001</color>
                <label>Conflicts - On Prem</label>
            </value>
            <value>
                <fullName>Intake - On Prem</fullName>
                <color>#E27001</color>
                <label>Intake - On Prem</label>
            </value>
            <value>
                <fullName>Records Management</fullName>
                <color>#E27001</color>
                <label>Records Management</label>
            </value>
            <value>
                <fullName>TFG - Legacy</fullName>
                <color>#E27001</color>
                <label>TFG - Legacy</label>
            </value>
            <value>
                <fullName>Terms - On Prem</fullName>
                <color>#E27001</color>
                <label>Terms - On Prem</label>
            </value>
            <value>
                <fullName>Terms - Cloud</fullName>
                <color>#E27001</color>
                <label>Terms - Cloud</label>
            </value>
            <value>
                <fullName>LegalKey - Legacy</fullName>
            </value>
            <value>
                <fullName>Experience - On Prem</fullName>
            </value>
            <value>
                <fullName>Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Multiple Products - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>L&amp;P - Cloud</fullName>
            </value>
            <value>
                <fullName>Relationships - On Prem</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - On Prem</fullName>
            </value>
            <value>
                <fullName>Multiple Products - Cloud</fullName>
            </value>
            <value>
                <fullName>Time - On Prem</fullName>
            </value>
            <value>
                <fullName>Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Walls - On Prem</fullName>
            </value>
            <value>
                <fullName>Integrate - On Prem</fullName>
            </value>
            <value>
                <fullName>DealCloud - Cloud</fullName>
            </value>
            <value>
                <fullName>OPIS - Cloud</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Integration Service - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_LineNew__c.field-meta.xml
<CustomField>
    <fullName>Product_LineNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line New IGNORE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Opportunities (Product Line)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/Opportunity_Product_Component__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Component</label>
    <nameField>
        <displayFormat>OPC-{0000000}</displayFormat>
        <label>Opportunity Product Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Product Components</relationshipLabel>
    <relationshipName>Opportunity_Product_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open Sandbox</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing</fullName>
            </value>
            <value>
                <fullName>Intapp Time</fullName>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Records Management</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Replicate</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>PSP</fullName>
            </value>
            <value>
                <fullName>Third Party Connectors</fullName>
            </value>
            <value>
                <fullName>Relationships</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Product_LineNew__c.field-meta.xml
<CustomField>
    <fullName>Product_LineNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Opportunity Product Components (Product Line)</relationshipLabel>
    <relationshipName>Opportunity_Product_Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Recurring_Amount_Change__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Amount_Change__c</fullName>
    <label>Recurring Amount Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is used to determine if this field should be available for use in the Product Line lookup fields.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_Historical_ProductLine_Test.cls
@isTest
public class Batch_Historical_ProductLine_Test {
	
    @testSetup static void CreateTestData() {
		Product_Line__c p1 = (Product_Line__c) SmartFactory.createSObject('Product_Line__c');
        p1.name = 'Walls';
        p1.Active__c = true;
        
        Product_Line__c p2 = (Product_Line__c) SmartFactory.createSObject('Product_Line__c');
        p2.name = 'Time';
        p2.Active__c = true;
        
        Product_Line__c p3 = (Product_Line__c) SmartFactory.createSObject('Product_Line__c');
        p3.name = 'Other';
        p3.Active__c = true;
        
        insert p1;
        insert p2;
        insert p3;
        
        Account a = IntappTestObjectFactory.createAccount(true);
        
        Contract c = IntappTestObjectFactory.createContract(a.Id);
    	insert c;
        
        Contact u = IntappTestObjectFactory.createContact(true);
        
        Opportunity o = IntappTestObjectFactory.createOpportunity();
        o.Client_Contact__c = u.Id;
        o.AccountId = a.Id;
        o.Associated_Contract_OSA__c = c.id;
        insert o;
        
        Opportunity_Product_Component__c opc1 = (Opportunity_Product_Component__c) SmartFactory.createSObject('Opportunity_Product_Component__c');
        opc1.Opportunity__c = o.Id;
        opc1.Product_Line__c = 'Walls';
        opc1.Recurring_Amount_Change__c = 200.00;
    
        Opportunity_Product_Component__c opc2 = (Opportunity_Product_Component__c) SmartFactory.createSObject('Opportunity_Product_Component__c');
        opc2.Opportunity__c = o.Id;
        opc2.Product_Line__c = 'Time';
        opc2.Recurring_Amount_Change__c = 400.00;

        insert opc1;
        insert opc2;
        
        Opportunity o2 = IntappTestObjectFactory.createOpportunity();
        o2.Client_Contact__c = u.Id;
        o2.AccountId = a.Id;
        o2.Associated_Contract_OSA__c = c.id;
        insert o2;
    }
    
    static testMethod void Test_Batch_Historical_OPCProductLineRollup() {
        String query = 'Select Id from Opportunity';
    	Batch_Historical_UpdateOppProdLines b1 = new Batch_Historical_UpdateOppProdLines(query, null);
        Database.executeBatch(b1);
    }
    
    static testMethod void Test_Batch_Historical_UpdateProductLine() {
        String sObjectType = 'Opportunity';
        String oldFieldName = 'Product_Line__c';
        String newFieldName = 'Product_LineNew__c';
        Map<String, String> map_productline_lookup = new Map<String, String>();
        map_productline_lookup.put('Walls', 'Walls');
        
        String query = 'Select Id, name, ' + oldFieldName + ',' + newFieldName + ' from Opportunity';
    	//(String query, String sObjectType, String oldFieldName, String newFieldName, Map<String, String> map_productline_lookup, Set<Integer> bToSkip)
        Batch_Historical_UpdateProductLine b2 = new Batch_Historical_UpdateProductLine(query, sObjectType, oldFieldName, newFieldName, map_productline_lookup, null);
        Database.executeBatch(b2);
    }
    
    static testMethod void Test_Batch_Historical_UpdateOppRAC() {
        String query = 'Select Id, name, Maintenance_Amount__c, (Select Id, Recurring_Amount_Change__c from Opportunity_Product_Components__r) from Opportunity';
    	//(String query, String sObjectType, String oldFieldName, String newFieldName, Map<String, String> map_productline_lookup, Set<Integer> bToSkip)
        Batch_Historical_UpdateOppRAC b3 = new Batch_Historical_UpdateOppRAC(query, null);
        Database.executeBatch(b3);
    }
    
}