force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/pse__Practice__c/pse__Practice__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__PracticeHelp</customHelpPage>
    <description>An entity that usually represents a product or business line. Practices are organized as an independent hierarchy determined by the Parent Practice field, with parent and child records of the same type. Every practice in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <label>Practice</label>
    <nameField>
        <label>Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/CSM__c.field-meta.xml
<CustomField>
    <fullName>CSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T-CSM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
                <color>#E27001</color>
                <label>Intapp Open - Conflicts</label>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
                <color>#E27001</color>
                <label>Intapp Open - Intake</label>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Time</fullName>
                <color>#78C953</color>
                <label>Intapp Time</label>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
                <color>#E27001</color>
                <label>TFG - Other</label>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
                <label>PSP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Subscriptions.cls
/**
 * See https://github.com/financialforcedev/fflib-apex-common for more info
 *
 * Install library via 
 *   https://githubsfdeploy.herokuapp.com/app/githubdeploy/financialforcedev/fflib-apex-common
 */

/**
 * Encapsulates all behaviour logic relating to the Subscription__c object
 * 
 * For more guidelines and details see 
 *   https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Domain_Layer
 *
 **/
public class Subscriptions extends fflib_SObjectDomain 
{
	public Subscriptions(List<Subscription__c> records) 
	{
		super(records);	
	}

	public override void onValidate()
	{
		for(Subscription__c record : (List<Subscription__c>) Records)
		{
		}
	}

	public override void onValidate(Map<Id,SObject> existingRecords)
	{
		for(Subscription__c record : (List<Subscription__c>) Records)
		{
		}
	}

	public override void onBeforeInsert()
	{
		PopulateCSMByPractice();
	}

	public void someMethod()
	{
		for(Subscription__c record : (List<Subscription__c>) Records)
		{
		}		
	}

	public void PopulateCSMByPractice()
	{
        /*
		//Identify which product lines to check
		Set<String> productLinesToCheck = new Set<String>{'Integration Builder', 'Wall Builder', 'Time', 'DTE'};
		
		//Map product lines to practice heads
		Map<String, Id> practiceOwners = new Map<String, Id>();
		List<pse__Practice__c> practices = [SELECT Id, Name, pse__Practice_Head__c FROM pse__Practice__c];
		system.debug('AW - Result count: ' + practices.size());
		for(pse__Practice__c prac : practices) {
			practiceOwners.put(prac.Name, prac.pse__Practice_Head__c);
		}
		
		//Update Subscriptions according to Practice Owner
		for (Subscription__c sub : (List<Subscription__c>)Records)
		{
			String practiceName = '';
			String productLine = sub.Product_Line__c;
			if (productLine.contains('Integration Builder')) { practiceName = 'Integration Builder'; }
			if (productLine.contains('Wall Builder')) { practiceName = 'Wall Builder'; }
			if (productLine.contains('DTE')) { practiceName = 'DTE'; }
			if (productLine.contains('Time')) { practiceName = 'Time'; }

			//Find Practice (based on Product Line)
			Id owner = practiceOwners.get(practiceName);
			system.debug('AW - Practice Owner is: ' + owner);
			if (owner != null)
			{
				//Retrieve contact record for Practice Owner
				Contact ownerContact = [SELECT Id, Name, pse__Salesforce_User__c FROM Contact where Id = :owner];
				system.debug('AW - Contact is: ' + ownerContact.Name);
				//Find User ID for Practice Head Contact
				User user = [SELECT Id, Name From User WHERE Id = :ownerContact.pse__Salesforce_User__c];
				system.debug('AW - User is: ' + user);
				if (user != null)
				{
					sub.CSM__c = user.Id;
				}
			}
		}
*/
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new Subscriptions(sObjectList);
		}
	}	
}