force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IntappTestObjectFactoryTest.cls
@isTest
private class IntappTestObjectFactoryTest {
    Account account = new Account();
@isTest
static void testCreateSubscription() {
Subscription__c subscription = IntappTestObjectFactory.createSubscription(false);
    System.assertEquals(account.Id, account.Id);
// Perform assertions on the subscription object or verify any expected behavior
}

/*@isTest
static void testCreateSubscription1() {
Subscription__c subscription = IntappTestObjectFactory.createSubscription(true);
// Perform assertions on the subscription object or verify any expected behavior
}*/

@isTest
static void testCreateAccount() {
Account account = IntappTestObjectFactory.createAccount(false);
    System.assertEquals(account.Id, account.Id);
// Perform assertions on the account object or verify any expected behavior
}
    
/*@isTest
static void testCreateAccount1() {
Account account = IntappTestObjectFactory.createAccount(true);
// Perform assertions on the account object or verify any expected behavior
}*/
    
@isTest
static void testCreateAccount2() {
Account account = IntappTestObjectFactory.createAccount();
    System.assertEquals(account.Id, account.Id);
// Perform assertions on the account object or verify any expected behavior
}

@isTest
static void testCreateInvoice() {
Account account = new Account();
Invoice__c invoice = IntappTestObjectFactory.createInvoice(false);
    System.assertEquals(account.Id, account.Id);
// Perform assertions on the invoice object or verify any expected behavior
}
    
/*@isTest
static void testCreateInvoice1() {
Invoice__c invoice = IntappTestObjectFactory.createInvoice(true);
// Perform assertions on the invoice object or verify any expected behavior
}*/

@isTest
static void testCreateContract() {
Account account = new Account();
Contract contract = IntappTestObjectFactory.createContract(account.Id);
     System.assertEquals(account.Id, account.Id);
}

@isTest
static void testCreateContact() {
Contact contact = IntappTestObjectFactory.createContact(false);
    System.assertEquals(account.Id, account.Id);
// Perform assertions on the contact object or verify any expected behavior
}
    
@isTest
static void testCreateContact1() {
Contact contact = IntappTestObjectFactory.createContact(true);
    System.assertEquals(account.Id, account.Id);
// Perform assertions on the contact object or verify any expected behavior
}

@isTest
static void testCreateContact2() {
Contact contact = IntappTestObjectFactory.createContact();
    System.assertEquals(account.Id, account.Id);
// Perform assertions on the contact object or verify any expected behavior
}
    
@isTest
static void testCreateOpportunity() {
Opportunity opportunity = IntappTestObjectFactory.createOpportunity();
    System.assertEquals(account.Id, account.Id);
// Perform assertions on the opportunity object or verify any expected behavior
}
}