force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Contract_Master_Terms__c.field-meta.xml
<CustomField>
    <fullName>Contract_Master_Terms__c</fullName>
    <description>Built according to BIZ-47359</description>
    <label>Contract Master Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Master_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_Master_Product__c/Item_Master_Product__c.object-meta.xml
<CustomObject>
    <label>Item Master Product</label>
    <nameField>
        <displayFormat>PIN-{00000}</displayFormat>
        <label>Product Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Master Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Associated_Contract_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contract_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the Contract record for this Opportunity?</description>
    <inlineHelpText>What is the Contract record for this Opportunity?</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Correct)</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Signer__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Signer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contract Signer)</relationshipLabel>
    <relationshipName>Opportunities6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/OSA_Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>OSA_Discount_Amount__c</fullName>
    <label>OSA Discount Amount (Recurring Software)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Item_Master_Product__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Master Product</label>
    <referenceTo>Item_Master_Product__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_License_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_License_Type__c</fullName>
    <description>If software, is this an Annual or Perpetual software license?</description>
    <inlineHelpText>If software, is this an Annual or Perpetual software license?</inlineHelpText>
    <label>Software License Term</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Early Adopter</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>The record type to be used for products such as Wall Builder</description>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Contract_Master_Terms__c.field-meta.xml
<CustomField>
    <fullName>Contract_Master_Terms__c</fullName>
    <label>Contract Master Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>URL Terms</fullName>
            </value>
            <value>
                <fullName>Existing Terms Cloud</fullName>
                <label>Existing Intapp MSSA Plus Cloud</label>
            </value>
            <value>
                <fullName>Existing Terms</fullName>
                <label>Existing Intapp MSSA Terms</label>
            </value>
            <value>
                <fullName>Existing Terms with Annex</fullName>
                <label>Existing Intapp MSSA plus Annex</label>
            </value>
            <value>
                <fullName>MSSA Attached</fullName>
                <label>New Intapp MSSA Attached</label>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>OnePlace Legacy</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Custom Master Term from Account</fullName>
            </value>
            <value>
                <fullName>Repstor Legacy Agreement Attached</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
                <label>Intapp Reseller</label>
            </value>
            <value>
                <fullName>Repstor G-Cloud</fullName>
            </value>
            <value>
                <fullName>Existing Intapp MSSA signed by Customer Affiliate</fullName>
            </value>
            <value>
                <fullName>Legacy DealCloud Agreement</fullName>
            </value>
            <value>
                <fullName>New MSSA Signed Separate</fullName>
            </value>
            <value>
                <fullName>Existing Intapp MSSA plus Cloud and Annex</fullName>
            </value>
            <value>
                <fullName>Existing Terms Plus Prime</fullName>
                <isActive>false</isActive>
                <label>Existing Terms Plus Prime</label>
            </value>
            <value>
                <fullName>Prime</fullName>
                <isActive>false</isActive>
                <label>Partner and Prime</label>
            </value>
            <value>
                <fullName>Repstor Legacy</fullName>
                <isActive>false</isActive>
                <label>Repstor Legacy</label>
            </value>
            <value>
                <fullName>Repstor Legacy Term</fullName>
                <isActive>false</isActive>
                <label>Repstor Legacy Term</label>
            </value>
            <value>
                <fullName>Repstor Retro-Booking</fullName>
                <isActive>false</isActive>
                <label>Repstor Retro-Booking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Contract_Master_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>URL Terms</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Terms Cloud</fullName>
        <label>Existing Intapp MSSA Plus Cloud</label>
    </customValue>
    <customValue>
        <fullName>Existing Terms</fullName>
        <label>Existing Intapp MSSA Terms</label>
    </customValue>
    <customValue>
        <fullName>Existing Terms with Annex</fullName>
        <label>Existing Intapp MSSA plus Annex</label>
    </customValue>
    <customValue>
        <fullName>MSSA Attached</fullName>
        <label>New Intapp MSSA Attached</label>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>OnePlace Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Trial</fullName>
    </customValue>
    <customValue>
        <fullName>Custom Master Term from Account</fullName>
    </customValue>
    <customValue>
        <fullName>Repstor Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
        <label>Intapp Reseller</label>
    </customValue>
    <customValue>
        <fullName>Repstor G-Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Intapp MSSA signed by Customer Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy DealCloud Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>New MSSA Signed Separate</fullName>
    </customValue>
    <customValue>
        <fullName>Existing Intapp MSSA plus Cloud and Annex</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Prime</fullName>
        <isActive>false</isActive>
        <label>Partner and Prime</label>
    </customValue>
    <customValue>
        <fullName>Repstor Retro-Booking</fullName>
        <isActive>false</isActive>
        <label>Repstor Retro-Booking</label>
    </customValue>
    <customValue>
        <fullName>Existing Terms Plus Prime</fullName>
        <isActive>false</isActive>
        <label>Existing Terms Plus Prime</label>
    </customValue>
    <description>Built according to BIZ-47359</description>
    <masterLabel>Contract Master Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SyncQuoteLineItems_Test.cls
@isTest 
private class SyncQuoteLineItems_Test {

	@isTest
	private static void syncLineItems() {
		//***Creating records for testing***
		Account a = (Account) SmartFactory.createSObject('Account');
		a.Industry = 'Legal';
		insert a;

		Contract c = (Contract) SmartFactory.createSObject('Contract');
		c.AccountId = a.Id;
		insert c;

		Contact con = (Contact) SmartFactory.createSObject('Contact');
		insert con;

		Opportunity opp = (Opportunity) SmartFactory.createSObject('Opportunity');
		opp.AccountId = a.Id;
		opp.Associated_Contract_OSA__c = c.Id;
		opp.Contract_Signer__c = con.Id;
		insert opp;

		Id pricebookId = Test.getStandardPricebookId();

		Item_Master_Product__c imp = (Item_Master_Product__c) SmartFactory.createSObject('Item_Master_Product__c');
		insert imp;
		//Create your product
		Product2 prod = new Product2(
			 Name = 'Product X',
			 ProductCode = 'Pro-X',
			 isActive = true,
			 Product_License_Type__c = 'Annual',
			 Item_Master_Product__c = imp.Id
		);
		insert prod;

		//Create your pricebook entry
		PricebookEntry pbEntry = new PricebookEntry(
			 Pricebook2Id = pricebookId,
			 Product2Id = prod.Id,
			 UnitPrice = 100.00,
			 IsActive = true
		);
		insert pbEntry;


		//create your opportunity line item.  This assumes you already have an opportunity created, called opp
		OpportunityLineItem oli = new OpportunityLineItem(
			 OpportunityId = opp.Id,
			 Quantity = 5,
			 PricebookEntryId = pbEntry.Id,
			 Product2Id = prod.Id,
			 TotalPrice = 5 * pbEntry.UnitPrice,
			 OSA_Discount_Amount__c = 10
		);

		insert oli;
		//***Creating records for testing***

		SBQQ__Quote__c q = (SBQQ__Quote__c) SmartFactory.createSObject('SBQQ__Quote__c');
		q.Contract_Master_Terms__c = 'URL Terms';
		q.SBQQ__Opportunity2__c = opp.Id;
		q.SBQQ__Account__c = a.Id;
		insert q;

		Test.startTest();
		String msg = SyncQuoteLineItems.syncLineItems(q.Id);
		Test.stopTest();
	}
}