force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/CR_Engagement__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>CR Engagements</relationshipLabel>
    <relationshipName>At_Risk_Period</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Subscription_Link__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Invoice_Subscription_Links</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Invoice_Subscription_Link__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoice_Subscription_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Conflicts - On Prem</fullName>
                <color>#E27001</color>
                <label>Conflicts - On Prem</label>
            </value>
            <value>
                <fullName>Intake - On Prem</fullName>
                <color>#E27001</color>
                <label>Intake - On Prem</label>
            </value>
            <value>
                <fullName>Records Management</fullName>
                <color>#E27001</color>
                <label>Records Management</label>
            </value>
            <value>
                <fullName>TFG - Legacy</fullName>
                <color>#E27001</color>
                <label>TFG - Legacy</label>
            </value>
            <value>
                <fullName>Terms - On Prem</fullName>
                <color>#E27001</color>
                <label>Terms - On Prem</label>
            </value>
            <value>
                <fullName>Terms - Cloud</fullName>
                <color>#E27001</color>
                <label>Terms - Cloud</label>
            </value>
            <value>
                <fullName>LegalKey - Legacy</fullName>
            </value>
            <value>
                <fullName>Experience - On Prem</fullName>
            </value>
            <value>
                <fullName>Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Multiple Products - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>L&amp;P - Cloud</fullName>
            </value>
            <value>
                <fullName>Relationships - On Prem</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - On Prem</fullName>
            </value>
            <value>
                <fullName>Multiple Products - Cloud</fullName>
            </value>
            <value>
                <fullName>Time - On Prem</fullName>
            </value>
            <value>
                <fullName>Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Walls - On Prem</fullName>
            </value>
            <value>
                <fullName>Integrate - On Prem</fullName>
            </value>
            <value>
                <fullName>DealCloud - Cloud</fullName>
            </value>
            <value>
                <fullName>OPIS - Cloud</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Integration Service - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Primary_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Primary_Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
                <color>#E27001</color>
                <label>Intapp Open - Conflicts</label>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
                <color>#E27001</color>
                <label>Intapp Open - Intake</label>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Time</fullName>
                <color>#78C953</color>
                <label>Intapp Time</label>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
                <color>#E27001</color>
                <label>TFG - Other</label>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
                <label>PSP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Term_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_End_Date__c</fullName>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Subscription_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription_Contact__c/fields/Primary_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Primary_Subscription__c</fullName>
    <formula>Subscription__r.Primary_Subscription__c</formula>
    <label>Primary Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription_Contact__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Product Customer</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Product Customer Contacts</relationshipLabel>
    <relationshipName>Subscription_Contact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SubscriptionHelperTest.cls
@isTest
public class SubscriptionHelperTest {
	@testSetup static void TestSetup() {
		Account account = IntappTestObjectFactory.createAccount(true);

		Subscription__c primarysub = IntappTestObjectFactory.createSubscription(false);
		primarysub.Account__c = account.Id;
		primarysub.Primary_Subscription__c = true;
		primarysub.Product_Line__c = 'Wall Builder';
		insert primarysub;

		Subscription__c fromsub = IntappTestObjectFactory.createSubscription(false);
		fromsub.Account__c = account.Id;
		fromsub.Primary_Subscription__c = false;
		fromsub.Product_Line__c = 'Wall Builder';
		insert fromsub;

		Subscription__c fromsub2 = IntappTestObjectFactory.createSubscription(false);
		fromsub2.Account__c = account.Id;
		fromsub2.Primary_Subscription__c = false;
		fromsub2.Product_Line__c = 'Wall Builder';
		insert fromsub2;

		Opportunity opp = IntappTestObjectFactory.createOpportunity();
		opp.Subscription__c = fromsub.Id;
		insert opp;

		Task task = new Task();
		task.WhatId = fromsub.Id;
		task.Subject = 'Test task for testing';
		insert task;

		Event event = new Event();
		event.DurationInMinutes = 60;
		event.WhatId = fromsub.Id;
		event.ActivityDateTime = Datetime.now();
		event.Subject = 'Test event for testing';
		insert event;

		CR_Engagement__c cr = new CR_Engagement__c();
		cr.Subscription__c = fromsub.Id;
		insert cr;

		Contact primContact = IntappTestObjectFactory.createContact(false);
		insert primContact;
		Contact fromContact = IntappTestObjectFactory.createContact(false);
		insert fromContact;

		Subscription_Contact__c sc = new Subscription_Contact__c();
		sc.Subscription__c = primarysub.Id;
		sc.Contact__c = primContact.Id;
		insert sc;

		Subscription_Contact__c sc2 = new Subscription_Contact__c();
		sc2.Subscription__c = fromsub.Id;
		sc2.Contact__c = fromContact.Id;
		insert sc2;

		Invoice__c invoice = IntappTestObjectFactory.createInvoice(false);
		invoice.Account__c = account.Id;
		insert invoice;

		Invoice_Subscription_Link__c isl = new Invoice_Subscription_Link__c();
		isl.Invoice__c = invoice.Id;
		isl.Subscription__c = fromsub.Id;
		insert isl;
	}

	@isTest static void TestMergeSubscriptionsForAccount() {
		Account account = [Select Id, Intapp_Account_Number__c FROM Account LIMIT 1];
		SubscriptionHelper.MergeSubscriptionsForAccount(account.IntApp_Account_Number__c);
	}

	@isTest static void TestMergeSubscriptionsForPrimarySub() {
		Account account = [Select Id, Intapp_Account_Number__c FROM Account LIMIT 1];
		Subscription__c sub = [SELECT Id from Subscription__c WHERE Primary_Subscription__c = true AND Account__c = :account.Id LIMIT 1];

		Subscription__c fromsub2 = IntappTestObjectFactory.createSubscription(false);
		fromsub2.Account__c = account.Id;
		fromsub2.Primary_Subscription__c = false;
		fromsub2.Product_Line__c = 'Wall Builder';
		insert fromsub2;

		SubscriptionHelper.MergeSubscriptionsForPrimarySubscription(sub.Id);
	}

	//@isTest static void TestMergeSubscriptionsToTerms() {
		//List<Subscription__c> subs = [SELECT ID, Name, Product_Line__c, Account__c, Term_End_Date__c, Primary_Subscription__c from Subscription__c LIMIT 2];
		
		//Subscription__c primarySub; 
		//if (subs[0].Primary_Subscription__c == true)
		//{
			//primarySub = subs[0];
		//}
		//else {
			//primarySub = subs[1];
		//}

		//SubscriptionHelper.MergeSubscriptionsToTerms(primarySub.Id);
	//}

	@isTest static void TestCreateTermsForInvoices() {
		List<Subscription__c> subs = [SELECT ID, Name, Product_Line__c, Account__c, Term_End_Date__c, Primary_Subscription__c from Subscription__c LIMIT 2];
		
		Subscription__c primarySub; 
		if (subs[0].Primary_Subscription__c == true)
		{
			primarySub = subs[0];
		}
		else {
			primarySub = subs[1];
		}

		SubscriptionHelper.CreateTermsForInvoices(primarySub.Id);
	}

}