force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>This is the main record type that should be used for all external contacts, and for internal contacts that do not act as resources in Financial Force. When in doubt - pick this record type.</description>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(
  ISPICKVAL(StatusCode,&quot;Activated&quot;),
  TRUE,
  FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Intapp_Settings__c/fields/Different_Product_Line_Check__c.field-meta.xml
<CustomField>
    <fullName>Different_Product_Line_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check if there are different product lines under the same Oppt</description>
    <inlineHelpText>Check if there are different product lines under the same Oppt</inlineHelpText>
    <label>Different Product Line Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Intapp_Settings__c/fields/Multiple_OPC_Check__c.field-meta.xml
<CustomField>
    <fullName>Multiple_OPC_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked - Validates whether Oppt has multiple OPCs while creating Order Headers</description>
    <inlineHelpText>When checked - Validates whether Oppt has multiple OPCs while creating Order Headers</inlineHelpText>
    <label>Multiple OPC Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Associated_Contract_OSA__c.field-meta.xml
<CustomField>
    <fullName>Associated_Contract_OSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the Contract record for this Opportunity?</description>
    <inlineHelpText>What is the Contract record for this Opportunity?</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (Correct)</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_Contact__c.field-meta.xml
<CustomField>
    <fullName>Client_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Software Delivery Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Client Contact)</relationshipLabel>
    <relationshipName>ClientContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Conflicts - On Prem</fullName>
                <color>#E27001</color>
                <label>Conflicts - On Prem</label>
            </value>
            <value>
                <fullName>Intake - On Prem</fullName>
                <color>#E27001</color>
                <label>Intake - On Prem</label>
            </value>
            <value>
                <fullName>Records Management</fullName>
                <color>#E27001</color>
                <label>Records Management</label>
            </value>
            <value>
                <fullName>TFG - Legacy</fullName>
                <color>#E27001</color>
                <label>TFG - Legacy</label>
            </value>
            <value>
                <fullName>Terms - On Prem</fullName>
                <color>#E27001</color>
                <label>Terms - On Prem</label>
            </value>
            <value>
                <fullName>Terms - Cloud</fullName>
                <color>#E27001</color>
                <label>Terms - Cloud</label>
            </value>
            <value>
                <fullName>LegalKey - Legacy</fullName>
            </value>
            <value>
                <fullName>Experience - On Prem</fullName>
            </value>
            <value>
                <fullName>Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Multiple Products - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - On Prem</fullName>
            </value>
            <value>
                <fullName>Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>L&amp;P - Cloud</fullName>
            </value>
            <value>
                <fullName>Relationships - On Prem</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
            <value>
                <fullName>CRM - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - Cloud</fullName>
            </value>
            <value>
                <fullName>Flow - On Prem</fullName>
            </value>
            <value>
                <fullName>Multiple Products - Cloud</fullName>
            </value>
            <value>
                <fullName>Time - On Prem</fullName>
            </value>
            <value>
                <fullName>Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Walls - On Prem</fullName>
            </value>
            <value>
                <fullName>Integrate - On Prem</fullName>
            </value>
            <value>
                <fullName>DealCloud - Cloud</fullName>
            </value>
            <value>
                <fullName>OPIS - Cloud</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Integration Service - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_LineNew__c.field-meta.xml
<CustomField>
    <fullName>Product_LineNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line New IGNORE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Opportunities (Product Line)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/Opportunity_Product_Component__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Component</label>
    <nameField>
        <displayFormat>OPC-{0000000}</displayFormat>
        <label>Opportunity Product Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Product Components</relationshipLabel>
    <relationshipName>Opportunity_Product_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line - EXPIRED</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intapp Integrate</fullName>
            </value>
            <value>
                <fullName>Intapp Integrate - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Conflicts - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Experience - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Intake - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Open Sandbox</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms</fullName>
            </value>
            <value>
                <fullName>Intapp Open - Terms - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing</fullName>
            </value>
            <value>
                <fullName>Intapp Time</fullName>
            </value>
            <value>
                <fullName>Intapp Time - Cloud</fullName>
            </value>
            <value>
                <fullName>Intapp Walls</fullName>
            </value>
            <value>
                <fullName>LegalKey</fullName>
            </value>
            <value>
                <fullName>Records Management</fullName>
            </value>
            <value>
                <fullName>TFG - Other</fullName>
            </value>
            <value>
                <fullName>Third Party Product - D&amp;B</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Replicate</fullName>
            </value>
            <value>
                <fullName>Third Party Product - Experience</fullName>
            </value>
            <value>
                <fullName>Intapp Pricing - Cloud</fullName>
            </value>
            <value>
                <fullName>PSP</fullName>
            </value>
            <value>
                <fullName>Third Party Connectors</fullName>
            </value>
            <value>
                <fullName>Relationships</fullName>
            </value>
            <value>
                <fullName>Relationships - Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Product_Component__c/fields/Product_LineNew__c.field-meta.xml
<CustomField>
    <fullName>Product_LineNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product_Line__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Opportunity Product Components (Product Line)</relationshipLabel>
    <relationshipName>Opportunity_Product_Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is used to determine if this field should be available for use in the Product Line lookup fields.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OrderHeaderServiceTest.cls
/**
Test class for OrderHeaderService class 
**/
@isTest
private class OrderHeaderServiceTest {

	@testSetup static void CreateTestData() {
		//Create using IntappTestObjectFactory (contract and opportunity)
		Account a = IntappTestObjectFactory.createAccount(true);

		Contract c = IntappTestObjectFactory.createContract(a.Id);
		insert c;

		Contact u = IntappTestObjectFactory.createContact(true);

		Opportunity o = IntappTestObjectFactory.createOpportunity();
		o.Client_Contact__c = u.Id;
		o.AccountId = a.Id;
		o.Associated_Contract_OSA__c = c.id;
		insert o;
		
        Product_Line__c pl1 = new Product_Line__c();
        pl1.Name = 'Walls';
        pl1.Active__c = true;
        insert pl1;
        
        Product_Line__c pl2 = new Product_Line__c();
        pl2.Name = 'Integrate';
        pl2.Active__c = true;
        insert pl2;
        
		Opportunity_Product_Component__c opc1 = (Opportunity_Product_Component__c) SmartFactory.createSObject('Opportunity_Product_Component__c');
		opc1.Opportunity__c = o.Id;
		opc1.Product_Line__c = 'Intapp Walls';
		opc1.Product_LineNew__c = pl1.Id;
        
		Opportunity_Product_Component__c opc2 = (Opportunity_Product_Component__c) SmartFactory.createSObject('Opportunity_Product_Component__c');
		opc2.Opportunity__c = o.Id;
		opc2.Product_Line__c = 'Intapp Walls';
		opc2.Product_LineNew__c = pl1.Id;
        
		insert opc1;
		insert opc2;

		Intapp_Settings__c settings = Intapp_Settings__c.getOrgDefaults();
		settings.Multiple_OPC_Check__c = true;
		settings.Multiple_OPC_Error_Message__c = 'Multiple OPC Validation';
		settings.Different_Product_Line_Check__c = true;
		settings.Different_Product_Line_Error__c = 'Same OPC Product Line Validation';

		upsert settings Intapp_Settings__c.Id;
	}

	static testMethod void TestCreateKeyAndMedia() {
		Opportunity o = [SELECT Id from Opportunity LIMIT 1];

		Opportunity_Product_Component__c opcTest = new Opportunity_Product_Component__c();

		// Execute the test
		Test.startTest();
			//Have 2 OPCs of same product line - Intapp Walls
			String OHresponse = OrderHeaderService.CreateKeyAndMedia(o.id, true);
			System.assertEquals('Same OPC Product Line Validation', OHresponse);
			
        	Product_Line__c plIntegrate = [Select Id from Product_Line__c where Name = 'Integrate'];
			//Change one OPC to Intapp Integrate
			for(Opportunity_Product_Component__c opc: [Select Id, Product_Line__c ,Product_LineNew__c from Opportunity_Product_Component__c where Opportunity__c = : o.id]){
				opc.Product_Line__c = 'Intapp Integrate';
				opc.Product_LineNew__c = plIntegrate.Id; 
                opcTest = opc;
				break;
			}

			update opcTest;

			OHresponse = OrderHeaderService.CreateKeyAndMedia(o.id, true);
			System.assertEquals('Multiple OPC Validation', OHresponse);
			
			//Ideal situation 1
			OHresponse = OrderHeaderService.CreateKeyAndMedia(opcTest.id, true);
			System.assertEquals('Key and Media Order Headers created.', OHresponse);

			//Ideal situation 2 - Remove one OPC and hve only one OPC on Oppt
			delete opcTest;
			OHresponse = OrderHeaderService.CreateKeyAndMedia(o.id, true);
			System.assertEquals('Key and Media Order Headers created.', OHresponse);

			//Remove Client Contact and verify validation
			o.Client_Contact__c = null;
			update o;
			OHresponse = OrderHeaderService.CreateKeyAndMedia(o.id, true);
			System.assertEquals('There was an error processing your request. Please verify that the related Opportunity has both a Client Contact and an OSA populated.', OHresponse);
		Test.stopTest();
		//Test end
	}
}